#IBM Queue
spring.fep.jms.prop.queueManager=QMFEPLOGP02
spring.fep.jms.prop.channel=SVRCONN.FROMEMS
spring.fep.jms.prop.connName=10.0.54.34(1415)
spring.fep.jms.prop.user=
spring.fep.jms.prop.password=

#EMS Receiver
spring.fep.jms.ems.receiver.prop.queueManager=QMFEPLOGP02
spring.fep.jms.ems.receiver.prop.channel=SVRCONN.FROMEMS
spring.fep.jms.ems.receiver.prop.connName=10.0.54.34(1415)
spring.fep.jms.ems.receiver.prop.user=
spring.fep.jms.ems.receiver.prop.password=
# Static or RoundRobin
spring.fep.jms.ems.sender.deliveryMode=RoundRobin
#EMS Sender
spring.fep.jms.ems.sender.log[0].queueManager=QMFEPLOGP01
spring.fep.jms.ems.sender.log[0].channel=SVRCONN.TOEMS
spring.fep.jms.ems.sender.log[0].connName=10.0.54.33(1415)
spring.fep.jms.ems.sender.log[0].user=
spring.fep.jms.ems.sender.log[0].password=
spring.fep.jms.ems.sender.log[0].queue-names.ems.destination=FEP.LOG.QL
spring.fep.jms.ems.sender.log[1].queueManager=QMFEPLOGP02
spring.fep.jms.ems.sender.log[1].channel=SVRCONN.TOEMS
spring.fep.jms.ems.sender.log[1].connName=10.0.54.34(1415)
spring.fep.jms.ems.sender.log[1].user=
spring.fep.jms.ems.sender.log[1].password=
spring.fep.jms.ems.sender.log[1].queue-names.ems.destination=FEP.LOG.QL
spring.fep.jms.ems.sender.alert[0].queueManager=QMFEPLOGP01
spring.fep.jms.ems.sender.alert[0].channel=SVRCONN.TOEMS
spring.fep.jms.ems.sender.alert[0].connName=10.0.54.33(1415)
spring.fep.jms.ems.sender.alert[0].user=
spring.fep.jms.ems.sender.alert[0].password=
spring.fep.jms.ems.sender.alert[0].queue-names.ems.destination=FEP.EMS.QL
spring.fep.jms.ems.sender.alert[1].queueManager=QMFEPLOGP02
spring.fep.jms.ems.sender.alert[1].channel=SVRCONN.TOEMS
spring.fep.jms.ems.sender.alert[1].connName=10.0.54.34(1415)
spring.fep.jms.ems.sender.alert[1].user=
spring.fep.jms.ems.sender.alert[1].password=
spring.fep.jms.ems.sender.alert[1].queue-names.ems.destination=FEP.EMS.QL

#===============================================================================
#FISC Sender(for fiscgw)
spring.fep.jms.fisc.sender.prop.host-name=fepap2P
spring.fep.jms.fisc.sender.prop.queueManager=QMFEPP02
spring.fep.jms.fisc.sender.prop.channel=SVRCONN.TOFISCGW
spring.fep.jms.fisc.sender.prop.connName=10.0.54.34(1414)
spring.fep.jms.fisc.sender.prop.user=
spring.fep.jms.fisc.sender.prop.password=

#FISC Sender Alternative(for fiscgw)
spring.fep.jms.fisc.sender.alternative.prop.host-name=fepap1P
spring.fep.jms.fisc.sender.alternative.prop.queueManager=QMFEPP01
spring.fep.jms.fisc.sender.alternative.prop.channel=SVRCONN.TOFISCGW
spring.fep.jms.fisc.sender.alternative.prop.connName=10.0.54.33(1414)
spring.fep.jms.fisc.sender.alternative.prop.user=
spring.fep.jms.fisc.sender.alternative.prop.password=
#===============================================================================



#Queue Name
spring.fep.jms.queue-names.ems.destination=FEP.EMS.QL
spring.fep.jms.queue-names.ems.concurrency=10-20
spring.fep.jms.queue-names.fisc.destination=FEP.FISC.ONLINE.RS
spring.fep.jms.queue-names.fiscAlternative.destination=FEP.FISC.ONLINE.RS

#Topic Name
spring.fep.jms.topic-names.test.destination=TestTopic

