server.port=8302

spring.fep.application.name=fep-gateway

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-fisc-agent
management.endpoint.health.show-details=always

#FISC Gateway Client Agent
spring.register.bean[0]=com.syscom.fep.gateway.agent.fisc.FISCGatewayClientAgentConfiguration
spring.register.bean[1]=com.syscom.fep.gateway.agent.fisc.FISCGatewayClientAgentJobLauncher
spring.register.controller[0]=com.syscom.fep.gateway.agent.fisc.FISCGatewayClientAgent

#FISC Gateway Client Agent Configuration
spring.fep.gateway.agent.fisc.cmdStart=/fep/fep-app/fep-gateway-fisc/fep_gateway_fisc_start.sh
spring.fep.gateway.agent.fisc.httpTerminate=http://${spring.fep.hostip}:8301/recv/fisc/terminate
spring.fep.gateway.agent.fisc.httpOperate=http://${spring.fep.hostip}:8301/recv/fisc/operate
spring.fep.gateway.agent.fisc.httpChangeFEPAP=http://${spring.fep.hostip}:8301/recv/fisc/changefepap
spring.fep.gateway.agent.fisc.httpCheckFEPAP=http://${spring.fep.hostip}:8301/recv/fisc/checkfepap
spring.fep.gateway.agent.fisc.recordHttpLog=true
spring.fep.gateway.agent.fisc.printInputStream=true
spring.fep.gateway.agent.fisc.gwLogPath=/fep/logs/{yyyy-MM-dd}/fep-gateway-fisc/fep-gateway-fisc-FISCGW-{logKind}-{yyyy-MM-dd}-(.*).log
spring.fep.gateway.agent.fisc.cmd.clear=/bin/sh -c clear

#FISC Gateway Client Agent Configuration ProcessCommandJobs
spring.fep.gateway.agent.fisc.cmdJobConfig[0].cronExpression=0 0 4 * * ?
spring.fep.gateway.agent.fisc.cmdJobConfig[0].command=/fep/fep-app/fep-batch-cmdline/fep_archivinglogfile_run.sh
spring.fep.gateway.agent.fisc.cmdJobConfig[1].cronExpression=0 0 3 * * ?
spring.fep.gateway.agent.fisc.cmdJobConfig[1].command=

#register Scheduler Job
spring.fep.scheduler.job.register[0].className=com.syscom.fep.scheduler.job.impl.AppMonitorJob
spring.fep.scheduler.job.register[0].configClassName=com.syscom.fep.scheduler.job.impl.AppMonitorJobConfig
spring.fep.scheduler.job.register[1].className=com.syscom.fep.scheduler.job.impl.SystemMonitorJob
spring.fep.scheduler.job.register[1].configClassName=com.syscom.fep.scheduler.job.impl.SystemMonitorJobConfig

#AppMonitorJob
spring.fep.scheduler.job.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.scheduler.job.app-monitor.serviceName=${management.metrics.tags.application}
spring.fep.scheduler.job.app-monitor.serviceHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.app-monitor.serviceHostName=${spring.fep.hostname}
spring.fep.scheduler.job.app-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}
spring.fep.scheduler.job.app-monitor.monitorPrimaryUrl=http://10.0.54.34:8730/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.monitorSecondaryUrl=http://10.0.54.33:8730/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.recordHttpLog=true

#SystemMonitorJob
spring.fep.scheduler.job.system-monitor.cronExpression=0 0/1 * * * ?
spring.fep.scheduler.job.system-monitor.systemHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.system-monitor.systemHostName=${spring.fep.hostname}
spring.fep.scheduler.job.system-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}
spring.fep.scheduler.job.system-monitor.monitorPrimaryUrl=http://10.0.54.34:8730/recv/mon/system
spring.fep.scheduler.job.system-monitor.monitorSecondaryUrl=http://10.0.54.33:8730/recv/mon/system
spring.fep.scheduler.job.system-monitor.recordHttpLog=true
spring.fep.scheduler.job.system-monitor.systemMount=/fep,/fep/logs