package com.syscom.fep.web.entity;

public interface WebCodeConstant {
	// 2010/8/4 modified by Daniel for scrollor
	public static final int DetailGridViewPageSize = 10;

	// 2010/2/2 經與明祥討論後，將UI的訊息以此處進行設定取用
	public static final String QueryFail = "資料查詢有誤";
	public static final String QueryNoData = "查無資料";
	public static final String QuerySuccess = "查詢成功";
	public static final String QueryComplete = "查詢完成";
	public static final String InsertSuccess = "新增成功";
	public static final String InsertFail = "新增失敗";
	public static final String UpdateSuccess = "修改成功";
	public static final String UpdateFail = "修改失敗";
	public static final String DeleteSuccess = "刪除成功";
	public static final String DeleteFail = "刪除失敗";
	public static final String ResetSuccess = "重設成功";
	public static final String ResetFail = "重設失敗";
	public static final String SetSuccess = "設定成功";
	public static final String SetFail = "設定失敗";
	public static final String ResponseSuccess = "電文處理成功";
	public static final String ResponseFail = "電文處理失敗";
	public static final String TimeInputFail = "時間輸入不完整";
	public static final String UserIDFail = "身份證字號格式不正確";
	public static final String PrortGroupIDFail = "功能群組代號不能為空";
	public static final String PrortProgIDFail = "程式名稱不能為空";
	public static final String MessageError = "無此錯誤訊息!!請洽資訊人員!";
	public static final String PleaseDoQuery = "請先查詢,再傳送交易處理結果!";
	public static final String CanNotBeResent = "已完成傳送交易處理結果, 不可再次傳送!";
	public static final String NoATMNo = "此櫃員機號不存在ATM主檔中";
	public static final String NoBankID = "此銀行代號不存在全國銀行檔中";
	public static final String PleaseInsertOther = "查無資料,若確定人工沖正請輸入其他欄位資訊";
	public static final String InstructionError = "沖正指示只可輸入000或001";
	public static final String DealSuccess = "交易成功!!";
	public static final String DealFail = "交易失敗!!";
	public static final String ReasonError = "REASON ERROR,無此錯誤代碼!";
	public static final String ModuleNOError = "模組序號(1~12)";
	public static final String MakeRMCDKeyError = "本行換KEY取得新的MAC/SYNC 錯誤";
	public static final String AlreadyChangedKey = "本行已換Key";
	public static final String SelfChangedKey = "本行更換基碼";
	public static final String CancelChangeKeyFail = "取消本行換KEY進行中記號失敗";
	// 2010/7/29 modify by Daniel for add RespDataArrayNoMatch
	public static final String RespDataArrayNoMatch = "負責人姓名/電子郵件/電話個數不一致";
	// 2010/8/4 modify by Daniel for add NoRelatedMSGFILE
	public static final String NoRelatedMSGFILE = "先請增加錯誤訊息檔資料後，再進行資料更新";

	public static final String VirBRNO = "900"; // 虛擬分行
	public static final String FISCNo = "950"; // FISC NO
	public static final String FEPSubNoZero = "00";

	public static final String AlarmDdlError = "警示代碼必須輸入";
	public static final String EventIssueTypeDdlError = "提報類別必須輸入";
	public static final String EventStatusDdlError = "處理狀態必須輸入";
	public static final String QueryConditionCnt = "除營業日期及交易時間外, 請輸入至少一項查詢條件"; // add by Anna Lin 2010/05/25
	public static final String QueryTopNData1 = "因資料過多, 本次查詢只顯示前"; // add by Anna Lin 2010/05/25
	public static final String QueryTopNData2 = "筆資料"; // add by Anna Lin 2010/05/25
	public static final String T1043 = "該帳戶已登記掛失"; // add by henny Lin 2010/05/27
	public static final String T1042 = "卡片狀態非領用/啟用"; // add by henny Lin 2010/05/27
	public static final String T1041 = "MMA金融信用卡掛失後,不可撤掛"; // add by henny Lin 2010/05/27
	public static final String T1044 = "該帳戶已取消掛失"; // add by henny Lin 2010/05/27
	public static final String ProgramExecuting = "程式已在執行中, 請暫時停在此畫面並等候回應"; // add by Ruling 2010/06/17
	public static final String ApidError = "應用系統代號輸入錯誤"; // add by Ruling 2010/06/18
	public static final String DeleteFlgSuccess = "停用成功"; // add by Anna Lin 2010/6/23
	public static final String DeleteFlgFail = "停用失敗"; // add by Anna Lin 2010/6/23
	public static final String SNONotExist = "該ATM機台資料不存在"; // add by Anna Lin 2010/6/28
	public static final String FirstRecord = "此為第一筆資料"; // add by Anna Lin 2010/7/2
	public static final String LastRecord = "此為最後一筆資料"; // add by Anna Lin 2010/7/2
	public static final String NoModelNo = "此型號不存在櫃員機型號檔中"; // add by Anna Lin 2010/7/13
	public static final String SNODisabled = "此廠商序號 (S/N) 己裝機"; // add by Anna Lin 2010/7/14
	public static final String SNOEnabled = "此廠商序號 (S/N) 尚未裝機, 可以繼續進行新增機台"; // add by Anna Lin 2010/7/14,modify by kyo 2011-05-19
	public static final String SNOEnabled_UI060007 = "此機台尚未裝機, 不可進行移機處理"; // add by Anna Lin 2010/7/14
	public static final String FileError = "檔案錯誤，請查明後再處理"; // add by Anna Lin 2010/7/14
	public static final String ATMNONotExist = "該ATM代號不存在，請輸入存在的ATM代號"; // 'add by Anna Lin 2010/7/14
	public static final String ATMDEVRemoveFirst = "該新的ATM代碼，尚未撤機，請先進行撤機作業"; // add by Anna Lin 2010/7/14
	public static final String ATMDEVChangeSuccess = "移穖成功"; // add by Anna Lin 2010/7/14
	public static final String ATMDEVChangeFail = "移穖失敗"; // add by Anna Lin 2010/7/14
	public static final String ATMNotClose = "該ATM已有未結案之事件存在，無需新增"; // add by Anna Lin 2010/7/16
	public static final String ATMNOExist = "該ATM代號有己結案之事件存在"; // 'modified by Anna Lin 2010/7/22
	public static final String ATMNONotExistEVENT = "該ATM代號不存在於EVENT中"; // 'add by Anna Lin 2010/7/22
	public static final String FEPUSER_LOGONIDExist = "該員工編號已存在"; // add by kyo Lai 2010/7/21
	public static final String FEPUSER_TLRNOExist = "該櫃員代號已存在"; // add by kyo Lai 2010/7/21
	public static final String ATMCloseNoLOG = "該事件己結案，不可再新增LOG"; // 'add by Anna Lin 2010/7/23
	public static final String ATMExist = "該ATM代號己存在ATM主檔中, 不可再新增"; // 'add by Anna Lin 2010/7/24
	public static final String ATMDeleted = "該ATM設備，已經撤機，請先復原後再做處理"; // 'add by Anna Lin 2010/7/26
	public static final String ATMNODELOFF = "該ATM代號目前己為啟用狀態"; // 'modified by Anna Lin 2010/7/27
	public static final String ATMNODelOnSuccess = "撤機成功"; // 'modified by Anna Lin 2010/7/28
	public static final String ATMNODelOnFail = "撤機失敗"; // 'modified by Anna Lin 2010/7/28
	public static final String ATMNODelOffSuccess = "復原成功"; // 'modified by Anna Lin 2010/7/28
	public static final String ATMNODelOffFail = "復原失敗"; // 'modified by Anna Lin 2010/7/28
	public static final String ATMDEVModSuccess = "機台變更成功"; // 'add by Anna Lin 2010/7/29
	public static final String ATMDEVModFail = "機台變更失敗"; // 'add by Anna Lin 2010/7/29
	public static final String EVENTGetSeqOK = "取號成功"; // add by Kyo Lai 2010/7/31
	public static final String LenthMoreThenMax = "長度超過最大長度MAX字節"; // add by Maxine Qin 2010/08/26
	public static final String ATMIPExist = "該ATMIP己存在ATM主檔中, 不可再新增"; // 'add by Kyo Lai 2010/09/07
	public static final String WEBATMDenied = "已經設定裝機的ATM代號不能更改為WEBATM"; // 'add by Kyo Lai 2010/09/07
	public static final String EmptyATMIsWEBATM = "未設定裝機的ATM代號只能設定為WEBATM"; // 'add by Kyo Lai 2010/09/07
	public static final String VendorandSNOExist = "此廠商與序號 (S/N) 資料己存在"; // 'add by Ed Hsiao 2010/12/07
	public static final String UpdateHKCbsModeFail = "切換失敗, 香港分行原存行服務尚未暫停"; // 'add by Ed Hsiao 2010/12/07
	public static final String UpdateMOCbsModeFail = "切換失敗, 澳門分行原存行服務尚未暫停"; // 'add by Ed Hsiao 2010/12/07
	public static final String INTLTXNDataNotExist = "不存在該筆國際卡交易資料"; // 'add by Anna Lin 2011/02/22
	public static final String EJFNOComma = "請輸入數字, 若同時查詢多組EJNO請以逗號區隔"; // add by Anna Lin 2011/03/14
	public static final String QueryConditionCnt_UI045500 = "除交易日期外, 請輸入至少一項查詢條件"; // add by Anna Lin 2011/04/13
	public static final String QueryDataFirst = "請先查詢欲更新資料"; // add by Anna Lin 2011/04/22
	public static final String CheckDataFirst = "請先勾選欲更新資料"; // add by Anna Lin 2011/04/22
	public static final String APBRNOError = "只能處理自身分行的卡片"; // add by kyo 2011/07/21
	public static final String EmailError = "負責人Email格式錯誤"; //add by Bruce 2022/06/10
	public static final String PleaseInputEmail = "請輸入負責人Email"; //add by Bruce 2022/06/10
	public static final String HasData =  "必須有資料";//add by Bruce 2022/06/10
	public static final String Multiple = "主鍵值重覆";//add by Bruce 2022/06/10
	public static final String NoStanEjfnoChannelIsRm = "無'STAN','EJFNO'不可查詢";//add by Bruce 2022/06/10
    public static final String requiredFisc = "請務必填寫財金暫停服務的起迄時間";//add by Bruce 2022/07/05
    public static final String requiredIntra = "請務必填寫本行暫停服務的起迄時間";//add by Bruce 2022/07/05
    public static final String startDateBeforeEndDateFisc = "財金暫停服務起始時間需早於結束時間";//add by Bruce 2022/07/05
    public static final String startDateBeforeEndDateIntra = "本行暫停服務起始時間需早於結束時間";//add by Bruce 2022/07/05
    public static final String pleaseTickStartAndEndFirstFisc = "填寫財金跑馬燈起迄時間之前請先勾選是否開啟/關閉自行跑馬燈";//add by Bruce 2022/07/05
    public static final String pleaseTickStartAndEndFirstIntra = "填寫本行跑馬燈起迄時間之前請先勾選是否開啟/關閉自行跑馬燈";//add by Bruce 2022/07/05
    public static final String noAction = "未開啟/關閉任何項目";//add by Bruce 2022/07/05
    public static final String reQueryAfter30Seconds = "請於30秒後重新按查詢按鈕查詢ATM狀態";//add by Bruce 2022/07/05
    public static final String requiredData = "必須有資料";//add by Bruce 2022/07/13
    public static final String startDateOrEndDateNotEntered = "起日或迄日未輸入";//add by Bruce 2022/07/18
    public static final String programError = "程式出現錯誤!!請洽資訊人員!";//add by Bruce 2022/08/09
    public static final String telegramError = "電文格式錯誤!!請洽資訊人員!";//add by Bruce 2023/04/29
    public static final String atmmstrUpdateSuccess = "總共{0}筆，更新成功{1}筆，更新失敗{2}筆 {3}，查無ATM：{4}筆 {5}";//add by Bruce 2023/03/22
    public static final String uploadExcelError = "請上傳EXCEL檔!";//add by Bruce 2023/03/22
    public static final String selectExcelError = "請選擇檔要上傳的檔案!";//add by Bruce 2023/03/22
    public static final String excelContentError = "檔案欄位錯誤，請修正為[機器代號][是否連線至FEP]!";//add by Bruce 2023/03/22 edit by Troy 2023/12/27
    public static final String contentEmpty = "請檢查檔案內是否有資料!";//add by Bruce 2023/03/22
	public static final String DATA_INQUIRY_EXCEPTION_OCCUR = "資料查詢出現異常";
	public static final String DATA_INQUIRY_EXCEPTION_OCCUR_WITH_MESSAGE = "資料查詢{0}出現異常, 異常訊息{1}";
	public static final String enckeyDetailedSuccess = "資料匯入完成,總處理筆數共{0}筆,成功{1}筆(新增{2}筆/更新{3}筆),失敗{4}筆(新增{5}筆/更新{6}筆)";
	public static final String enckeyDetailedSuccessErr = "資料匯入完成,總處理筆數共{0}筆,成功{1}筆(新增{2}筆/更新{3}筆),失敗{4}筆(新增{5}筆/更新{6}筆),資料異常{7}筆";
	public static final String enckeySuccess = "資料匯入完成,總處理筆數共{0}筆,成功{1}筆,失敗{2}筆,資料異常{3}筆";
}
