<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.syscom</groupId>
		<artifactId>feptcb</artifactId>
		<version>1.0.0</version>
	</parent>
	<groupId>com.syscom.feptcb</groupId>
	<artifactId>fep-config</artifactId>
	<name>fep-config</name>
	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>*.properties</include>
					<include>*.xml</include>
					<include>*.p12</include>
					<include>*.cer</include>
					<include>*.conf</include>
				</includes>
				<excludes>
					<exclude>application-devtools.properties</exclude>
					<exclude>mybatis-generator-*.xml</exclude>
					<exclude>*.pem</exclude>
					<exclude>*.jks</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources/pki/fatinst1</directory>
				<targetPath>PKI/fatinst1</targetPath>
			</resource>
			<resource>
				<directory>src/main/resources/pki/fbdinst1</directory>
				<targetPath>PKI/fbdinst1</targetPath>
			</resource>
			<resource>
				<directory>src/main/resources/pki/fhpinst1</directory>
				<targetPath>PKI/fhpinst1</targetPath>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler-plugin-version}</version>
				<configuration>
					<source>${java-source-version}</source>
					<target>${java-target-version}</target>
					<encoding>${project.build.sourceEncoding}</encoding>
					<parameters>true</parameters>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
