server.port=8083

spring.fep.application.name=fep-server

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-graylist
management.endpoint.health.show-details=always

#log
spring.fep.log.total.size.cap=100GB

#register Controller recv message from Gateway via restful
spring.register.controller[0]=com.syscom.fep.server.controller.restful.GRAYLISTQryController

#register Netty recv message from Gateway via restful
#spring.register.bean[0]=com.syscom.fep.server.netty.impl.FISCNettyServer

#API Key
gray.list.apikey = 82c9a94d0223cd5b67c1ddcb1776e87fb06e5d0d5572206ded0aba0e577ea9fe,\
                        86e1213c23adda96d26efb1877a780e48aa49b6167681bcbe750a3829f0b7023,\
                        1d7778117738b1e30ce27ff44a5bd66600f33a1fd04d04d5b1f921667abf56dc