management.metrics.tags.application=fep-batch-cmdline

spring.fep.batch.task.inserteventmessagelog.processToLogNameMap={fep-gateway-cbs:[CBSGW],fep-server-atm:[ATMService],fep-server-fisc:[FISCService],fep-server-imsgw:[IMSGateway],fep-gateway-atm:[ATMGW],fep-gateway-fisc:[FISCGW]}
spring.fep.batch.task.inserteventmessagelog.ignoreLineContainsContent=KeepAlive,FISCService Client