server.port=8213

spring.fep.application.name=fep-server

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-imsgw
management.endpoint.health.show-details=always

#log
spring.fep.log.total.size.cap=100GB

# register IMS Gateway Spring Bean
spring.register.bean[0]=com.syscom.fep.server.gateway.ims.IMSGatewayConfiguration
spring.register.bean[1]=com.syscom.fep.server.gateway.ims.IMSGatewayManager
spring.register.bean[2]=com.syscom.fep.server.gateway.ims.keepalive.IMSGatewayKeepAliveServerConfiguration
spring.register.bean[3]=com.syscom.fep.server.gateway.ims.keepalive.IMSGatewayKeepAliveClientConfiguration
spring.register.bean[4]=com.syscom.fep.server.gateway.ims.keepalive.IMSGatewayKeepAliveRestfulClient

# register Restful Controller for Operation Command
spring.register.controller[0]=com.syscom.fep.server.gateway.ims.IMSGatewayController
# register Restful Controller for Receive and Ack KeepAlive
spring.register.controller[1]=com.syscom.fep.server.gateway.ims.keepalive.IMSGatewayKeepAliveRestfulServer

# Configuration for IMS Gateway
spring.fep.server.gateway.ims.imsApiLogPath=/fep/logs/
spring.fep.server.gateway.ims.sleepForRebuildConnectionInMilliseconds=100
spring.fep.server.gateway.ims.waitTransactionExecutedFinishedBeforeTerminate=true
spring.fep.server.gateway.ims.waitTransactionExecutedFinishedAtMostBeforeTerminateInMilliseconds=10000
spring.fep.server.gateway.ims.clientId=IFEPTA{0},51,55
spring.fep.server.gateway.ims.httpChannel=http://127.0.0.1:8223/recv/ims/channel
spring.fep.server.gateway.ims.httpTimeout=10000
spring.fep.server.gateway.ims.sleepForStartPrimary=3000
spring.fep.server.gateway.ims.mailAddress=richard_yu@email.lingan.com.cn
spring.fep.server.gateway.ims.recordHttpLog=true
#spring.fep.server.gateway.ims.simulatorReceiveAndSend=true

# Primary Sender
spring.fep.server.gateway.ims.primary.sender.host=127.0.0.1
spring.fep.server.gateway.ims.primary.sender.port=6669
spring.fep.server.gateway.ims.primary.sender.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.primary.sender.clientId=IFEPTA52,IFEPTA62
spring.fep.server.gateway.ims.primary.sender.resumeInterval=120000
spring.fep.server.gateway.ims.primary.sender.dataStore=ICONDS

# Primary Alternative Sender
spring.fep.server.gateway.ims.primary.alternative-sender.host=127.0.0.1
spring.fep.server.gateway.ims.primary.alternative-sender.port=6669
spring.fep.server.gateway.ims.primary.alternative-sender.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.primary.alternative-sender.clientId=IFEPTA72,IFEPTA82
spring.fep.server.gateway.ims.primary.alternative-sender.resumeInterval=120000
spring.fep.server.gateway.ims.primary.alternative-sender.dataStore=ICONDS

# Primary Receiver
spring.fep.server.gateway.ims.primary.receiver.host=127.0.0.1
spring.fep.server.gateway.ims.primary.receiver.port=6669
spring.fep.server.gateway.ims.primary.receiver.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.primary.receiver.clientId=IFEPTA51,IFEPTA61
spring.fep.server.gateway.ims.primary.receiver.resumeInterval=120000
spring.fep.server.gateway.ims.primary.receiver.dataStore=ICONDS

# Primary Alternative Receiver
spring.fep.server.gateway.ims.primary.alternative-receiver.host=127.0.0.1
spring.fep.server.gateway.ims.primary.alternative-receiver.port=6669
spring.fep.server.gateway.ims.primary.alternative-receiver.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.primary.alternative-receiver.clientId=IFEPTA71,IFEPTA81
spring.fep.server.gateway.ims.primary.alternative-receiver.resumeInterval=120000
spring.fep.server.gateway.ims.primary.alternative-receiver.dataStore=ICONDS

# Secondary Sender
spring.fep.server.gateway.ims.secondary.sender.host=127.0.0.1
spring.fep.server.gateway.ims.secondary.sender.port=6669
spring.fep.server.gateway.ims.secondary.sender.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.secondary.sender.clientId=IFEPTA54,IFEPTA64
spring.fep.server.gateway.ims.secondary.sender.resumeInterval=120000
spring.fep.server.gateway.ims.secondary.sender.dataStore=ICONDS

# Secondary Alternative Sender
spring.fep.server.gateway.ims.secondary.alternative-sender.host=127.0.0.1
spring.fep.server.gateway.ims.secondary.alternative-sender.port=6669
spring.fep.server.gateway.ims.secondary.alternative-sender.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.secondary.alternative-sender.clientId=IFEPTA74,IFEPTA84
spring.fep.server.gateway.ims.secondary.alternative-sender.resumeInterval=120000
spring.fep.server.gateway.ims.secondary.alternative-sender.dataStore=ICONDS

# Secondary Receiver
spring.fep.server.gateway.ims.secondary.receiver.host=127.0.0.1
spring.fep.server.gateway.ims.secondary.receiver.port=6669
spring.fep.server.gateway.ims.secondary.receiver.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.secondary.receiver.clientId=IFEPTA53,IFEPTA63
spring.fep.server.gateway.ims.secondary.receiver.resumeInterval=120000
spring.fep.server.gateway.ims.secondary.receiver.dataStore=ICONDS

# Secondary Alternative Receiver
spring.fep.server.gateway.ims.secondary.alternative-receiver.host=127.0.0.1
spring.fep.server.gateway.ims.secondary.alternative-receiver.port=6669
spring.fep.server.gateway.ims.secondary.alternative-receiver.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.secondary.alternative-receiver.clientId=IFEPTA73,IFEPTA83
spring.fep.server.gateway.ims.secondary.alternative-receiver.resumeInterval=120000
spring.fep.server.gateway.ims.secondary.alternative-receiver.dataStore=ICONDS

#IMS Gateway KeepAlive Server
spring.fep.server.gateway.ims.keepalive.server.host=${spring.fep.hostip}
spring.fep.server.gateway.ims.keepalive.server.port=8702
#spring.fep.server.gateway.ims.keepalive.server.logging=true

#IMS Gateway KeepAlive Client
spring.fep.server.gateway.ims.keepalive.client.host=${spring.fep.hostip}
spring.fep.server.gateway.ims.keepalive.client.port=8702
spring.fep.server.gateway.ims.keepalive.client.interval=10
spring.fep.server.gateway.ims.keepalive.client.retryCount=3
spring.fep.server.gateway.ims.keepalive.client.retryInterval=5
spring.fep.server.gateway.ims.keepalive.client.timeout=5
spring.fep.server.gateway.ims.keepalive.client.httpKeepAlive=http://localhost:8223/recv/keepalive
#spring.fep.server.gateway.ims.keepalive.client.logging=true

#IMS Gateway Job
spring.fep.server.gateway.ims.app-monitor.cronExpression=0/10 * * * * ?
spring.fep.server.gateway.ims.app-monitor.monitorUrl=http://${spring.fep.hostip}:8201/recv/net/client
spring.fep.server.gateway.ims.app-monitor.recordHttpLog=true
