server.port=8081

#enable https
#server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store=classpath:atmgw-certificate.p12
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=1.0
#server.ssl.key-password=syscom
#server.ssl.key-store-password=syscom

spring.fep.application.name=fep-web

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}
management.endpoint.health.show-details=always

server.servlet.session.tracking-modes=cookie
spring.thymeleaf.prefix=classpath:/templates/

spring.fep.web.title=\u5408\u4F5C\u91D1\u5EAB\u5546\u696D\u9280\u884C
spring.fep.web.web-type=FEP
spring.fep.web.query-only=0
spring.fep.web.demo=true
spring.fep.web.ldap=false
spring.fep.web.ldap.simulator=false
spring.fep.web.time-out=30000
spring.fep.web.subsys=1,2,3,4,5,6,7,8,9,10,11,12,13,14

#FEPMQService\u63A5\u6536\u6307\u4EE4\u7684Port
spring.fep.web.mq.service.port=8161
#FEPMQService\u63A5\u6536\u7684\u5730\u5740
spring.fep.web.mq.service.request=/api/CustomCommand

#For LDAP
spring.fep.web.system.userid=HWAFANG
spring.fep.web.system.principal=HWAFANG@tcbt.com
spring.fep.web.system.sscode=Tcb123456
spring.fep.web.system.webaddress=ldaps://10.0.6.2:636
spring.fep.web.system.strtemp=dc=tcbt,dc=com
spring.fep.web.system.username=HWAFANG
spring.fep.web.system.userinname=HWAFANG
spring.fep.web.system.chkid=G201450209
spring.fep.web.system.unitid=0410
spring.fep.web.system.fileName=fepd.cer
spring.fep.web.system.filesscode=changeit
spring.fep.web.system.certificateName=X.509
spring.fep.web.system.fiddler=fiddler

#APP Monitor
spring.fep.web.app-mon.ip=${spring.fep.hostip}
spring.fep.web.app-mon.port=8201

#Bruce add download log
spring.fep.web.system.download.feplogpath=/fep/logs
spring.fep.web.system.download.fepwaslogpath=/fep/waslogs
spring.fep.web.system.download.feplogarchivespath=/fep/logs/archives
spring.fep.web.system.download.fepwaslogarchivespath=/fep/waslogs/archives

#Bruce add create log path
spring.fep.log.path=/fep/waslogs
spring.fep.log.total.size.cap=100GB

#AP Log
spring.fep.web.aplog[0].server=fepap1T
spring.fep.web.aplog[0].logtype=aplog,waslog
spring.fep.web.aplog[0].service=http://${spring.fep.hostip}:${server.port}/UI060610/GetAPLog
spring.fep.web.aplog[1].server=fepap2T
spring.fep.web.aplog[1].logtype=aplog,waslog
spring.fep.web.aplog[1].service=http://${spring.fep.hostip}:${server.port}/UI060610/GetAPLog
spring.fep.web.aplog[2].server=fepgw1T
spring.fep.web.aplog[2].logtype=aplog
spring.fep.web.aplog[2].service=http://${spring.fep.hostip}:8302/fepgwagent/GetAPLog
spring.fep.web.aplog[3].server=fepgw2T
spring.fep.web.aplog[3].logtype=aplog
spring.fep.web.aplog[3].service=http://${spring.fep.hostip}:8302/fepgwagent/GetAPLog

#Web Audit Interceptor
spring.fep.web.interceptor.audit.enableAudit=true
spring.fep.web.interceptor.audit.showAudit=false
spring.fep.web.interceptor.audit.flushIntervalInMilliseconds=5000

#Queue Receiver
spring.fep.web.queue.ctrlUri.getConcurrency=http://{0}:{1}/consumers/{2}/getConcurrency
spring.fep.web.queue.ctrlUri.setConcurrency=http://{0}:{1}/consumers/{2}/setConcurrency
spring.fep.web.queue.receiver[0].programName=EATMServerReceiver
spring.fep.web.queue.receiver[0].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[0].port=8080
spring.fep.web.queue.receiver[1].programName=HCEServerReceiver
spring.fep.web.queue.receiver[1].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[1].port=8080
spring.fep.web.queue.receiver[2].programName=IVRServerReceiver
spring.fep.web.queue.receiver[2].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[2].port=8080
spring.fep.web.queue.receiver[3].programName=MBServerReceiver
spring.fep.web.queue.receiver[3].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[3].port=8080
spring.fep.web.queue.receiver[4].programName=MFTServerReceiver
spring.fep.web.queue.receiver[4].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[4].port=8080
spring.fep.web.queue.receiver[5].programName=NBServerReceiver
spring.fep.web.queue.receiver[5].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[5].port=8080
spring.fep.web.queue.receiver[6].programName=PYBatchReceiver
spring.fep.web.queue.receiver[6].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[6].port=8080
spring.fep.web.queue.receiver[7].programName=TWMPServerReceiver
spring.fep.web.queue.receiver[7].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[7].port=8080
spring.fep.web.queue.receiver[8].programName=TestReceiver
spring.fep.web.queue.receiver[8].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[8].port=8080

#FISC Gateway Agent
spring.fep.web.fisc.ctrlUri.start=http://{0}:{1}/recv/fisc/start
spring.fep.web.fisc.ctrlUri.stop=http://{0}:{1}/recv/fisc/stop
spring.fep.web.fisc.ctrlUri.channel=http://{0}:{1}/recv/fisc/channel
spring.fep.web.fisc.ctrlUri.check=http://{0}:{1}/recv/fisc/check
spring.fep.web.fisc.waitInMillisecondsAfterStartAndStop=10000
spring.fep.web.fisc.agent[0].name=FISCGW1
spring.fep.web.fisc.agent[0].ip=${spring.fep.hostip}
spring.fep.web.fisc.agent[0].port=8304
spring.fep.web.fisc.agent[1].name=FISCGW2
spring.fep.web.fisc.agent[1].ip=${spring.fep.hostip}
spring.fep.web.fisc.agent[1].port=8304

#Simple Netty Server
spring.fep.web.simple.netty.ctrlUri.getEventExecutorData=http://{0}:{1}/recv/{2}/getEventExecutorData
spring.fep.web.simple.netty.ctrlUri.setEventExecutorThreads=http://{0}:{1}/recv/{2}/setEventExecutorThreads
spring.fep.web.simple.netty.server[0].name=ATM Service
spring.fep.web.simple.netty.server[0].programName=ATMNettyServer
spring.fep.web.simple.netty.server[0].ip=${spring.fep.hostip}
spring.fep.web.simple.netty.server[0].port=8080
spring.fep.web.simple.netty.server[1].name=FISC Service
spring.fep.web.simple.netty.server[1].programName=FISCNettyServer
spring.fep.web.simple.netty.server[1].ip=${spring.fep.hostip}
spring.fep.web.simple.netty.server[1].port=8080

#CBS Gateway
spring.fep.web.cbs.ctrlUri.getAllLineStatus=http://{0}:{1}/recv/cbs/getAllLineStatus
spring.fep.web.cbs.ctrlUri.changeLineStatus=http://{0}:{1}/recv/cbs/changeLineStatus
spring.fep.web.cbs.ctrlUri.changeServerStatus=http://{0}:{1}/recv/cbs/changeServerStatus
spring.fep.web.cbs.waitInMillisecondsAfterChangeLineStatus=1000
spring.fep.web.cbs.primaryReadOnly=true
spring.fep.web.cbs.gw[0].ip=${spring.fep.hostip}
spring.fep.web.cbs.gw[0].port=8305
spring.fep.web.cbs.gw[1].ip=${spring.fep.hostip}
spring.fep.web.cbs.gw[1].port=8315

#IMS Gateway
spring.fep.web.ims.ctrlUri.getAllLineStatus=http://{0}:{1}/recv/ims/getAllLineStatus
spring.fep.web.ims.ctrlUri.changeLineStatus=http://{0}:{1}/recv/ims/changeLineStatus
spring.fep.web.ims.waitInMillisecondsAfterChangeLineStatus=1000
spring.fep.web.ims.gw[0].ip=${spring.fep.hostip}
spring.fep.web.ims.gw[0].port=8213
spring.fep.web.ims.gw[1].ip=${spring.fep.hostip}
spring.fep.web.ims.gw[1].port=8223

#FEPTXNQry API Key
spring.fep.web.apikey = c884cf9291361c3381bded302b1e91c87d9bf600304581a432962b3eb047e542,\
                        82b3445fef4f3ec2d28f9a5dc8b4d1b36a064178c02e0e24e90cfeba5d5b25d7,\
                        4f99353377f58c43c5f6a77f7248c0506ff656354288598d39e8850f9ae575b0
#FEPUCDQry API Key
spring.fep.web.ucd.apikey = 1eab68ce245da6402493faabea64ab7a35828b128b6bbe6d2717487ea40d69e,\
                            d8d31a136c005431b8e2c3d9cd07e4bf9e1d448e6ab6a07f98917181bda7f72b

# Channel & AppName Mapping for fepap
spring.fep.web.apChannelToAppName.FISC=fep-server-fisc
spring.fep.web.apChannelToAppName.ATM=fep-server-atm
spring.fep.web.apChannelToAppName.BIZ=fep-server-biz
spring.fep.web.apChannelToAppName.DIG=fep-server-dig
spring.fep.web.apChannelToAppName.EAT=fep-server-eat
spring.fep.web.apChannelToAppName.EDI=fep-server-edi
spring.fep.web.apChannelToAppName.EIP=fep-server-eip
spring.fep.web.apChannelToAppName.EOI=fep-server-eoi
spring.fep.web.apChannelToAppName.FID=fep-server-fid
spring.fep.web.apChannelToAppName.HCA=fep-server-hca
spring.fep.web.apChannelToAppName.HLN=fep-server-hln
spring.fep.web.apChannelToAppName.IVR=fep-server-ivr
spring.fep.web.apChannelToAppName.MBQ=fep-server-mbq
spring.fep.web.apChannelToAppName.MFT=fep-server-mft
spring.fep.web.apChannelToAppName.MQQ=fep-server-mqq
spring.fep.web.apChannelToAppName.MSQ=fep-server-msq
spring.fep.web.apChannelToAppName.NBB=fep-server-nbb
spring.fep.web.apChannelToAppName.NBP=fep-server-nbp
spring.fep.web.apChannelToAppName.NBQ=fep-server-nbq
spring.fep.web.apChannelToAppName.ONL=fep-server-onl
spring.fep.web.apChannelToAppName.POS=fep-server-pos
spring.fep.web.apChannelToAppName.SSO=fep-server-sso
spring.fep.web.apChannelToAppName.VO=fep-server-vo

# Channel & AppName Mapping for fepgw
spring.fep.web.gwChannelToAppName.FISC=fep-gateway-fisc;fep-gateway-fisc-agent
spring.fep.web.gwChannelToAppName.ATM=fep-gateway-atm;fep-gateway-atm-agent
spring.fep.web.gwChannelToAppName.CBS=fep-gateway-cbs