server.port=8305
server.servlet.context-path=

spring.fep.application.name=fep-gateway

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-cbs
management.endpoint.health.show-details=always

spring.fep.ims.enableTrace=true

#log
spring.fep.log.total.size.cap=50GB

#CBSGatewayManager
spring.register.bean[0]=com.syscom.fep.gateway.ims.cbs.CBSGatewayManager
#CBSGatewayCtrl
spring.register.controller[0]=com.syscom.fep.gateway.ims.cbs.CBSGatewayCtrl

#CBS Gateway Server
spring.fep.gateway.transmission.cbs.fepap[0].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[0].port=8752
spring.fep.gateway.transmission.cbs.fepap[0].bisThreadNum=200
spring.fep.gateway.transmission.cbs.fepap[0].cbsType=CBS
spring.fep.gateway.transmission.cbs.fepap[0].retrySendToIMS=false

spring.fep.gateway.transmission.cbs.fepap[1].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[1].port=8754
spring.fep.gateway.transmission.cbs.fepap[1].bisThreadNum=200
spring.fep.gateway.transmission.cbs.fepap[1].cbsType=FISC

spring.fep.gateway.transmission.cbs.fepap[2].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[2].port=8756
spring.fep.gateway.transmission.cbs.fepap[2].bisThreadNum=200
spring.fep.gateway.transmission.cbs.fepap[2].cbsType=473X

spring.fep.gateway.transmission.cbs.fepap[3].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[3].port=8758
spring.fep.gateway.transmission.cbs.fepap[3].bisThreadNum=200
spring.fep.gateway.transmission.cbs.fepap[3].cbsType=NONATM

spring.fep.gateway.transmission.cbs.fepap[4].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[4].port=8760
spring.fep.gateway.transmission.cbs.fepap[4].bisThreadNum=200
spring.fep.gateway.transmission.cbs.fepap[4].cbsType=FISCTCB

#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[0].host=127.0.0.1
spring.fep.gateway.transmission.cbs.sender[0].port=6669
spring.fep.gateway.transmission.cbs.sender[0].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[0].clientId=IFEPTA01,IFEPTA02,IFEPTA03,IFEPTA04
spring.fep.gateway.transmission.cbs.sender[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[0].cbsType=CBS

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[0].host=127.0.0.1
spring.fep.gateway.transmission.cbs.receiver[0].port=6669
spring.fep.gateway.transmission.cbs.receiver[0].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.receiver[0].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[0].clientId=IFEPTB01,IFEPTB02,IFEPTB03,IFEPTB04
spring.fep.gateway.transmission.cbs.receiver[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[0].cbsType=CBS

#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[1].host=127.0.0.1
spring.fep.gateway.transmission.cbs.sender[1].port=6669
spring.fep.gateway.transmission.cbs.sender[1].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[1].clientId=IFEPTA11,IFEPTA12,IFEPTA13,IFEPTA14
spring.fep.gateway.transmission.cbs.sender[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[1].cbsType=FISC

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[1].host=127.0.0.1
spring.fep.gateway.transmission.cbs.receiver[1].port=6669
spring.fep.gateway.transmission.cbs.receiver[1].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.receiver[1].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[1].clientId=IFEPTB11,IFEPTB12,IFEPTB13,IFEPTB14
spring.fep.gateway.transmission.cbs.receiver[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[1].cbsType=FISC

#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[2].host=127.0.0.1
spring.fep.gateway.transmission.cbs.sender[2].port=6669
spring.fep.gateway.transmission.cbs.sender[2].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[2].clientId=IFEPTA21,IFEPTA22,IFEPTA23,IFEPTA24
spring.fep.gateway.transmission.cbs.sender[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[2].cbsType=473X

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[2].host=127.0.0.1
spring.fep.gateway.transmission.cbs.receiver[2].port=6669
spring.fep.gateway.transmission.cbs.receiver[2].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.receiver[2].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[2].clientId=IFEPTB21,IFEPTB22,IFEPTB23,IFEPTB24
spring.fep.gateway.transmission.cbs.receiver[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[2].cbsType=473X

#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[3].host=127.0.0.1
spring.fep.gateway.transmission.cbs.sender[3].port=6669
spring.fep.gateway.transmission.cbs.sender[3].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[3].clientId=IFEPTA31,IFEPTA32,IFEPTA33,IFEPTA34
spring.fep.gateway.transmission.cbs.sender[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[3].cbsType=NONATM

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[3].host=127.0.0.1
spring.fep.gateway.transmission.cbs.receiver[3].port=6669
spring.fep.gateway.transmission.cbs.receiver[3].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.receiver[3].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[3].clientId=IFEPTB31,IFEPTB32,IFEPTB33,IFEPTB34
spring.fep.gateway.transmission.cbs.receiver[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[3].cbsType=NONATM

#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[4].host=127.0.0.1
spring.fep.gateway.transmission.cbs.sender[4].port=6669
spring.fep.gateway.transmission.cbs.sender[4].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[4].clientId=IFEPTA41,IFEPTA42,IFEPTA43,IFEPTA44
spring.fep.gateway.transmission.cbs.sender[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[4].cbsType=FISCTCB

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[4].host=127.0.0.1
spring.fep.gateway.transmission.cbs.receiver[4].port=6669
spring.fep.gateway.transmission.cbs.receiver[4].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.receiver[4].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[4].clientId=IFEPTB41,IFEPTB42,IFEPTB43,IFEPTB44
spring.fep.gateway.transmission.cbs.receiver[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[4].cbsType=FISCTCB

#CBS Gateway Alternative Sender
spring.fep.gateway.transmission.cbs.alternative-sender[0].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-sender[0].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[0].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[0].clientId=IFEPTC01,IFEPTC02,IFEPTC03,IFEPTC04
spring.fep.gateway.transmission.cbs.alternative-sender[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[0].cbsType=CBS

#CBS Gateway Alternative Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[0].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-receiver[0].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[0].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-receiver[0].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[0].clientId=IFEPTD01,IFEPTD02,IFEPTD03,IFEPTD04
spring.fep.gateway.transmission.cbs.alternative-receiver[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[0].cbsType=CBS

#CBS Gateway Alternative Sender
spring.fep.gateway.transmission.cbs.alternative-sender[1].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-sender[1].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[1].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[1].clientId=IFEPTC11,IFEPTC12,IFEPTC13,IFEPTC14
spring.fep.gateway.transmission.cbs.alternative-sender[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[1].cbsType=FISC

#CBS Gateway Alternative Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[1].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-receiver[1].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[1].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-receiver[1].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[1].clientId=IFEPTD11,IFEPTD12,IFEPTD13,IFEPTD14
spring.fep.gateway.transmission.cbs.alternative-receiver[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[1].cbsType=FISC

#CBS Gateway Alternative Sender
spring.fep.gateway.transmission.cbs.alternative-sender[2].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-sender[2].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[2].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[2].clientId=IFEPTC21,IFEPTC22,IFEPTC23,IFEPTC24
spring.fep.gateway.transmission.cbs.alternative-sender[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[2].cbsType=473X

#CBS Gateway Alternative Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[2].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-receiver[2].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[2].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-receiver[2].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[2].clientId=IFEPTD21,IFEPTD22,IFEPTD23,IFEPTD24
spring.fep.gateway.transmission.cbs.alternative-receiver[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[2].cbsType=473X

#CBS Gateway Alternative Sender
spring.fep.gateway.transmission.cbs.alternative-sender[3].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-sender[3].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[3].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[3].clientId=IFEPTC31,IFEPTC32,IFEPTC33,IFEPTC34
spring.fep.gateway.transmission.cbs.alternative-sender[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[3].cbsType=NONATM

#CBS Gateway Alternative Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[3].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-receiver[3].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[3].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-receiver[3].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[3].clientId=IFEPTD31,IFEPTD32,IFEPTD33,IFEPTD34
spring.fep.gateway.transmission.cbs.alternative-receiver[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[3].cbsType=NONATM

#CBS Gateway Alternative Sender
spring.fep.gateway.transmission.cbs.alternative-sender[4].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-sender[4].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[4].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[4].clientId=IFEPTC41,IFEPTC42,IFEPTC43,IFEPTC44
spring.fep.gateway.transmission.cbs.alternative-sender[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[4].cbsType=FISCTCB

#CBS Gateway Alternative Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[4].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-receiver[4].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[4].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-receiver[4].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[4].clientId=IFEPTD41,IFEPTD42,IFEPTD43,IFEPTD44
spring.fep.gateway.transmission.cbs.alternative-receiver[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[4].cbsType=FISCTCB

#register Scheduler Job
spring.fep.scheduler.job.register[0].className=com.syscom.fep.scheduler.job.impl.AppMonitorJob
spring.fep.scheduler.job.register[0].configClassName=com.syscom.fep.scheduler.job.impl.AppMonitorJobConfig
spring.fep.scheduler.job.register[1].className=com.syscom.fep.gateway.job.cbs.CBSGatewayAppMonitorJob
spring.fep.scheduler.job.register[1].configClassName=com.syscom.fep.gateway.job.cbs.CBSGatewayAppMonitorJobConfig

#AppMonitorJob
spring.fep.scheduler.job.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.scheduler.job.app-monitor.serviceName=${management.metrics.tags.application}
spring.fep.scheduler.job.app-monitor.serviceHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.app-monitor.serviceHostName=${spring.fep.hostname}
spring.fep.scheduler.job.app-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}${server.servlet.context-path}
spring.fep.scheduler.job.app-monitor.monitorPrimaryUrl=http://${spring.fep.hostip}:8201/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.monitorSecondaryUrl=http://${spring.fep.hostip}:8201/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.recordHttpLog=true

#CBS Gateway Job
spring.fep.gateway.job.cbs.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.gateway.job.cbs.app-monitor.monitorUrl=http://${spring.fep.hostip}:8201/recv/net/client
spring.fep.gateway.job.cbs.app-monitor.recordHttpLog=true