server.port=8300

spring.fep.application.name=fep-gateway

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-atm
management.endpoint.health.show-details=always

#log
spring.fep.log.total.size.cap=50GB

#register ATM Gateway Server
spring.fep.gateway.register[0].gtwClassName=com.syscom.fep.gateway.netty.atm.ATMGatewayServer
spring.fep.gateway.register[0].hdrClassName=com.syscom.fep.gateway.netty.atm.ATMGatewayServerChannelInboundHandlerAdapter
spring.fep.gateway.register[0].mgrClassName=com.syscom.fep.gateway.netty.atm.ATMGatewayServerProcessRequestManager
spring.fep.gateway.register[0].cnfClassName=com.syscom.fep.gateway.netty.atm.ATMGatewayServerConfiguration
spring.fep.gateway.register[0].ipfClassName=com.syscom.fep.gateway.netty.atm.ATMGatewayServerRuleIpFilter

#ATM Gateway Server
spring.fep.gateway.transmission.atm.host=${spring.fep.hostip}
spring.fep.gateway.transmission.atm.port=18090
spring.fep.gateway.transmission.atm.reestablishConnectionInterval=3000
spring.fep.gateway.transmission.atm.bypassCheckAtmIp=
spring.fep.gateway.transmission.atm.sslNeedClientAuth=false
spring.fep.gateway.transmission.atm.backlog=100
spring.fep.gateway.transmission.atm.tcpKeepIdle=120
spring.fep.gateway.transmission.atm.tcpKeepInterval=10
spring.fep.gateway.transmission.atm.timeout=70000
spring.fep.gateway.transmission.atm.bisThreadNum=300
spring.fep.gateway.transmission.atm.handshakeTimeoutMillis=12000
spring.fep.gateway.transmission.atm.checkClientFailedTimesLimit=99
spring.fep.gateway.transmission.atm.clearBlackListInterval=1
spring.fep.gateway.transmission.atm.checkAtmServiceInterval=5
spring.fep.gateway.transmission.atm.keepAliveTimesForUpdateAtmstate=5
spring.fep.gateway.transmission.atm.tofepatm[0].host=${spring.fep.hostip}
spring.fep.gateway.transmission.atm.tofepatm[0].port=8731
spring.fep.gateway.transmission.atm.tofepatm[1].host=${spring.fep.hostip}
spring.fep.gateway.transmission.atm.tofepatm[1].port=8731
#spring.fep.gateway.transmission.atm.loadTestMode=true

#register Scheduler Job
spring.fep.scheduler.job.register[0].className=com.syscom.fep.scheduler.job.impl.AppMonitorJob
spring.fep.scheduler.job.register[0].configClassName=com.syscom.fep.scheduler.job.impl.AppMonitorJobConfig
spring.fep.scheduler.job.register[1].className=com.syscom.fep.gateway.job.atm.ATMGatewayServerAppMonitorJob
spring.fep.scheduler.job.register[1].configClassName=com.syscom.fep.gateway.job.atm.ATMGatewayServerAppMonitorJobConfig

#AppMonitorJob
spring.fep.scheduler.job.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.scheduler.job.app-monitor.serviceName=${management.metrics.tags.application}
spring.fep.scheduler.job.app-monitor.serviceHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.app-monitor.serviceHostName=${spring.fep.hostname}
spring.fep.scheduler.job.app-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}
spring.fep.scheduler.job.app-monitor.monitorPrimaryUrl=http://${spring.fep.hostip}:8201/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.monitorSecondaryUrl=http://${spring.fep.hostip}:8201/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.recordHttpLog=true

#ATM Gateway Server ATM Client Monitor Data Job
spring.fep.gateway.job.atm.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.gateway.job.atm.app-monitor.monitorUrl=http://${spring.fep.hostip}:8201/recv/net/server
spring.fep.gateway.job.atm.app-monitor.recordHttpLog=true