server.port=8304

spring.fep.application.name=fep-gateway

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-fisc-agent
management.endpoint.health.show-details=always

#FISC Gateway Client Agent
spring.register.bean[0]=com.syscom.fep.gateway.agent.fisc.FISCGatewayClientAgentConfiguration
spring.register.bean[1]=com.syscom.fep.gateway.agent.fisc.FISCGatewayClientAgentJobLauncher
spring.register.controller[0]=com.syscom.fep.gateway.agent.fisc.FISCGatewayClientAgent
spring.register.controller[1]=com.syscom.fep.frmcommon.restful.processcommand.ProcessCommandController

#FISC Gateway Client Agent Configuration
spring.fep.gateway.agent.fisc.cmdStart=E:/FEP/git-db2-TCBFEP/source/fep-assembly/fep-app/fep-gateway-fisc/fep-gateway-fisc-run.bat
spring.fep.gateway.agent.fisc.httpTerminate=http://${spring.fep.hostip}:8301/recv/fisc/terminate
spring.fep.gateway.agent.fisc.httpOperate=http://${spring.fep.hostip}:8301/recv/fisc/operate
spring.fep.gateway.agent.fisc.httpChangeFEPAP=http://${spring.fep.hostip}:8301/recv/fisc/changefepap
spring.fep.gateway.agent.fisc.httpCheckFEPAP=http://${spring.fep.hostip}:8301/recv/fisc/checkfepap
spring.fep.gateway.agent.fisc.recordHttpLog=true
spring.fep.gateway.agent.fisc.printInputStream=true
spring.fep.gateway.agent.fisc.gwLogPath=/fep/logs/{yyyy-MM-dd}/fep-gateway-fisc/fep-gateway-fisc-FISCGW-{logKind}-{yyyy-MM-dd}-(.*).log
spring.fep.gateway.agent.fisc.cmd.clear=/bin/sh -c clear

#FISC Gateway Client Agent Configuration ProcessCommandJobs
# spring.fep.gateway.agent.fisc.cmdJobConfig[0].cronExpression=0/5 * * * * ?
# spring.fep.gateway.agent.fisc.cmdJobConfig[0].command=ping 127.0.0.1
# spring.fep.gateway.agent.fisc.cmdJobConfig[0].output=true
# spring.fep.gateway.agent.fisc.cmdJobConfig[0].outputCharsetName=GB2312
# spring.fep.gateway.agent.fisc.cmdJobConfig[1].cronExpression=0/10 * * * * ?
# spring.fep.gateway.agent.fisc.cmdJobConfig[1].command=ping 192.168.30.30
# spring.fep.gateway.agent.fisc.cmdJobConfig[1].output=true
# spring.fep.gateway.agent.fisc.cmdJobConfig[1].outputCharsetName=GB2312

#register Scheduler Job
spring.fep.scheduler.job.register[0].className=com.syscom.fep.scheduler.job.impl.AppMonitorJob
spring.fep.scheduler.job.register[0].configClassName=com.syscom.fep.scheduler.job.impl.AppMonitorJobConfig
spring.fep.scheduler.job.register[1].className=com.syscom.fep.scheduler.job.impl.SystemMonitorJob
spring.fep.scheduler.job.register[1].configClassName=com.syscom.fep.scheduler.job.impl.SystemMonitorJobConfig

#AppMonitorJob
spring.fep.scheduler.job.app-monitor.cronExpression=0/10 * * * * ?
spring.fep.scheduler.job.app-monitor.serviceName=${management.metrics.tags.application}
spring.fep.scheduler.job.app-monitor.serviceHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.app-monitor.serviceHostName=${spring.fep.hostname}
spring.fep.scheduler.job.app-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}
spring.fep.scheduler.job.app-monitor.monitorPrimaryUrl=http://${spring.fep.hostip}:8201/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.monitorSecondaryUrl=http://${spring.fep.hostip}:8201/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.recordHttpLog=true

#SystemMonitorJob
spring.fep.scheduler.job.system-monitor.cronExpression=0/10 * * * * ?
spring.fep.scheduler.job.system-monitor.systemHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.system-monitor.systemHostName=${spring.fep.hostname}
spring.fep.scheduler.job.system-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}
spring.fep.scheduler.job.system-monitor.monitorPrimaryUrl=http://${spring.fep.hostip}:8201/recv/mon/system
spring.fep.scheduler.job.system-monitor.monitorSecondaryUrl=http://${spring.fep.hostip}:8201/recv/mon/system
spring.fep.scheduler.job.system-monitor.systemMount=/fep,/fep/logs,/fep/waslogs
spring.fep.scheduler.job.system-monitor.systemMountInterval=20000
spring.fep.scheduler.job.system-monitor.recordHttpLog=true
