#First SSL
# spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeyPath=fep-atmgwd.p12
# spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeySscode=ENC(mz0wIIvOHSllkMorjgfcTQpMEFIC65j+Kg0KmyPidYfQOhrKD59nGrtkS+Or9wQb)
# spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeyType=PKCS12
#Second SSL
# spring.fep.gateway.transmission.atm.sslConfigs[1].sslKeyPath=atmgw-certificate_2.p12
# spring.fep.gateway.transmission.atm.sslConfigs[1].sslKeySscode=ENC(mz0wIIvOHSllkMorjgfcTQpMEFIC65j+Kg0KmyPidYfQOhrKD59nGrtkS+Or9wQb)
# spring.fep.gateway.transmission.atm.sslConfigs[1].sslKeyType=PKCS12

spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeyPath=root.p12
spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeySscode=syscom
spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeyType=PKCS12

spring.fep.gateway.transmission.atm.sslConfigs[1].sslKeyPath=root2.p12
spring.fep.gateway.transmission.atm.sslConfigs[1].sslKeySscode=syscom
spring.fep.gateway.transmission.atm.sslConfigs[1].sslKeyType=PKCS12

spring.fep.gateway.transmission.atm.sslConfigs[2].sslKeyPath=root3.p12
spring.fep.gateway.transmission.atm.sslConfigs[2].sslKeySscode=syscom
spring.fep.gateway.transmission.atm.sslConfigs[2].sslKeyType=PKCS12

spring.fep.gateway.transmission.atm.sslConfigs[3].sslKeyPath=atmgw-certificate_expired.p12
spring.fep.gateway.transmission.atm.sslConfigs[3].sslKeySscode=syscom
spring.fep.gateway.transmission.atm.sslConfigs[3].sslKeyType=PKCS12

spring.fep.gateway.transmission.atm.sslConfigs[4].sslKeyPath=fep-3.p12
spring.fep.gateway.transmission.atm.sslConfigs[4].sslKeySscode=1qaz@WSX
spring.fep.gateway.transmission.atm.sslConfigs[4].sslKeyType=PKCS12