server.port=8080

spring.fep.application.name=fep-server

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-fido
management.endpoint.health.show-details=always

#log
spring.fep.log.total.size.cap=100GB

#register Receiver
spring.register.bean[0]=com.syscom.fep.server.queue.FIDOServerReceiver

#FIDO Map Queue
#spring.fep.jms.fido.debug=-1
spring.fep.jms.fido.prop[0].queueManager=QM1
spring.fep.jms.fido.prop[0].channel=DEV.ADMIN.SVRCONN
spring.fep.jms.fido.prop[0].connName=10.3.101.3(1414)
spring.fep.jms.fido.prop[0].user=admin
spring.fep.jms.fido.prop[0].password=ENC(qTrx9C64J6cFB8P4TTt6KGEUyAqe2TdRtf5FhZAtl10LZI15gP9KVJXklM9+dbuV)
#spring.fep.jms.fido.prop[0].queue-names.fidoAck.destination=FIDO1.FEP.ONLINE.RS
#spring.fep.jms.fido.prop[0].replyTo=queue://QMAAIT01/FIDO1.FEP.ONLINE.RS?targetClient=1
#spring.fep.jms.fido.prop[1].queueManager=QM1
#spring.fep.jms.fido.prop[1].channel=DEV.ADMIN.SVRCONN
#spring.fep.jms.fido.prop[1].connName=10.3.101.3(1414)
#spring.fep.jms.fido.prop[1].user=admin
#spring.fep.jms.fido.prop[1].password=ENC(qTrx9C64J6cFB8P4TTt6KGEUyAqe2TdRtf5FhZAtl10LZI15gP9KVJXklM9+dbuV)
#spring.fep.jms.fido.prop[1].queue-names.fidoAck.destination=FIDO2.FEP.ONLINE.RS
#spring.fep.jms.fido.prop[1].replyTo=queue://QMAAIT02/FIDO2.FEP.ONLINE.RS?targetClient=1