server.port=8085

spring.fep.application.name=fep-batch

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}
management.endpoint.health.show-details=always

spring.fep.batch.subsys=1;2
spring.fep.batch.mailsender=fep2022@qq.com
spring.fep.batch.maillist=richard_yu@email.lingan.com.cn
spring.fep.batch.updateNextRunTimeInitialDelayMilliseconds=30000
spring.fep.batch.updateNextRunTimeIntervalMilliseconds=60000
spring.fep.batch.quartzProperties=quartz-batch-fepap2.properties
spring.fep.batch.execute.develop=true

spring.fep.hostname=fepap2

#BATCH
spring.fep.jms.batch.prop.queueManager=QM1
spring.fep.jms.batch.prop.channel=DEV.ADMIN.SVRCONN
spring.fep.jms.batch.prop.connName=localhost(1414)
spring.fep.jms.batch.prop.user=admin
spring.fep.jms.batch.prop.password=ENC(qTrx9C64J6cFB8P4TTt6KGEUyAqe2TdRtf5FhZAtl10LZI15gP9KVJXklM9+dbuV)

spring.fep.jms.queue-names.batch.destination=BATCH_QUEUE2