server.port=8315
server.servlet.context-path=

spring.fep.application.name=fep-gateway

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-cbs2
management.endpoint.health.show-details=always

spring.fep.hostname=fepap2

spring.fep.ims.enableTrace=true

#log
spring.fep.log.total.size.cap=50GB

#CBSGatewayManager
spring.register.bean[0]=com.syscom.fep.gateway.ims.cbs.CBSGatewayManager
#CBSGatewayCtrl
spring.register.controller[0]=com.syscom.fep.gateway.ims.cbs.CBSGatewayCtrl

#CBS Gateway Server
spring.fep.gateway.transmission.cbs.fepap[0].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[0].port=8762
spring.fep.gateway.transmission.cbs.fepap[0].bisThreadNum=200
spring.fep.gateway.transmission.cbs.fepap[0].cbsType=CBS
spring.fep.gateway.transmission.cbs.fepap[0].retrySendToIMS=false

spring.fep.gateway.transmission.cbs.fepap[1].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[1].port=8764
spring.fep.gateway.transmission.cbs.fepap[1].bisThreadNum=200
spring.fep.gateway.transmission.cbs.fepap[1].cbsType=FISC

spring.fep.gateway.transmission.cbs.fepap[2].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[2].port=8766
spring.fep.gateway.transmission.cbs.fepap[2].bisThreadNum=200
spring.fep.gateway.transmission.cbs.fepap[2].cbsType=473X

spring.fep.gateway.transmission.cbs.fepap[3].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[3].port=8768
spring.fep.gateway.transmission.cbs.fepap[3].bisThreadNum=200
spring.fep.gateway.transmission.cbs.fepap[3].cbsType=NONATM

spring.fep.gateway.transmission.cbs.fepap[4].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[4].port=8770
spring.fep.gateway.transmission.cbs.fepap[4].bisThreadNum=200
spring.fep.gateway.transmission.cbs.fepap[4].cbsType=FISCTCB

#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[0].host=127.0.0.1
spring.fep.gateway.transmission.cbs.sender[0].port=6669
spring.fep.gateway.transmission.cbs.sender[0].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[0].clientId=IFEPTA05,IFEPTA06,IFEPTA07,IFEPTA08
spring.fep.gateway.transmission.cbs.sender[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[0].cbsType=CBS

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[0].host=127.0.0.1
spring.fep.gateway.transmission.cbs.receiver[0].port=6669
spring.fep.gateway.transmission.cbs.receiver[0].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.receiver[0].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[0].clientId=IFEPTB05,IFEPTB06,IFEPTB07,IFEPTB08
spring.fep.gateway.transmission.cbs.receiver[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[0].cbsType=CBS

#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[1].host=127.0.0.1
spring.fep.gateway.transmission.cbs.sender[1].port=6669
spring.fep.gateway.transmission.cbs.sender[1].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[1].clientId=IFEPTA15,IFEPTA16,IFEPTA17,IFEPTA18
spring.fep.gateway.transmission.cbs.sender[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[1].cbsType=FISC

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[1].host=127.0.0.1
spring.fep.gateway.transmission.cbs.receiver[1].port=6669
spring.fep.gateway.transmission.cbs.receiver[1].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.receiver[1].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[1].clientId=IFEPTB15,IFEPTB16,IFEPTB17,IFEPTB18
spring.fep.gateway.transmission.cbs.receiver[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[1].cbsType=FISC

#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[2].host=127.0.0.1
spring.fep.gateway.transmission.cbs.sender[2].port=6669
spring.fep.gateway.transmission.cbs.sender[2].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[2].clientId=IFEPTA25,IFEPTA26,IFEPTA27,IFEPTA28
spring.fep.gateway.transmission.cbs.sender[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[2].cbsType=473X

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[2].host=127.0.0.1
spring.fep.gateway.transmission.cbs.receiver[2].port=6669
spring.fep.gateway.transmission.cbs.receiver[2].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.receiver[2].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[2].clientId=IFEPTB25,IFEPTB26,IFEPTB27,IFEPTB28
spring.fep.gateway.transmission.cbs.receiver[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[2].cbsType=473X

#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[3].host=127.0.0.1
spring.fep.gateway.transmission.cbs.sender[3].port=6669
spring.fep.gateway.transmission.cbs.sender[3].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[3].clientId=IFEPTA35,IFEPTA36,IFEPTA37,IFEPTA38
spring.fep.gateway.transmission.cbs.sender[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[3].cbsType=NONATM

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[3].host=127.0.0.1
spring.fep.gateway.transmission.cbs.receiver[3].port=6669
spring.fep.gateway.transmission.cbs.receiver[3].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.receiver[3].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[3].clientId=IFEPTB35,IFEPTB36,IFEPTB37,IFEPTB38
spring.fep.gateway.transmission.cbs.receiver[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[3].cbsType=NONATM

#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[4].host=127.0.0.1
spring.fep.gateway.transmission.cbs.sender[4].port=6669
spring.fep.gateway.transmission.cbs.sender[4].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[4].clientId=IFEPTA45,IFEPTA46,IFEPTA47,IFEPTA48
spring.fep.gateway.transmission.cbs.sender[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[4].cbsType=FISCTCB

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[4].host=127.0.0.1
spring.fep.gateway.transmission.cbs.receiver[4].port=6669
spring.fep.gateway.transmission.cbs.receiver[4].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.receiver[4].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[4].clientId=IFEPTB45,IFEPTB46,IFEPTB47,IFEPTB48
spring.fep.gateway.transmission.cbs.receiver[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[4].cbsType=FISCTCB

#CBS Gateway Alternative Sender
spring.fep.gateway.transmission.cbs.alternative-sender[0].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-sender[0].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[0].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[0].clientId=IFEPTC05,IFEPTC06,IFEPTC07,IFEPTC08
spring.fep.gateway.transmission.cbs.alternative-sender[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[0].cbsType=CBS

#CBS Gateway Alternative Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[0].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-receiver[0].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[0].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-receiver[0].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[0].clientId=IFEPTD05,IFEPTD06,IFEPTD07,IFEPTD08
spring.fep.gateway.transmission.cbs.alternative-receiver[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[0].cbsType=CBS

#CBS Gateway Alternative Sender
spring.fep.gateway.transmission.cbs.alternative-sender[1].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-sender[1].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[1].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[1].clientId=IFEPTC15,IFEPTC16,IFEPTC17,IFEPTC18
spring.fep.gateway.transmission.cbs.alternative-sender[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[1].cbsType=FISC

#CBS Gateway Alternative Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[1].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-receiver[1].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[1].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-receiver[1].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[1].clientId=IFEPTD15,IFEPTD16,IFEPTD17,IFEPTD18
spring.fep.gateway.transmission.cbs.alternative-receiver[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[1].cbsType=FISC

#CBS Gateway Alternative Sender
spring.fep.gateway.transmission.cbs.alternative-sender[2].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-sender[2].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[2].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[2].clientId=IFEPTC25,IFEPTC26,IFEPTC27,IFEPTC28
spring.fep.gateway.transmission.cbs.alternative-sender[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[2].cbsType=473X

#CBS Gateway Alternative Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[2].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-receiver[2].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[2].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-receiver[2].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[2].clientId=IFEPTD25,IFEPTD26,IFEPTD27,IFEPTD28
spring.fep.gateway.transmission.cbs.alternative-receiver[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[2].cbsType=473X

#CBS Gateway Alternative Sender
spring.fep.gateway.transmission.cbs.alternative-sender[3].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-sender[3].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[3].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[3].clientId=IFEPTC35,IFEPTC36,IFEPTC37,IFEPTC38
spring.fep.gateway.transmission.cbs.alternative-sender[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[3].cbsType=NONATM

#CBS Gateway Alternative Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[3].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-receiver[3].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[3].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-receiver[3].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[3].clientId=IFEPTD35,IFEPTD36,IFEPTD37,IFEPTD38
spring.fep.gateway.transmission.cbs.alternative-receiver[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[3].cbsType=NONATM

#CBS Gateway Alternative Sender
spring.fep.gateway.transmission.cbs.alternative-sender[4].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-sender[4].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[4].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[4].clientId=IFEPTC45,IFEPTC46,IFEPTC47,IFEPTC48
spring.fep.gateway.transmission.cbs.alternative-sender[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[4].cbsType=FISCTCB

#CBS Gateway Alternative Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[4].host=127.0.0.1
spring.fep.gateway.transmission.cbs.alternative-receiver[4].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[4].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-receiver[4].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[4].clientId=IFEPTD45,IFEPTD46,IFEPTD47,IFEPTD48
spring.fep.gateway.transmission.cbs.alternative-receiver[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[4].cbsType=FISCTCB

#register Scheduler Job
spring.fep.scheduler.job.register[0].className=com.syscom.fep.scheduler.job.impl.AppMonitorJob
spring.fep.scheduler.job.register[0].configClassName=com.syscom.fep.scheduler.job.impl.AppMonitorJobConfig
spring.fep.scheduler.job.register[1].className=com.syscom.fep.gateway.job.cbs.CBSGatewayAppMonitorJob
spring.fep.scheduler.job.register[1].configClassName=com.syscom.fep.gateway.job.cbs.CBSGatewayAppMonitorJobConfig

#AppMonitorJob
spring.fep.scheduler.job.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.scheduler.job.app-monitor.serviceName=${management.metrics.tags.application}
spring.fep.scheduler.job.app-monitor.serviceHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.app-monitor.serviceHostName=${spring.fep.hostname}
spring.fep.scheduler.job.app-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}${server.servlet.context-path}
spring.fep.scheduler.job.app-monitor.monitorPrimaryUrl=http://${spring.fep.hostip}:8201/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.monitorSecondaryUrl=http://${spring.fep.hostip}:8201/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.recordHttpLog=true

#CBS Gateway Job
spring.fep.gateway.job.cbs.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.gateway.job.cbs.app-monitor.monitorUrl=http://${spring.fep.hostip}:8201/recv/net/client
spring.fep.gateway.job.cbs.app-monitor.recordHttpLog=true