server.port=9090
spring.fep.application.name=fep-notify

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}
management.endpoint.health.show-details=always

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

##### cache configure #####
cache.expireAfterWrite=600
cache.maximumSize=5000

##### email configure #####
fep.notify.email001.smtp=smtp.qq.com
fep.notify.email001.port=25
fep.notify.email001.account=fep2022
fep.notify.email001.sscode=ENC(jUehmbhv7e9Izy0ATf8p4paqsx7bn5zhMTIZo99ytE7qLgU+rxU7YMfjR6j+pblY0EC4Jt0Z6YGZu8Tos5IUXw==)
fep.notify.email001.from=fep2022@qq.com
fep.notify.email001.classname=com.syscom.fep.notify.common.email.Email001
fep.notify.email001.sslOnConnect=true

##### sms configure #####
fep.notify.sms001.domain=https://stgtcb.mitake.com.tw:8105/tcb/mtk/SmSend
fep.notify.sms001.username=TCBTEST
fep.notify.sms001.sscode=ENC(dCo3yokr6hD4bNOT/l7RLUdtROyG6rBfnl1YlQdj74OMRGJVfKfy5/juQwOEwLqS)
fep.notify.sms001.classname=com.syscom.fep.notify.common.sms.Sms001

##### push configure #####
fep.notify.push001.hostname=10.0.13.141
fep.notify.push001.port=1414
fep.notify.push001.channel=SVRCONN.FEPAP
fep.notify.push001.managerId=QMFEPD01
fep.notify.push001.accessQueueId=AP.PUSH.ONLINE.RQ
fep.notify.push001.toMqUserID=fepmq
fep.notify.push001.classname=com.syscom.fep.notify.common.push.Push001

##### notClassified configure #####
fep.notify.notclassified001.url=Http://10.10.2.222:3032/PushAPI4Http
fep.notify.notclassified001.appIds=tw.com.scsb.android.mbank.test,tw.com.scsb.ios.mbank.test
fep.notify.notclassified001.classname=com.syscom.fep.notify.common.notClassified.NotClassified001

