PKI_PATH=/PKI
InstanceName1=fatinst1
InstanceName1Db=FEPDB,DESDB,FEPDB_BATCH
InstanceName2=fbdinst1
InstanceName2Db=EMSDB,DESLOGDB,REPORTDB
InstanceName3=fhpinst1
InstanceName3Db=FEPHIS,FEPHIS_BATCH

FEPDB.driver-class-name=com.ibm.db2.jcc.DB2Driver
FEPDB.jdbc-url=jdbc:db2://10.3.101.1:25000/FEPDB:currentSchema=DBO;

DESDB.driver-class-name=com.ibm.db2.jcc.DB2Driver
DESDB.jdbc-url=jdbc:db2://10.3.101.1:25000/DESDB:currentSchema=DBO;

FEPDB_BATCH.driver-class-name=com.ibm.db2.jcc.DB2Driver
FEPDB_BATCH.jdbc-url=jdbc:db2://10.3.101.1:25000/FEPDB:currentSchema=DBO;

EMSDB.driver-class-name=com.ibm.db2.jcc.DB2Driver
EMSDB.jdbc-url=jdbc:db2://10.3.101.1:25000/FEPDB:currentSchema=EMS;

DESLOGDB.driver-class-name=com.ibm.db2.jcc.DB2Driver
DESLOGDB.jdbc-url=jdbc:db2://10.3.101.1:25000/DESLOG:currentSchema=DBO;

FEPHIS.driver-class-name=com.ibm.db2.jcc.DB2Driver
FEPHIS.jdbc-url=jdbc:db2://fep.db.syscom:10008/FEPDB:currentSchema=FEPHIS

FEPHIS_BATCH.driver-class-name=com.ibm.db2.jcc.DB2Driver
FEPHIS_BATCH.jdbc-url=jdbc:db2://10.3.101.1:25000/FEPDB:currentSchema=DBO;

REPORTDB.driver-class-name=com.ibm.db2.jcc.DB2Driver
REPORTDB.jdbc-url=jdbc:db2://10.3.101.1:25000/FEPDB:currentSchema=DBO;

JdbcLoginTimeout=5