spring.datasource.fepdb.username=db2admin
spring.datasource.fepdb.password=ENC(rq7spHpmsd5nMmO25S2AWak+p5X/ueOaOR0LUD4gI5H3u3KsQlI+actC9wU4zr2R)
spring.datasource.fepdb.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.datasource.fepdb.jdbc-url=jdbc:db2://10.3.101.1:25000/FEPDB:currentSchema=DBO;fullyMaterializeInputStreams=true;progressiveStreaming=2;

spring.datasource.fephis.username=db2admin
spring.datasource.fephis.password=ENC(rq7spHpmsd5nMmO25S2AWak+p5X/ueOaOR0LUD4gI5H3u3KsQlI+actC9wU4zr2R)
spring.datasource.fephis.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.datasource.fephis.jdbc-url=jdbc:db2://10.3.101.1:25000/FEPDB:currentSchema=FEPHIS;fullyMaterializeInputStreams=true;progressiveStreaming=2;

spring.datasource.fepdb-batch.username=db2admin
spring.datasource.fepdb-batch.password=ENC(rq7spHpmsd5nMmO25S2AWak+p5X/ueOaOR0LUD4gI5H3u3KsQlI+actC9wU4zr2R)
spring.datasource.fepdb-batch.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.datasource.fepdb-batch.jdbc-url=jdbc:db2://10.3.101.1:25000/FEPDB:currentSchema=DBO;fullyMaterializeInputStreams=true;progressiveStreaming=2;

spring.datasource.fephis-batch.username=db2admin
spring.datasource.fephis-batch.password=ENC(rq7spHpmsd5nMmO25S2AWak+p5X/ueOaOR0LUD4gI5H3u3KsQlI+actC9wU4zr2R)
spring.datasource.fephis-batch.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.datasource.fephis-batch.jdbc-url=jdbc:db2://10.3.101.1:25000/FEPDB:currentSchema=FEPHIS;fullyMaterializeInputStreams=true;progressiveStreaming=2;

spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=540000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM SYSIBM.SYSDUMMY1

spring.fep.task.log.path=/fep/logs
spring.fep.task.log.console.encoding=BIG5

#PKI
spring.fep.pki.path=/PKI/fatinst1/acdu,/PKI/fatinst1/acdp,/PKI/fbdinst1/acdu,/PKI/fbdinst1/acdp,/PKI/fhpinst1/acdu,/PKI/fhpinst1/acdp