<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.syscom</groupId>
        <artifactId>feptcb</artifactId>
        <version>1.0.0</version>
    </parent>
    <groupId>com.syscom.feptcb</groupId>
    <artifactId>fep-common</artifactId>
    <name>fep-common</name>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>*.txt</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin-version}</version>
                <configuration>
                    <source>${java-source-version}</source>
                    <target>${java-target-version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin-version}</version>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-frmcommon</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-config</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter-api-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring-boot-starter-test-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-notify-vo</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>${pom.basedir}/../fep-lib/lib/fep-notify-vo.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>${mybatis-spring-boot-starter-version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.ibm.db2</groupId>
            <artifactId>jcc</artifactId>
            <version>${jcc-version}</version>
        </dependency>
        <dependency>
            <groupId>com.astar</groupId>
            <artifactId>tb-convert</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>${pom.basedir}/../fep-lib/lib/tb-convert-1.0.0.jar</systemPath>
        </dependency>
    </dependencies>
    <profiles>
        <profile>
            <id>maven-jar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <project.packaging>jar</project.packaging>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-clean-plugin</artifactId>
                        <version>${maven-clean-plugin-version}</version>
                        <configuration>
                            <followSymLinks>false</followSymLinks>
                            <filesets>
                                <fileset>
                                    <directory>../../${assembly-directory}</directory>
                                    <includes>
                                        <include>${project.artifactId}-*.tar.gz</include>
                                    </includes>
                                </fileset>
                            </filesets>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>com.soebes.maven.plugins</groupId>
                        <artifactId>iterator-maven-plugin</artifactId>
                        <version>${iterator-maven-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>iterator</goal>
                                </goals>
                                <configuration>
                                    <itemsWithProperties>
                                        <itemWithProperty>
                                            <name>fep-jasypt-tool</name>
                                            <properties>
                                                <assembly-func>fep-jasypt-tool</assembly-func>
                                                <assembly-shell>fep_jasypt_tool</assembly-shell>
                                            </properties>
                                        </itemWithProperty>
                                    </itemsWithProperties>
                                    <pluginExecutors>
                                        <pluginExecutor>
                                            <plugin>
                                                <groupId>org.apache.maven.plugins</groupId>
                                                <artifactId>maven-antrun-plugin</artifactId>
                                                <version>${maven-antrun-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <id>copy-release-note</id>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>run</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>run</goal>
                                            <configuration>
                                                <target>
                                                    <delete file="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                                    <copy file="${assembly-release-note-path}/${assembly-func}.txt"
                                                          tofile="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                                </target>
                                            </configuration>
                                        </pluginExecutor>
                                        <pluginExecutor>
                                            <plugin>
                                                <groupId>org.apache.maven.plugins</groupId>
                                                <artifactId>maven-jar-plugin</artifactId>
                                                <version>${maven-jar-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <id>make-jar</id>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>jar</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>jar</goal>
                                            <configuration>
                                                <finalName>${project.artifactId}</finalName>
                                                <classifier>${assembly-func}</classifier>
                                                <archive>
                                                    <addMavenDescriptor>false</addMavenDescriptor>
                                                    <manifest>
                                                        <addClasspath>true</addClasspath>
                                                        <classpathPrefix>lib/</classpathPrefix>
                                                    </manifest>
                                                    <manifestEntries>
                                                        <Class-Path>.</Class-Path>
                                                    </manifestEntries>
                                                </archive>
                                            </configuration>
                                        </pluginExecutor>
                                        <pluginExecutor>
                                            <plugin>
                                                <artifactId>maven-assembly-plugin</artifactId>
                                                <version>${maven-assembly-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <id>make-assembly</id>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>single</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>single</goal>
                                            <configuration>
                                                <finalName>${project.artifactId}</finalName>
                                                <descriptors>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/${assembly-func}/assembly.xml</descriptor>
                                                </descriptors>
                                                <outputDirectory>${assembly-output-path}</outputDirectory>
                                            </configuration>
                                        </pluginExecutor>
                                    </pluginExecutors>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin-version}</version>
                        <configuration>
                            <source>${java-source-version}</source>
                            <target>${java-target-version}</target>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>