package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class Atmiac extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATMIAC.ATMIAC_ACTNO
     *
     * @mbg.generated
     */
    private String atmiacActno = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATMIAC.ATMIAC_CURCD
     *
     * @mbg.generated
     */
    private String atmiacCurcd = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATMIAC.ATMIAC_KIND
     *
     * @mbg.generated
     */
    private Short atmiacKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATMIAC.ATMIAC_RATE_DISC
     *
     * @mbg.generated
     */
    private Short atmiacRateDisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATMIAC.ATMIAC_FEE_DISC
     *
     * @mbg.generated
     */
    private Short atmiacFeeDisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATMIAC.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATMIAC.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ATMIAC
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMIAC
     *
     * @mbg.generated
     */
    public Atmiac(String atmiacActno, String atmiacCurcd, Short atmiacKind, Short atmiacRateDisc, Short atmiacFeeDisc, Integer updateUserid, Date updateTime) {
        this.atmiacActno = atmiacActno;
        this.atmiacCurcd = atmiacCurcd;
        this.atmiacKind = atmiacKind;
        this.atmiacRateDisc = atmiacRateDisc;
        this.atmiacFeeDisc = atmiacFeeDisc;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMIAC
     *
     * @mbg.generated
     */
    public Atmiac() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATMIAC.ATMIAC_ACTNO
     *
     * @return the value of ATMIAC.ATMIAC_ACTNO
     *
     * @mbg.generated
     */
    public String getAtmiacActno() {
        return atmiacActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATMIAC.ATMIAC_ACTNO
     *
     * @param atmiacActno the value for ATMIAC.ATMIAC_ACTNO
     *
     * @mbg.generated
     */
    public void setAtmiacActno(String atmiacActno) {
        this.atmiacActno = atmiacActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATMIAC.ATMIAC_CURCD
     *
     * @return the value of ATMIAC.ATMIAC_CURCD
     *
     * @mbg.generated
     */
    public String getAtmiacCurcd() {
        return atmiacCurcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATMIAC.ATMIAC_CURCD
     *
     * @param atmiacCurcd the value for ATMIAC.ATMIAC_CURCD
     *
     * @mbg.generated
     */
    public void setAtmiacCurcd(String atmiacCurcd) {
        this.atmiacCurcd = atmiacCurcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATMIAC.ATMIAC_KIND
     *
     * @return the value of ATMIAC.ATMIAC_KIND
     *
     * @mbg.generated
     */
    public Short getAtmiacKind() {
        return atmiacKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATMIAC.ATMIAC_KIND
     *
     * @param atmiacKind the value for ATMIAC.ATMIAC_KIND
     *
     * @mbg.generated
     */
    public void setAtmiacKind(Short atmiacKind) {
        this.atmiacKind = atmiacKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATMIAC.ATMIAC_RATE_DISC
     *
     * @return the value of ATMIAC.ATMIAC_RATE_DISC
     *
     * @mbg.generated
     */
    public Short getAtmiacRateDisc() {
        return atmiacRateDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATMIAC.ATMIAC_RATE_DISC
     *
     * @param atmiacRateDisc the value for ATMIAC.ATMIAC_RATE_DISC
     *
     * @mbg.generated
     */
    public void setAtmiacRateDisc(Short atmiacRateDisc) {
        this.atmiacRateDisc = atmiacRateDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATMIAC.ATMIAC_FEE_DISC
     *
     * @return the value of ATMIAC.ATMIAC_FEE_DISC
     *
     * @mbg.generated
     */
    public Short getAtmiacFeeDisc() {
        return atmiacFeeDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATMIAC.ATMIAC_FEE_DISC
     *
     * @param atmiacFeeDisc the value for ATMIAC.ATMIAC_FEE_DISC
     *
     * @mbg.generated
     */
    public void setAtmiacFeeDisc(Short atmiacFeeDisc) {
        this.atmiacFeeDisc = atmiacFeeDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATMIAC.UPDATE_USERID
     *
     * @return the value of ATMIAC.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATMIAC.UPDATE_USERID
     *
     * @param updateUserid the value for ATMIAC.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATMIAC.UPDATE_TIME
     *
     * @return the value of ATMIAC.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATMIAC.UPDATE_TIME
     *
     * @param updateTime the value for ATMIAC.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMIAC
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", atmiacActno=").append(atmiacActno);
        sb.append(", atmiacCurcd=").append(atmiacCurcd);
        sb.append(", atmiacKind=").append(atmiacKind);
        sb.append(", atmiacRateDisc=").append(atmiacRateDisc);
        sb.append(", atmiacFeeDisc=").append(atmiacFeeDisc);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMIAC
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Atmiac other = (Atmiac) that;
        return (this.getAtmiacActno() == null ? other.getAtmiacActno() == null : this.getAtmiacActno().equals(other.getAtmiacActno()))
            && (this.getAtmiacCurcd() == null ? other.getAtmiacCurcd() == null : this.getAtmiacCurcd().equals(other.getAtmiacCurcd()))
            && (this.getAtmiacKind() == null ? other.getAtmiacKind() == null : this.getAtmiacKind().equals(other.getAtmiacKind()))
            && (this.getAtmiacRateDisc() == null ? other.getAtmiacRateDisc() == null : this.getAtmiacRateDisc().equals(other.getAtmiacRateDisc()))
            && (this.getAtmiacFeeDisc() == null ? other.getAtmiacFeeDisc() == null : this.getAtmiacFeeDisc().equals(other.getAtmiacFeeDisc()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMIAC
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getAtmiacActno() == null) ? 0 : getAtmiacActno().hashCode());
        result = 31 * result + ((getAtmiacCurcd() == null) ? 0 : getAtmiacCurcd().hashCode());
        result = 31 * result + ((getAtmiacKind() == null) ? 0 : getAtmiacKind().hashCode());
        result = 31 * result + ((getAtmiacRateDisc() == null) ? 0 : getAtmiacRateDisc().hashCode());
        result = 31 * result + ((getAtmiacFeeDisc() == null) ? 0 : getAtmiacFeeDisc().hashCode());
        result = 31 * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = 31 * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMIAC
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<ATMIAC_ACTNO>").append(this.atmiacActno).append("</ATMIAC_ACTNO>");
        sb.append("<ATMIAC_CURCD>").append(this.atmiacCurcd).append("</ATMIAC_CURCD>");
        sb.append("<ATMIAC_KIND>").append(this.atmiacKind).append("</ATMIAC_KIND>");
        sb.append("<ATMIAC_RATE_DISC>").append(this.atmiacRateDisc).append("</ATMIAC_RATE_DISC>");
        sb.append("<ATMIAC_FEE_DISC>").append(this.atmiacFeeDisc).append("</ATMIAC_FEE_DISC>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        return sb.toString();
    }
}