package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class Billtax extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TBSDY
     *
     * @mbg.generated
     */
    private String billtaxTbsdy = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_STAN
     *
     * @mbg.generated
     */
    private String billtaxStan = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ACQ_BKNO
     *
     * @mbg.generated
     */
    private String billtaxAcqBkno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TROUT_BKNO
     *
     * @mbg.generated
     */
    private String billtaxTroutBkno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TRIN_BKNO
     *
     * @mbg.generated
     */
    private String billtaxTrinBkno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_PCODE
     *
     * @mbg.generated
     */
    private String billtaxPcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_BUSS_DATE
     *
     * @mbg.generated
     */
    private String billtaxBussDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TX_DATE
     *
     * @mbg.generated
     */
    private String billtaxTxDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TX_TIME
     *
     * @mbg.generated
     */
    private String billtaxTxTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ATMNO
     *
     * @mbg.generated
     */
    private String billtaxAtmno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TRIN_ACTNO
     *
     * @mbg.generated
     */
    private String billtaxTrinActno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TROUT_ACTNO
     *
     * @mbg.generated
     */
    private String billtaxTroutActno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_REP1_RC
     *
     * @mbg.generated
     */
    private String billtaxRep1Rc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_REP2_RC
     *
     * @mbg.generated
     */
    private String billtaxRep2Rc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_CON1_RC
     *
     * @mbg.generated
     */
    private String billtaxCon1Rc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_CON2_RC
     *
     * @mbg.generated
     */
    private String billtaxCon2Rc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_FISC_RC
     *
     * @mbg.generated
     */
    private String billtaxFiscRc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TX_AMT
     *
     * @mbg.generated
     */
    private BigDecimal billtaxTxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TXRUST
     *
     * @mbg.generated
     */
    private String billtaxTxrust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TAX_HQ
     *
     * @mbg.generated
     */
    private String billtaxTaxHq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_UTL_HQ
     *
     * @mbg.generated
     */
    private String billtaxUtlHq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_PAYTYPE
     *
     * @mbg.generated
     */
    private String billtaxPaytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_DUE_DATE
     *
     * @mbg.generated
     */
    private String billtaxDueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_RECON_SEQNO
     *
     * @mbg.generated
     */
    private String billtaxReconSeqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TAX_UNIT
     *
     * @mbg.generated
     */
    private String billtaxTaxUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_IDNO
     *
     * @mbg.generated
     */
    private String billtaxIdno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TAX_DETAIL
     *
     * @mbg.generated
     */
    private String billtaxTaxDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TAX_CITY
     *
     * @mbg.generated
     */
    private String billtaxTaxCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_PAY_KIND
     *
     * @mbg.generated
     */
    private String billtaxPayKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_IC_SEQNO
     *
     * @mbg.generated
     */
    private String billtaxIcSeqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ATM_CHK
     *
     * @mbg.generated
     */
    private String billtaxAtmChk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_TRM_TYPE
     *
     * @mbg.generated
     */
    private String billtaxTrmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_PAY_STAT
     *
     * @mbg.generated
     */
    private String billtaxPayStat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_NPS_FEE_RCVR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxNpsFeeRcvr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_NPS_FEE_AGENT
     *
     * @mbg.generated
     */
    private BigDecimal billtaxNpsFeeAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_NPS_FEE_TROUT
     *
     * @mbg.generated
     */
    private BigDecimal billtaxNpsFeeTrout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_NPS_FEE_TRIN
     *
     * @mbg.generated
     */
    private BigDecimal billtaxNpsFeeTrin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_NPS_FEE_FISC
     *
     * @mbg.generated
     */
    private BigDecimal billtaxNpsFeeFisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ATX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxAtxFeeMbnkCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ATX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxAtxFeeMbnkDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ATX_FEE_CR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxAtxFeeCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ATX_FEE_DR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxAtxFeeDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_OTX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxOtxFeeMbnkCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_OTX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxOtxFeeMbnkDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_OTX_FEE_CR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxOtxFeeCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_OTX_FEE_DR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxOtxFeeDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ITX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxItxFeeMbnkCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ITX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxItxFeeMbnkDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ITX_FEE_CR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxItxFeeCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.BILLTAX_ITX_FEE_DR
     *
     * @mbg.generated
     */
    private BigDecimal billtaxItxFeeDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLTAX.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BILLTAX
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTAX
     *
     * @mbg.generated
     */
    public Billtax(String billtaxTbsdy, String billtaxStan, String billtaxAcqBkno, String billtaxTroutBkno, String billtaxTrinBkno, String billtaxPcode, String billtaxBussDate, String billtaxTxDate, String billtaxTxTime, String billtaxAtmno, String billtaxTrinActno, String billtaxTroutActno, String billtaxRep1Rc, String billtaxRep2Rc, String billtaxCon1Rc, String billtaxCon2Rc, String billtaxFiscRc, BigDecimal billtaxTxAmt, String billtaxTxrust, String billtaxTaxHq, String billtaxUtlHq, String billtaxPaytype, String billtaxDueDate, String billtaxReconSeqno, String billtaxTaxUnit, String billtaxIdno, String billtaxTaxDetail, String billtaxTaxCity, String billtaxPayKind, String billtaxIcSeqno, String billtaxAtmChk, String billtaxTrmType, String billtaxPayStat, BigDecimal billtaxNpsFeeRcvr, BigDecimal billtaxNpsFeeAgent, BigDecimal billtaxNpsFeeTrout, BigDecimal billtaxNpsFeeTrin, BigDecimal billtaxNpsFeeFisc, BigDecimal billtaxAtxFeeMbnkCr, BigDecimal billtaxAtxFeeMbnkDr, BigDecimal billtaxAtxFeeCr, BigDecimal billtaxAtxFeeDr, BigDecimal billtaxOtxFeeMbnkCr, BigDecimal billtaxOtxFeeMbnkDr, BigDecimal billtaxOtxFeeCr, BigDecimal billtaxOtxFeeDr, BigDecimal billtaxItxFeeMbnkCr, BigDecimal billtaxItxFeeMbnkDr, BigDecimal billtaxItxFeeCr, BigDecimal billtaxItxFeeDr, Integer updateUserid, Date updateTime) {
        this.billtaxTbsdy = billtaxTbsdy;
        this.billtaxStan = billtaxStan;
        this.billtaxAcqBkno = billtaxAcqBkno;
        this.billtaxTroutBkno = billtaxTroutBkno;
        this.billtaxTrinBkno = billtaxTrinBkno;
        this.billtaxPcode = billtaxPcode;
        this.billtaxBussDate = billtaxBussDate;
        this.billtaxTxDate = billtaxTxDate;
        this.billtaxTxTime = billtaxTxTime;
        this.billtaxAtmno = billtaxAtmno;
        this.billtaxTrinActno = billtaxTrinActno;
        this.billtaxTroutActno = billtaxTroutActno;
        this.billtaxRep1Rc = billtaxRep1Rc;
        this.billtaxRep2Rc = billtaxRep2Rc;
        this.billtaxCon1Rc = billtaxCon1Rc;
        this.billtaxCon2Rc = billtaxCon2Rc;
        this.billtaxFiscRc = billtaxFiscRc;
        this.billtaxTxAmt = billtaxTxAmt;
        this.billtaxTxrust = billtaxTxrust;
        this.billtaxTaxHq = billtaxTaxHq;
        this.billtaxUtlHq = billtaxUtlHq;
        this.billtaxPaytype = billtaxPaytype;
        this.billtaxDueDate = billtaxDueDate;
        this.billtaxReconSeqno = billtaxReconSeqno;
        this.billtaxTaxUnit = billtaxTaxUnit;
        this.billtaxIdno = billtaxIdno;
        this.billtaxTaxDetail = billtaxTaxDetail;
        this.billtaxTaxCity = billtaxTaxCity;
        this.billtaxPayKind = billtaxPayKind;
        this.billtaxIcSeqno = billtaxIcSeqno;
        this.billtaxAtmChk = billtaxAtmChk;
        this.billtaxTrmType = billtaxTrmType;
        this.billtaxPayStat = billtaxPayStat;
        this.billtaxNpsFeeRcvr = billtaxNpsFeeRcvr;
        this.billtaxNpsFeeAgent = billtaxNpsFeeAgent;
        this.billtaxNpsFeeTrout = billtaxNpsFeeTrout;
        this.billtaxNpsFeeTrin = billtaxNpsFeeTrin;
        this.billtaxNpsFeeFisc = billtaxNpsFeeFisc;
        this.billtaxAtxFeeMbnkCr = billtaxAtxFeeMbnkCr;
        this.billtaxAtxFeeMbnkDr = billtaxAtxFeeMbnkDr;
        this.billtaxAtxFeeCr = billtaxAtxFeeCr;
        this.billtaxAtxFeeDr = billtaxAtxFeeDr;
        this.billtaxOtxFeeMbnkCr = billtaxOtxFeeMbnkCr;
        this.billtaxOtxFeeMbnkDr = billtaxOtxFeeMbnkDr;
        this.billtaxOtxFeeCr = billtaxOtxFeeCr;
        this.billtaxOtxFeeDr = billtaxOtxFeeDr;
        this.billtaxItxFeeMbnkCr = billtaxItxFeeMbnkCr;
        this.billtaxItxFeeMbnkDr = billtaxItxFeeMbnkDr;
        this.billtaxItxFeeCr = billtaxItxFeeCr;
        this.billtaxItxFeeDr = billtaxItxFeeDr;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTAX
     *
     * @mbg.generated
     */
    public Billtax() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TBSDY
     *
     * @return the value of BILLTAX.BILLTAX_TBSDY
     *
     * @mbg.generated
     */
    public String getBilltaxTbsdy() {
        return billtaxTbsdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TBSDY
     *
     * @param billtaxTbsdy the value for BILLTAX.BILLTAX_TBSDY
     *
     * @mbg.generated
     */
    public void setBilltaxTbsdy(String billtaxTbsdy) {
        this.billtaxTbsdy = billtaxTbsdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_STAN
     *
     * @return the value of BILLTAX.BILLTAX_STAN
     *
     * @mbg.generated
     */
    public String getBilltaxStan() {
        return billtaxStan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_STAN
     *
     * @param billtaxStan the value for BILLTAX.BILLTAX_STAN
     *
     * @mbg.generated
     */
    public void setBilltaxStan(String billtaxStan) {
        this.billtaxStan = billtaxStan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ACQ_BKNO
     *
     * @return the value of BILLTAX.BILLTAX_ACQ_BKNO
     *
     * @mbg.generated
     */
    public String getBilltaxAcqBkno() {
        return billtaxAcqBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ACQ_BKNO
     *
     * @param billtaxAcqBkno the value for BILLTAX.BILLTAX_ACQ_BKNO
     *
     * @mbg.generated
     */
    public void setBilltaxAcqBkno(String billtaxAcqBkno) {
        this.billtaxAcqBkno = billtaxAcqBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TROUT_BKNO
     *
     * @return the value of BILLTAX.BILLTAX_TROUT_BKNO
     *
     * @mbg.generated
     */
    public String getBilltaxTroutBkno() {
        return billtaxTroutBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TROUT_BKNO
     *
     * @param billtaxTroutBkno the value for BILLTAX.BILLTAX_TROUT_BKNO
     *
     * @mbg.generated
     */
    public void setBilltaxTroutBkno(String billtaxTroutBkno) {
        this.billtaxTroutBkno = billtaxTroutBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TRIN_BKNO
     *
     * @return the value of BILLTAX.BILLTAX_TRIN_BKNO
     *
     * @mbg.generated
     */
    public String getBilltaxTrinBkno() {
        return billtaxTrinBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TRIN_BKNO
     *
     * @param billtaxTrinBkno the value for BILLTAX.BILLTAX_TRIN_BKNO
     *
     * @mbg.generated
     */
    public void setBilltaxTrinBkno(String billtaxTrinBkno) {
        this.billtaxTrinBkno = billtaxTrinBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_PCODE
     *
     * @return the value of BILLTAX.BILLTAX_PCODE
     *
     * @mbg.generated
     */
    public String getBilltaxPcode() {
        return billtaxPcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_PCODE
     *
     * @param billtaxPcode the value for BILLTAX.BILLTAX_PCODE
     *
     * @mbg.generated
     */
    public void setBilltaxPcode(String billtaxPcode) {
        this.billtaxPcode = billtaxPcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_BUSS_DATE
     *
     * @return the value of BILLTAX.BILLTAX_BUSS_DATE
     *
     * @mbg.generated
     */
    public String getBilltaxBussDate() {
        return billtaxBussDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_BUSS_DATE
     *
     * @param billtaxBussDate the value for BILLTAX.BILLTAX_BUSS_DATE
     *
     * @mbg.generated
     */
    public void setBilltaxBussDate(String billtaxBussDate) {
        this.billtaxBussDate = billtaxBussDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TX_DATE
     *
     * @return the value of BILLTAX.BILLTAX_TX_DATE
     *
     * @mbg.generated
     */
    public String getBilltaxTxDate() {
        return billtaxTxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TX_DATE
     *
     * @param billtaxTxDate the value for BILLTAX.BILLTAX_TX_DATE
     *
     * @mbg.generated
     */
    public void setBilltaxTxDate(String billtaxTxDate) {
        this.billtaxTxDate = billtaxTxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TX_TIME
     *
     * @return the value of BILLTAX.BILLTAX_TX_TIME
     *
     * @mbg.generated
     */
    public String getBilltaxTxTime() {
        return billtaxTxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TX_TIME
     *
     * @param billtaxTxTime the value for BILLTAX.BILLTAX_TX_TIME
     *
     * @mbg.generated
     */
    public void setBilltaxTxTime(String billtaxTxTime) {
        this.billtaxTxTime = billtaxTxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ATMNO
     *
     * @return the value of BILLTAX.BILLTAX_ATMNO
     *
     * @mbg.generated
     */
    public String getBilltaxAtmno() {
        return billtaxAtmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ATMNO
     *
     * @param billtaxAtmno the value for BILLTAX.BILLTAX_ATMNO
     *
     * @mbg.generated
     */
    public void setBilltaxAtmno(String billtaxAtmno) {
        this.billtaxAtmno = billtaxAtmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TRIN_ACTNO
     *
     * @return the value of BILLTAX.BILLTAX_TRIN_ACTNO
     *
     * @mbg.generated
     */
    public String getBilltaxTrinActno() {
        return billtaxTrinActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TRIN_ACTNO
     *
     * @param billtaxTrinActno the value for BILLTAX.BILLTAX_TRIN_ACTNO
     *
     * @mbg.generated
     */
    public void setBilltaxTrinActno(String billtaxTrinActno) {
        this.billtaxTrinActno = billtaxTrinActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TROUT_ACTNO
     *
     * @return the value of BILLTAX.BILLTAX_TROUT_ACTNO
     *
     * @mbg.generated
     */
    public String getBilltaxTroutActno() {
        return billtaxTroutActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TROUT_ACTNO
     *
     * @param billtaxTroutActno the value for BILLTAX.BILLTAX_TROUT_ACTNO
     *
     * @mbg.generated
     */
    public void setBilltaxTroutActno(String billtaxTroutActno) {
        this.billtaxTroutActno = billtaxTroutActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_REP1_RC
     *
     * @return the value of BILLTAX.BILLTAX_REP1_RC
     *
     * @mbg.generated
     */
    public String getBilltaxRep1Rc() {
        return billtaxRep1Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_REP1_RC
     *
     * @param billtaxRep1Rc the value for BILLTAX.BILLTAX_REP1_RC
     *
     * @mbg.generated
     */
    public void setBilltaxRep1Rc(String billtaxRep1Rc) {
        this.billtaxRep1Rc = billtaxRep1Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_REP2_RC
     *
     * @return the value of BILLTAX.BILLTAX_REP2_RC
     *
     * @mbg.generated
     */
    public String getBilltaxRep2Rc() {
        return billtaxRep2Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_REP2_RC
     *
     * @param billtaxRep2Rc the value for BILLTAX.BILLTAX_REP2_RC
     *
     * @mbg.generated
     */
    public void setBilltaxRep2Rc(String billtaxRep2Rc) {
        this.billtaxRep2Rc = billtaxRep2Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_CON1_RC
     *
     * @return the value of BILLTAX.BILLTAX_CON1_RC
     *
     * @mbg.generated
     */
    public String getBilltaxCon1Rc() {
        return billtaxCon1Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_CON1_RC
     *
     * @param billtaxCon1Rc the value for BILLTAX.BILLTAX_CON1_RC
     *
     * @mbg.generated
     */
    public void setBilltaxCon1Rc(String billtaxCon1Rc) {
        this.billtaxCon1Rc = billtaxCon1Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_CON2_RC
     *
     * @return the value of BILLTAX.BILLTAX_CON2_RC
     *
     * @mbg.generated
     */
    public String getBilltaxCon2Rc() {
        return billtaxCon2Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_CON2_RC
     *
     * @param billtaxCon2Rc the value for BILLTAX.BILLTAX_CON2_RC
     *
     * @mbg.generated
     */
    public void setBilltaxCon2Rc(String billtaxCon2Rc) {
        this.billtaxCon2Rc = billtaxCon2Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_FISC_RC
     *
     * @return the value of BILLTAX.BILLTAX_FISC_RC
     *
     * @mbg.generated
     */
    public String getBilltaxFiscRc() {
        return billtaxFiscRc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_FISC_RC
     *
     * @param billtaxFiscRc the value for BILLTAX.BILLTAX_FISC_RC
     *
     * @mbg.generated
     */
    public void setBilltaxFiscRc(String billtaxFiscRc) {
        this.billtaxFiscRc = billtaxFiscRc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TX_AMT
     *
     * @return the value of BILLTAX.BILLTAX_TX_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxTxAmt() {
        return billtaxTxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TX_AMT
     *
     * @param billtaxTxAmt the value for BILLTAX.BILLTAX_TX_AMT
     *
     * @mbg.generated
     */
    public void setBilltaxTxAmt(BigDecimal billtaxTxAmt) {
        this.billtaxTxAmt = billtaxTxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TXRUST
     *
     * @return the value of BILLTAX.BILLTAX_TXRUST
     *
     * @mbg.generated
     */
    public String getBilltaxTxrust() {
        return billtaxTxrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TXRUST
     *
     * @param billtaxTxrust the value for BILLTAX.BILLTAX_TXRUST
     *
     * @mbg.generated
     */
    public void setBilltaxTxrust(String billtaxTxrust) {
        this.billtaxTxrust = billtaxTxrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TAX_HQ
     *
     * @return the value of BILLTAX.BILLTAX_TAX_HQ
     *
     * @mbg.generated
     */
    public String getBilltaxTaxHq() {
        return billtaxTaxHq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TAX_HQ
     *
     * @param billtaxTaxHq the value for BILLTAX.BILLTAX_TAX_HQ
     *
     * @mbg.generated
     */
    public void setBilltaxTaxHq(String billtaxTaxHq) {
        this.billtaxTaxHq = billtaxTaxHq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_UTL_HQ
     *
     * @return the value of BILLTAX.BILLTAX_UTL_HQ
     *
     * @mbg.generated
     */
    public String getBilltaxUtlHq() {
        return billtaxUtlHq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_UTL_HQ
     *
     * @param billtaxUtlHq the value for BILLTAX.BILLTAX_UTL_HQ
     *
     * @mbg.generated
     */
    public void setBilltaxUtlHq(String billtaxUtlHq) {
        this.billtaxUtlHq = billtaxUtlHq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_PAYTYPE
     *
     * @return the value of BILLTAX.BILLTAX_PAYTYPE
     *
     * @mbg.generated
     */
    public String getBilltaxPaytype() {
        return billtaxPaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_PAYTYPE
     *
     * @param billtaxPaytype the value for BILLTAX.BILLTAX_PAYTYPE
     *
     * @mbg.generated
     */
    public void setBilltaxPaytype(String billtaxPaytype) {
        this.billtaxPaytype = billtaxPaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_DUE_DATE
     *
     * @return the value of BILLTAX.BILLTAX_DUE_DATE
     *
     * @mbg.generated
     */
    public String getBilltaxDueDate() {
        return billtaxDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_DUE_DATE
     *
     * @param billtaxDueDate the value for BILLTAX.BILLTAX_DUE_DATE
     *
     * @mbg.generated
     */
    public void setBilltaxDueDate(String billtaxDueDate) {
        this.billtaxDueDate = billtaxDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_RECON_SEQNO
     *
     * @return the value of BILLTAX.BILLTAX_RECON_SEQNO
     *
     * @mbg.generated
     */
    public String getBilltaxReconSeqno() {
        return billtaxReconSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_RECON_SEQNO
     *
     * @param billtaxReconSeqno the value for BILLTAX.BILLTAX_RECON_SEQNO
     *
     * @mbg.generated
     */
    public void setBilltaxReconSeqno(String billtaxReconSeqno) {
        this.billtaxReconSeqno = billtaxReconSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TAX_UNIT
     *
     * @return the value of BILLTAX.BILLTAX_TAX_UNIT
     *
     * @mbg.generated
     */
    public String getBilltaxTaxUnit() {
        return billtaxTaxUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TAX_UNIT
     *
     * @param billtaxTaxUnit the value for BILLTAX.BILLTAX_TAX_UNIT
     *
     * @mbg.generated
     */
    public void setBilltaxTaxUnit(String billtaxTaxUnit) {
        this.billtaxTaxUnit = billtaxTaxUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_IDNO
     *
     * @return the value of BILLTAX.BILLTAX_IDNO
     *
     * @mbg.generated
     */
    public String getBilltaxIdno() {
        return billtaxIdno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_IDNO
     *
     * @param billtaxIdno the value for BILLTAX.BILLTAX_IDNO
     *
     * @mbg.generated
     */
    public void setBilltaxIdno(String billtaxIdno) {
        this.billtaxIdno = billtaxIdno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TAX_DETAIL
     *
     * @return the value of BILLTAX.BILLTAX_TAX_DETAIL
     *
     * @mbg.generated
     */
    public String getBilltaxTaxDetail() {
        return billtaxTaxDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TAX_DETAIL
     *
     * @param billtaxTaxDetail the value for BILLTAX.BILLTAX_TAX_DETAIL
     *
     * @mbg.generated
     */
    public void setBilltaxTaxDetail(String billtaxTaxDetail) {
        this.billtaxTaxDetail = billtaxTaxDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TAX_CITY
     *
     * @return the value of BILLTAX.BILLTAX_TAX_CITY
     *
     * @mbg.generated
     */
    public String getBilltaxTaxCity() {
        return billtaxTaxCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TAX_CITY
     *
     * @param billtaxTaxCity the value for BILLTAX.BILLTAX_TAX_CITY
     *
     * @mbg.generated
     */
    public void setBilltaxTaxCity(String billtaxTaxCity) {
        this.billtaxTaxCity = billtaxTaxCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_PAY_KIND
     *
     * @return the value of BILLTAX.BILLTAX_PAY_KIND
     *
     * @mbg.generated
     */
    public String getBilltaxPayKind() {
        return billtaxPayKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_PAY_KIND
     *
     * @param billtaxPayKind the value for BILLTAX.BILLTAX_PAY_KIND
     *
     * @mbg.generated
     */
    public void setBilltaxPayKind(String billtaxPayKind) {
        this.billtaxPayKind = billtaxPayKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_IC_SEQNO
     *
     * @return the value of BILLTAX.BILLTAX_IC_SEQNO
     *
     * @mbg.generated
     */
    public String getBilltaxIcSeqno() {
        return billtaxIcSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_IC_SEQNO
     *
     * @param billtaxIcSeqno the value for BILLTAX.BILLTAX_IC_SEQNO
     *
     * @mbg.generated
     */
    public void setBilltaxIcSeqno(String billtaxIcSeqno) {
        this.billtaxIcSeqno = billtaxIcSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ATM_CHK
     *
     * @return the value of BILLTAX.BILLTAX_ATM_CHK
     *
     * @mbg.generated
     */
    public String getBilltaxAtmChk() {
        return billtaxAtmChk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ATM_CHK
     *
     * @param billtaxAtmChk the value for BILLTAX.BILLTAX_ATM_CHK
     *
     * @mbg.generated
     */
    public void setBilltaxAtmChk(String billtaxAtmChk) {
        this.billtaxAtmChk = billtaxAtmChk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_TRM_TYPE
     *
     * @return the value of BILLTAX.BILLTAX_TRM_TYPE
     *
     * @mbg.generated
     */
    public String getBilltaxTrmType() {
        return billtaxTrmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_TRM_TYPE
     *
     * @param billtaxTrmType the value for BILLTAX.BILLTAX_TRM_TYPE
     *
     * @mbg.generated
     */
    public void setBilltaxTrmType(String billtaxTrmType) {
        this.billtaxTrmType = billtaxTrmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_PAY_STAT
     *
     * @return the value of BILLTAX.BILLTAX_PAY_STAT
     *
     * @mbg.generated
     */
    public String getBilltaxPayStat() {
        return billtaxPayStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_PAY_STAT
     *
     * @param billtaxPayStat the value for BILLTAX.BILLTAX_PAY_STAT
     *
     * @mbg.generated
     */
    public void setBilltaxPayStat(String billtaxPayStat) {
        this.billtaxPayStat = billtaxPayStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_NPS_FEE_RCVR
     *
     * @return the value of BILLTAX.BILLTAX_NPS_FEE_RCVR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxNpsFeeRcvr() {
        return billtaxNpsFeeRcvr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_NPS_FEE_RCVR
     *
     * @param billtaxNpsFeeRcvr the value for BILLTAX.BILLTAX_NPS_FEE_RCVR
     *
     * @mbg.generated
     */
    public void setBilltaxNpsFeeRcvr(BigDecimal billtaxNpsFeeRcvr) {
        this.billtaxNpsFeeRcvr = billtaxNpsFeeRcvr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_NPS_FEE_AGENT
     *
     * @return the value of BILLTAX.BILLTAX_NPS_FEE_AGENT
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxNpsFeeAgent() {
        return billtaxNpsFeeAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_NPS_FEE_AGENT
     *
     * @param billtaxNpsFeeAgent the value for BILLTAX.BILLTAX_NPS_FEE_AGENT
     *
     * @mbg.generated
     */
    public void setBilltaxNpsFeeAgent(BigDecimal billtaxNpsFeeAgent) {
        this.billtaxNpsFeeAgent = billtaxNpsFeeAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_NPS_FEE_TROUT
     *
     * @return the value of BILLTAX.BILLTAX_NPS_FEE_TROUT
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxNpsFeeTrout() {
        return billtaxNpsFeeTrout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_NPS_FEE_TROUT
     *
     * @param billtaxNpsFeeTrout the value for BILLTAX.BILLTAX_NPS_FEE_TROUT
     *
     * @mbg.generated
     */
    public void setBilltaxNpsFeeTrout(BigDecimal billtaxNpsFeeTrout) {
        this.billtaxNpsFeeTrout = billtaxNpsFeeTrout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_NPS_FEE_TRIN
     *
     * @return the value of BILLTAX.BILLTAX_NPS_FEE_TRIN
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxNpsFeeTrin() {
        return billtaxNpsFeeTrin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_NPS_FEE_TRIN
     *
     * @param billtaxNpsFeeTrin the value for BILLTAX.BILLTAX_NPS_FEE_TRIN
     *
     * @mbg.generated
     */
    public void setBilltaxNpsFeeTrin(BigDecimal billtaxNpsFeeTrin) {
        this.billtaxNpsFeeTrin = billtaxNpsFeeTrin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_NPS_FEE_FISC
     *
     * @return the value of BILLTAX.BILLTAX_NPS_FEE_FISC
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxNpsFeeFisc() {
        return billtaxNpsFeeFisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_NPS_FEE_FISC
     *
     * @param billtaxNpsFeeFisc the value for BILLTAX.BILLTAX_NPS_FEE_FISC
     *
     * @mbg.generated
     */
    public void setBilltaxNpsFeeFisc(BigDecimal billtaxNpsFeeFisc) {
        this.billtaxNpsFeeFisc = billtaxNpsFeeFisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ATX_FEE_MBNK_CR
     *
     * @return the value of BILLTAX.BILLTAX_ATX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxAtxFeeMbnkCr() {
        return billtaxAtxFeeMbnkCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ATX_FEE_MBNK_CR
     *
     * @param billtaxAtxFeeMbnkCr the value for BILLTAX.BILLTAX_ATX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    public void setBilltaxAtxFeeMbnkCr(BigDecimal billtaxAtxFeeMbnkCr) {
        this.billtaxAtxFeeMbnkCr = billtaxAtxFeeMbnkCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ATX_FEE_MBNK_DR
     *
     * @return the value of BILLTAX.BILLTAX_ATX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxAtxFeeMbnkDr() {
        return billtaxAtxFeeMbnkDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ATX_FEE_MBNK_DR
     *
     * @param billtaxAtxFeeMbnkDr the value for BILLTAX.BILLTAX_ATX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    public void setBilltaxAtxFeeMbnkDr(BigDecimal billtaxAtxFeeMbnkDr) {
        this.billtaxAtxFeeMbnkDr = billtaxAtxFeeMbnkDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ATX_FEE_CR
     *
     * @return the value of BILLTAX.BILLTAX_ATX_FEE_CR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxAtxFeeCr() {
        return billtaxAtxFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ATX_FEE_CR
     *
     * @param billtaxAtxFeeCr the value for BILLTAX.BILLTAX_ATX_FEE_CR
     *
     * @mbg.generated
     */
    public void setBilltaxAtxFeeCr(BigDecimal billtaxAtxFeeCr) {
        this.billtaxAtxFeeCr = billtaxAtxFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ATX_FEE_DR
     *
     * @return the value of BILLTAX.BILLTAX_ATX_FEE_DR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxAtxFeeDr() {
        return billtaxAtxFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ATX_FEE_DR
     *
     * @param billtaxAtxFeeDr the value for BILLTAX.BILLTAX_ATX_FEE_DR
     *
     * @mbg.generated
     */
    public void setBilltaxAtxFeeDr(BigDecimal billtaxAtxFeeDr) {
        this.billtaxAtxFeeDr = billtaxAtxFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_OTX_FEE_MBNK_CR
     *
     * @return the value of BILLTAX.BILLTAX_OTX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxOtxFeeMbnkCr() {
        return billtaxOtxFeeMbnkCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_OTX_FEE_MBNK_CR
     *
     * @param billtaxOtxFeeMbnkCr the value for BILLTAX.BILLTAX_OTX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    public void setBilltaxOtxFeeMbnkCr(BigDecimal billtaxOtxFeeMbnkCr) {
        this.billtaxOtxFeeMbnkCr = billtaxOtxFeeMbnkCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_OTX_FEE_MBNK_DR
     *
     * @return the value of BILLTAX.BILLTAX_OTX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxOtxFeeMbnkDr() {
        return billtaxOtxFeeMbnkDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_OTX_FEE_MBNK_DR
     *
     * @param billtaxOtxFeeMbnkDr the value for BILLTAX.BILLTAX_OTX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    public void setBilltaxOtxFeeMbnkDr(BigDecimal billtaxOtxFeeMbnkDr) {
        this.billtaxOtxFeeMbnkDr = billtaxOtxFeeMbnkDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_OTX_FEE_CR
     *
     * @return the value of BILLTAX.BILLTAX_OTX_FEE_CR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxOtxFeeCr() {
        return billtaxOtxFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_OTX_FEE_CR
     *
     * @param billtaxOtxFeeCr the value for BILLTAX.BILLTAX_OTX_FEE_CR
     *
     * @mbg.generated
     */
    public void setBilltaxOtxFeeCr(BigDecimal billtaxOtxFeeCr) {
        this.billtaxOtxFeeCr = billtaxOtxFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_OTX_FEE_DR
     *
     * @return the value of BILLTAX.BILLTAX_OTX_FEE_DR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxOtxFeeDr() {
        return billtaxOtxFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_OTX_FEE_DR
     *
     * @param billtaxOtxFeeDr the value for BILLTAX.BILLTAX_OTX_FEE_DR
     *
     * @mbg.generated
     */
    public void setBilltaxOtxFeeDr(BigDecimal billtaxOtxFeeDr) {
        this.billtaxOtxFeeDr = billtaxOtxFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ITX_FEE_MBNK_CR
     *
     * @return the value of BILLTAX.BILLTAX_ITX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxItxFeeMbnkCr() {
        return billtaxItxFeeMbnkCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ITX_FEE_MBNK_CR
     *
     * @param billtaxItxFeeMbnkCr the value for BILLTAX.BILLTAX_ITX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    public void setBilltaxItxFeeMbnkCr(BigDecimal billtaxItxFeeMbnkCr) {
        this.billtaxItxFeeMbnkCr = billtaxItxFeeMbnkCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ITX_FEE_MBNK_DR
     *
     * @return the value of BILLTAX.BILLTAX_ITX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxItxFeeMbnkDr() {
        return billtaxItxFeeMbnkDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ITX_FEE_MBNK_DR
     *
     * @param billtaxItxFeeMbnkDr the value for BILLTAX.BILLTAX_ITX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    public void setBilltaxItxFeeMbnkDr(BigDecimal billtaxItxFeeMbnkDr) {
        this.billtaxItxFeeMbnkDr = billtaxItxFeeMbnkDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ITX_FEE_CR
     *
     * @return the value of BILLTAX.BILLTAX_ITX_FEE_CR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxItxFeeCr() {
        return billtaxItxFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ITX_FEE_CR
     *
     * @param billtaxItxFeeCr the value for BILLTAX.BILLTAX_ITX_FEE_CR
     *
     * @mbg.generated
     */
    public void setBilltaxItxFeeCr(BigDecimal billtaxItxFeeCr) {
        this.billtaxItxFeeCr = billtaxItxFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.BILLTAX_ITX_FEE_DR
     *
     * @return the value of BILLTAX.BILLTAX_ITX_FEE_DR
     *
     * @mbg.generated
     */
    public BigDecimal getBilltaxItxFeeDr() {
        return billtaxItxFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.BILLTAX_ITX_FEE_DR
     *
     * @param billtaxItxFeeDr the value for BILLTAX.BILLTAX_ITX_FEE_DR
     *
     * @mbg.generated
     */
    public void setBilltaxItxFeeDr(BigDecimal billtaxItxFeeDr) {
        this.billtaxItxFeeDr = billtaxItxFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.UPDATE_USERID
     *
     * @return the value of BILLTAX.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.UPDATE_USERID
     *
     * @param updateUserid the value for BILLTAX.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLTAX.UPDATE_TIME
     *
     * @return the value of BILLTAX.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLTAX.UPDATE_TIME
     *
     * @param updateTime the value for BILLTAX.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTAX
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", billtaxTbsdy=").append(billtaxTbsdy);
        sb.append(", billtaxStan=").append(billtaxStan);
        sb.append(", billtaxAcqBkno=").append(billtaxAcqBkno);
        sb.append(", billtaxTroutBkno=").append(billtaxTroutBkno);
        sb.append(", billtaxTrinBkno=").append(billtaxTrinBkno);
        sb.append(", billtaxPcode=").append(billtaxPcode);
        sb.append(", billtaxBussDate=").append(billtaxBussDate);
        sb.append(", billtaxTxDate=").append(billtaxTxDate);
        sb.append(", billtaxTxTime=").append(billtaxTxTime);
        sb.append(", billtaxAtmno=").append(billtaxAtmno);
        sb.append(", billtaxTrinActno=").append(billtaxTrinActno);
        sb.append(", billtaxTroutActno=").append(billtaxTroutActno);
        sb.append(", billtaxRep1Rc=").append(billtaxRep1Rc);
        sb.append(", billtaxRep2Rc=").append(billtaxRep2Rc);
        sb.append(", billtaxCon1Rc=").append(billtaxCon1Rc);
        sb.append(", billtaxCon2Rc=").append(billtaxCon2Rc);
        sb.append(", billtaxFiscRc=").append(billtaxFiscRc);
        sb.append(", billtaxTxAmt=").append(billtaxTxAmt);
        sb.append(", billtaxTxrust=").append(billtaxTxrust);
        sb.append(", billtaxTaxHq=").append(billtaxTaxHq);
        sb.append(", billtaxUtlHq=").append(billtaxUtlHq);
        sb.append(", billtaxPaytype=").append(billtaxPaytype);
        sb.append(", billtaxDueDate=").append(billtaxDueDate);
        sb.append(", billtaxReconSeqno=").append(billtaxReconSeqno);
        sb.append(", billtaxTaxUnit=").append(billtaxTaxUnit);
        sb.append(", billtaxIdno=").append(billtaxIdno);
        sb.append(", billtaxTaxDetail=").append(billtaxTaxDetail);
        sb.append(", billtaxTaxCity=").append(billtaxTaxCity);
        sb.append(", billtaxPayKind=").append(billtaxPayKind);
        sb.append(", billtaxIcSeqno=").append(billtaxIcSeqno);
        sb.append(", billtaxAtmChk=").append(billtaxAtmChk);
        sb.append(", billtaxTrmType=").append(billtaxTrmType);
        sb.append(", billtaxPayStat=").append(billtaxPayStat);
        sb.append(", billtaxNpsFeeRcvr=").append(billtaxNpsFeeRcvr);
        sb.append(", billtaxNpsFeeAgent=").append(billtaxNpsFeeAgent);
        sb.append(", billtaxNpsFeeTrout=").append(billtaxNpsFeeTrout);
        sb.append(", billtaxNpsFeeTrin=").append(billtaxNpsFeeTrin);
        sb.append(", billtaxNpsFeeFisc=").append(billtaxNpsFeeFisc);
        sb.append(", billtaxAtxFeeMbnkCr=").append(billtaxAtxFeeMbnkCr);
        sb.append(", billtaxAtxFeeMbnkDr=").append(billtaxAtxFeeMbnkDr);
        sb.append(", billtaxAtxFeeCr=").append(billtaxAtxFeeCr);
        sb.append(", billtaxAtxFeeDr=").append(billtaxAtxFeeDr);
        sb.append(", billtaxOtxFeeMbnkCr=").append(billtaxOtxFeeMbnkCr);
        sb.append(", billtaxOtxFeeMbnkDr=").append(billtaxOtxFeeMbnkDr);
        sb.append(", billtaxOtxFeeCr=").append(billtaxOtxFeeCr);
        sb.append(", billtaxOtxFeeDr=").append(billtaxOtxFeeDr);
        sb.append(", billtaxItxFeeMbnkCr=").append(billtaxItxFeeMbnkCr);
        sb.append(", billtaxItxFeeMbnkDr=").append(billtaxItxFeeMbnkDr);
        sb.append(", billtaxItxFeeCr=").append(billtaxItxFeeCr);
        sb.append(", billtaxItxFeeDr=").append(billtaxItxFeeDr);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTAX
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Billtax other = (Billtax) that;
        return (this.getBilltaxTbsdy() == null ? other.getBilltaxTbsdy() == null : this.getBilltaxTbsdy().equals(other.getBilltaxTbsdy()))
            && (this.getBilltaxStan() == null ? other.getBilltaxStan() == null : this.getBilltaxStan().equals(other.getBilltaxStan()))
            && (this.getBilltaxAcqBkno() == null ? other.getBilltaxAcqBkno() == null : this.getBilltaxAcqBkno().equals(other.getBilltaxAcqBkno()))
            && (this.getBilltaxTroutBkno() == null ? other.getBilltaxTroutBkno() == null : this.getBilltaxTroutBkno().equals(other.getBilltaxTroutBkno()))
            && (this.getBilltaxTrinBkno() == null ? other.getBilltaxTrinBkno() == null : this.getBilltaxTrinBkno().equals(other.getBilltaxTrinBkno()))
            && (this.getBilltaxPcode() == null ? other.getBilltaxPcode() == null : this.getBilltaxPcode().equals(other.getBilltaxPcode()))
            && (this.getBilltaxBussDate() == null ? other.getBilltaxBussDate() == null : this.getBilltaxBussDate().equals(other.getBilltaxBussDate()))
            && (this.getBilltaxTxDate() == null ? other.getBilltaxTxDate() == null : this.getBilltaxTxDate().equals(other.getBilltaxTxDate()))
            && (this.getBilltaxTxTime() == null ? other.getBilltaxTxTime() == null : this.getBilltaxTxTime().equals(other.getBilltaxTxTime()))
            && (this.getBilltaxAtmno() == null ? other.getBilltaxAtmno() == null : this.getBilltaxAtmno().equals(other.getBilltaxAtmno()))
            && (this.getBilltaxTrinActno() == null ? other.getBilltaxTrinActno() == null : this.getBilltaxTrinActno().equals(other.getBilltaxTrinActno()))
            && (this.getBilltaxTroutActno() == null ? other.getBilltaxTroutActno() == null : this.getBilltaxTroutActno().equals(other.getBilltaxTroutActno()))
            && (this.getBilltaxRep1Rc() == null ? other.getBilltaxRep1Rc() == null : this.getBilltaxRep1Rc().equals(other.getBilltaxRep1Rc()))
            && (this.getBilltaxRep2Rc() == null ? other.getBilltaxRep2Rc() == null : this.getBilltaxRep2Rc().equals(other.getBilltaxRep2Rc()))
            && (this.getBilltaxCon1Rc() == null ? other.getBilltaxCon1Rc() == null : this.getBilltaxCon1Rc().equals(other.getBilltaxCon1Rc()))
            && (this.getBilltaxCon2Rc() == null ? other.getBilltaxCon2Rc() == null : this.getBilltaxCon2Rc().equals(other.getBilltaxCon2Rc()))
            && (this.getBilltaxFiscRc() == null ? other.getBilltaxFiscRc() == null : this.getBilltaxFiscRc().equals(other.getBilltaxFiscRc()))
            && (this.getBilltaxTxAmt() == null ? other.getBilltaxTxAmt() == null : this.getBilltaxTxAmt().equals(other.getBilltaxTxAmt()))
            && (this.getBilltaxTxrust() == null ? other.getBilltaxTxrust() == null : this.getBilltaxTxrust().equals(other.getBilltaxTxrust()))
            && (this.getBilltaxTaxHq() == null ? other.getBilltaxTaxHq() == null : this.getBilltaxTaxHq().equals(other.getBilltaxTaxHq()))
            && (this.getBilltaxUtlHq() == null ? other.getBilltaxUtlHq() == null : this.getBilltaxUtlHq().equals(other.getBilltaxUtlHq()))
            && (this.getBilltaxPaytype() == null ? other.getBilltaxPaytype() == null : this.getBilltaxPaytype().equals(other.getBilltaxPaytype()))
            && (this.getBilltaxDueDate() == null ? other.getBilltaxDueDate() == null : this.getBilltaxDueDate().equals(other.getBilltaxDueDate()))
            && (this.getBilltaxReconSeqno() == null ? other.getBilltaxReconSeqno() == null : this.getBilltaxReconSeqno().equals(other.getBilltaxReconSeqno()))
            && (this.getBilltaxTaxUnit() == null ? other.getBilltaxTaxUnit() == null : this.getBilltaxTaxUnit().equals(other.getBilltaxTaxUnit()))
            && (this.getBilltaxIdno() == null ? other.getBilltaxIdno() == null : this.getBilltaxIdno().equals(other.getBilltaxIdno()))
            && (this.getBilltaxTaxDetail() == null ? other.getBilltaxTaxDetail() == null : this.getBilltaxTaxDetail().equals(other.getBilltaxTaxDetail()))
            && (this.getBilltaxTaxCity() == null ? other.getBilltaxTaxCity() == null : this.getBilltaxTaxCity().equals(other.getBilltaxTaxCity()))
            && (this.getBilltaxPayKind() == null ? other.getBilltaxPayKind() == null : this.getBilltaxPayKind().equals(other.getBilltaxPayKind()))
            && (this.getBilltaxIcSeqno() == null ? other.getBilltaxIcSeqno() == null : this.getBilltaxIcSeqno().equals(other.getBilltaxIcSeqno()))
            && (this.getBilltaxAtmChk() == null ? other.getBilltaxAtmChk() == null : this.getBilltaxAtmChk().equals(other.getBilltaxAtmChk()))
            && (this.getBilltaxTrmType() == null ? other.getBilltaxTrmType() == null : this.getBilltaxTrmType().equals(other.getBilltaxTrmType()))
            && (this.getBilltaxPayStat() == null ? other.getBilltaxPayStat() == null : this.getBilltaxPayStat().equals(other.getBilltaxPayStat()))
            && (this.getBilltaxNpsFeeRcvr() == null ? other.getBilltaxNpsFeeRcvr() == null : this.getBilltaxNpsFeeRcvr().equals(other.getBilltaxNpsFeeRcvr()))
            && (this.getBilltaxNpsFeeAgent() == null ? other.getBilltaxNpsFeeAgent() == null : this.getBilltaxNpsFeeAgent().equals(other.getBilltaxNpsFeeAgent()))
            && (this.getBilltaxNpsFeeTrout() == null ? other.getBilltaxNpsFeeTrout() == null : this.getBilltaxNpsFeeTrout().equals(other.getBilltaxNpsFeeTrout()))
            && (this.getBilltaxNpsFeeTrin() == null ? other.getBilltaxNpsFeeTrin() == null : this.getBilltaxNpsFeeTrin().equals(other.getBilltaxNpsFeeTrin()))
            && (this.getBilltaxNpsFeeFisc() == null ? other.getBilltaxNpsFeeFisc() == null : this.getBilltaxNpsFeeFisc().equals(other.getBilltaxNpsFeeFisc()))
            && (this.getBilltaxAtxFeeMbnkCr() == null ? other.getBilltaxAtxFeeMbnkCr() == null : this.getBilltaxAtxFeeMbnkCr().equals(other.getBilltaxAtxFeeMbnkCr()))
            && (this.getBilltaxAtxFeeMbnkDr() == null ? other.getBilltaxAtxFeeMbnkDr() == null : this.getBilltaxAtxFeeMbnkDr().equals(other.getBilltaxAtxFeeMbnkDr()))
            && (this.getBilltaxAtxFeeCr() == null ? other.getBilltaxAtxFeeCr() == null : this.getBilltaxAtxFeeCr().equals(other.getBilltaxAtxFeeCr()))
            && (this.getBilltaxAtxFeeDr() == null ? other.getBilltaxAtxFeeDr() == null : this.getBilltaxAtxFeeDr().equals(other.getBilltaxAtxFeeDr()))
            && (this.getBilltaxOtxFeeMbnkCr() == null ? other.getBilltaxOtxFeeMbnkCr() == null : this.getBilltaxOtxFeeMbnkCr().equals(other.getBilltaxOtxFeeMbnkCr()))
            && (this.getBilltaxOtxFeeMbnkDr() == null ? other.getBilltaxOtxFeeMbnkDr() == null : this.getBilltaxOtxFeeMbnkDr().equals(other.getBilltaxOtxFeeMbnkDr()))
            && (this.getBilltaxOtxFeeCr() == null ? other.getBilltaxOtxFeeCr() == null : this.getBilltaxOtxFeeCr().equals(other.getBilltaxOtxFeeCr()))
            && (this.getBilltaxOtxFeeDr() == null ? other.getBilltaxOtxFeeDr() == null : this.getBilltaxOtxFeeDr().equals(other.getBilltaxOtxFeeDr()))
            && (this.getBilltaxItxFeeMbnkCr() == null ? other.getBilltaxItxFeeMbnkCr() == null : this.getBilltaxItxFeeMbnkCr().equals(other.getBilltaxItxFeeMbnkCr()))
            && (this.getBilltaxItxFeeMbnkDr() == null ? other.getBilltaxItxFeeMbnkDr() == null : this.getBilltaxItxFeeMbnkDr().equals(other.getBilltaxItxFeeMbnkDr()))
            && (this.getBilltaxItxFeeCr() == null ? other.getBilltaxItxFeeCr() == null : this.getBilltaxItxFeeCr().equals(other.getBilltaxItxFeeCr()))
            && (this.getBilltaxItxFeeDr() == null ? other.getBilltaxItxFeeDr() == null : this.getBilltaxItxFeeDr().equals(other.getBilltaxItxFeeDr()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTAX
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getBilltaxTbsdy() == null) ? 0 : getBilltaxTbsdy().hashCode());
        result = 31 * result + ((getBilltaxStan() == null) ? 0 : getBilltaxStan().hashCode());
        result = 31 * result + ((getBilltaxAcqBkno() == null) ? 0 : getBilltaxAcqBkno().hashCode());
        result = 31 * result + ((getBilltaxTroutBkno() == null) ? 0 : getBilltaxTroutBkno().hashCode());
        result = 31 * result + ((getBilltaxTrinBkno() == null) ? 0 : getBilltaxTrinBkno().hashCode());
        result = 31 * result + ((getBilltaxPcode() == null) ? 0 : getBilltaxPcode().hashCode());
        result = 31 * result + ((getBilltaxBussDate() == null) ? 0 : getBilltaxBussDate().hashCode());
        result = 31 * result + ((getBilltaxTxDate() == null) ? 0 : getBilltaxTxDate().hashCode());
        result = 31 * result + ((getBilltaxTxTime() == null) ? 0 : getBilltaxTxTime().hashCode());
        result = 31 * result + ((getBilltaxAtmno() == null) ? 0 : getBilltaxAtmno().hashCode());
        result = 31 * result + ((getBilltaxTrinActno() == null) ? 0 : getBilltaxTrinActno().hashCode());
        result = 31 * result + ((getBilltaxTroutActno() == null) ? 0 : getBilltaxTroutActno().hashCode());
        result = 31 * result + ((getBilltaxRep1Rc() == null) ? 0 : getBilltaxRep1Rc().hashCode());
        result = 31 * result + ((getBilltaxRep2Rc() == null) ? 0 : getBilltaxRep2Rc().hashCode());
        result = 31 * result + ((getBilltaxCon1Rc() == null) ? 0 : getBilltaxCon1Rc().hashCode());
        result = 31 * result + ((getBilltaxCon2Rc() == null) ? 0 : getBilltaxCon2Rc().hashCode());
        result = 31 * result + ((getBilltaxFiscRc() == null) ? 0 : getBilltaxFiscRc().hashCode());
        result = 31 * result + ((getBilltaxTxAmt() == null) ? 0 : getBilltaxTxAmt().hashCode());
        result = 31 * result + ((getBilltaxTxrust() == null) ? 0 : getBilltaxTxrust().hashCode());
        result = 31 * result + ((getBilltaxTaxHq() == null) ? 0 : getBilltaxTaxHq().hashCode());
        result = 31 * result + ((getBilltaxUtlHq() == null) ? 0 : getBilltaxUtlHq().hashCode());
        result = 31 * result + ((getBilltaxPaytype() == null) ? 0 : getBilltaxPaytype().hashCode());
        result = 31 * result + ((getBilltaxDueDate() == null) ? 0 : getBilltaxDueDate().hashCode());
        result = 31 * result + ((getBilltaxReconSeqno() == null) ? 0 : getBilltaxReconSeqno().hashCode());
        result = 31 * result + ((getBilltaxTaxUnit() == null) ? 0 : getBilltaxTaxUnit().hashCode());
        result = 31 * result + ((getBilltaxIdno() == null) ? 0 : getBilltaxIdno().hashCode());
        result = 31 * result + ((getBilltaxTaxDetail() == null) ? 0 : getBilltaxTaxDetail().hashCode());
        result = 31 * result + ((getBilltaxTaxCity() == null) ? 0 : getBilltaxTaxCity().hashCode());
        result = 31 * result + ((getBilltaxPayKind() == null) ? 0 : getBilltaxPayKind().hashCode());
        result = 31 * result + ((getBilltaxIcSeqno() == null) ? 0 : getBilltaxIcSeqno().hashCode());
        result = 31 * result + ((getBilltaxAtmChk() == null) ? 0 : getBilltaxAtmChk().hashCode());
        result = 31 * result + ((getBilltaxTrmType() == null) ? 0 : getBilltaxTrmType().hashCode());
        result = 31 * result + ((getBilltaxPayStat() == null) ? 0 : getBilltaxPayStat().hashCode());
        result = 31 * result + ((getBilltaxNpsFeeRcvr() == null) ? 0 : getBilltaxNpsFeeRcvr().hashCode());
        result = 31 * result + ((getBilltaxNpsFeeAgent() == null) ? 0 : getBilltaxNpsFeeAgent().hashCode());
        result = 31 * result + ((getBilltaxNpsFeeTrout() == null) ? 0 : getBilltaxNpsFeeTrout().hashCode());
        result = 31 * result + ((getBilltaxNpsFeeTrin() == null) ? 0 : getBilltaxNpsFeeTrin().hashCode());
        result = 31 * result + ((getBilltaxNpsFeeFisc() == null) ? 0 : getBilltaxNpsFeeFisc().hashCode());
        result = 31 * result + ((getBilltaxAtxFeeMbnkCr() == null) ? 0 : getBilltaxAtxFeeMbnkCr().hashCode());
        result = 31 * result + ((getBilltaxAtxFeeMbnkDr() == null) ? 0 : getBilltaxAtxFeeMbnkDr().hashCode());
        result = 31 * result + ((getBilltaxAtxFeeCr() == null) ? 0 : getBilltaxAtxFeeCr().hashCode());
        result = 31 * result + ((getBilltaxAtxFeeDr() == null) ? 0 : getBilltaxAtxFeeDr().hashCode());
        result = 31 * result + ((getBilltaxOtxFeeMbnkCr() == null) ? 0 : getBilltaxOtxFeeMbnkCr().hashCode());
        result = 31 * result + ((getBilltaxOtxFeeMbnkDr() == null) ? 0 : getBilltaxOtxFeeMbnkDr().hashCode());
        result = 31 * result + ((getBilltaxOtxFeeCr() == null) ? 0 : getBilltaxOtxFeeCr().hashCode());
        result = 31 * result + ((getBilltaxOtxFeeDr() == null) ? 0 : getBilltaxOtxFeeDr().hashCode());
        result = 31 * result + ((getBilltaxItxFeeMbnkCr() == null) ? 0 : getBilltaxItxFeeMbnkCr().hashCode());
        result = 31 * result + ((getBilltaxItxFeeMbnkDr() == null) ? 0 : getBilltaxItxFeeMbnkDr().hashCode());
        result = 31 * result + ((getBilltaxItxFeeCr() == null) ? 0 : getBilltaxItxFeeCr().hashCode());
        result = 31 * result + ((getBilltaxItxFeeDr() == null) ? 0 : getBilltaxItxFeeDr().hashCode());
        result = 31 * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = 31 * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTAX
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<BILLTAX_TBSDY>").append(this.billtaxTbsdy).append("</BILLTAX_TBSDY>");
        sb.append("<BILLTAX_STAN>").append(this.billtaxStan).append("</BILLTAX_STAN>");
        sb.append("<BILLTAX_ACQ_BKNO>").append(this.billtaxAcqBkno).append("</BILLTAX_ACQ_BKNO>");
        sb.append("<BILLTAX_TROUT_BKNO>").append(this.billtaxTroutBkno).append("</BILLTAX_TROUT_BKNO>");
        sb.append("<BILLTAX_TRIN_BKNO>").append(this.billtaxTrinBkno).append("</BILLTAX_TRIN_BKNO>");
        sb.append("<BILLTAX_PCODE>").append(this.billtaxPcode).append("</BILLTAX_PCODE>");
        sb.append("<BILLTAX_BUSS_DATE>").append(this.billtaxBussDate).append("</BILLTAX_BUSS_DATE>");
        sb.append("<BILLTAX_TX_DATE>").append(this.billtaxTxDate).append("</BILLTAX_TX_DATE>");
        sb.append("<BILLTAX_TX_TIME>").append(this.billtaxTxTime).append("</BILLTAX_TX_TIME>");
        sb.append("<BILLTAX_ATMNO>").append(this.billtaxAtmno).append("</BILLTAX_ATMNO>");
        sb.append("<BILLTAX_TRIN_ACTNO>").append(this.billtaxTrinActno).append("</BILLTAX_TRIN_ACTNO>");
        sb.append("<BILLTAX_TROUT_ACTNO>").append(this.billtaxTroutActno).append("</BILLTAX_TROUT_ACTNO>");
        sb.append("<BILLTAX_REP1_RC>").append(this.billtaxRep1Rc).append("</BILLTAX_REP1_RC>");
        sb.append("<BILLTAX_REP2_RC>").append(this.billtaxRep2Rc).append("</BILLTAX_REP2_RC>");
        sb.append("<BILLTAX_CON1_RC>").append(this.billtaxCon1Rc).append("</BILLTAX_CON1_RC>");
        sb.append("<BILLTAX_CON2_RC>").append(this.billtaxCon2Rc).append("</BILLTAX_CON2_RC>");
        sb.append("<BILLTAX_FISC_RC>").append(this.billtaxFiscRc).append("</BILLTAX_FISC_RC>");
        sb.append("<BILLTAX_TX_AMT>").append(this.billtaxTxAmt).append("</BILLTAX_TX_AMT>");
        sb.append("<BILLTAX_TXRUST>").append(this.billtaxTxrust).append("</BILLTAX_TXRUST>");
        sb.append("<BILLTAX_TAX_HQ>").append(this.billtaxTaxHq).append("</BILLTAX_TAX_HQ>");
        sb.append("<BILLTAX_UTL_HQ>").append(this.billtaxUtlHq).append("</BILLTAX_UTL_HQ>");
        sb.append("<BILLTAX_PAYTYPE>").append(this.billtaxPaytype).append("</BILLTAX_PAYTYPE>");
        sb.append("<BILLTAX_DUE_DATE>").append(this.billtaxDueDate).append("</BILLTAX_DUE_DATE>");
        sb.append("<BILLTAX_RECON_SEQNO>").append(this.billtaxReconSeqno).append("</BILLTAX_RECON_SEQNO>");
        sb.append("<BILLTAX_TAX_UNIT>").append(this.billtaxTaxUnit).append("</BILLTAX_TAX_UNIT>");
        sb.append("<BILLTAX_IDNO>").append(this.billtaxIdno).append("</BILLTAX_IDNO>");
        sb.append("<BILLTAX_TAX_DETAIL>").append(this.billtaxTaxDetail).append("</BILLTAX_TAX_DETAIL>");
        sb.append("<BILLTAX_TAX_CITY>").append(this.billtaxTaxCity).append("</BILLTAX_TAX_CITY>");
        sb.append("<BILLTAX_PAY_KIND>").append(this.billtaxPayKind).append("</BILLTAX_PAY_KIND>");
        sb.append("<BILLTAX_IC_SEQNO>").append(this.billtaxIcSeqno).append("</BILLTAX_IC_SEQNO>");
        sb.append("<BILLTAX_ATM_CHK>").append(this.billtaxAtmChk).append("</BILLTAX_ATM_CHK>");
        sb.append("<BILLTAX_TRM_TYPE>").append(this.billtaxTrmType).append("</BILLTAX_TRM_TYPE>");
        sb.append("<BILLTAX_PAY_STAT>").append(this.billtaxPayStat).append("</BILLTAX_PAY_STAT>");
        sb.append("<BILLTAX_NPS_FEE_RCVR>").append(this.billtaxNpsFeeRcvr).append("</BILLTAX_NPS_FEE_RCVR>");
        sb.append("<BILLTAX_NPS_FEE_AGENT>").append(this.billtaxNpsFeeAgent).append("</BILLTAX_NPS_FEE_AGENT>");
        sb.append("<BILLTAX_NPS_FEE_TROUT>").append(this.billtaxNpsFeeTrout).append("</BILLTAX_NPS_FEE_TROUT>");
        sb.append("<BILLTAX_NPS_FEE_TRIN>").append(this.billtaxNpsFeeTrin).append("</BILLTAX_NPS_FEE_TRIN>");
        sb.append("<BILLTAX_NPS_FEE_FISC>").append(this.billtaxNpsFeeFisc).append("</BILLTAX_NPS_FEE_FISC>");
        sb.append("<BILLTAX_ATX_FEE_MBNK_CR>").append(this.billtaxAtxFeeMbnkCr).append("</BILLTAX_ATX_FEE_MBNK_CR>");
        sb.append("<BILLTAX_ATX_FEE_MBNK_DR>").append(this.billtaxAtxFeeMbnkDr).append("</BILLTAX_ATX_FEE_MBNK_DR>");
        sb.append("<BILLTAX_ATX_FEE_CR>").append(this.billtaxAtxFeeCr).append("</BILLTAX_ATX_FEE_CR>");
        sb.append("<BILLTAX_ATX_FEE_DR>").append(this.billtaxAtxFeeDr).append("</BILLTAX_ATX_FEE_DR>");
        sb.append("<BILLTAX_OTX_FEE_MBNK_CR>").append(this.billtaxOtxFeeMbnkCr).append("</BILLTAX_OTX_FEE_MBNK_CR>");
        sb.append("<BILLTAX_OTX_FEE_MBNK_DR>").append(this.billtaxOtxFeeMbnkDr).append("</BILLTAX_OTX_FEE_MBNK_DR>");
        sb.append("<BILLTAX_OTX_FEE_CR>").append(this.billtaxOtxFeeCr).append("</BILLTAX_OTX_FEE_CR>");
        sb.append("<BILLTAX_OTX_FEE_DR>").append(this.billtaxOtxFeeDr).append("</BILLTAX_OTX_FEE_DR>");
        sb.append("<BILLTAX_ITX_FEE_MBNK_CR>").append(this.billtaxItxFeeMbnkCr).append("</BILLTAX_ITX_FEE_MBNK_CR>");
        sb.append("<BILLTAX_ITX_FEE_MBNK_DR>").append(this.billtaxItxFeeMbnkDr).append("</BILLTAX_ITX_FEE_MBNK_DR>");
        sb.append("<BILLTAX_ITX_FEE_CR>").append(this.billtaxItxFeeCr).append("</BILLTAX_ITX_FEE_CR>");
        sb.append("<BILLTAX_ITX_FEE_DR>").append(this.billtaxItxFeeDr).append("</BILLTAX_ITX_FEE_DR>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        return sb.toString();
    }
}