package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class Chip251 extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_TBSDY
     *
     * @mbg.generated
     */
    private String chip251Tbsdy = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_STAN
     *
     * @mbg.generated
     */
    private String chip251Stan = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_SRC_BKNO
     *
     * @mbg.generated
     */
    private String chip251SrcBkno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_DES_BKNO
     *
     * @mbg.generated
     */
    private String chip251DesBkno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_PCODE
     *
     * @mbg.generated
     */
    private String chip251Pcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_TX_TIME
     *
     * @mbg.generated
     */
    private String chip251TxTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_TROUT_ACTNO
     *
     * @mbg.generated
     */
    private String chip251TroutActno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_ATMNO
     *
     * @mbg.generated
     */
    private String chip251Atmno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_TXRUST
     *
     * @mbg.generated
     */
    private String chip251Txrust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_REQ_RC
     *
     * @mbg.generated
     */
    private String chip251ReqRc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_REP_RC
     *
     * @mbg.generated
     */
    private String chip251RepRc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_CON1_RC
     *
     * @mbg.generated
     */
    private String chip251Con1Rc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_CON2_RC
     *
     * @mbg.generated
     */
    private String chip251Con2Rc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_TX_AMT
     *
     * @mbg.generated
     */
    private BigDecimal chip251TxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_TX_DATE
     *
     * @mbg.generated
     */
    private String chip251TxDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_SRC_BRNO
     *
     * @mbg.generated
     */
    private String chip251SrcBrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_DES_BRNO
     *
     * @mbg.generated
     */
    private String chip251DesBrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_IC_SEQNO
     *
     * @mbg.generated
     */
    private String chip251IcSeqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_ATM_CHK
     *
     * @mbg.generated
     */
    private String chip251AtmChk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_STX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    private BigDecimal chip251StxFeeMbnkCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_STX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    private BigDecimal chip251StxFeeMbnkDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_STX_FEE_CR
     *
     * @mbg.generated
     */
    private BigDecimal chip251StxFeeCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_STX_FEE_DR
     *
     * @mbg.generated
     */
    private BigDecimal chip251StxFeeDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_DTX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    private BigDecimal chip251DtxFeeMbnkCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_DTX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    private BigDecimal chip251DtxFeeMbnkDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_DTX_FEE_CR
     *
     * @mbg.generated
     */
    private BigDecimal chip251DtxFeeCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.CHIP251_DTX_FEE_DR
     *
     * @mbg.generated
     */
    private BigDecimal chip251DtxFeeDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP251.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHIP251
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP251
     *
     * @mbg.generated
     */
    public Chip251(String chip251Tbsdy, String chip251Stan, String chip251SrcBkno, String chip251DesBkno, String chip251Pcode, String chip251TxTime, String chip251TroutActno, String chip251Atmno, String chip251Txrust, String chip251ReqRc, String chip251RepRc, String chip251Con1Rc, String chip251Con2Rc, BigDecimal chip251TxAmt, String chip251TxDate, String chip251SrcBrno, String chip251DesBrno, String chip251IcSeqno, String chip251AtmChk, BigDecimal chip251StxFeeMbnkCr, BigDecimal chip251StxFeeMbnkDr, BigDecimal chip251StxFeeCr, BigDecimal chip251StxFeeDr, BigDecimal chip251DtxFeeMbnkCr, BigDecimal chip251DtxFeeMbnkDr, BigDecimal chip251DtxFeeCr, BigDecimal chip251DtxFeeDr, Integer updateUserid, Date updateTime) {
        this.chip251Tbsdy = chip251Tbsdy;
        this.chip251Stan = chip251Stan;
        this.chip251SrcBkno = chip251SrcBkno;
        this.chip251DesBkno = chip251DesBkno;
        this.chip251Pcode = chip251Pcode;
        this.chip251TxTime = chip251TxTime;
        this.chip251TroutActno = chip251TroutActno;
        this.chip251Atmno = chip251Atmno;
        this.chip251Txrust = chip251Txrust;
        this.chip251ReqRc = chip251ReqRc;
        this.chip251RepRc = chip251RepRc;
        this.chip251Con1Rc = chip251Con1Rc;
        this.chip251Con2Rc = chip251Con2Rc;
        this.chip251TxAmt = chip251TxAmt;
        this.chip251TxDate = chip251TxDate;
        this.chip251SrcBrno = chip251SrcBrno;
        this.chip251DesBrno = chip251DesBrno;
        this.chip251IcSeqno = chip251IcSeqno;
        this.chip251AtmChk = chip251AtmChk;
        this.chip251StxFeeMbnkCr = chip251StxFeeMbnkCr;
        this.chip251StxFeeMbnkDr = chip251StxFeeMbnkDr;
        this.chip251StxFeeCr = chip251StxFeeCr;
        this.chip251StxFeeDr = chip251StxFeeDr;
        this.chip251DtxFeeMbnkCr = chip251DtxFeeMbnkCr;
        this.chip251DtxFeeMbnkDr = chip251DtxFeeMbnkDr;
        this.chip251DtxFeeCr = chip251DtxFeeCr;
        this.chip251DtxFeeDr = chip251DtxFeeDr;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP251
     *
     * @mbg.generated
     */
    public Chip251() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_TBSDY
     *
     * @return the value of CHIP251.CHIP251_TBSDY
     *
     * @mbg.generated
     */
    public String getChip251Tbsdy() {
        return chip251Tbsdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_TBSDY
     *
     * @param chip251Tbsdy the value for CHIP251.CHIP251_TBSDY
     *
     * @mbg.generated
     */
    public void setChip251Tbsdy(String chip251Tbsdy) {
        this.chip251Tbsdy = chip251Tbsdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_STAN
     *
     * @return the value of CHIP251.CHIP251_STAN
     *
     * @mbg.generated
     */
    public String getChip251Stan() {
        return chip251Stan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_STAN
     *
     * @param chip251Stan the value for CHIP251.CHIP251_STAN
     *
     * @mbg.generated
     */
    public void setChip251Stan(String chip251Stan) {
        this.chip251Stan = chip251Stan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_SRC_BKNO
     *
     * @return the value of CHIP251.CHIP251_SRC_BKNO
     *
     * @mbg.generated
     */
    public String getChip251SrcBkno() {
        return chip251SrcBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_SRC_BKNO
     *
     * @param chip251SrcBkno the value for CHIP251.CHIP251_SRC_BKNO
     *
     * @mbg.generated
     */
    public void setChip251SrcBkno(String chip251SrcBkno) {
        this.chip251SrcBkno = chip251SrcBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_DES_BKNO
     *
     * @return the value of CHIP251.CHIP251_DES_BKNO
     *
     * @mbg.generated
     */
    public String getChip251DesBkno() {
        return chip251DesBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_DES_BKNO
     *
     * @param chip251DesBkno the value for CHIP251.CHIP251_DES_BKNO
     *
     * @mbg.generated
     */
    public void setChip251DesBkno(String chip251DesBkno) {
        this.chip251DesBkno = chip251DesBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_PCODE
     *
     * @return the value of CHIP251.CHIP251_PCODE
     *
     * @mbg.generated
     */
    public String getChip251Pcode() {
        return chip251Pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_PCODE
     *
     * @param chip251Pcode the value for CHIP251.CHIP251_PCODE
     *
     * @mbg.generated
     */
    public void setChip251Pcode(String chip251Pcode) {
        this.chip251Pcode = chip251Pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_TX_TIME
     *
     * @return the value of CHIP251.CHIP251_TX_TIME
     *
     * @mbg.generated
     */
    public String getChip251TxTime() {
        return chip251TxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_TX_TIME
     *
     * @param chip251TxTime the value for CHIP251.CHIP251_TX_TIME
     *
     * @mbg.generated
     */
    public void setChip251TxTime(String chip251TxTime) {
        this.chip251TxTime = chip251TxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_TROUT_ACTNO
     *
     * @return the value of CHIP251.CHIP251_TROUT_ACTNO
     *
     * @mbg.generated
     */
    public String getChip251TroutActno() {
        return chip251TroutActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_TROUT_ACTNO
     *
     * @param chip251TroutActno the value for CHIP251.CHIP251_TROUT_ACTNO
     *
     * @mbg.generated
     */
    public void setChip251TroutActno(String chip251TroutActno) {
        this.chip251TroutActno = chip251TroutActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_ATMNO
     *
     * @return the value of CHIP251.CHIP251_ATMNO
     *
     * @mbg.generated
     */
    public String getChip251Atmno() {
        return chip251Atmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_ATMNO
     *
     * @param chip251Atmno the value for CHIP251.CHIP251_ATMNO
     *
     * @mbg.generated
     */
    public void setChip251Atmno(String chip251Atmno) {
        this.chip251Atmno = chip251Atmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_TXRUST
     *
     * @return the value of CHIP251.CHIP251_TXRUST
     *
     * @mbg.generated
     */
    public String getChip251Txrust() {
        return chip251Txrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_TXRUST
     *
     * @param chip251Txrust the value for CHIP251.CHIP251_TXRUST
     *
     * @mbg.generated
     */
    public void setChip251Txrust(String chip251Txrust) {
        this.chip251Txrust = chip251Txrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_REQ_RC
     *
     * @return the value of CHIP251.CHIP251_REQ_RC
     *
     * @mbg.generated
     */
    public String getChip251ReqRc() {
        return chip251ReqRc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_REQ_RC
     *
     * @param chip251ReqRc the value for CHIP251.CHIP251_REQ_RC
     *
     * @mbg.generated
     */
    public void setChip251ReqRc(String chip251ReqRc) {
        this.chip251ReqRc = chip251ReqRc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_REP_RC
     *
     * @return the value of CHIP251.CHIP251_REP_RC
     *
     * @mbg.generated
     */
    public String getChip251RepRc() {
        return chip251RepRc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_REP_RC
     *
     * @param chip251RepRc the value for CHIP251.CHIP251_REP_RC
     *
     * @mbg.generated
     */
    public void setChip251RepRc(String chip251RepRc) {
        this.chip251RepRc = chip251RepRc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_CON1_RC
     *
     * @return the value of CHIP251.CHIP251_CON1_RC
     *
     * @mbg.generated
     */
    public String getChip251Con1Rc() {
        return chip251Con1Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_CON1_RC
     *
     * @param chip251Con1Rc the value for CHIP251.CHIP251_CON1_RC
     *
     * @mbg.generated
     */
    public void setChip251Con1Rc(String chip251Con1Rc) {
        this.chip251Con1Rc = chip251Con1Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_CON2_RC
     *
     * @return the value of CHIP251.CHIP251_CON2_RC
     *
     * @mbg.generated
     */
    public String getChip251Con2Rc() {
        return chip251Con2Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_CON2_RC
     *
     * @param chip251Con2Rc the value for CHIP251.CHIP251_CON2_RC
     *
     * @mbg.generated
     */
    public void setChip251Con2Rc(String chip251Con2Rc) {
        this.chip251Con2Rc = chip251Con2Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_TX_AMT
     *
     * @return the value of CHIP251.CHIP251_TX_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getChip251TxAmt() {
        return chip251TxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_TX_AMT
     *
     * @param chip251TxAmt the value for CHIP251.CHIP251_TX_AMT
     *
     * @mbg.generated
     */
    public void setChip251TxAmt(BigDecimal chip251TxAmt) {
        this.chip251TxAmt = chip251TxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_TX_DATE
     *
     * @return the value of CHIP251.CHIP251_TX_DATE
     *
     * @mbg.generated
     */
    public String getChip251TxDate() {
        return chip251TxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_TX_DATE
     *
     * @param chip251TxDate the value for CHIP251.CHIP251_TX_DATE
     *
     * @mbg.generated
     */
    public void setChip251TxDate(String chip251TxDate) {
        this.chip251TxDate = chip251TxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_SRC_BRNO
     *
     * @return the value of CHIP251.CHIP251_SRC_BRNO
     *
     * @mbg.generated
     */
    public String getChip251SrcBrno() {
        return chip251SrcBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_SRC_BRNO
     *
     * @param chip251SrcBrno the value for CHIP251.CHIP251_SRC_BRNO
     *
     * @mbg.generated
     */
    public void setChip251SrcBrno(String chip251SrcBrno) {
        this.chip251SrcBrno = chip251SrcBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_DES_BRNO
     *
     * @return the value of CHIP251.CHIP251_DES_BRNO
     *
     * @mbg.generated
     */
    public String getChip251DesBrno() {
        return chip251DesBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_DES_BRNO
     *
     * @param chip251DesBrno the value for CHIP251.CHIP251_DES_BRNO
     *
     * @mbg.generated
     */
    public void setChip251DesBrno(String chip251DesBrno) {
        this.chip251DesBrno = chip251DesBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_IC_SEQNO
     *
     * @return the value of CHIP251.CHIP251_IC_SEQNO
     *
     * @mbg.generated
     */
    public String getChip251IcSeqno() {
        return chip251IcSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_IC_SEQNO
     *
     * @param chip251IcSeqno the value for CHIP251.CHIP251_IC_SEQNO
     *
     * @mbg.generated
     */
    public void setChip251IcSeqno(String chip251IcSeqno) {
        this.chip251IcSeqno = chip251IcSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_ATM_CHK
     *
     * @return the value of CHIP251.CHIP251_ATM_CHK
     *
     * @mbg.generated
     */
    public String getChip251AtmChk() {
        return chip251AtmChk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_ATM_CHK
     *
     * @param chip251AtmChk the value for CHIP251.CHIP251_ATM_CHK
     *
     * @mbg.generated
     */
    public void setChip251AtmChk(String chip251AtmChk) {
        this.chip251AtmChk = chip251AtmChk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_STX_FEE_MBNK_CR
     *
     * @return the value of CHIP251.CHIP251_STX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    public BigDecimal getChip251StxFeeMbnkCr() {
        return chip251StxFeeMbnkCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_STX_FEE_MBNK_CR
     *
     * @param chip251StxFeeMbnkCr the value for CHIP251.CHIP251_STX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    public void setChip251StxFeeMbnkCr(BigDecimal chip251StxFeeMbnkCr) {
        this.chip251StxFeeMbnkCr = chip251StxFeeMbnkCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_STX_FEE_MBNK_DR
     *
     * @return the value of CHIP251.CHIP251_STX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    public BigDecimal getChip251StxFeeMbnkDr() {
        return chip251StxFeeMbnkDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_STX_FEE_MBNK_DR
     *
     * @param chip251StxFeeMbnkDr the value for CHIP251.CHIP251_STX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    public void setChip251StxFeeMbnkDr(BigDecimal chip251StxFeeMbnkDr) {
        this.chip251StxFeeMbnkDr = chip251StxFeeMbnkDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_STX_FEE_CR
     *
     * @return the value of CHIP251.CHIP251_STX_FEE_CR
     *
     * @mbg.generated
     */
    public BigDecimal getChip251StxFeeCr() {
        return chip251StxFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_STX_FEE_CR
     *
     * @param chip251StxFeeCr the value for CHIP251.CHIP251_STX_FEE_CR
     *
     * @mbg.generated
     */
    public void setChip251StxFeeCr(BigDecimal chip251StxFeeCr) {
        this.chip251StxFeeCr = chip251StxFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_STX_FEE_DR
     *
     * @return the value of CHIP251.CHIP251_STX_FEE_DR
     *
     * @mbg.generated
     */
    public BigDecimal getChip251StxFeeDr() {
        return chip251StxFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_STX_FEE_DR
     *
     * @param chip251StxFeeDr the value for CHIP251.CHIP251_STX_FEE_DR
     *
     * @mbg.generated
     */
    public void setChip251StxFeeDr(BigDecimal chip251StxFeeDr) {
        this.chip251StxFeeDr = chip251StxFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_DTX_FEE_MBNK_CR
     *
     * @return the value of CHIP251.CHIP251_DTX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    public BigDecimal getChip251DtxFeeMbnkCr() {
        return chip251DtxFeeMbnkCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_DTX_FEE_MBNK_CR
     *
     * @param chip251DtxFeeMbnkCr the value for CHIP251.CHIP251_DTX_FEE_MBNK_CR
     *
     * @mbg.generated
     */
    public void setChip251DtxFeeMbnkCr(BigDecimal chip251DtxFeeMbnkCr) {
        this.chip251DtxFeeMbnkCr = chip251DtxFeeMbnkCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_DTX_FEE_MBNK_DR
     *
     * @return the value of CHIP251.CHIP251_DTX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    public BigDecimal getChip251DtxFeeMbnkDr() {
        return chip251DtxFeeMbnkDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_DTX_FEE_MBNK_DR
     *
     * @param chip251DtxFeeMbnkDr the value for CHIP251.CHIP251_DTX_FEE_MBNK_DR
     *
     * @mbg.generated
     */
    public void setChip251DtxFeeMbnkDr(BigDecimal chip251DtxFeeMbnkDr) {
        this.chip251DtxFeeMbnkDr = chip251DtxFeeMbnkDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_DTX_FEE_CR
     *
     * @return the value of CHIP251.CHIP251_DTX_FEE_CR
     *
     * @mbg.generated
     */
    public BigDecimal getChip251DtxFeeCr() {
        return chip251DtxFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_DTX_FEE_CR
     *
     * @param chip251DtxFeeCr the value for CHIP251.CHIP251_DTX_FEE_CR
     *
     * @mbg.generated
     */
    public void setChip251DtxFeeCr(BigDecimal chip251DtxFeeCr) {
        this.chip251DtxFeeCr = chip251DtxFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.CHIP251_DTX_FEE_DR
     *
     * @return the value of CHIP251.CHIP251_DTX_FEE_DR
     *
     * @mbg.generated
     */
    public BigDecimal getChip251DtxFeeDr() {
        return chip251DtxFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.CHIP251_DTX_FEE_DR
     *
     * @param chip251DtxFeeDr the value for CHIP251.CHIP251_DTX_FEE_DR
     *
     * @mbg.generated
     */
    public void setChip251DtxFeeDr(BigDecimal chip251DtxFeeDr) {
        this.chip251DtxFeeDr = chip251DtxFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.UPDATE_USERID
     *
     * @return the value of CHIP251.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.UPDATE_USERID
     *
     * @param updateUserid the value for CHIP251.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP251.UPDATE_TIME
     *
     * @return the value of CHIP251.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP251.UPDATE_TIME
     *
     * @param updateTime the value for CHIP251.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP251
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chip251Tbsdy=").append(chip251Tbsdy);
        sb.append(", chip251Stan=").append(chip251Stan);
        sb.append(", chip251SrcBkno=").append(chip251SrcBkno);
        sb.append(", chip251DesBkno=").append(chip251DesBkno);
        sb.append(", chip251Pcode=").append(chip251Pcode);
        sb.append(", chip251TxTime=").append(chip251TxTime);
        sb.append(", chip251TroutActno=").append(chip251TroutActno);
        sb.append(", chip251Atmno=").append(chip251Atmno);
        sb.append(", chip251Txrust=").append(chip251Txrust);
        sb.append(", chip251ReqRc=").append(chip251ReqRc);
        sb.append(", chip251RepRc=").append(chip251RepRc);
        sb.append(", chip251Con1Rc=").append(chip251Con1Rc);
        sb.append(", chip251Con2Rc=").append(chip251Con2Rc);
        sb.append(", chip251TxAmt=").append(chip251TxAmt);
        sb.append(", chip251TxDate=").append(chip251TxDate);
        sb.append(", chip251SrcBrno=").append(chip251SrcBrno);
        sb.append(", chip251DesBrno=").append(chip251DesBrno);
        sb.append(", chip251IcSeqno=").append(chip251IcSeqno);
        sb.append(", chip251AtmChk=").append(chip251AtmChk);
        sb.append(", chip251StxFeeMbnkCr=").append(chip251StxFeeMbnkCr);
        sb.append(", chip251StxFeeMbnkDr=").append(chip251StxFeeMbnkDr);
        sb.append(", chip251StxFeeCr=").append(chip251StxFeeCr);
        sb.append(", chip251StxFeeDr=").append(chip251StxFeeDr);
        sb.append(", chip251DtxFeeMbnkCr=").append(chip251DtxFeeMbnkCr);
        sb.append(", chip251DtxFeeMbnkDr=").append(chip251DtxFeeMbnkDr);
        sb.append(", chip251DtxFeeCr=").append(chip251DtxFeeCr);
        sb.append(", chip251DtxFeeDr=").append(chip251DtxFeeDr);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP251
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Chip251 other = (Chip251) that;
        return (this.getChip251Tbsdy() == null ? other.getChip251Tbsdy() == null : this.getChip251Tbsdy().equals(other.getChip251Tbsdy()))
            && (this.getChip251Stan() == null ? other.getChip251Stan() == null : this.getChip251Stan().equals(other.getChip251Stan()))
            && (this.getChip251SrcBkno() == null ? other.getChip251SrcBkno() == null : this.getChip251SrcBkno().equals(other.getChip251SrcBkno()))
            && (this.getChip251DesBkno() == null ? other.getChip251DesBkno() == null : this.getChip251DesBkno().equals(other.getChip251DesBkno()))
            && (this.getChip251Pcode() == null ? other.getChip251Pcode() == null : this.getChip251Pcode().equals(other.getChip251Pcode()))
            && (this.getChip251TxTime() == null ? other.getChip251TxTime() == null : this.getChip251TxTime().equals(other.getChip251TxTime()))
            && (this.getChip251TroutActno() == null ? other.getChip251TroutActno() == null : this.getChip251TroutActno().equals(other.getChip251TroutActno()))
            && (this.getChip251Atmno() == null ? other.getChip251Atmno() == null : this.getChip251Atmno().equals(other.getChip251Atmno()))
            && (this.getChip251Txrust() == null ? other.getChip251Txrust() == null : this.getChip251Txrust().equals(other.getChip251Txrust()))
            && (this.getChip251ReqRc() == null ? other.getChip251ReqRc() == null : this.getChip251ReqRc().equals(other.getChip251ReqRc()))
            && (this.getChip251RepRc() == null ? other.getChip251RepRc() == null : this.getChip251RepRc().equals(other.getChip251RepRc()))
            && (this.getChip251Con1Rc() == null ? other.getChip251Con1Rc() == null : this.getChip251Con1Rc().equals(other.getChip251Con1Rc()))
            && (this.getChip251Con2Rc() == null ? other.getChip251Con2Rc() == null : this.getChip251Con2Rc().equals(other.getChip251Con2Rc()))
            && (this.getChip251TxAmt() == null ? other.getChip251TxAmt() == null : this.getChip251TxAmt().equals(other.getChip251TxAmt()))
            && (this.getChip251TxDate() == null ? other.getChip251TxDate() == null : this.getChip251TxDate().equals(other.getChip251TxDate()))
            && (this.getChip251SrcBrno() == null ? other.getChip251SrcBrno() == null : this.getChip251SrcBrno().equals(other.getChip251SrcBrno()))
            && (this.getChip251DesBrno() == null ? other.getChip251DesBrno() == null : this.getChip251DesBrno().equals(other.getChip251DesBrno()))
            && (this.getChip251IcSeqno() == null ? other.getChip251IcSeqno() == null : this.getChip251IcSeqno().equals(other.getChip251IcSeqno()))
            && (this.getChip251AtmChk() == null ? other.getChip251AtmChk() == null : this.getChip251AtmChk().equals(other.getChip251AtmChk()))
            && (this.getChip251StxFeeMbnkCr() == null ? other.getChip251StxFeeMbnkCr() == null : this.getChip251StxFeeMbnkCr().equals(other.getChip251StxFeeMbnkCr()))
            && (this.getChip251StxFeeMbnkDr() == null ? other.getChip251StxFeeMbnkDr() == null : this.getChip251StxFeeMbnkDr().equals(other.getChip251StxFeeMbnkDr()))
            && (this.getChip251StxFeeCr() == null ? other.getChip251StxFeeCr() == null : this.getChip251StxFeeCr().equals(other.getChip251StxFeeCr()))
            && (this.getChip251StxFeeDr() == null ? other.getChip251StxFeeDr() == null : this.getChip251StxFeeDr().equals(other.getChip251StxFeeDr()))
            && (this.getChip251DtxFeeMbnkCr() == null ? other.getChip251DtxFeeMbnkCr() == null : this.getChip251DtxFeeMbnkCr().equals(other.getChip251DtxFeeMbnkCr()))
            && (this.getChip251DtxFeeMbnkDr() == null ? other.getChip251DtxFeeMbnkDr() == null : this.getChip251DtxFeeMbnkDr().equals(other.getChip251DtxFeeMbnkDr()))
            && (this.getChip251DtxFeeCr() == null ? other.getChip251DtxFeeCr() == null : this.getChip251DtxFeeCr().equals(other.getChip251DtxFeeCr()))
            && (this.getChip251DtxFeeDr() == null ? other.getChip251DtxFeeDr() == null : this.getChip251DtxFeeDr().equals(other.getChip251DtxFeeDr()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP251
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getChip251Tbsdy() == null) ? 0 : getChip251Tbsdy().hashCode());
        result = 31 * result + ((getChip251Stan() == null) ? 0 : getChip251Stan().hashCode());
        result = 31 * result + ((getChip251SrcBkno() == null) ? 0 : getChip251SrcBkno().hashCode());
        result = 31 * result + ((getChip251DesBkno() == null) ? 0 : getChip251DesBkno().hashCode());
        result = 31 * result + ((getChip251Pcode() == null) ? 0 : getChip251Pcode().hashCode());
        result = 31 * result + ((getChip251TxTime() == null) ? 0 : getChip251TxTime().hashCode());
        result = 31 * result + ((getChip251TroutActno() == null) ? 0 : getChip251TroutActno().hashCode());
        result = 31 * result + ((getChip251Atmno() == null) ? 0 : getChip251Atmno().hashCode());
        result = 31 * result + ((getChip251Txrust() == null) ? 0 : getChip251Txrust().hashCode());
        result = 31 * result + ((getChip251ReqRc() == null) ? 0 : getChip251ReqRc().hashCode());
        result = 31 * result + ((getChip251RepRc() == null) ? 0 : getChip251RepRc().hashCode());
        result = 31 * result + ((getChip251Con1Rc() == null) ? 0 : getChip251Con1Rc().hashCode());
        result = 31 * result + ((getChip251Con2Rc() == null) ? 0 : getChip251Con2Rc().hashCode());
        result = 31 * result + ((getChip251TxAmt() == null) ? 0 : getChip251TxAmt().hashCode());
        result = 31 * result + ((getChip251TxDate() == null) ? 0 : getChip251TxDate().hashCode());
        result = 31 * result + ((getChip251SrcBrno() == null) ? 0 : getChip251SrcBrno().hashCode());
        result = 31 * result + ((getChip251DesBrno() == null) ? 0 : getChip251DesBrno().hashCode());
        result = 31 * result + ((getChip251IcSeqno() == null) ? 0 : getChip251IcSeqno().hashCode());
        result = 31 * result + ((getChip251AtmChk() == null) ? 0 : getChip251AtmChk().hashCode());
        result = 31 * result + ((getChip251StxFeeMbnkCr() == null) ? 0 : getChip251StxFeeMbnkCr().hashCode());
        result = 31 * result + ((getChip251StxFeeMbnkDr() == null) ? 0 : getChip251StxFeeMbnkDr().hashCode());
        result = 31 * result + ((getChip251StxFeeCr() == null) ? 0 : getChip251StxFeeCr().hashCode());
        result = 31 * result + ((getChip251StxFeeDr() == null) ? 0 : getChip251StxFeeDr().hashCode());
        result = 31 * result + ((getChip251DtxFeeMbnkCr() == null) ? 0 : getChip251DtxFeeMbnkCr().hashCode());
        result = 31 * result + ((getChip251DtxFeeMbnkDr() == null) ? 0 : getChip251DtxFeeMbnkDr().hashCode());
        result = 31 * result + ((getChip251DtxFeeCr() == null) ? 0 : getChip251DtxFeeCr().hashCode());
        result = 31 * result + ((getChip251DtxFeeDr() == null) ? 0 : getChip251DtxFeeDr().hashCode());
        result = 31 * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = 31 * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP251
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<CHIP251_TBSDY>").append(this.chip251Tbsdy).append("</CHIP251_TBSDY>");
        sb.append("<CHIP251_STAN>").append(this.chip251Stan).append("</CHIP251_STAN>");
        sb.append("<CHIP251_SRC_BKNO>").append(this.chip251SrcBkno).append("</CHIP251_SRC_BKNO>");
        sb.append("<CHIP251_DES_BKNO>").append(this.chip251DesBkno).append("</CHIP251_DES_BKNO>");
        sb.append("<CHIP251_PCODE>").append(this.chip251Pcode).append("</CHIP251_PCODE>");
        sb.append("<CHIP251_TX_TIME>").append(this.chip251TxTime).append("</CHIP251_TX_TIME>");
        sb.append("<CHIP251_TROUT_ACTNO>").append(this.chip251TroutActno).append("</CHIP251_TROUT_ACTNO>");
        sb.append("<CHIP251_ATMNO>").append(this.chip251Atmno).append("</CHIP251_ATMNO>");
        sb.append("<CHIP251_TXRUST>").append(this.chip251Txrust).append("</CHIP251_TXRUST>");
        sb.append("<CHIP251_REQ_RC>").append(this.chip251ReqRc).append("</CHIP251_REQ_RC>");
        sb.append("<CHIP251_REP_RC>").append(this.chip251RepRc).append("</CHIP251_REP_RC>");
        sb.append("<CHIP251_CON1_RC>").append(this.chip251Con1Rc).append("</CHIP251_CON1_RC>");
        sb.append("<CHIP251_CON2_RC>").append(this.chip251Con2Rc).append("</CHIP251_CON2_RC>");
        sb.append("<CHIP251_TX_AMT>").append(this.chip251TxAmt).append("</CHIP251_TX_AMT>");
        sb.append("<CHIP251_TX_DATE>").append(this.chip251TxDate).append("</CHIP251_TX_DATE>");
        sb.append("<CHIP251_SRC_BRNO>").append(this.chip251SrcBrno).append("</CHIP251_SRC_BRNO>");
        sb.append("<CHIP251_DES_BRNO>").append(this.chip251DesBrno).append("</CHIP251_DES_BRNO>");
        sb.append("<CHIP251_IC_SEQNO>").append(this.chip251IcSeqno).append("</CHIP251_IC_SEQNO>");
        sb.append("<CHIP251_ATM_CHK>").append(this.chip251AtmChk).append("</CHIP251_ATM_CHK>");
        sb.append("<CHIP251_STX_FEE_MBNK_CR>").append(this.chip251StxFeeMbnkCr).append("</CHIP251_STX_FEE_MBNK_CR>");
        sb.append("<CHIP251_STX_FEE_MBNK_DR>").append(this.chip251StxFeeMbnkDr).append("</CHIP251_STX_FEE_MBNK_DR>");
        sb.append("<CHIP251_STX_FEE_CR>").append(this.chip251StxFeeCr).append("</CHIP251_STX_FEE_CR>");
        sb.append("<CHIP251_STX_FEE_DR>").append(this.chip251StxFeeDr).append("</CHIP251_STX_FEE_DR>");
        sb.append("<CHIP251_DTX_FEE_MBNK_CR>").append(this.chip251DtxFeeMbnkCr).append("</CHIP251_DTX_FEE_MBNK_CR>");
        sb.append("<CHIP251_DTX_FEE_MBNK_DR>").append(this.chip251DtxFeeMbnkDr).append("</CHIP251_DTX_FEE_MBNK_DR>");
        sb.append("<CHIP251_DTX_FEE_CR>").append(this.chip251DtxFeeCr).append("</CHIP251_DTX_FEE_CR>");
        sb.append("<CHIP251_DTX_FEE_DR>").append(this.chip251DtxFeeDr).append("</CHIP251_DTX_FEE_DR>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        return sb.toString();
    }
}