package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class Chip25nd extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_TBSDY
     *
     * @mbg.generated
     */
    private String chip25ndTbsdy = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_STAN
     *
     * @mbg.generated
     */
    private String chip25ndStan = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ISS_BKNO
     *
     * @mbg.generated
     */
    private String chip25ndIssBkno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ISS_BRNO
     *
     * @mbg.generated
     */
    private String chip25ndIssBrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_BUSS_DATE
     *
     * @mbg.generated
     */
    private String chip25ndBussDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_TX_DATE
     *
     * @mbg.generated
     */
    private String chip25ndTxDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_TX_TIME
     *
     * @mbg.generated
     */
    private String chip25ndTxTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ATMNO
     *
     * @mbg.generated
     */
    private String chip25ndAtmno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_PCODE
     *
     * @mbg.generated
     */
    private String chip25ndPcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ACQ_BANK
     *
     * @mbg.generated
     */
    private String chip25ndAcqBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ISS_BANK
     *
     * @mbg.generated
     */
    private String chip25ndIssBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_TROUT_ACTNO
     *
     * @mbg.generated
     */
    private String chip25ndTroutActno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ATM_CUR
     *
     * @mbg.generated
     */
    private String chip25ndAtmCur;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ACQ_CNTRY
     *
     * @mbg.generated
     */
    private String chip25ndAcqCntry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_TX_AMT
     *
     * @mbg.generated
     */
    private BigDecimal chip25ndTxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ACQ_FEE
     *
     * @mbg.generated
     */
    private BigDecimal chip25ndAcqFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_TOT_AMT
     *
     * @mbg.generated
     */
    private BigDecimal chip25ndTotAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_SET_AMT
     *
     * @mbg.generated
     */
    private BigDecimal chip25ndSetAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ISS_FEE_CR
     *
     * @mbg.generated
     */
    private BigDecimal chip25ndIssFeeCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ISS_FEE_DR
     *
     * @mbg.generated
     */
    private BigDecimal chip25ndIssFeeDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_FISC_FEE_CR
     *
     * @mbg.generated
     */
    private BigDecimal chip25ndFiscFeeCr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_FISC_FEE_DR
     *
     * @mbg.generated
     */
    private BigDecimal chip25ndFiscFeeDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_SET_EXRATE
     *
     * @mbg.generated
     */
    private String chip25ndSetExrate = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_EXRATE
     *
     * @mbg.generated
     */
    private BigDecimal chip25ndExrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_MERCHANT_ID
     *
     * @mbg.generated
     */
    private String chip25ndMerchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ATM_CHK
     *
     * @mbg.generated
     */
    private String chip25ndAtmChk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_IC_SEQNO
     *
     * @mbg.generated
     */
    private String chip25ndIcSeqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ORG_STAN
     *
     * @mbg.generated
     */
    private String chip25ndOrgStan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ORG_DATE
     *
     * @mbg.generated
     */
    private String chip25ndOrgDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_ORDER_NO
     *
     * @mbg.generated
     */
    private String chip25ndOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_RS_CODE
     *
     * @mbg.generated
     */
    private String chip25ndRsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_TXRUST
     *
     * @mbg.generated
     */
    private String chip25ndTxrust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_REP1_RC
     *
     * @mbg.generated
     */
    private String chip25ndRep1Rc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_REP2_RC
     *
     * @mbg.generated
     */
    private String chip25ndRep2Rc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_CON1_RC
     *
     * @mbg.generated
     */
    private String chip25ndCon1Rc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.CHIP25ND_CON2_RC
     *
     * @mbg.generated
     */
    private String chip25ndCon2Rc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIP25ND.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHIP25ND
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP25ND
     *
     * @mbg.generated
     */
    public Chip25nd(String chip25ndTbsdy, String chip25ndStan, String chip25ndIssBkno, String chip25ndIssBrno, String chip25ndBussDate, String chip25ndTxDate, String chip25ndTxTime, String chip25ndAtmno, String chip25ndPcode, String chip25ndAcqBank, String chip25ndIssBank, String chip25ndTroutActno, String chip25ndAtmCur, String chip25ndAcqCntry, BigDecimal chip25ndTxAmt, BigDecimal chip25ndAcqFee, BigDecimal chip25ndTotAmt, BigDecimal chip25ndSetAmt, BigDecimal chip25ndIssFeeCr, BigDecimal chip25ndIssFeeDr, BigDecimal chip25ndFiscFeeCr, BigDecimal chip25ndFiscFeeDr, String chip25ndSetExrate, BigDecimal chip25ndExrate, String chip25ndMerchantId, String chip25ndAtmChk, String chip25ndIcSeqno, String chip25ndOrgStan, String chip25ndOrgDate, String chip25ndOrderNo, String chip25ndRsCode, String chip25ndTxrust, String chip25ndRep1Rc, String chip25ndRep2Rc, String chip25ndCon1Rc, String chip25ndCon2Rc, Integer updateUserid, Date updateTime) {
        this.chip25ndTbsdy = chip25ndTbsdy;
        this.chip25ndStan = chip25ndStan;
        this.chip25ndIssBkno = chip25ndIssBkno;
        this.chip25ndIssBrno = chip25ndIssBrno;
        this.chip25ndBussDate = chip25ndBussDate;
        this.chip25ndTxDate = chip25ndTxDate;
        this.chip25ndTxTime = chip25ndTxTime;
        this.chip25ndAtmno = chip25ndAtmno;
        this.chip25ndPcode = chip25ndPcode;
        this.chip25ndAcqBank = chip25ndAcqBank;
        this.chip25ndIssBank = chip25ndIssBank;
        this.chip25ndTroutActno = chip25ndTroutActno;
        this.chip25ndAtmCur = chip25ndAtmCur;
        this.chip25ndAcqCntry = chip25ndAcqCntry;
        this.chip25ndTxAmt = chip25ndTxAmt;
        this.chip25ndAcqFee = chip25ndAcqFee;
        this.chip25ndTotAmt = chip25ndTotAmt;
        this.chip25ndSetAmt = chip25ndSetAmt;
        this.chip25ndIssFeeCr = chip25ndIssFeeCr;
        this.chip25ndIssFeeDr = chip25ndIssFeeDr;
        this.chip25ndFiscFeeCr = chip25ndFiscFeeCr;
        this.chip25ndFiscFeeDr = chip25ndFiscFeeDr;
        this.chip25ndSetExrate = chip25ndSetExrate;
        this.chip25ndExrate = chip25ndExrate;
        this.chip25ndMerchantId = chip25ndMerchantId;
        this.chip25ndAtmChk = chip25ndAtmChk;
        this.chip25ndIcSeqno = chip25ndIcSeqno;
        this.chip25ndOrgStan = chip25ndOrgStan;
        this.chip25ndOrgDate = chip25ndOrgDate;
        this.chip25ndOrderNo = chip25ndOrderNo;
        this.chip25ndRsCode = chip25ndRsCode;
        this.chip25ndTxrust = chip25ndTxrust;
        this.chip25ndRep1Rc = chip25ndRep1Rc;
        this.chip25ndRep2Rc = chip25ndRep2Rc;
        this.chip25ndCon1Rc = chip25ndCon1Rc;
        this.chip25ndCon2Rc = chip25ndCon2Rc;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP25ND
     *
     * @mbg.generated
     */
    public Chip25nd() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_TBSDY
     *
     * @return the value of CHIP25ND.CHIP25ND_TBSDY
     *
     * @mbg.generated
     */
    public String getChip25ndTbsdy() {
        return chip25ndTbsdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_TBSDY
     *
     * @param chip25ndTbsdy the value for CHIP25ND.CHIP25ND_TBSDY
     *
     * @mbg.generated
     */
    public void setChip25ndTbsdy(String chip25ndTbsdy) {
        this.chip25ndTbsdy = chip25ndTbsdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_STAN
     *
     * @return the value of CHIP25ND.CHIP25ND_STAN
     *
     * @mbg.generated
     */
    public String getChip25ndStan() {
        return chip25ndStan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_STAN
     *
     * @param chip25ndStan the value for CHIP25ND.CHIP25ND_STAN
     *
     * @mbg.generated
     */
    public void setChip25ndStan(String chip25ndStan) {
        this.chip25ndStan = chip25ndStan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ISS_BKNO
     *
     * @return the value of CHIP25ND.CHIP25ND_ISS_BKNO
     *
     * @mbg.generated
     */
    public String getChip25ndIssBkno() {
        return chip25ndIssBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ISS_BKNO
     *
     * @param chip25ndIssBkno the value for CHIP25ND.CHIP25ND_ISS_BKNO
     *
     * @mbg.generated
     */
    public void setChip25ndIssBkno(String chip25ndIssBkno) {
        this.chip25ndIssBkno = chip25ndIssBkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ISS_BRNO
     *
     * @return the value of CHIP25ND.CHIP25ND_ISS_BRNO
     *
     * @mbg.generated
     */
    public String getChip25ndIssBrno() {
        return chip25ndIssBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ISS_BRNO
     *
     * @param chip25ndIssBrno the value for CHIP25ND.CHIP25ND_ISS_BRNO
     *
     * @mbg.generated
     */
    public void setChip25ndIssBrno(String chip25ndIssBrno) {
        this.chip25ndIssBrno = chip25ndIssBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_BUSS_DATE
     *
     * @return the value of CHIP25ND.CHIP25ND_BUSS_DATE
     *
     * @mbg.generated
     */
    public String getChip25ndBussDate() {
        return chip25ndBussDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_BUSS_DATE
     *
     * @param chip25ndBussDate the value for CHIP25ND.CHIP25ND_BUSS_DATE
     *
     * @mbg.generated
     */
    public void setChip25ndBussDate(String chip25ndBussDate) {
        this.chip25ndBussDate = chip25ndBussDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_TX_DATE
     *
     * @return the value of CHIP25ND.CHIP25ND_TX_DATE
     *
     * @mbg.generated
     */
    public String getChip25ndTxDate() {
        return chip25ndTxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_TX_DATE
     *
     * @param chip25ndTxDate the value for CHIP25ND.CHIP25ND_TX_DATE
     *
     * @mbg.generated
     */
    public void setChip25ndTxDate(String chip25ndTxDate) {
        this.chip25ndTxDate = chip25ndTxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_TX_TIME
     *
     * @return the value of CHIP25ND.CHIP25ND_TX_TIME
     *
     * @mbg.generated
     */
    public String getChip25ndTxTime() {
        return chip25ndTxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_TX_TIME
     *
     * @param chip25ndTxTime the value for CHIP25ND.CHIP25ND_TX_TIME
     *
     * @mbg.generated
     */
    public void setChip25ndTxTime(String chip25ndTxTime) {
        this.chip25ndTxTime = chip25ndTxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ATMNO
     *
     * @return the value of CHIP25ND.CHIP25ND_ATMNO
     *
     * @mbg.generated
     */
    public String getChip25ndAtmno() {
        return chip25ndAtmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ATMNO
     *
     * @param chip25ndAtmno the value for CHIP25ND.CHIP25ND_ATMNO
     *
     * @mbg.generated
     */
    public void setChip25ndAtmno(String chip25ndAtmno) {
        this.chip25ndAtmno = chip25ndAtmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_PCODE
     *
     * @return the value of CHIP25ND.CHIP25ND_PCODE
     *
     * @mbg.generated
     */
    public String getChip25ndPcode() {
        return chip25ndPcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_PCODE
     *
     * @param chip25ndPcode the value for CHIP25ND.CHIP25ND_PCODE
     *
     * @mbg.generated
     */
    public void setChip25ndPcode(String chip25ndPcode) {
        this.chip25ndPcode = chip25ndPcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ACQ_BANK
     *
     * @return the value of CHIP25ND.CHIP25ND_ACQ_BANK
     *
     * @mbg.generated
     */
    public String getChip25ndAcqBank() {
        return chip25ndAcqBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ACQ_BANK
     *
     * @param chip25ndAcqBank the value for CHIP25ND.CHIP25ND_ACQ_BANK
     *
     * @mbg.generated
     */
    public void setChip25ndAcqBank(String chip25ndAcqBank) {
        this.chip25ndAcqBank = chip25ndAcqBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ISS_BANK
     *
     * @return the value of CHIP25ND.CHIP25ND_ISS_BANK
     *
     * @mbg.generated
     */
    public String getChip25ndIssBank() {
        return chip25ndIssBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ISS_BANK
     *
     * @param chip25ndIssBank the value for CHIP25ND.CHIP25ND_ISS_BANK
     *
     * @mbg.generated
     */
    public void setChip25ndIssBank(String chip25ndIssBank) {
        this.chip25ndIssBank = chip25ndIssBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_TROUT_ACTNO
     *
     * @return the value of CHIP25ND.CHIP25ND_TROUT_ACTNO
     *
     * @mbg.generated
     */
    public String getChip25ndTroutActno() {
        return chip25ndTroutActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_TROUT_ACTNO
     *
     * @param chip25ndTroutActno the value for CHIP25ND.CHIP25ND_TROUT_ACTNO
     *
     * @mbg.generated
     */
    public void setChip25ndTroutActno(String chip25ndTroutActno) {
        this.chip25ndTroutActno = chip25ndTroutActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ATM_CUR
     *
     * @return the value of CHIP25ND.CHIP25ND_ATM_CUR
     *
     * @mbg.generated
     */
    public String getChip25ndAtmCur() {
        return chip25ndAtmCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ATM_CUR
     *
     * @param chip25ndAtmCur the value for CHIP25ND.CHIP25ND_ATM_CUR
     *
     * @mbg.generated
     */
    public void setChip25ndAtmCur(String chip25ndAtmCur) {
        this.chip25ndAtmCur = chip25ndAtmCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ACQ_CNTRY
     *
     * @return the value of CHIP25ND.CHIP25ND_ACQ_CNTRY
     *
     * @mbg.generated
     */
    public String getChip25ndAcqCntry() {
        return chip25ndAcqCntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ACQ_CNTRY
     *
     * @param chip25ndAcqCntry the value for CHIP25ND.CHIP25ND_ACQ_CNTRY
     *
     * @mbg.generated
     */
    public void setChip25ndAcqCntry(String chip25ndAcqCntry) {
        this.chip25ndAcqCntry = chip25ndAcqCntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_TX_AMT
     *
     * @return the value of CHIP25ND.CHIP25ND_TX_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getChip25ndTxAmt() {
        return chip25ndTxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_TX_AMT
     *
     * @param chip25ndTxAmt the value for CHIP25ND.CHIP25ND_TX_AMT
     *
     * @mbg.generated
     */
    public void setChip25ndTxAmt(BigDecimal chip25ndTxAmt) {
        this.chip25ndTxAmt = chip25ndTxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ACQ_FEE
     *
     * @return the value of CHIP25ND.CHIP25ND_ACQ_FEE
     *
     * @mbg.generated
     */
    public BigDecimal getChip25ndAcqFee() {
        return chip25ndAcqFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ACQ_FEE
     *
     * @param chip25ndAcqFee the value for CHIP25ND.CHIP25ND_ACQ_FEE
     *
     * @mbg.generated
     */
    public void setChip25ndAcqFee(BigDecimal chip25ndAcqFee) {
        this.chip25ndAcqFee = chip25ndAcqFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_TOT_AMT
     *
     * @return the value of CHIP25ND.CHIP25ND_TOT_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getChip25ndTotAmt() {
        return chip25ndTotAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_TOT_AMT
     *
     * @param chip25ndTotAmt the value for CHIP25ND.CHIP25ND_TOT_AMT
     *
     * @mbg.generated
     */
    public void setChip25ndTotAmt(BigDecimal chip25ndTotAmt) {
        this.chip25ndTotAmt = chip25ndTotAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_SET_AMT
     *
     * @return the value of CHIP25ND.CHIP25ND_SET_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getChip25ndSetAmt() {
        return chip25ndSetAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_SET_AMT
     *
     * @param chip25ndSetAmt the value for CHIP25ND.CHIP25ND_SET_AMT
     *
     * @mbg.generated
     */
    public void setChip25ndSetAmt(BigDecimal chip25ndSetAmt) {
        this.chip25ndSetAmt = chip25ndSetAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ISS_FEE_CR
     *
     * @return the value of CHIP25ND.CHIP25ND_ISS_FEE_CR
     *
     * @mbg.generated
     */
    public BigDecimal getChip25ndIssFeeCr() {
        return chip25ndIssFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ISS_FEE_CR
     *
     * @param chip25ndIssFeeCr the value for CHIP25ND.CHIP25ND_ISS_FEE_CR
     *
     * @mbg.generated
     */
    public void setChip25ndIssFeeCr(BigDecimal chip25ndIssFeeCr) {
        this.chip25ndIssFeeCr = chip25ndIssFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ISS_FEE_DR
     *
     * @return the value of CHIP25ND.CHIP25ND_ISS_FEE_DR
     *
     * @mbg.generated
     */
    public BigDecimal getChip25ndIssFeeDr() {
        return chip25ndIssFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ISS_FEE_DR
     *
     * @param chip25ndIssFeeDr the value for CHIP25ND.CHIP25ND_ISS_FEE_DR
     *
     * @mbg.generated
     */
    public void setChip25ndIssFeeDr(BigDecimal chip25ndIssFeeDr) {
        this.chip25ndIssFeeDr = chip25ndIssFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_FISC_FEE_CR
     *
     * @return the value of CHIP25ND.CHIP25ND_FISC_FEE_CR
     *
     * @mbg.generated
     */
    public BigDecimal getChip25ndFiscFeeCr() {
        return chip25ndFiscFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_FISC_FEE_CR
     *
     * @param chip25ndFiscFeeCr the value for CHIP25ND.CHIP25ND_FISC_FEE_CR
     *
     * @mbg.generated
     */
    public void setChip25ndFiscFeeCr(BigDecimal chip25ndFiscFeeCr) {
        this.chip25ndFiscFeeCr = chip25ndFiscFeeCr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_FISC_FEE_DR
     *
     * @return the value of CHIP25ND.CHIP25ND_FISC_FEE_DR
     *
     * @mbg.generated
     */
    public BigDecimal getChip25ndFiscFeeDr() {
        return chip25ndFiscFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_FISC_FEE_DR
     *
     * @param chip25ndFiscFeeDr the value for CHIP25ND.CHIP25ND_FISC_FEE_DR
     *
     * @mbg.generated
     */
    public void setChip25ndFiscFeeDr(BigDecimal chip25ndFiscFeeDr) {
        this.chip25ndFiscFeeDr = chip25ndFiscFeeDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_SET_EXRATE
     *
     * @return the value of CHIP25ND.CHIP25ND_SET_EXRATE
     *
     * @mbg.generated
     */
    public String getChip25ndSetExrate() {
        return chip25ndSetExrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_SET_EXRATE
     *
     * @param chip25ndSetExrate the value for CHIP25ND.CHIP25ND_SET_EXRATE
     *
     * @mbg.generated
     */
    public void setChip25ndSetExrate(String chip25ndSetExrate) {
        this.chip25ndSetExrate = chip25ndSetExrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_EXRATE
     *
     * @return the value of CHIP25ND.CHIP25ND_EXRATE
     *
     * @mbg.generated
     */
    public BigDecimal getChip25ndExrate() {
        return chip25ndExrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_EXRATE
     *
     * @param chip25ndExrate the value for CHIP25ND.CHIP25ND_EXRATE
     *
     * @mbg.generated
     */
    public void setChip25ndExrate(BigDecimal chip25ndExrate) {
        this.chip25ndExrate = chip25ndExrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_MERCHANT_ID
     *
     * @return the value of CHIP25ND.CHIP25ND_MERCHANT_ID
     *
     * @mbg.generated
     */
    public String getChip25ndMerchantId() {
        return chip25ndMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_MERCHANT_ID
     *
     * @param chip25ndMerchantId the value for CHIP25ND.CHIP25ND_MERCHANT_ID
     *
     * @mbg.generated
     */
    public void setChip25ndMerchantId(String chip25ndMerchantId) {
        this.chip25ndMerchantId = chip25ndMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ATM_CHK
     *
     * @return the value of CHIP25ND.CHIP25ND_ATM_CHK
     *
     * @mbg.generated
     */
    public String getChip25ndAtmChk() {
        return chip25ndAtmChk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ATM_CHK
     *
     * @param chip25ndAtmChk the value for CHIP25ND.CHIP25ND_ATM_CHK
     *
     * @mbg.generated
     */
    public void setChip25ndAtmChk(String chip25ndAtmChk) {
        this.chip25ndAtmChk = chip25ndAtmChk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_IC_SEQNO
     *
     * @return the value of CHIP25ND.CHIP25ND_IC_SEQNO
     *
     * @mbg.generated
     */
    public String getChip25ndIcSeqno() {
        return chip25ndIcSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_IC_SEQNO
     *
     * @param chip25ndIcSeqno the value for CHIP25ND.CHIP25ND_IC_SEQNO
     *
     * @mbg.generated
     */
    public void setChip25ndIcSeqno(String chip25ndIcSeqno) {
        this.chip25ndIcSeqno = chip25ndIcSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ORG_STAN
     *
     * @return the value of CHIP25ND.CHIP25ND_ORG_STAN
     *
     * @mbg.generated
     */
    public String getChip25ndOrgStan() {
        return chip25ndOrgStan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ORG_STAN
     *
     * @param chip25ndOrgStan the value for CHIP25ND.CHIP25ND_ORG_STAN
     *
     * @mbg.generated
     */
    public void setChip25ndOrgStan(String chip25ndOrgStan) {
        this.chip25ndOrgStan = chip25ndOrgStan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ORG_DATE
     *
     * @return the value of CHIP25ND.CHIP25ND_ORG_DATE
     *
     * @mbg.generated
     */
    public String getChip25ndOrgDate() {
        return chip25ndOrgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ORG_DATE
     *
     * @param chip25ndOrgDate the value for CHIP25ND.CHIP25ND_ORG_DATE
     *
     * @mbg.generated
     */
    public void setChip25ndOrgDate(String chip25ndOrgDate) {
        this.chip25ndOrgDate = chip25ndOrgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_ORDER_NO
     *
     * @return the value of CHIP25ND.CHIP25ND_ORDER_NO
     *
     * @mbg.generated
     */
    public String getChip25ndOrderNo() {
        return chip25ndOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_ORDER_NO
     *
     * @param chip25ndOrderNo the value for CHIP25ND.CHIP25ND_ORDER_NO
     *
     * @mbg.generated
     */
    public void setChip25ndOrderNo(String chip25ndOrderNo) {
        this.chip25ndOrderNo = chip25ndOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_RS_CODE
     *
     * @return the value of CHIP25ND.CHIP25ND_RS_CODE
     *
     * @mbg.generated
     */
    public String getChip25ndRsCode() {
        return chip25ndRsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_RS_CODE
     *
     * @param chip25ndRsCode the value for CHIP25ND.CHIP25ND_RS_CODE
     *
     * @mbg.generated
     */
    public void setChip25ndRsCode(String chip25ndRsCode) {
        this.chip25ndRsCode = chip25ndRsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_TXRUST
     *
     * @return the value of CHIP25ND.CHIP25ND_TXRUST
     *
     * @mbg.generated
     */
    public String getChip25ndTxrust() {
        return chip25ndTxrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_TXRUST
     *
     * @param chip25ndTxrust the value for CHIP25ND.CHIP25ND_TXRUST
     *
     * @mbg.generated
     */
    public void setChip25ndTxrust(String chip25ndTxrust) {
        this.chip25ndTxrust = chip25ndTxrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_REP1_RC
     *
     * @return the value of CHIP25ND.CHIP25ND_REP1_RC
     *
     * @mbg.generated
     */
    public String getChip25ndRep1Rc() {
        return chip25ndRep1Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_REP1_RC
     *
     * @param chip25ndRep1Rc the value for CHIP25ND.CHIP25ND_REP1_RC
     *
     * @mbg.generated
     */
    public void setChip25ndRep1Rc(String chip25ndRep1Rc) {
        this.chip25ndRep1Rc = chip25ndRep1Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_REP2_RC
     *
     * @return the value of CHIP25ND.CHIP25ND_REP2_RC
     *
     * @mbg.generated
     */
    public String getChip25ndRep2Rc() {
        return chip25ndRep2Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_REP2_RC
     *
     * @param chip25ndRep2Rc the value for CHIP25ND.CHIP25ND_REP2_RC
     *
     * @mbg.generated
     */
    public void setChip25ndRep2Rc(String chip25ndRep2Rc) {
        this.chip25ndRep2Rc = chip25ndRep2Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_CON1_RC
     *
     * @return the value of CHIP25ND.CHIP25ND_CON1_RC
     *
     * @mbg.generated
     */
    public String getChip25ndCon1Rc() {
        return chip25ndCon1Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_CON1_RC
     *
     * @param chip25ndCon1Rc the value for CHIP25ND.CHIP25ND_CON1_RC
     *
     * @mbg.generated
     */
    public void setChip25ndCon1Rc(String chip25ndCon1Rc) {
        this.chip25ndCon1Rc = chip25ndCon1Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.CHIP25ND_CON2_RC
     *
     * @return the value of CHIP25ND.CHIP25ND_CON2_RC
     *
     * @mbg.generated
     */
    public String getChip25ndCon2Rc() {
        return chip25ndCon2Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.CHIP25ND_CON2_RC
     *
     * @param chip25ndCon2Rc the value for CHIP25ND.CHIP25ND_CON2_RC
     *
     * @mbg.generated
     */
    public void setChip25ndCon2Rc(String chip25ndCon2Rc) {
        this.chip25ndCon2Rc = chip25ndCon2Rc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.UPDATE_USERID
     *
     * @return the value of CHIP25ND.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.UPDATE_USERID
     *
     * @param updateUserid the value for CHIP25ND.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIP25ND.UPDATE_TIME
     *
     * @return the value of CHIP25ND.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIP25ND.UPDATE_TIME
     *
     * @param updateTime the value for CHIP25ND.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP25ND
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chip25ndTbsdy=").append(chip25ndTbsdy);
        sb.append(", chip25ndStan=").append(chip25ndStan);
        sb.append(", chip25ndIssBkno=").append(chip25ndIssBkno);
        sb.append(", chip25ndIssBrno=").append(chip25ndIssBrno);
        sb.append(", chip25ndBussDate=").append(chip25ndBussDate);
        sb.append(", chip25ndTxDate=").append(chip25ndTxDate);
        sb.append(", chip25ndTxTime=").append(chip25ndTxTime);
        sb.append(", chip25ndAtmno=").append(chip25ndAtmno);
        sb.append(", chip25ndPcode=").append(chip25ndPcode);
        sb.append(", chip25ndAcqBank=").append(chip25ndAcqBank);
        sb.append(", chip25ndIssBank=").append(chip25ndIssBank);
        sb.append(", chip25ndTroutActno=").append(chip25ndTroutActno);
        sb.append(", chip25ndAtmCur=").append(chip25ndAtmCur);
        sb.append(", chip25ndAcqCntry=").append(chip25ndAcqCntry);
        sb.append(", chip25ndTxAmt=").append(chip25ndTxAmt);
        sb.append(", chip25ndAcqFee=").append(chip25ndAcqFee);
        sb.append(", chip25ndTotAmt=").append(chip25ndTotAmt);
        sb.append(", chip25ndSetAmt=").append(chip25ndSetAmt);
        sb.append(", chip25ndIssFeeCr=").append(chip25ndIssFeeCr);
        sb.append(", chip25ndIssFeeDr=").append(chip25ndIssFeeDr);
        sb.append(", chip25ndFiscFeeCr=").append(chip25ndFiscFeeCr);
        sb.append(", chip25ndFiscFeeDr=").append(chip25ndFiscFeeDr);
        sb.append(", chip25ndSetExrate=").append(chip25ndSetExrate);
        sb.append(", chip25ndExrate=").append(chip25ndExrate);
        sb.append(", chip25ndMerchantId=").append(chip25ndMerchantId);
        sb.append(", chip25ndAtmChk=").append(chip25ndAtmChk);
        sb.append(", chip25ndIcSeqno=").append(chip25ndIcSeqno);
        sb.append(", chip25ndOrgStan=").append(chip25ndOrgStan);
        sb.append(", chip25ndOrgDate=").append(chip25ndOrgDate);
        sb.append(", chip25ndOrderNo=").append(chip25ndOrderNo);
        sb.append(", chip25ndRsCode=").append(chip25ndRsCode);
        sb.append(", chip25ndTxrust=").append(chip25ndTxrust);
        sb.append(", chip25ndRep1Rc=").append(chip25ndRep1Rc);
        sb.append(", chip25ndRep2Rc=").append(chip25ndRep2Rc);
        sb.append(", chip25ndCon1Rc=").append(chip25ndCon1Rc);
        sb.append(", chip25ndCon2Rc=").append(chip25ndCon2Rc);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP25ND
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Chip25nd other = (Chip25nd) that;
        return (this.getChip25ndTbsdy() == null ? other.getChip25ndTbsdy() == null : this.getChip25ndTbsdy().equals(other.getChip25ndTbsdy()))
            && (this.getChip25ndStan() == null ? other.getChip25ndStan() == null : this.getChip25ndStan().equals(other.getChip25ndStan()))
            && (this.getChip25ndIssBkno() == null ? other.getChip25ndIssBkno() == null : this.getChip25ndIssBkno().equals(other.getChip25ndIssBkno()))
            && (this.getChip25ndIssBrno() == null ? other.getChip25ndIssBrno() == null : this.getChip25ndIssBrno().equals(other.getChip25ndIssBrno()))
            && (this.getChip25ndBussDate() == null ? other.getChip25ndBussDate() == null : this.getChip25ndBussDate().equals(other.getChip25ndBussDate()))
            && (this.getChip25ndTxDate() == null ? other.getChip25ndTxDate() == null : this.getChip25ndTxDate().equals(other.getChip25ndTxDate()))
            && (this.getChip25ndTxTime() == null ? other.getChip25ndTxTime() == null : this.getChip25ndTxTime().equals(other.getChip25ndTxTime()))
            && (this.getChip25ndAtmno() == null ? other.getChip25ndAtmno() == null : this.getChip25ndAtmno().equals(other.getChip25ndAtmno()))
            && (this.getChip25ndPcode() == null ? other.getChip25ndPcode() == null : this.getChip25ndPcode().equals(other.getChip25ndPcode()))
            && (this.getChip25ndAcqBank() == null ? other.getChip25ndAcqBank() == null : this.getChip25ndAcqBank().equals(other.getChip25ndAcqBank()))
            && (this.getChip25ndIssBank() == null ? other.getChip25ndIssBank() == null : this.getChip25ndIssBank().equals(other.getChip25ndIssBank()))
            && (this.getChip25ndTroutActno() == null ? other.getChip25ndTroutActno() == null : this.getChip25ndTroutActno().equals(other.getChip25ndTroutActno()))
            && (this.getChip25ndAtmCur() == null ? other.getChip25ndAtmCur() == null : this.getChip25ndAtmCur().equals(other.getChip25ndAtmCur()))
            && (this.getChip25ndAcqCntry() == null ? other.getChip25ndAcqCntry() == null : this.getChip25ndAcqCntry().equals(other.getChip25ndAcqCntry()))
            && (this.getChip25ndTxAmt() == null ? other.getChip25ndTxAmt() == null : this.getChip25ndTxAmt().equals(other.getChip25ndTxAmt()))
            && (this.getChip25ndAcqFee() == null ? other.getChip25ndAcqFee() == null : this.getChip25ndAcqFee().equals(other.getChip25ndAcqFee()))
            && (this.getChip25ndTotAmt() == null ? other.getChip25ndTotAmt() == null : this.getChip25ndTotAmt().equals(other.getChip25ndTotAmt()))
            && (this.getChip25ndSetAmt() == null ? other.getChip25ndSetAmt() == null : this.getChip25ndSetAmt().equals(other.getChip25ndSetAmt()))
            && (this.getChip25ndIssFeeCr() == null ? other.getChip25ndIssFeeCr() == null : this.getChip25ndIssFeeCr().equals(other.getChip25ndIssFeeCr()))
            && (this.getChip25ndIssFeeDr() == null ? other.getChip25ndIssFeeDr() == null : this.getChip25ndIssFeeDr().equals(other.getChip25ndIssFeeDr()))
            && (this.getChip25ndFiscFeeCr() == null ? other.getChip25ndFiscFeeCr() == null : this.getChip25ndFiscFeeCr().equals(other.getChip25ndFiscFeeCr()))
            && (this.getChip25ndFiscFeeDr() == null ? other.getChip25ndFiscFeeDr() == null : this.getChip25ndFiscFeeDr().equals(other.getChip25ndFiscFeeDr()))
            && (this.getChip25ndSetExrate() == null ? other.getChip25ndSetExrate() == null : this.getChip25ndSetExrate().equals(other.getChip25ndSetExrate()))
            && (this.getChip25ndExrate() == null ? other.getChip25ndExrate() == null : this.getChip25ndExrate().equals(other.getChip25ndExrate()))
            && (this.getChip25ndMerchantId() == null ? other.getChip25ndMerchantId() == null : this.getChip25ndMerchantId().equals(other.getChip25ndMerchantId()))
            && (this.getChip25ndAtmChk() == null ? other.getChip25ndAtmChk() == null : this.getChip25ndAtmChk().equals(other.getChip25ndAtmChk()))
            && (this.getChip25ndIcSeqno() == null ? other.getChip25ndIcSeqno() == null : this.getChip25ndIcSeqno().equals(other.getChip25ndIcSeqno()))
            && (this.getChip25ndOrgStan() == null ? other.getChip25ndOrgStan() == null : this.getChip25ndOrgStan().equals(other.getChip25ndOrgStan()))
            && (this.getChip25ndOrgDate() == null ? other.getChip25ndOrgDate() == null : this.getChip25ndOrgDate().equals(other.getChip25ndOrgDate()))
            && (this.getChip25ndOrderNo() == null ? other.getChip25ndOrderNo() == null : this.getChip25ndOrderNo().equals(other.getChip25ndOrderNo()))
            && (this.getChip25ndRsCode() == null ? other.getChip25ndRsCode() == null : this.getChip25ndRsCode().equals(other.getChip25ndRsCode()))
            && (this.getChip25ndTxrust() == null ? other.getChip25ndTxrust() == null : this.getChip25ndTxrust().equals(other.getChip25ndTxrust()))
            && (this.getChip25ndRep1Rc() == null ? other.getChip25ndRep1Rc() == null : this.getChip25ndRep1Rc().equals(other.getChip25ndRep1Rc()))
            && (this.getChip25ndRep2Rc() == null ? other.getChip25ndRep2Rc() == null : this.getChip25ndRep2Rc().equals(other.getChip25ndRep2Rc()))
            && (this.getChip25ndCon1Rc() == null ? other.getChip25ndCon1Rc() == null : this.getChip25ndCon1Rc().equals(other.getChip25ndCon1Rc()))
            && (this.getChip25ndCon2Rc() == null ? other.getChip25ndCon2Rc() == null : this.getChip25ndCon2Rc().equals(other.getChip25ndCon2Rc()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP25ND
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getChip25ndTbsdy() == null) ? 0 : getChip25ndTbsdy().hashCode());
        result = 31 * result + ((getChip25ndStan() == null) ? 0 : getChip25ndStan().hashCode());
        result = 31 * result + ((getChip25ndIssBkno() == null) ? 0 : getChip25ndIssBkno().hashCode());
        result = 31 * result + ((getChip25ndIssBrno() == null) ? 0 : getChip25ndIssBrno().hashCode());
        result = 31 * result + ((getChip25ndBussDate() == null) ? 0 : getChip25ndBussDate().hashCode());
        result = 31 * result + ((getChip25ndTxDate() == null) ? 0 : getChip25ndTxDate().hashCode());
        result = 31 * result + ((getChip25ndTxTime() == null) ? 0 : getChip25ndTxTime().hashCode());
        result = 31 * result + ((getChip25ndAtmno() == null) ? 0 : getChip25ndAtmno().hashCode());
        result = 31 * result + ((getChip25ndPcode() == null) ? 0 : getChip25ndPcode().hashCode());
        result = 31 * result + ((getChip25ndAcqBank() == null) ? 0 : getChip25ndAcqBank().hashCode());
        result = 31 * result + ((getChip25ndIssBank() == null) ? 0 : getChip25ndIssBank().hashCode());
        result = 31 * result + ((getChip25ndTroutActno() == null) ? 0 : getChip25ndTroutActno().hashCode());
        result = 31 * result + ((getChip25ndAtmCur() == null) ? 0 : getChip25ndAtmCur().hashCode());
        result = 31 * result + ((getChip25ndAcqCntry() == null) ? 0 : getChip25ndAcqCntry().hashCode());
        result = 31 * result + ((getChip25ndTxAmt() == null) ? 0 : getChip25ndTxAmt().hashCode());
        result = 31 * result + ((getChip25ndAcqFee() == null) ? 0 : getChip25ndAcqFee().hashCode());
        result = 31 * result + ((getChip25ndTotAmt() == null) ? 0 : getChip25ndTotAmt().hashCode());
        result = 31 * result + ((getChip25ndSetAmt() == null) ? 0 : getChip25ndSetAmt().hashCode());
        result = 31 * result + ((getChip25ndIssFeeCr() == null) ? 0 : getChip25ndIssFeeCr().hashCode());
        result = 31 * result + ((getChip25ndIssFeeDr() == null) ? 0 : getChip25ndIssFeeDr().hashCode());
        result = 31 * result + ((getChip25ndFiscFeeCr() == null) ? 0 : getChip25ndFiscFeeCr().hashCode());
        result = 31 * result + ((getChip25ndFiscFeeDr() == null) ? 0 : getChip25ndFiscFeeDr().hashCode());
        result = 31 * result + ((getChip25ndSetExrate() == null) ? 0 : getChip25ndSetExrate().hashCode());
        result = 31 * result + ((getChip25ndExrate() == null) ? 0 : getChip25ndExrate().hashCode());
        result = 31 * result + ((getChip25ndMerchantId() == null) ? 0 : getChip25ndMerchantId().hashCode());
        result = 31 * result + ((getChip25ndAtmChk() == null) ? 0 : getChip25ndAtmChk().hashCode());
        result = 31 * result + ((getChip25ndIcSeqno() == null) ? 0 : getChip25ndIcSeqno().hashCode());
        result = 31 * result + ((getChip25ndOrgStan() == null) ? 0 : getChip25ndOrgStan().hashCode());
        result = 31 * result + ((getChip25ndOrgDate() == null) ? 0 : getChip25ndOrgDate().hashCode());
        result = 31 * result + ((getChip25ndOrderNo() == null) ? 0 : getChip25ndOrderNo().hashCode());
        result = 31 * result + ((getChip25ndRsCode() == null) ? 0 : getChip25ndRsCode().hashCode());
        result = 31 * result + ((getChip25ndTxrust() == null) ? 0 : getChip25ndTxrust().hashCode());
        result = 31 * result + ((getChip25ndRep1Rc() == null) ? 0 : getChip25ndRep1Rc().hashCode());
        result = 31 * result + ((getChip25ndRep2Rc() == null) ? 0 : getChip25ndRep2Rc().hashCode());
        result = 31 * result + ((getChip25ndCon1Rc() == null) ? 0 : getChip25ndCon1Rc().hashCode());
        result = 31 * result + ((getChip25ndCon2Rc() == null) ? 0 : getChip25ndCon2Rc().hashCode());
        result = 31 * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = 31 * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHIP25ND
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<CHIP25ND_TBSDY>").append(this.chip25ndTbsdy).append("</CHIP25ND_TBSDY>");
        sb.append("<CHIP25ND_STAN>").append(this.chip25ndStan).append("</CHIP25ND_STAN>");
        sb.append("<CHIP25ND_ISS_BKNO>").append(this.chip25ndIssBkno).append("</CHIP25ND_ISS_BKNO>");
        sb.append("<CHIP25ND_ISS_BRNO>").append(this.chip25ndIssBrno).append("</CHIP25ND_ISS_BRNO>");
        sb.append("<CHIP25ND_BUSS_DATE>").append(this.chip25ndBussDate).append("</CHIP25ND_BUSS_DATE>");
        sb.append("<CHIP25ND_TX_DATE>").append(this.chip25ndTxDate).append("</CHIP25ND_TX_DATE>");
        sb.append("<CHIP25ND_TX_TIME>").append(this.chip25ndTxTime).append("</CHIP25ND_TX_TIME>");
        sb.append("<CHIP25ND_ATMNO>").append(this.chip25ndAtmno).append("</CHIP25ND_ATMNO>");
        sb.append("<CHIP25ND_PCODE>").append(this.chip25ndPcode).append("</CHIP25ND_PCODE>");
        sb.append("<CHIP25ND_ACQ_BANK>").append(this.chip25ndAcqBank).append("</CHIP25ND_ACQ_BANK>");
        sb.append("<CHIP25ND_ISS_BANK>").append(this.chip25ndIssBank).append("</CHIP25ND_ISS_BANK>");
        sb.append("<CHIP25ND_TROUT_ACTNO>").append(this.chip25ndTroutActno).append("</CHIP25ND_TROUT_ACTNO>");
        sb.append("<CHIP25ND_ATM_CUR>").append(this.chip25ndAtmCur).append("</CHIP25ND_ATM_CUR>");
        sb.append("<CHIP25ND_ACQ_CNTRY>").append(this.chip25ndAcqCntry).append("</CHIP25ND_ACQ_CNTRY>");
        sb.append("<CHIP25ND_TX_AMT>").append(this.chip25ndTxAmt).append("</CHIP25ND_TX_AMT>");
        sb.append("<CHIP25ND_ACQ_FEE>").append(this.chip25ndAcqFee).append("</CHIP25ND_ACQ_FEE>");
        sb.append("<CHIP25ND_TOT_AMT>").append(this.chip25ndTotAmt).append("</CHIP25ND_TOT_AMT>");
        sb.append("<CHIP25ND_SET_AMT>").append(this.chip25ndSetAmt).append("</CHIP25ND_SET_AMT>");
        sb.append("<CHIP25ND_ISS_FEE_CR>").append(this.chip25ndIssFeeCr).append("</CHIP25ND_ISS_FEE_CR>");
        sb.append("<CHIP25ND_ISS_FEE_DR>").append(this.chip25ndIssFeeDr).append("</CHIP25ND_ISS_FEE_DR>");
        sb.append("<CHIP25ND_FISC_FEE_CR>").append(this.chip25ndFiscFeeCr).append("</CHIP25ND_FISC_FEE_CR>");
        sb.append("<CHIP25ND_FISC_FEE_DR>").append(this.chip25ndFiscFeeDr).append("</CHIP25ND_FISC_FEE_DR>");
        sb.append("<CHIP25ND_SET_EXRATE>").append(this.chip25ndSetExrate).append("</CHIP25ND_SET_EXRATE>");
        sb.append("<CHIP25ND_EXRATE>").append(this.chip25ndExrate).append("</CHIP25ND_EXRATE>");
        sb.append("<CHIP25ND_MERCHANT_ID>").append(this.chip25ndMerchantId).append("</CHIP25ND_MERCHANT_ID>");
        sb.append("<CHIP25ND_ATM_CHK>").append(this.chip25ndAtmChk).append("</CHIP25ND_ATM_CHK>");
        sb.append("<CHIP25ND_IC_SEQNO>").append(this.chip25ndIcSeqno).append("</CHIP25ND_IC_SEQNO>");
        sb.append("<CHIP25ND_ORG_STAN>").append(this.chip25ndOrgStan).append("</CHIP25ND_ORG_STAN>");
        sb.append("<CHIP25ND_ORG_DATE>").append(this.chip25ndOrgDate).append("</CHIP25ND_ORG_DATE>");
        sb.append("<CHIP25ND_ORDER_NO>").append(this.chip25ndOrderNo).append("</CHIP25ND_ORDER_NO>");
        sb.append("<CHIP25ND_RS_CODE>").append(this.chip25ndRsCode).append("</CHIP25ND_RS_CODE>");
        sb.append("<CHIP25ND_TXRUST>").append(this.chip25ndTxrust).append("</CHIP25ND_TXRUST>");
        sb.append("<CHIP25ND_REP1_RC>").append(this.chip25ndRep1Rc).append("</CHIP25ND_REP1_RC>");
        sb.append("<CHIP25ND_REP2_RC>").append(this.chip25ndRep2Rc).append("</CHIP25ND_REP2_RC>");
        sb.append("<CHIP25ND_CON1_RC>").append(this.chip25ndCon1Rc).append("</CHIP25ND_CON1_RC>");
        sb.append("<CHIP25ND_CON2_RC>").append(this.chip25ndCon2Rc).append("</CHIP25ND_CON2_RC>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        return sb.toString();
    }
}