package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class Dttsm extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_TX_DATE
     *
     * @mbg.generated
     */
    private String dttsmTxDate = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_EJFNO
     *
     * @mbg.generated
     */
    private Integer dttsmEjfno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_TX_TIME
     *
     * @mbg.generated
     */
    private String dttsmTxTime = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_TBSDY_FISC
     *
     * @mbg.generated
     */
    private String dttsmTbsdyFisc = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_TBSDY
     *
     * @mbg.generated
     */
    private String dttsmTbsdy = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_PCODE
     *
     * @mbg.generated
     */
    private String dttsmPcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_MERCHANT_ID
     *
     * @mbg.generated
     */
    private String dttsmMerchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_ATMNO
     *
     * @mbg.generated
     */
    private String dttsmAtmno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_TROUT_ACTNO
     *
     * @mbg.generated
     */
    private String dttsmTroutActno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_TX_AMT
     *
     * @mbg.generated
     */
    private BigDecimal dttsmTxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_TYPE
     *
     * @mbg.generated
     */
    private String dttsmType = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTTSM.DTTSM_CARD_SEQ
     *
     * @mbg.generated
     */
    private Short dttsmCardSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DTTSM
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTTSM
     *
     * @mbg.generated
     */
    public Dttsm(String dttsmTxDate, Integer dttsmEjfno, String dttsmTxTime, String dttsmTbsdyFisc, String dttsmTbsdy, String dttsmPcode, String dttsmMerchantId, String dttsmAtmno, String dttsmTroutActno, BigDecimal dttsmTxAmt, String dttsmType, Integer updateUserid, Date updateTime, Short dttsmCardSeq) {
        this.dttsmTxDate = dttsmTxDate;
        this.dttsmEjfno = dttsmEjfno;
        this.dttsmTxTime = dttsmTxTime;
        this.dttsmTbsdyFisc = dttsmTbsdyFisc;
        this.dttsmTbsdy = dttsmTbsdy;
        this.dttsmPcode = dttsmPcode;
        this.dttsmMerchantId = dttsmMerchantId;
        this.dttsmAtmno = dttsmAtmno;
        this.dttsmTroutActno = dttsmTroutActno;
        this.dttsmTxAmt = dttsmTxAmt;
        this.dttsmType = dttsmType;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
        this.dttsmCardSeq = dttsmCardSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTTSM
     *
     * @mbg.generated
     */
    public Dttsm() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_TX_DATE
     *
     * @return the value of DTTSM.DTTSM_TX_DATE
     *
     * @mbg.generated
     */
    public String getDttsmTxDate() {
        return dttsmTxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_TX_DATE
     *
     * @param dttsmTxDate the value for DTTSM.DTTSM_TX_DATE
     *
     * @mbg.generated
     */
    public void setDttsmTxDate(String dttsmTxDate) {
        this.dttsmTxDate = dttsmTxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_EJFNO
     *
     * @return the value of DTTSM.DTTSM_EJFNO
     *
     * @mbg.generated
     */
    public Integer getDttsmEjfno() {
        return dttsmEjfno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_EJFNO
     *
     * @param dttsmEjfno the value for DTTSM.DTTSM_EJFNO
     *
     * @mbg.generated
     */
    public void setDttsmEjfno(Integer dttsmEjfno) {
        this.dttsmEjfno = dttsmEjfno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_TX_TIME
     *
     * @return the value of DTTSM.DTTSM_TX_TIME
     *
     * @mbg.generated
     */
    public String getDttsmTxTime() {
        return dttsmTxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_TX_TIME
     *
     * @param dttsmTxTime the value for DTTSM.DTTSM_TX_TIME
     *
     * @mbg.generated
     */
    public void setDttsmTxTime(String dttsmTxTime) {
        this.dttsmTxTime = dttsmTxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_TBSDY_FISC
     *
     * @return the value of DTTSM.DTTSM_TBSDY_FISC
     *
     * @mbg.generated
     */
    public String getDttsmTbsdyFisc() {
        return dttsmTbsdyFisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_TBSDY_FISC
     *
     * @param dttsmTbsdyFisc the value for DTTSM.DTTSM_TBSDY_FISC
     *
     * @mbg.generated
     */
    public void setDttsmTbsdyFisc(String dttsmTbsdyFisc) {
        this.dttsmTbsdyFisc = dttsmTbsdyFisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_TBSDY
     *
     * @return the value of DTTSM.DTTSM_TBSDY
     *
     * @mbg.generated
     */
    public String getDttsmTbsdy() {
        return dttsmTbsdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_TBSDY
     *
     * @param dttsmTbsdy the value for DTTSM.DTTSM_TBSDY
     *
     * @mbg.generated
     */
    public void setDttsmTbsdy(String dttsmTbsdy) {
        this.dttsmTbsdy = dttsmTbsdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_PCODE
     *
     * @return the value of DTTSM.DTTSM_PCODE
     *
     * @mbg.generated
     */
    public String getDttsmPcode() {
        return dttsmPcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_PCODE
     *
     * @param dttsmPcode the value for DTTSM.DTTSM_PCODE
     *
     * @mbg.generated
     */
    public void setDttsmPcode(String dttsmPcode) {
        this.dttsmPcode = dttsmPcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_MERCHANT_ID
     *
     * @return the value of DTTSM.DTTSM_MERCHANT_ID
     *
     * @mbg.generated
     */
    public String getDttsmMerchantId() {
        return dttsmMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_MERCHANT_ID
     *
     * @param dttsmMerchantId the value for DTTSM.DTTSM_MERCHANT_ID
     *
     * @mbg.generated
     */
    public void setDttsmMerchantId(String dttsmMerchantId) {
        this.dttsmMerchantId = dttsmMerchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_ATMNO
     *
     * @return the value of DTTSM.DTTSM_ATMNO
     *
     * @mbg.generated
     */
    public String getDttsmAtmno() {
        return dttsmAtmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_ATMNO
     *
     * @param dttsmAtmno the value for DTTSM.DTTSM_ATMNO
     *
     * @mbg.generated
     */
    public void setDttsmAtmno(String dttsmAtmno) {
        this.dttsmAtmno = dttsmAtmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_TROUT_ACTNO
     *
     * @return the value of DTTSM.DTTSM_TROUT_ACTNO
     *
     * @mbg.generated
     */
    public String getDttsmTroutActno() {
        return dttsmTroutActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_TROUT_ACTNO
     *
     * @param dttsmTroutActno the value for DTTSM.DTTSM_TROUT_ACTNO
     *
     * @mbg.generated
     */
    public void setDttsmTroutActno(String dttsmTroutActno) {
        this.dttsmTroutActno = dttsmTroutActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_TX_AMT
     *
     * @return the value of DTTSM.DTTSM_TX_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getDttsmTxAmt() {
        return dttsmTxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_TX_AMT
     *
     * @param dttsmTxAmt the value for DTTSM.DTTSM_TX_AMT
     *
     * @mbg.generated
     */
    public void setDttsmTxAmt(BigDecimal dttsmTxAmt) {
        this.dttsmTxAmt = dttsmTxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_TYPE
     *
     * @return the value of DTTSM.DTTSM_TYPE
     *
     * @mbg.generated
     */
    public String getDttsmType() {
        return dttsmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_TYPE
     *
     * @param dttsmType the value for DTTSM.DTTSM_TYPE
     *
     * @mbg.generated
     */
    public void setDttsmType(String dttsmType) {
        this.dttsmType = dttsmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.UPDATE_USERID
     *
     * @return the value of DTTSM.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.UPDATE_USERID
     *
     * @param updateUserid the value for DTTSM.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.UPDATE_TIME
     *
     * @return the value of DTTSM.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.UPDATE_TIME
     *
     * @param updateTime the value for DTTSM.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTTSM.DTTSM_CARD_SEQ
     *
     * @return the value of DTTSM.DTTSM_CARD_SEQ
     *
     * @mbg.generated
     */
    public Short getDttsmCardSeq() {
        return dttsmCardSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTTSM.DTTSM_CARD_SEQ
     *
     * @param dttsmCardSeq the value for DTTSM.DTTSM_CARD_SEQ
     *
     * @mbg.generated
     */
    public void setDttsmCardSeq(Short dttsmCardSeq) {
        this.dttsmCardSeq = dttsmCardSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTTSM
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dttsmTxDate=").append(dttsmTxDate);
        sb.append(", dttsmEjfno=").append(dttsmEjfno);
        sb.append(", dttsmTxTime=").append(dttsmTxTime);
        sb.append(", dttsmTbsdyFisc=").append(dttsmTbsdyFisc);
        sb.append(", dttsmTbsdy=").append(dttsmTbsdy);
        sb.append(", dttsmPcode=").append(dttsmPcode);
        sb.append(", dttsmMerchantId=").append(dttsmMerchantId);
        sb.append(", dttsmAtmno=").append(dttsmAtmno);
        sb.append(", dttsmTroutActno=").append(dttsmTroutActno);
        sb.append(", dttsmTxAmt=").append(dttsmTxAmt);
        sb.append(", dttsmType=").append(dttsmType);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", dttsmCardSeq=").append(dttsmCardSeq);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTTSM
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Dttsm other = (Dttsm) that;
        return (this.getDttsmTxDate() == null ? other.getDttsmTxDate() == null : this.getDttsmTxDate().equals(other.getDttsmTxDate()))
            && (this.getDttsmEjfno() == null ? other.getDttsmEjfno() == null : this.getDttsmEjfno().equals(other.getDttsmEjfno()))
            && (this.getDttsmTxTime() == null ? other.getDttsmTxTime() == null : this.getDttsmTxTime().equals(other.getDttsmTxTime()))
            && (this.getDttsmTbsdyFisc() == null ? other.getDttsmTbsdyFisc() == null : this.getDttsmTbsdyFisc().equals(other.getDttsmTbsdyFisc()))
            && (this.getDttsmTbsdy() == null ? other.getDttsmTbsdy() == null : this.getDttsmTbsdy().equals(other.getDttsmTbsdy()))
            && (this.getDttsmPcode() == null ? other.getDttsmPcode() == null : this.getDttsmPcode().equals(other.getDttsmPcode()))
            && (this.getDttsmMerchantId() == null ? other.getDttsmMerchantId() == null : this.getDttsmMerchantId().equals(other.getDttsmMerchantId()))
            && (this.getDttsmAtmno() == null ? other.getDttsmAtmno() == null : this.getDttsmAtmno().equals(other.getDttsmAtmno()))
            && (this.getDttsmTroutActno() == null ? other.getDttsmTroutActno() == null : this.getDttsmTroutActno().equals(other.getDttsmTroutActno()))
            && (this.getDttsmTxAmt() == null ? other.getDttsmTxAmt() == null : this.getDttsmTxAmt().equals(other.getDttsmTxAmt()))
            && (this.getDttsmType() == null ? other.getDttsmType() == null : this.getDttsmType().equals(other.getDttsmType()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDttsmCardSeq() == null ? other.getDttsmCardSeq() == null : this.getDttsmCardSeq().equals(other.getDttsmCardSeq()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTTSM
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getDttsmTxDate() == null) ? 0 : getDttsmTxDate().hashCode());
        result = 31 * result + ((getDttsmEjfno() == null) ? 0 : getDttsmEjfno().hashCode());
        result = 31 * result + ((getDttsmTxTime() == null) ? 0 : getDttsmTxTime().hashCode());
        result = 31 * result + ((getDttsmTbsdyFisc() == null) ? 0 : getDttsmTbsdyFisc().hashCode());
        result = 31 * result + ((getDttsmTbsdy() == null) ? 0 : getDttsmTbsdy().hashCode());
        result = 31 * result + ((getDttsmPcode() == null) ? 0 : getDttsmPcode().hashCode());
        result = 31 * result + ((getDttsmMerchantId() == null) ? 0 : getDttsmMerchantId().hashCode());
        result = 31 * result + ((getDttsmAtmno() == null) ? 0 : getDttsmAtmno().hashCode());
        result = 31 * result + ((getDttsmTroutActno() == null) ? 0 : getDttsmTroutActno().hashCode());
        result = 31 * result + ((getDttsmTxAmt() == null) ? 0 : getDttsmTxAmt().hashCode());
        result = 31 * result + ((getDttsmType() == null) ? 0 : getDttsmType().hashCode());
        result = 31 * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = 31 * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = 31 * result + ((getDttsmCardSeq() == null) ? 0 : getDttsmCardSeq().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTTSM
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<DTTSM_TX_DATE>").append(this.dttsmTxDate).append("</DTTSM_TX_DATE>");
        sb.append("<DTTSM_EJFNO>").append(this.dttsmEjfno).append("</DTTSM_EJFNO>");
        sb.append("<DTTSM_TX_TIME>").append(this.dttsmTxTime).append("</DTTSM_TX_TIME>");
        sb.append("<DTTSM_TBSDY_FISC>").append(this.dttsmTbsdyFisc).append("</DTTSM_TBSDY_FISC>");
        sb.append("<DTTSM_TBSDY>").append(this.dttsmTbsdy).append("</DTTSM_TBSDY>");
        sb.append("<DTTSM_PCODE>").append(this.dttsmPcode).append("</DTTSM_PCODE>");
        sb.append("<DTTSM_MERCHANT_ID>").append(this.dttsmMerchantId).append("</DTTSM_MERCHANT_ID>");
        sb.append("<DTTSM_ATMNO>").append(this.dttsmAtmno).append("</DTTSM_ATMNO>");
        sb.append("<DTTSM_TROUT_ACTNO>").append(this.dttsmTroutActno).append("</DTTSM_TROUT_ACTNO>");
        sb.append("<DTTSM_TX_AMT>").append(this.dttsmTxAmt).append("</DTTSM_TX_AMT>");
        sb.append("<DTTSM_TYPE>").append(this.dttsmType).append("</DTTSM_TYPE>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        sb.append("<DTTSM_CARD_SEQ>").append(this.dttsmCardSeq).append("</DTTSM_CARD_SEQ>");
        return sb.toString();
    }
}