package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import org.apache.commons.lang3.StringUtils;

import java.math.BigDecimal;
import java.util.Date;

public class Eaitxn extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TX_DATE
     *
     * @mbg.generated
     */
    private String eaitxnTxDate = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_EJFNO
     *
     * @mbg.generated
     */
    private Integer eaitxnEjfno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_STAN
     *
     * @mbg.generated
     */
    private String eaitxnStan = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_MSGID
     *
     * @mbg.generated
     */
    private String eaitxnMsgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TX_TIME
     *
     * @mbg.generated
     */
    private String eaitxnTxTime = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_SERV
     *
     * @mbg.generated
     */
    private String eaitxnServ = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TD
     *
     * @mbg.generated
     */
    private String eaitxnTd = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_AP
     *
     * @mbg.generated
     */
    private String eaitxnAp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_IDNO
     *
     * @mbg.generated
     */
    private String eaitxnIdno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_OUTRTC
     *
     * @mbg.generated
     */
    private String eaitxnOutrtc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_OUTBILL
     *
     * @mbg.generated
     */
    private String eaitxnOutbill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_ACCDATE
     *
     * @mbg.generated
     */
    private String eaitxnAccdate = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRNSFROUTIDNO
     *
     * @mbg.generated
     */
    private String eaitxnTrnsfroutidno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRNSFROUTBANK
     *
     * @mbg.generated
     */
    private String eaitxnTrnsfroutbank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRNSFROUTACCNT
     *
     * @mbg.generated
     */
    private String eaitxnTrnsfroutaccnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRNSFRINIDNO
     *
     * @mbg.generated
     */
    private String eaitxnTrnsfrinidno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRNSFRINBANK
     *
     * @mbg.generated
     */
    private String eaitxnTrnsfrinbank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRNSFRINACCNT
     *
     * @mbg.generated
     */
    private String eaitxnTrnsfrinaccnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TX_AMT
     *
     * @mbg.generated
     */
    private BigDecimal eaitxnTxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_FEEPAYMENTTYPE
     *
     * @mbg.generated
     */
    private String eaitxnFeepaymenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_CUSTPAY_FEE
     *
     * @mbg.generated
     */
    private BigDecimal eaitxnCustpayFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_FISC_FEE
     *
     * @mbg.generated
     */
    private BigDecimal eaitxnFiscFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_OTHERBANK_FEE
     *
     * @mbg.generated
     */
    private BigDecimal eaitxnOtherbankFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_CHAFEE_BRANCH
     *
     * @mbg.generated
     */
    private String eaitxnChafeeBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_CHAFEE_AMT
     *
     * @mbg.generated
     */
    private BigDecimal eaitxnChafeeAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRANSAMTOUT
     *
     * @mbg.generated
     */
    private BigDecimal eaitxnTransamtout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRANSFROUTBAL
     *
     * @mbg.generated
     */
    private BigDecimal eaitxnTransfroutbal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRANSAMTIN
     *
     * @mbg.generated
     */
    private BigDecimal eaitxnTransamtin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_CLEANBRANCH_OUT
     *
     * @mbg.generated
     */
    private String eaitxnCleanbranchOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_CLEANBRANCH_IN
     *
     * @mbg.generated
     */
    private String eaitxnCleanbranchIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_RECEIVENAME
     *
     * @mbg.generated
     */
    private String eaitxnReceivename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_PAYERNOTE
     *
     * @mbg.generated
     */
    private String eaitxnPayernote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRNSFRINNAME
     *
     * @mbg.generated
     */
    private String eaitxnTrnsfrinname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRNSFROUTNAME
     *
     * @mbg.generated
     */
    private String eaitxnTrnsfroutname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_PAYEREMAIL
     *
     * @mbg.generated
     */
    private String eaitxnPayeremail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_PWATXDAY
     *
     * @mbg.generated
     */
    private String eaitxnPwatxday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_CHAFEE_TYPE
     *
     * @mbg.generated
     */
    private String eaitxnChafeeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_FAXFEE
     *
     * @mbg.generated
     */
    private BigDecimal eaitxnFaxfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRANSFEE
     *
     * @mbg.generated
     */
    private BigDecimal eaitxnTransfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TRANSOUTCUST
     *
     * @mbg.generated
     */
    private String eaitxnTransoutcust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.EAITXN_TAX_BRANCH
     *
     * @mbg.generated
     */
    private String eaitxnTaxBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EAITXN.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EAITXN
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EAITXN
     *
     * @mbg.generated
     */
    public Eaitxn(String eaitxnTxDate, Integer eaitxnEjfno, String eaitxnStan, String eaitxnMsgid, String eaitxnTxTime, String eaitxnServ, String eaitxnTd, String eaitxnAp, String eaitxnIdno, String eaitxnOutrtc, String eaitxnOutbill, String eaitxnAccdate, String eaitxnTrnsfroutidno, String eaitxnTrnsfroutbank, String eaitxnTrnsfroutaccnt, String eaitxnTrnsfrinidno, String eaitxnTrnsfrinbank, String eaitxnTrnsfrinaccnt, BigDecimal eaitxnTxAmt, String eaitxnFeepaymenttype, BigDecimal eaitxnCustpayFee, BigDecimal eaitxnFiscFee, BigDecimal eaitxnOtherbankFee, String eaitxnChafeeBranch, BigDecimal eaitxnChafeeAmt, BigDecimal eaitxnTransamtout, BigDecimal eaitxnTransfroutbal,BigDecimal eaitxnTransamtin, String eaitxnCleanbranchOut, String eaitxnCleanbranchIn, String eaitxnReceivename, String eaitxnPayernote, String eaitxnTrnsfrinname, String eaitxnTrnsfroutname, String eaitxnPayeremail, String eaitxnPwatxday, String eaitxnChafeeType, BigDecimal eaitxnFaxfee, BigDecimal eaitxnTransfee, String eaitxnTransoutcust, String eaitxnTaxBranch, Integer updateUserid, Date updateTime) {
        this.eaitxnTxDate = eaitxnTxDate;
        this.eaitxnEjfno = eaitxnEjfno;
        this.eaitxnStan = eaitxnStan;
        this.eaitxnMsgid = eaitxnMsgid;
        this.eaitxnTxTime = eaitxnTxTime;
        this.eaitxnServ = eaitxnServ;
        this.eaitxnTd = eaitxnTd;
        this.eaitxnAp = eaitxnAp;
        this.eaitxnIdno = eaitxnIdno;
        this.eaitxnOutrtc = eaitxnOutrtc;
        this.eaitxnOutbill = eaitxnOutbill;
        this.eaitxnAccdate = eaitxnAccdate;
        this.eaitxnTrnsfroutidno = eaitxnTrnsfroutidno;
        this.eaitxnTrnsfroutbank = eaitxnTrnsfroutbank;
        this.eaitxnTrnsfroutaccnt = eaitxnTrnsfroutaccnt;
        this.eaitxnTrnsfrinidno = eaitxnTrnsfrinidno;
        this.eaitxnTrnsfrinbank = eaitxnTrnsfrinbank;
        this.eaitxnTrnsfrinaccnt = eaitxnTrnsfrinaccnt;
        this.eaitxnTxAmt = eaitxnTxAmt;
        this.eaitxnFeepaymenttype = eaitxnFeepaymenttype;
        this.eaitxnCustpayFee = eaitxnCustpayFee;
        this.eaitxnFiscFee = eaitxnFiscFee;
        this.eaitxnOtherbankFee = eaitxnOtherbankFee;
        this.eaitxnChafeeBranch = eaitxnChafeeBranch;
        this.eaitxnChafeeAmt = eaitxnChafeeAmt;
        this.eaitxnTransamtout = eaitxnTransamtout;
        this.eaitxnTransfroutbal = eaitxnTransfroutbal;
        this.eaitxnTransamtin = eaitxnTransamtin;
        this.eaitxnCleanbranchOut = eaitxnCleanbranchOut;
        this.eaitxnCleanbranchIn = eaitxnCleanbranchIn;
        this.eaitxnReceivename = eaitxnReceivename;
        this.eaitxnPayernote = eaitxnPayernote;
        this.eaitxnTrnsfrinname = eaitxnTrnsfrinname;
        this.eaitxnTrnsfroutname = eaitxnTrnsfroutname;
        this.eaitxnPayeremail = eaitxnPayeremail;
        this.eaitxnPwatxday = eaitxnPwatxday;
        this.eaitxnChafeeType = eaitxnChafeeType;
        this.eaitxnFaxfee = eaitxnFaxfee;
        this.eaitxnTransfee = eaitxnTransfee;
        this.eaitxnTransoutcust = eaitxnTransoutcust;
        this.eaitxnTaxBranch = eaitxnTaxBranch;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EAITXN
     *
     * @mbg.generated
     */
    public Eaitxn() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TX_DATE
     *
     * @return the value of EAITXN.EAITXN_TX_DATE
     *
     * @mbg.generated
     */
    public String getEaitxnTxDate() {
        return eaitxnTxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TX_DATE
     *
     * @param eaitxnTxDate the value for EAITXN.EAITXN_TX_DATE
     *
     * @mbg.generated
     */
    public void setEaitxnTxDate(String eaitxnTxDate) {
        this.eaitxnTxDate = eaitxnTxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_EJFNO
     *
     * @return the value of EAITXN.EAITXN_EJFNO
     *
     * @mbg.generated
     */
    public Integer getEaitxnEjfno() {
        return eaitxnEjfno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_EJFNO
     *
     * @param eaitxnEjfno the value for EAITXN.EAITXN_EJFNO
     *
     * @mbg.generated
     */
    public void setEaitxnEjfno(Integer eaitxnEjfno) {
        this.eaitxnEjfno = eaitxnEjfno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_STAN
     *
     * @return the value of EAITXN.EAITXN_STAN
     *
     * @mbg.generated
     */
    public String getEaitxnStan() {
        return eaitxnStan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_STAN
     *
     * @param eaitxnStan the value for EAITXN.EAITXN_STAN
     *
     * @mbg.generated
     */
    public void setEaitxnStan(String eaitxnStan) {
        this.eaitxnStan = eaitxnStan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_MSGID
     *
     * @return the value of EAITXN.EAITXN_MSGID
     *
     * @mbg.generated
     */
    public String getEaitxnMsgid() {
        return eaitxnMsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_MSGID
     *
     * @param eaitxnMsgid the value for EAITXN.EAITXN_MSGID
     *
     * @mbg.generated
     */
    public void setEaitxnMsgid(String eaitxnMsgid) {
        this.eaitxnMsgid = eaitxnMsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TX_TIME
     *
     * @return the value of EAITXN.EAITXN_TX_TIME
     *
     * @mbg.generated
     */
    public String getEaitxnTxTime() {
        return eaitxnTxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TX_TIME
     *
     * @param eaitxnTxTime the value for EAITXN.EAITXN_TX_TIME
     *
     * @mbg.generated
     */
    public void setEaitxnTxTime(String eaitxnTxTime) {
        this.eaitxnTxTime = eaitxnTxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_SERV
     *
     * @return the value of EAITXN.EAITXN_SERV
     *
     * @mbg.generated
     */
    public String getEaitxnServ() {
        return eaitxnServ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_SERV
     *
     * @param eaitxnServ the value for EAITXN.EAITXN_SERV
     *
     * @mbg.generated
     */
    public void setEaitxnServ(String eaitxnServ) {
        this.eaitxnServ = eaitxnServ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TD
     *
     * @return the value of EAITXN.EAITXN_TD
     *
     * @mbg.generated
     */
    public String getEaitxnTd() {
        return eaitxnTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TD
     *
     * @param eaitxnTd the value for EAITXN.EAITXN_TD
     *
     * @mbg.generated
     */
    public void setEaitxnTd(String eaitxnTd) {
        this.eaitxnTd = eaitxnTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_AP
     *
     * @return the value of EAITXN.EAITXN_AP
     *
     * @mbg.generated
     */
    public String getEaitxnAp() {
        return eaitxnAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_AP
     *
     * @param eaitxnAp the value for EAITXN.EAITXN_AP
     *
     * @mbg.generated
     */
    public void setEaitxnAp(String eaitxnAp) {
        this.eaitxnAp = eaitxnAp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_IDNO
     *
     * @return the value of EAITXN.EAITXN_IDNO
     *
     * @mbg.generated
     */
    public String getEaitxnIdno() {
        return eaitxnIdno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_IDNO
     *
     * @param eaitxnIdno the value for EAITXN.EAITXN_IDNO
     *
     * @mbg.generated
     */
    public void setEaitxnIdno(String eaitxnIdno) {
        this.eaitxnIdno = eaitxnIdno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_OUTRTC
     *
     * @return the value of EAITXN.EAITXN_OUTRTC
     *
     * @mbg.generated
     */
    public String getEaitxnOutrtc() {
        return eaitxnOutrtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_OUTRTC
     *
     * @param eaitxnOutrtc the value for EAITXN.EAITXN_OUTRTC
     *
     * @mbg.generated
     */
    public void setEaitxnOutrtc(String eaitxnOutrtc) {
        this.eaitxnOutrtc = eaitxnOutrtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_OUTBILL
     *
     * @return the value of EAITXN.EAITXN_OUTBILL
     *
     * @mbg.generated
     */
    public String getEaitxnOutbill() {
        return eaitxnOutbill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_OUTBILL
     *
     * @param eaitxnOutbill the value for EAITXN.EAITXN_OUTBILL
     *
     * @mbg.generated
     */
    public void setEaitxnOutbill(String eaitxnOutbill) {
        this.eaitxnOutbill = eaitxnOutbill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_ACCDATE
     *
     * @return the value of EAITXN.EAITXN_ACCDATE
     *
     * @mbg.generated
     */
    public String getEaitxnAccdate() {
        return eaitxnAccdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_ACCDATE
     *
     * @param eaitxnAccdate the value for EAITXN.EAITXN_ACCDATE
     *
     * @mbg.generated
     */
    public void setEaitxnAccdate(String eaitxnAccdate) {
        this.eaitxnAccdate = eaitxnAccdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRNSFROUTIDNO
     *
     * @return the value of EAITXN.EAITXN_TRNSFROUTIDNO
     *
     * @mbg.generated
     */
    public String getEaitxnTrnsfroutidno() {
        return eaitxnTrnsfroutidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRNSFROUTIDNO
     *
     * @param eaitxnTrnsfroutidno the value for EAITXN.EAITXN_TRNSFROUTIDNO
     *
     * @mbg.generated
     */
    public void setEaitxnTrnsfroutidno(String eaitxnTrnsfroutidno) {
        this.eaitxnTrnsfroutidno = eaitxnTrnsfroutidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRNSFROUTBANK
     *
     * @return the value of EAITXN.EAITXN_TRNSFROUTBANK
     *
     * @mbg.generated
     */
    public String getEaitxnTrnsfroutbank() {
        return eaitxnTrnsfroutbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRNSFROUTBANK
     *
     * @param eaitxnTrnsfroutbank the value for EAITXN.EAITXN_TRNSFROUTBANK
     *
     * @mbg.generated
     */
    public void setEaitxnTrnsfroutbank(String eaitxnTrnsfroutbank) {
        this.eaitxnTrnsfroutbank = eaitxnTrnsfroutbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRNSFROUTACCNT
     *
     * @return the value of EAITXN.EAITXN_TRNSFROUTACCNT
     *
     * @mbg.generated
     */
    public String getEaitxnTrnsfroutaccnt() {
        return eaitxnTrnsfroutaccnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRNSFROUTACCNT
     *
     * @param eaitxnTrnsfroutaccnt the value for EAITXN.EAITXN_TRNSFROUTACCNT
     *
     * @mbg.generated
     */
    public void setEaitxnTrnsfroutaccnt(String eaitxnTrnsfroutaccnt) {
        this.eaitxnTrnsfroutaccnt = eaitxnTrnsfroutaccnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRNSFRINIDNO
     *
     * @return the value of EAITXN.EAITXN_TRNSFRINIDNO
     *
     * @mbg.generated
     */
    public String getEaitxnTrnsfrinidno() {
        return eaitxnTrnsfrinidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRNSFRINIDNO
     *
     * @param eaitxnTrnsfrinidno the value for EAITXN.EAITXN_TRNSFRINIDNO
     *
     * @mbg.generated
     */
    public void setEaitxnTrnsfrinidno(String eaitxnTrnsfrinidno) {
        this.eaitxnTrnsfrinidno = eaitxnTrnsfrinidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRNSFRINBANK
     *
     * @return the value of EAITXN.EAITXN_TRNSFRINBANK
     *
     * @mbg.generated
     */
    public String getEaitxnTrnsfrinbank() {
        return eaitxnTrnsfrinbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRNSFRINBANK
     *
     * @param eaitxnTrnsfrinbank the value for EAITXN.EAITXN_TRNSFRINBANK
     *
     * @mbg.generated
     */
    public void setEaitxnTrnsfrinbank(String eaitxnTrnsfrinbank) {
        this.eaitxnTrnsfrinbank = eaitxnTrnsfrinbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRNSFRINACCNT
     *
     * @return the value of EAITXN.EAITXN_TRNSFRINACCNT
     *
     * @mbg.generated
     */
    public String getEaitxnTrnsfrinaccnt() {
        return eaitxnTrnsfrinaccnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRNSFRINACCNT
     *
     * @param eaitxnTrnsfrinaccnt the value for EAITXN.EAITXN_TRNSFRINACCNT
     *
     * @mbg.generated
     */
    public void setEaitxnTrnsfrinaccnt(String eaitxnTrnsfrinaccnt) {
        this.eaitxnTrnsfrinaccnt = eaitxnTrnsfrinaccnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TX_AMT
     *
     * @return the value of EAITXN.EAITXN_TX_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getEaitxnTxAmt() {
        return eaitxnTxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TX_AMT
     *
     * @param eaitxnTxAmt the value for EAITXN.EAITXN_TX_AMT
     *
     * @mbg.generated
     */
    public void setEaitxnTxAmt(BigDecimal eaitxnTxAmt) {
        this.eaitxnTxAmt = eaitxnTxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_FEEPAYMENTTYPE
     *
     * @return the value of EAITXN.EAITXN_FEEPAYMENTTYPE
     *
     * @mbg.generated
     */
    public String getEaitxnFeepaymenttype() {
        return eaitxnFeepaymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_FEEPAYMENTTYPE
     *
     * @param eaitxnFeepaymenttype the value for EAITXN.EAITXN_FEEPAYMENTTYPE
     *
     * @mbg.generated
     */
    public void setEaitxnFeepaymenttype(String eaitxnFeepaymenttype) {
        this.eaitxnFeepaymenttype = eaitxnFeepaymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_CUSTPAY_FEE
     *
     * @return the value of EAITXN.EAITXN_CUSTPAY_FEE
     *
     * @mbg.generated
     */
    public BigDecimal getEaitxnCustpayFee() {
        return eaitxnCustpayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_CUSTPAY_FEE
     *
     * @param eaitxnCustpayFee the value for EAITXN.EAITXN_CUSTPAY_FEE
     *
     * @mbg.generated
     */
    public void setEaitxnCustpayFee(BigDecimal eaitxnCustpayFee) {
        this.eaitxnCustpayFee = eaitxnCustpayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_FISC_FEE
     *
     * @return the value of EAITXN.EAITXN_FISC_FEE
     *
     * @mbg.generated
     */
    public BigDecimal getEaitxnFiscFee() {
        return eaitxnFiscFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_FISC_FEE
     *
     * @param eaitxnFiscFee the value for EAITXN.EAITXN_FISC_FEE
     *
     * @mbg.generated
     */
    public void setEaitxnFiscFee(BigDecimal eaitxnFiscFee) {
        this.eaitxnFiscFee = eaitxnFiscFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_OTHERBANK_FEE
     *
     * @return the value of EAITXN.EAITXN_OTHERBANK_FEE
     *
     * @mbg.generated
     */
    public BigDecimal getEaitxnOtherbankFee() {
        return eaitxnOtherbankFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_OTHERBANK_FEE
     *
     * @param eaitxnOtherbankFee the value for EAITXN.EAITXN_OTHERBANK_FEE
     *
     * @mbg.generated
     */
    public void setEaitxnOtherbankFee(BigDecimal eaitxnOtherbankFee) {
        this.eaitxnOtherbankFee = eaitxnOtherbankFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_CHAFEE_BRANCH
     *
     * @return the value of EAITXN.EAITXN_CHAFEE_BRANCH
     *
     * @mbg.generated
     */
    public String getEaitxnChafeeBranch() {
        return eaitxnChafeeBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_CHAFEE_BRANCH
     *
     * @param eaitxnChafeeBranch the value for EAITXN.EAITXN_CHAFEE_BRANCH
     *
     * @mbg.generated
     */
    public void setEaitxnChafeeBranch(String eaitxnChafeeBranch) {
        this.eaitxnChafeeBranch = eaitxnChafeeBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_CHAFEE_AMT
     *
     * @return the value of EAITXN.EAITXN_CHAFEE_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getEaitxnChafeeAmt() {
        return eaitxnChafeeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_CHAFEE_AMT
     *
     * @param eaitxnChafeeAmt the value for EAITXN.EAITXN_CHAFEE_AMT
     *
     * @mbg.generated
     */
    public void setEaitxnChafeeAmt(BigDecimal eaitxnChafeeAmt) {
        this.eaitxnChafeeAmt = eaitxnChafeeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRANSAMTOUT
     *
     * @return the value of EAITXN.EAITXN_TRANSAMTOUT
     *
     * @mbg.generated
     */
    public BigDecimal getEaitxnTransamtout() {
        return eaitxnTransamtout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRANSFROUTBAL
     *
     * @return the value of EAITXN.EAITXN_TRANSFROUTBAL
     *
     * @mbg.generated
     */
    public BigDecimal getEaitxnTransfroutbal() {
        return eaitxnTransfroutbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRANSAMTOUT
     *
     * @param eaitxnTransamtout the value for EAITXN.EAITXN_TRANSAMTOUT
     *
     * @mbg.generated
     */
    public void setEaitxnTransamtout(BigDecimal eaitxnTransamtout) {
        this.eaitxnTransamtout = eaitxnTransamtout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRANSFROUTBAL
     *
     * @param eaitxnTransfroutbal the value for EAITXN.EAITXN_TRANSFROUTBAL
     *
     * @mbg.generated
     */
    public void setEaitxnTransfroutbal(BigDecimal eaitxnTransfroutbal) {
        this.eaitxnTransfroutbal = eaitxnTransfroutbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRANSAMTIN
     *
     * @return the value of EAITXN.EAITXN_TRANSAMTIN
     *
     * @mbg.generated
     */
    public BigDecimal getEaitxnTransamtin() {
        return eaitxnTransamtin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRANSAMTIN
     *
     * @param eaitxnTransamtin the value for EAITXN.EAITXN_TRANSAMTIN
     *
     * @mbg.generated
     */
    public void setEaitxnTransamtin(BigDecimal eaitxnTransamtin) {
        this.eaitxnTransamtin = eaitxnTransamtin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_CLEANBRANCH_OUT
     *
     * @return the value of EAITXN.EAITXN_CLEANBRANCH_OUT
     *
     * @mbg.generated
     */
    public String getEaitxnCleanbranchOut() {
        return eaitxnCleanbranchOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_CLEANBRANCH_OUT
     *
     * @param eaitxnCleanbranchOut the value for EAITXN.EAITXN_CLEANBRANCH_OUT
     *
     * @mbg.generated
     */
    public void setEaitxnCleanbranchOut(String eaitxnCleanbranchOut) {
        this.eaitxnCleanbranchOut = eaitxnCleanbranchOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_CLEANBRANCH_IN
     *
     * @return the value of EAITXN.EAITXN_CLEANBRANCH_IN
     *
     * @mbg.generated
     */
    public String getEaitxnCleanbranchIn() {
        return eaitxnCleanbranchIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_CLEANBRANCH_IN
     *
     * @param eaitxnCleanbranchIn the value for EAITXN.EAITXN_CLEANBRANCH_IN
     *
     * @mbg.generated
     */
    public void setEaitxnCleanbranchIn(String eaitxnCleanbranchIn) {
        this.eaitxnCleanbranchIn = eaitxnCleanbranchIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_RECEIVENAME
     *
     * @return the value of EAITXN.EAITXN_RECEIVENAME
     *
     * @mbg.generated
     */
    public String getEaitxnReceivename() {
        return eaitxnReceivename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_RECEIVENAME
     *
     * @param eaitxnReceivename the value for EAITXN.EAITXN_RECEIVENAME
     *
     * @mbg.generated
     */
    public void setEaitxnReceivename(String eaitxnReceivename) {
        this.eaitxnReceivename = eaitxnReceivename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_PAYERNOTE
     *
     * @return the value of EAITXN.EAITXN_PAYERNOTE
     *
     * @mbg.generated
     */
    public String getEaitxnPayernote() {
        return eaitxnPayernote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_PAYERNOTE
     *
     * @param eaitxnPayernote the value for EAITXN.EAITXN_PAYERNOTE
     *
     * @mbg.generated
     */
    public void setEaitxnPayernote(String eaitxnPayernote) {
        this.eaitxnPayernote = eaitxnPayernote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRNSFRINNAME
     *
     * @return the value of EAITXN.EAITXN_TRNSFRINNAME
     *
     * @mbg.generated
     */
    public String getEaitxnTrnsfrinname() {
        return eaitxnTrnsfrinname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRNSFRINNAME
     *
     * @param eaitxnTrnsfrinname the value for EAITXN.EAITXN_TRNSFRINNAME
     *
     * @mbg.generated
     */
    public void setEaitxnTrnsfrinname(String eaitxnTrnsfrinname) {
        this.eaitxnTrnsfrinname = eaitxnTrnsfrinname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRNSFROUTNAME
     *
     * @return the value of EAITXN.EAITXN_TRNSFROUTNAME
     *
     * @mbg.generated
     */
    public String getEaitxnTrnsfroutname() {
        return eaitxnTrnsfroutname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRNSFROUTNAME
     *
     * @param eaitxnTrnsfroutname the value for EAITXN.EAITXN_TRNSFROUTNAME
     *
     * @mbg.generated
     */
    public void setEaitxnTrnsfroutname(String eaitxnTrnsfroutname) {
        this.eaitxnTrnsfroutname = eaitxnTrnsfroutname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_PAYEREMAIL
     *
     * @return the value of EAITXN.EAITXN_PAYEREMAIL
     *
     * @mbg.generated
     */
    public String getEaitxnPayeremail() {
        return eaitxnPayeremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_PAYEREMAIL
     *
     * @param eaitxnPayeremail the value for EAITXN.EAITXN_PAYEREMAIL
     *
     * @mbg.generated
     */
    public void setEaitxnPayeremail(String eaitxnPayeremail) {
        this.eaitxnPayeremail = eaitxnPayeremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_PWATXDAY
     *
     * @return the value of EAITXN.EAITXN_PWATXDAY
     *
     * @mbg.generated
     */
    public String getEaitxnPwatxday() {
        return eaitxnPwatxday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_PWATXDAY
     *
     * @param eaitxnPwatxday the value for EAITXN.EAITXN_PWATXDAY
     *
     * @mbg.generated
     */
    public void setEaitxnPwatxday(String eaitxnPwatxday) {
        this.eaitxnPwatxday = eaitxnPwatxday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_CHAFEE_TYPE
     *
     * @return the value of EAITXN.EAITXN_CHAFEE_TYPE
     *
     * @mbg.generated
     */
    public String getEaitxnChafeeType() {
        return eaitxnChafeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_CHAFEE_TYPE
     *
     * @param eaitxnChafeeType the value for EAITXN.EAITXN_CHAFEE_TYPE
     *
     * @mbg.generated
     */
    public void setEaitxnChafeeType(String eaitxnChafeeType) {
        this.eaitxnChafeeType = eaitxnChafeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_FAXFEE
     *
     * @return the value of EAITXN.EAITXN_FAXFEE
     *
     * @mbg.generated
     */
    public BigDecimal getEaitxnFaxfee() {
        return eaitxnFaxfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_FAXFEE
     *
     * @param eaitxnFaxfee the value for EAITXN.EAITXN_FAXFEE
     *
     * @mbg.generated
     */
    public void setEaitxnFaxfee(BigDecimal eaitxnFaxfee) {
        this.eaitxnFaxfee = eaitxnFaxfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRANSFEE
     *
     * @return the value of EAITXN.EAITXN_TRANSFEE
     *
     * @mbg.generated
     */
    public BigDecimal getEaitxnTransfee() {
        return eaitxnTransfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRANSFEE
     *
     * @param eaitxnTransfee the value for EAITXN.EAITXN_TRANSFEE
     *
     * @mbg.generated
     */
    public void setEaitxnTransfee(BigDecimal eaitxnTransfee) {
        this.eaitxnTransfee = eaitxnTransfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TRANSOUTCUST
     *
     * @return the value of EAITXN.EAITXN_TRANSOUTCUST
     *
     * @mbg.generated
     */
    public String getEaitxnTransoutcust() {
        return eaitxnTransoutcust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TRANSOUTCUST
     *
     * @param eaitxnTransoutcust the value for EAITXN.EAITXN_TRANSOUTCUST
     *
     * @mbg.generated
     */
    public void setEaitxnTransoutcust(String eaitxnTransoutcust) {
        this.eaitxnTransoutcust = eaitxnTransoutcust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.EAITXN_TAX_BRANCH
     *
     * @return the value of EAITXN.EAITXN_TAX_BRANCH
     *
     * @mbg.generated
     */
    public String getEaitxnTaxBranch() {
        return eaitxnTaxBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.EAITXN_TAX_BRANCH
     *
     * @param eaitxnTaxBranch the value for EAITXN.EAITXN_TAX_BRANCH
     *
     * @mbg.generated
     */
    public void setEaitxnTaxBranch(String eaitxnTaxBranch) {
        this.eaitxnTaxBranch = eaitxnTaxBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.UPDATE_USERID
     *
     * @return the value of EAITXN.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.UPDATE_USERID
     *
     * @param updateUserid the value for EAITXN.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EAITXN.UPDATE_TIME
     *
     * @return the value of EAITXN.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EAITXN.UPDATE_TIME
     *
     * @param updateTime the value for EAITXN.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EAITXN
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Eaitxn other = (Eaitxn) that;
        return (this.getEaitxnTxDate() == null ? other.getEaitxnTxDate() == null : this.getEaitxnTxDate().equals(other.getEaitxnTxDate()))
            && (this.getEaitxnEjfno() == null ? other.getEaitxnEjfno() == null : this.getEaitxnEjfno().equals(other.getEaitxnEjfno()))
            && (this.getEaitxnStan() == null ? other.getEaitxnStan() == null : this.getEaitxnStan().equals(other.getEaitxnStan()))
            && (this.getEaitxnMsgid() == null ? other.getEaitxnMsgid() == null : this.getEaitxnMsgid().equals(other.getEaitxnMsgid()))
            && (this.getEaitxnTxTime() == null ? other.getEaitxnTxTime() == null : this.getEaitxnTxTime().equals(other.getEaitxnTxTime()))
            && (this.getEaitxnServ() == null ? other.getEaitxnServ() == null : this.getEaitxnServ().equals(other.getEaitxnServ()))
            && (this.getEaitxnTd() == null ? other.getEaitxnTd() == null : this.getEaitxnTd().equals(other.getEaitxnTd()))
            && (this.getEaitxnAp() == null ? other.getEaitxnAp() == null : this.getEaitxnAp().equals(other.getEaitxnAp()))
            && (this.getEaitxnIdno() == null ? other.getEaitxnIdno() == null : this.getEaitxnIdno().equals(other.getEaitxnIdno()))
            && (this.getEaitxnOutrtc() == null ? other.getEaitxnOutrtc() == null : this.getEaitxnOutrtc().equals(other.getEaitxnOutrtc()))
            && (this.getEaitxnOutbill() == null ? other.getEaitxnOutbill() == null : this.getEaitxnOutbill().equals(other.getEaitxnOutbill()))
            && (this.getEaitxnAccdate() == null ? other.getEaitxnAccdate() == null : this.getEaitxnAccdate().equals(other.getEaitxnAccdate()))
            && (this.getEaitxnTrnsfroutidno() == null ? other.getEaitxnTrnsfroutidno() == null : this.getEaitxnTrnsfroutidno().equals(other.getEaitxnTrnsfroutidno()))
            && (this.getEaitxnTrnsfroutbank() == null ? other.getEaitxnTrnsfroutbank() == null : this.getEaitxnTrnsfroutbank().equals(other.getEaitxnTrnsfroutbank()))
            && (this.getEaitxnTrnsfroutaccnt() == null ? other.getEaitxnTrnsfroutaccnt() == null : this.getEaitxnTrnsfroutaccnt().equals(other.getEaitxnTrnsfroutaccnt()))
            && (this.getEaitxnTrnsfrinidno() == null ? other.getEaitxnTrnsfrinidno() == null : this.getEaitxnTrnsfrinidno().equals(other.getEaitxnTrnsfrinidno()))
            && (this.getEaitxnTrnsfrinbank() == null ? other.getEaitxnTrnsfrinbank() == null : this.getEaitxnTrnsfrinbank().equals(other.getEaitxnTrnsfrinbank()))
            && (this.getEaitxnTrnsfrinaccnt() == null ? other.getEaitxnTrnsfrinaccnt() == null : this.getEaitxnTrnsfrinaccnt().equals(other.getEaitxnTrnsfrinaccnt()))
            && (this.getEaitxnTxAmt() == null ? other.getEaitxnTxAmt() == null : this.getEaitxnTxAmt().equals(other.getEaitxnTxAmt()))
            && (this.getEaitxnFeepaymenttype() == null ? other.getEaitxnFeepaymenttype() == null : this.getEaitxnFeepaymenttype().equals(other.getEaitxnFeepaymenttype()))
            && (this.getEaitxnCustpayFee() == null ? other.getEaitxnCustpayFee() == null : this.getEaitxnCustpayFee().equals(other.getEaitxnCustpayFee()))
            && (this.getEaitxnFiscFee() == null ? other.getEaitxnFiscFee() == null : this.getEaitxnFiscFee().equals(other.getEaitxnFiscFee()))
            && (this.getEaitxnOtherbankFee() == null ? other.getEaitxnOtherbankFee() == null : this.getEaitxnOtherbankFee().equals(other.getEaitxnOtherbankFee()))
            && (this.getEaitxnChafeeBranch() == null ? other.getEaitxnChafeeBranch() == null : this.getEaitxnChafeeBranch().equals(other.getEaitxnChafeeBranch()))
            && (this.getEaitxnChafeeAmt() == null ? other.getEaitxnChafeeAmt() == null : this.getEaitxnChafeeAmt().equals(other.getEaitxnChafeeAmt()))
            && (this.getEaitxnTransamtout() == null ? other.getEaitxnTransamtout() == null : this.getEaitxnTransamtout().equals(other.getEaitxnTransamtout()))
            && (this.getEaitxnTransfroutbal() == null ? other.getEaitxnTransfroutbal() == null : this.getEaitxnTransfroutbal().equals(other.getEaitxnTransfroutbal()))
            && (this.getEaitxnTransamtin() == null ? other.getEaitxnTransamtin() == null : this.getEaitxnTransamtin().equals(other.getEaitxnTransamtin()))
            && (this.getEaitxnCleanbranchOut() == null ? other.getEaitxnCleanbranchOut() == null : this.getEaitxnCleanbranchOut().equals(other.getEaitxnCleanbranchOut()))
            && (this.getEaitxnCleanbranchIn() == null ? other.getEaitxnCleanbranchIn() == null : this.getEaitxnCleanbranchIn().equals(other.getEaitxnCleanbranchIn()))
            && (this.getEaitxnReceivename() == null ? other.getEaitxnReceivename() == null : this.getEaitxnReceivename().equals(other.getEaitxnReceivename()))
            && (this.getEaitxnPayernote() == null ? other.getEaitxnPayernote() == null : this.getEaitxnPayernote().equals(other.getEaitxnPayernote()))
            && (this.getEaitxnTrnsfrinname() == null ? other.getEaitxnTrnsfrinname() == null : this.getEaitxnTrnsfrinname().equals(other.getEaitxnTrnsfrinname()))
            && (this.getEaitxnTrnsfroutname() == null ? other.getEaitxnTrnsfroutname() == null : this.getEaitxnTrnsfroutname().equals(other.getEaitxnTrnsfroutname()))
            && (this.getEaitxnPayeremail() == null ? other.getEaitxnPayeremail() == null : this.getEaitxnPayeremail().equals(other.getEaitxnPayeremail()))
            && (this.getEaitxnPwatxday() == null ? other.getEaitxnPwatxday() == null : this.getEaitxnPwatxday().equals(other.getEaitxnPwatxday()))
            && (this.getEaitxnChafeeType() == null ? other.getEaitxnChafeeType() == null : this.getEaitxnChafeeType().equals(other.getEaitxnChafeeType()))
            && (this.getEaitxnFaxfee() == null ? other.getEaitxnFaxfee() == null : this.getEaitxnFaxfee().equals(other.getEaitxnFaxfee()))
            && (this.getEaitxnTransfee() == null ? other.getEaitxnTransfee() == null : this.getEaitxnTransfee().equals(other.getEaitxnTransfee()))
            && (this.getEaitxnTransoutcust() == null ? other.getEaitxnTransoutcust() == null : this.getEaitxnTransoutcust().equals(other.getEaitxnTransoutcust()))
            && (this.getEaitxnTaxBranch() == null ? other.getEaitxnTaxBranch() == null : this.getEaitxnTaxBranch().equals(other.getEaitxnTaxBranch()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EAITXN
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEaitxnTxDate() == null) ? 0 : getEaitxnTxDate().hashCode());
        result = prime * result + ((getEaitxnEjfno() == null) ? 0 : getEaitxnEjfno().hashCode());
        result = prime * result + ((getEaitxnStan() == null) ? 0 : getEaitxnStan().hashCode());
        result = prime * result + ((getEaitxnMsgid() == null) ? 0 : getEaitxnMsgid().hashCode());
        result = prime * result + ((getEaitxnTxTime() == null) ? 0 : getEaitxnTxTime().hashCode());
        result = prime * result + ((getEaitxnServ() == null) ? 0 : getEaitxnServ().hashCode());
        result = prime * result + ((getEaitxnTd() == null) ? 0 : getEaitxnTd().hashCode());
        result = prime * result + ((getEaitxnAp() == null) ? 0 : getEaitxnAp().hashCode());
        result = prime * result + ((getEaitxnIdno() == null) ? 0 : getEaitxnIdno().hashCode());
        result = prime * result + ((getEaitxnOutrtc() == null) ? 0 : getEaitxnOutrtc().hashCode());
        result = prime * result + ((getEaitxnOutbill() == null) ? 0 : getEaitxnOutbill().hashCode());
        result = prime * result + ((getEaitxnAccdate() == null) ? 0 : getEaitxnAccdate().hashCode());
        result = prime * result + ((getEaitxnTrnsfroutidno() == null) ? 0 : getEaitxnTrnsfroutidno().hashCode());
        result = prime * result + ((getEaitxnTrnsfroutbank() == null) ? 0 : getEaitxnTrnsfroutbank().hashCode());
        result = prime * result + ((getEaitxnTrnsfroutaccnt() == null) ? 0 : getEaitxnTrnsfroutaccnt().hashCode());
        result = prime * result + ((getEaitxnTrnsfrinidno() == null) ? 0 : getEaitxnTrnsfrinidno().hashCode());
        result = prime * result + ((getEaitxnTrnsfrinbank() == null) ? 0 : getEaitxnTrnsfrinbank().hashCode());
        result = prime * result + ((getEaitxnTrnsfrinaccnt() == null) ? 0 : getEaitxnTrnsfrinaccnt().hashCode());
        result = prime * result + ((getEaitxnTxAmt() == null) ? 0 : getEaitxnTxAmt().hashCode());
        result = prime * result + ((getEaitxnFeepaymenttype() == null) ? 0 : getEaitxnFeepaymenttype().hashCode());
        result = prime * result + ((getEaitxnCustpayFee() == null) ? 0 : getEaitxnCustpayFee().hashCode());
        result = prime * result + ((getEaitxnFiscFee() == null) ? 0 : getEaitxnFiscFee().hashCode());
        result = prime * result + ((getEaitxnOtherbankFee() == null) ? 0 : getEaitxnOtherbankFee().hashCode());
        result = prime * result + ((getEaitxnChafeeBranch() == null) ? 0 : getEaitxnChafeeBranch().hashCode());
        result = prime * result + ((getEaitxnChafeeAmt() == null) ? 0 : getEaitxnChafeeAmt().hashCode());
        result = prime * result + ((getEaitxnTransamtout() == null) ? 0 : getEaitxnTransamtout().hashCode());
        result = prime * result + ((getEaitxnTransfroutbal() == null) ? 0 : getEaitxnTransfroutbal().hashCode());
        result = prime * result + ((getEaitxnTransamtin() == null) ? 0 : getEaitxnTransamtin().hashCode());
        result = prime * result + ((getEaitxnCleanbranchOut() == null) ? 0 : getEaitxnCleanbranchOut().hashCode());
        result = prime * result + ((getEaitxnCleanbranchIn() == null) ? 0 : getEaitxnCleanbranchIn().hashCode());
        result = prime * result + ((getEaitxnReceivename() == null) ? 0 : getEaitxnReceivename().hashCode());
        result = prime * result + ((getEaitxnPayernote() == null) ? 0 : getEaitxnPayernote().hashCode());
        result = prime * result + ((getEaitxnTrnsfrinname() == null) ? 0 : getEaitxnTrnsfrinname().hashCode());
        result = prime * result + ((getEaitxnTrnsfroutname() == null) ? 0 : getEaitxnTrnsfroutname().hashCode());
        result = prime * result + ((getEaitxnPayeremail() == null) ? 0 : getEaitxnPayeremail().hashCode());
        result = prime * result + ((getEaitxnPwatxday() == null) ? 0 : getEaitxnPwatxday().hashCode());
        result = prime * result + ((getEaitxnChafeeType() == null) ? 0 : getEaitxnChafeeType().hashCode());
        result = prime * result + ((getEaitxnFaxfee() == null) ? 0 : getEaitxnFaxfee().hashCode());
        result = prime * result + ((getEaitxnTransfee() == null) ? 0 : getEaitxnTransfee().hashCode());
        result = prime * result + ((getEaitxnTransoutcust() == null) ? 0 : getEaitxnTransoutcust().hashCode());
        result = prime * result + ((getEaitxnTaxBranch() == null) ? 0 : getEaitxnTaxBranch().hashCode());
        result = prime * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EAITXN
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eaitxnTxDate=").append(eaitxnTxDate);
        sb.append(", eaitxnEjfno=").append(eaitxnEjfno);
        sb.append(", eaitxnStan=").append(eaitxnStan);
        sb.append(", eaitxnMsgid=").append(eaitxnMsgid);
        sb.append(", eaitxnTxTime=").append(eaitxnTxTime);
        sb.append(", eaitxnServ=").append(eaitxnServ);
        sb.append(", eaitxnTd=").append(eaitxnTd);
        sb.append(", eaitxnAp=").append(eaitxnAp);
        sb.append(", eaitxnIdno=").append(eaitxnIdno);
        sb.append(", eaitxnOutrtc=").append(eaitxnOutrtc);
        sb.append(", eaitxnOutbill=").append(eaitxnOutbill);
        sb.append(", eaitxnAccdate=").append(eaitxnAccdate);
        sb.append(", eaitxnTrnsfroutidno=").append(eaitxnTrnsfroutidno);
        sb.append(", eaitxnTrnsfroutbank=").append(eaitxnTrnsfroutbank);
        sb.append(", eaitxnTrnsfroutaccnt=").append(eaitxnTrnsfroutaccnt);
        sb.append(", eaitxnTrnsfrinidno=").append(eaitxnTrnsfrinidno);
        sb.append(", eaitxnTrnsfrinbank=").append(eaitxnTrnsfrinbank);
        sb.append(", eaitxnTrnsfrinaccnt=").append(eaitxnTrnsfrinaccnt);
        sb.append(", eaitxnTxAmt=").append(eaitxnTxAmt);
        sb.append(", eaitxnFeepaymenttype=").append(eaitxnFeepaymenttype);
        sb.append(", eaitxnCustpayFee=").append(eaitxnCustpayFee);
        sb.append(", eaitxnFiscFee=").append(eaitxnFiscFee);
        sb.append(", eaitxnOtherbankFee=").append(eaitxnOtherbankFee);
        sb.append(", eaitxnChafeeBranch=").append(eaitxnChafeeBranch);
        sb.append(", eaitxnChafeeAmt=").append(eaitxnChafeeAmt);
        sb.append(", eaitxnTransamtout=").append(eaitxnTransamtout);
        sb.append(", eaitxnTransfroutbal=").append(eaitxnTransfroutbal);
        sb.append(", eaitxnTransamtin=").append(eaitxnTransamtin);
        sb.append(", eaitxnCleanbranchOut=").append(eaitxnCleanbranchOut);
        sb.append(", eaitxnCleanbranchIn=").append(eaitxnCleanbranchIn);
        sb.append(", eaitxnReceivename=").append(eaitxnReceivename);
        sb.append(", eaitxnPayernote=").append(eaitxnPayernote);
        sb.append(", eaitxnTrnsfrinname=").append(eaitxnTrnsfrinname);
        sb.append(", eaitxnTrnsfroutname=").append(eaitxnTrnsfroutname);
        sb.append(", eaitxnPayeremail=").append(eaitxnPayeremail);
        sb.append(", eaitxnPwatxday=").append(eaitxnPwatxday);
        sb.append(", eaitxnChafeeType=").append(eaitxnChafeeType);
        sb.append(", eaitxnFaxfee=").append(eaitxnFaxfee);
        sb.append(", eaitxnTransfee=").append(eaitxnTransfee);
        sb.append(", eaitxnTransoutcust=").append(eaitxnTransoutcust);
        sb.append(", eaitxnTaxBranch=").append(eaitxnTaxBranch);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EAITXN
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<EAITXN_TX_DATE>").append(this.eaitxnTxDate).append("</EAITXN_TX_DATE>");
        sb.append("<EAITXN_EJFNO>").append(this.eaitxnEjfno).append("</EAITXN_EJFNO>");
        sb.append("<EAITXN_STAN>").append(this.eaitxnStan).append("</EAITXN_STAN>");
        sb.append("<EAITXN_MSGID>").append(this.eaitxnMsgid).append("</EAITXN_MSGID>");
        sb.append("<EAITXN_TX_TIME>").append(this.eaitxnTxTime).append("</EAITXN_TX_TIME>");
        sb.append("<EAITXN_SERV>").append(this.eaitxnServ).append("</EAITXN_SERV>");
        sb.append("<EAITXN_TD>").append(this.eaitxnTd).append("</EAITXN_TD>");
        sb.append("<EAITXN_AP>").append(this.eaitxnAp).append("</EAITXN_AP>");
        sb.append("<EAITXN_IDNO>").append(this.eaitxnIdno).append("</EAITXN_IDNO>");
        sb.append("<EAITXN_OUTRTC>").append(this.eaitxnOutrtc).append("</EAITXN_OUTRTC>");
        sb.append("<EAITXN_OUTBILL>").append(this.eaitxnOutbill).append("</EAITXN_OUTBILL>");
        sb.append("<EAITXN_ACCDATE>").append(this.eaitxnAccdate).append("</EAITXN_ACCDATE>");
        sb.append("<EAITXN_TRNSFROUTIDNO>").append(this.eaitxnTrnsfroutidno).append("</EAITXN_TRNSFROUTIDNO>");
        sb.append("<EAITXN_TRNSFROUTBANK>").append(this.eaitxnTrnsfroutbank).append("</EAITXN_TRNSFROUTBANK>");
        sb.append("<EAITXN_TRNSFROUTACCNT>").append(this.eaitxnTrnsfroutaccnt).append("</EAITXN_TRNSFROUTACCNT>");
        sb.append("<EAITXN_TRNSFRINIDNO>").append(this.eaitxnTrnsfrinidno).append("</EAITXN_TRNSFRINIDNO>");
        sb.append("<EAITXN_TRNSFRINBANK>").append(this.eaitxnTrnsfrinbank).append("</EAITXN_TRNSFRINBANK>");
        sb.append("<EAITXN_TRNSFRINACCNT>").append(this.eaitxnTrnsfrinaccnt).append("</EAITXN_TRNSFRINACCNT>");
        sb.append("<EAITXN_TX_AMT>").append(this.eaitxnTxAmt).append("</EAITXN_TX_AMT>");
        sb.append("<EAITXN_FEEPAYMENTTYPE>").append(this.eaitxnFeepaymenttype).append("</EAITXN_FEEPAYMENTTYPE>");
        sb.append("<EAITXN_CUSTPAY_FEE>").append(this.eaitxnCustpayFee).append("</EAITXN_CUSTPAY_FEE>");
        sb.append("<EAITXN_FISC_FEE>").append(this.eaitxnFiscFee).append("</EAITXN_FISC_FEE>");
        sb.append("<EAITXN_OTHERBANK_FEE>").append(this.eaitxnOtherbankFee).append("</EAITXN_OTHERBANK_FEE>");
        sb.append("<EAITXN_CHAFEE_BRANCH>").append(this.eaitxnChafeeBranch).append("</EAITXN_CHAFEE_BRANCH>");
        sb.append("<EAITXN_CHAFEE_AMT>").append(this.eaitxnChafeeAmt).append("</EAITXN_CHAFEE_AMT>");
        sb.append("<EAITXN_TRANSAMTOUT>").append(this.eaitxnTransamtout).append("</EAITXN_TRANSAMTOUT>");
        sb.append("<EAITXN_TRANSFROUTBAL>").append(this.eaitxnTransfroutbal).append("</EAITXN_TRANSFROUTBAL>");
        sb.append("<EAITXN_TRANSAMTIN>").append(this.eaitxnTransamtin).append("</EAITXN_TRANSAMTIN>");
        sb.append("<EAITXN_CLEANBRANCH_OUT>").append(this.eaitxnCleanbranchOut).append("</EAITXN_CLEANBRANCH_OUT>");
        sb.append("<EAITXN_CLEANBRANCH_IN>").append(this.eaitxnCleanbranchIn).append("</EAITXN_CLEANBRANCH_IN>");
        sb.append("<EAITXN_RECEIVENAME>").append(this.eaitxnReceivename).append("</EAITXN_RECEIVENAME>");
        sb.append("<EAITXN_PAYERNOTE>").append(this.eaitxnPayernote).append("</EAITXN_PAYERNOTE>");
        sb.append("<EAITXN_TRNSFRINNAME>").append(this.eaitxnTrnsfrinname).append("</EAITXN_TRNSFRINNAME>");
        sb.append("<EAITXN_TRNSFROUTNAME>").append(this.eaitxnTrnsfroutname).append("</EAITXN_TRNSFROUTNAME>");
        sb.append("<EAITXN_PAYEREMAIL>").append(this.eaitxnPayeremail).append("</EAITXN_PAYEREMAIL>");
        sb.append("<EAITXN_PWATXDAY>").append(this.eaitxnPwatxday).append("</EAITXN_PWATXDAY>");
        sb.append("<EAITXN_CHAFEE_TYPE>").append(this.eaitxnChafeeType).append("</EAITXN_CHAFEE_TYPE>");
        sb.append("<EAITXN_FAXFEE>").append(this.eaitxnFaxfee).append("</EAITXN_FAXFEE>");
        sb.append("<EAITXN_TRANSFEE>").append(this.eaitxnTransfee).append("</EAITXN_TRANSFEE>");
        sb.append("<EAITXN_TRANSOUTCUST>").append(this.eaitxnTransoutcust).append("</EAITXN_TRANSOUTCUST>");
        sb.append("<EAITXN_TAX_BRANCH>").append(this.eaitxnTaxBranch).append("</EAITXN_TAX_BRANCH>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        return sb.toString();
    }
}