package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class Fcrmtot extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_TXDATE
     *
     * @mbg.generated
     */
    private String fcrmtotTxdate = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_BRNO
     *
     * @mbg.generated
     */
    private String fcrmtotBrno = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_CURRENCY
     *
     * @mbg.generated
     */
    private String fcrmtotCurrency = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_REG_COUNT
     *
     * @mbg.generated
     */
    private Integer fcrmtotRegCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_REG_AMT
     *
     * @mbg.generated
     */
    private BigDecimal fcrmtotRegAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_FISC_OUT_COUNT
     *
     * @mbg.generated
     */
    private Integer fcrmtotFiscOutCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_FISC_OUT_AMT
     *
     * @mbg.generated
     */
    private BigDecimal fcrmtotFiscOutAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_CBS_OUT_COUNT
     *
     * @mbg.generated
     */
    private Integer fcrmtotCbsOutCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_CBS_OUT_AMT
     *
     * @mbg.generated
     */
    private BigDecimal fcrmtotCbsOutAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_FISC_IN_COUNT
     *
     * @mbg.generated
     */
    private Integer fcrmtotFiscInCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_FISC_IN_AMT
     *
     * @mbg.generated
     */
    private BigDecimal fcrmtotFiscInAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_CBS_IN_COUNT
     *
     * @mbg.generated
     */
    private Integer fcrmtotCbsInCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.FCRMTOT_CBS_IN_AMT
     *
     * @mbg.generated
     */
    private BigDecimal fcrmtotCbsInAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCRMTOT.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FCRMTOT
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCRMTOT
     *
     * @mbg.generated
     */
    public Fcrmtot(String fcrmtotTxdate, String fcrmtotBrno, String fcrmtotCurrency, Integer fcrmtotRegCount, BigDecimal fcrmtotRegAmt, Integer fcrmtotFiscOutCount, BigDecimal fcrmtotFiscOutAmt, Integer fcrmtotCbsOutCount, BigDecimal fcrmtotCbsOutAmt, Integer fcrmtotFiscInCount, BigDecimal fcrmtotFiscInAmt, Integer fcrmtotCbsInCount, BigDecimal fcrmtotCbsInAmt, Integer updateUserid, Date updateTime) {
        this.fcrmtotTxdate = fcrmtotTxdate;
        this.fcrmtotBrno = fcrmtotBrno;
        this.fcrmtotCurrency = fcrmtotCurrency;
        this.fcrmtotRegCount = fcrmtotRegCount;
        this.fcrmtotRegAmt = fcrmtotRegAmt;
        this.fcrmtotFiscOutCount = fcrmtotFiscOutCount;
        this.fcrmtotFiscOutAmt = fcrmtotFiscOutAmt;
        this.fcrmtotCbsOutCount = fcrmtotCbsOutCount;
        this.fcrmtotCbsOutAmt = fcrmtotCbsOutAmt;
        this.fcrmtotFiscInCount = fcrmtotFiscInCount;
        this.fcrmtotFiscInAmt = fcrmtotFiscInAmt;
        this.fcrmtotCbsInCount = fcrmtotCbsInCount;
        this.fcrmtotCbsInAmt = fcrmtotCbsInAmt;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCRMTOT
     *
     * @mbg.generated
     */
    public Fcrmtot() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_TXDATE
     *
     * @return the value of FCRMTOT.FCRMTOT_TXDATE
     *
     * @mbg.generated
     */
    public String getFcrmtotTxdate() {
        return fcrmtotTxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_TXDATE
     *
     * @param fcrmtotTxdate the value for FCRMTOT.FCRMTOT_TXDATE
     *
     * @mbg.generated
     */
    public void setFcrmtotTxdate(String fcrmtotTxdate) {
        this.fcrmtotTxdate = fcrmtotTxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_BRNO
     *
     * @return the value of FCRMTOT.FCRMTOT_BRNO
     *
     * @mbg.generated
     */
    public String getFcrmtotBrno() {
        return fcrmtotBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_BRNO
     *
     * @param fcrmtotBrno the value for FCRMTOT.FCRMTOT_BRNO
     *
     * @mbg.generated
     */
    public void setFcrmtotBrno(String fcrmtotBrno) {
        this.fcrmtotBrno = fcrmtotBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_CURRENCY
     *
     * @return the value of FCRMTOT.FCRMTOT_CURRENCY
     *
     * @mbg.generated
     */
    public String getFcrmtotCurrency() {
        return fcrmtotCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_CURRENCY
     *
     * @param fcrmtotCurrency the value for FCRMTOT.FCRMTOT_CURRENCY
     *
     * @mbg.generated
     */
    public void setFcrmtotCurrency(String fcrmtotCurrency) {
        this.fcrmtotCurrency = fcrmtotCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_REG_COUNT
     *
     * @return the value of FCRMTOT.FCRMTOT_REG_COUNT
     *
     * @mbg.generated
     */
    public Integer getFcrmtotRegCount() {
        return fcrmtotRegCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_REG_COUNT
     *
     * @param fcrmtotRegCount the value for FCRMTOT.FCRMTOT_REG_COUNT
     *
     * @mbg.generated
     */
    public void setFcrmtotRegCount(Integer fcrmtotRegCount) {
        this.fcrmtotRegCount = fcrmtotRegCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_REG_AMT
     *
     * @return the value of FCRMTOT.FCRMTOT_REG_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getFcrmtotRegAmt() {
        return fcrmtotRegAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_REG_AMT
     *
     * @param fcrmtotRegAmt the value for FCRMTOT.FCRMTOT_REG_AMT
     *
     * @mbg.generated
     */
    public void setFcrmtotRegAmt(BigDecimal fcrmtotRegAmt) {
        this.fcrmtotRegAmt = fcrmtotRegAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_FISC_OUT_COUNT
     *
     * @return the value of FCRMTOT.FCRMTOT_FISC_OUT_COUNT
     *
     * @mbg.generated
     */
    public Integer getFcrmtotFiscOutCount() {
        return fcrmtotFiscOutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_FISC_OUT_COUNT
     *
     * @param fcrmtotFiscOutCount the value for FCRMTOT.FCRMTOT_FISC_OUT_COUNT
     *
     * @mbg.generated
     */
    public void setFcrmtotFiscOutCount(Integer fcrmtotFiscOutCount) {
        this.fcrmtotFiscOutCount = fcrmtotFiscOutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_FISC_OUT_AMT
     *
     * @return the value of FCRMTOT.FCRMTOT_FISC_OUT_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getFcrmtotFiscOutAmt() {
        return fcrmtotFiscOutAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_FISC_OUT_AMT
     *
     * @param fcrmtotFiscOutAmt the value for FCRMTOT.FCRMTOT_FISC_OUT_AMT
     *
     * @mbg.generated
     */
    public void setFcrmtotFiscOutAmt(BigDecimal fcrmtotFiscOutAmt) {
        this.fcrmtotFiscOutAmt = fcrmtotFiscOutAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_CBS_OUT_COUNT
     *
     * @return the value of FCRMTOT.FCRMTOT_CBS_OUT_COUNT
     *
     * @mbg.generated
     */
    public Integer getFcrmtotCbsOutCount() {
        return fcrmtotCbsOutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_CBS_OUT_COUNT
     *
     * @param fcrmtotCbsOutCount the value for FCRMTOT.FCRMTOT_CBS_OUT_COUNT
     *
     * @mbg.generated
     */
    public void setFcrmtotCbsOutCount(Integer fcrmtotCbsOutCount) {
        this.fcrmtotCbsOutCount = fcrmtotCbsOutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_CBS_OUT_AMT
     *
     * @return the value of FCRMTOT.FCRMTOT_CBS_OUT_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getFcrmtotCbsOutAmt() {
        return fcrmtotCbsOutAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_CBS_OUT_AMT
     *
     * @param fcrmtotCbsOutAmt the value for FCRMTOT.FCRMTOT_CBS_OUT_AMT
     *
     * @mbg.generated
     */
    public void setFcrmtotCbsOutAmt(BigDecimal fcrmtotCbsOutAmt) {
        this.fcrmtotCbsOutAmt = fcrmtotCbsOutAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_FISC_IN_COUNT
     *
     * @return the value of FCRMTOT.FCRMTOT_FISC_IN_COUNT
     *
     * @mbg.generated
     */
    public Integer getFcrmtotFiscInCount() {
        return fcrmtotFiscInCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_FISC_IN_COUNT
     *
     * @param fcrmtotFiscInCount the value for FCRMTOT.FCRMTOT_FISC_IN_COUNT
     *
     * @mbg.generated
     */
    public void setFcrmtotFiscInCount(Integer fcrmtotFiscInCount) {
        this.fcrmtotFiscInCount = fcrmtotFiscInCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_FISC_IN_AMT
     *
     * @return the value of FCRMTOT.FCRMTOT_FISC_IN_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getFcrmtotFiscInAmt() {
        return fcrmtotFiscInAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_FISC_IN_AMT
     *
     * @param fcrmtotFiscInAmt the value for FCRMTOT.FCRMTOT_FISC_IN_AMT
     *
     * @mbg.generated
     */
    public void setFcrmtotFiscInAmt(BigDecimal fcrmtotFiscInAmt) {
        this.fcrmtotFiscInAmt = fcrmtotFiscInAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_CBS_IN_COUNT
     *
     * @return the value of FCRMTOT.FCRMTOT_CBS_IN_COUNT
     *
     * @mbg.generated
     */
    public Integer getFcrmtotCbsInCount() {
        return fcrmtotCbsInCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_CBS_IN_COUNT
     *
     * @param fcrmtotCbsInCount the value for FCRMTOT.FCRMTOT_CBS_IN_COUNT
     *
     * @mbg.generated
     */
    public void setFcrmtotCbsInCount(Integer fcrmtotCbsInCount) {
        this.fcrmtotCbsInCount = fcrmtotCbsInCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.FCRMTOT_CBS_IN_AMT
     *
     * @return the value of FCRMTOT.FCRMTOT_CBS_IN_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getFcrmtotCbsInAmt() {
        return fcrmtotCbsInAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.FCRMTOT_CBS_IN_AMT
     *
     * @param fcrmtotCbsInAmt the value for FCRMTOT.FCRMTOT_CBS_IN_AMT
     *
     * @mbg.generated
     */
    public void setFcrmtotCbsInAmt(BigDecimal fcrmtotCbsInAmt) {
        this.fcrmtotCbsInAmt = fcrmtotCbsInAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.UPDATE_USERID
     *
     * @return the value of FCRMTOT.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.UPDATE_USERID
     *
     * @param updateUserid the value for FCRMTOT.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCRMTOT.UPDATE_TIME
     *
     * @return the value of FCRMTOT.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCRMTOT.UPDATE_TIME
     *
     * @param updateTime the value for FCRMTOT.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCRMTOT
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Fcrmtot other = (Fcrmtot) that;
        return (this.getFcrmtotTxdate() == null ? other.getFcrmtotTxdate() == null : this.getFcrmtotTxdate().equals(other.getFcrmtotTxdate()))
            && (this.getFcrmtotBrno() == null ? other.getFcrmtotBrno() == null : this.getFcrmtotBrno().equals(other.getFcrmtotBrno()))
            && (this.getFcrmtotCurrency() == null ? other.getFcrmtotCurrency() == null : this.getFcrmtotCurrency().equals(other.getFcrmtotCurrency()))
            && (this.getFcrmtotRegCount() == null ? other.getFcrmtotRegCount() == null : this.getFcrmtotRegCount().equals(other.getFcrmtotRegCount()))
            && (this.getFcrmtotRegAmt() == null ? other.getFcrmtotRegAmt() == null : this.getFcrmtotRegAmt().equals(other.getFcrmtotRegAmt()))
            && (this.getFcrmtotFiscOutCount() == null ? other.getFcrmtotFiscOutCount() == null : this.getFcrmtotFiscOutCount().equals(other.getFcrmtotFiscOutCount()))
            && (this.getFcrmtotFiscOutAmt() == null ? other.getFcrmtotFiscOutAmt() == null : this.getFcrmtotFiscOutAmt().equals(other.getFcrmtotFiscOutAmt()))
            && (this.getFcrmtotCbsOutCount() == null ? other.getFcrmtotCbsOutCount() == null : this.getFcrmtotCbsOutCount().equals(other.getFcrmtotCbsOutCount()))
            && (this.getFcrmtotCbsOutAmt() == null ? other.getFcrmtotCbsOutAmt() == null : this.getFcrmtotCbsOutAmt().equals(other.getFcrmtotCbsOutAmt()))
            && (this.getFcrmtotFiscInCount() == null ? other.getFcrmtotFiscInCount() == null : this.getFcrmtotFiscInCount().equals(other.getFcrmtotFiscInCount()))
            && (this.getFcrmtotFiscInAmt() == null ? other.getFcrmtotFiscInAmt() == null : this.getFcrmtotFiscInAmt().equals(other.getFcrmtotFiscInAmt()))
            && (this.getFcrmtotCbsInCount() == null ? other.getFcrmtotCbsInCount() == null : this.getFcrmtotCbsInCount().equals(other.getFcrmtotCbsInCount()))
            && (this.getFcrmtotCbsInAmt() == null ? other.getFcrmtotCbsInAmt() == null : this.getFcrmtotCbsInAmt().equals(other.getFcrmtotCbsInAmt()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCRMTOT
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFcrmtotTxdate() == null) ? 0 : getFcrmtotTxdate().hashCode());
        result = prime * result + ((getFcrmtotBrno() == null) ? 0 : getFcrmtotBrno().hashCode());
        result = prime * result + ((getFcrmtotCurrency() == null) ? 0 : getFcrmtotCurrency().hashCode());
        result = prime * result + ((getFcrmtotRegCount() == null) ? 0 : getFcrmtotRegCount().hashCode());
        result = prime * result + ((getFcrmtotRegAmt() == null) ? 0 : getFcrmtotRegAmt().hashCode());
        result = prime * result + ((getFcrmtotFiscOutCount() == null) ? 0 : getFcrmtotFiscOutCount().hashCode());
        result = prime * result + ((getFcrmtotFiscOutAmt() == null) ? 0 : getFcrmtotFiscOutAmt().hashCode());
        result = prime * result + ((getFcrmtotCbsOutCount() == null) ? 0 : getFcrmtotCbsOutCount().hashCode());
        result = prime * result + ((getFcrmtotCbsOutAmt() == null) ? 0 : getFcrmtotCbsOutAmt().hashCode());
        result = prime * result + ((getFcrmtotFiscInCount() == null) ? 0 : getFcrmtotFiscInCount().hashCode());
        result = prime * result + ((getFcrmtotFiscInAmt() == null) ? 0 : getFcrmtotFiscInAmt().hashCode());
        result = prime * result + ((getFcrmtotCbsInCount() == null) ? 0 : getFcrmtotCbsInCount().hashCode());
        result = prime * result + ((getFcrmtotCbsInAmt() == null) ? 0 : getFcrmtotCbsInAmt().hashCode());
        result = prime * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCRMTOT
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fcrmtotTxdate=").append(fcrmtotTxdate);
        sb.append(", fcrmtotBrno=").append(fcrmtotBrno);
        sb.append(", fcrmtotCurrency=").append(fcrmtotCurrency);
        sb.append(", fcrmtotRegCount=").append(fcrmtotRegCount);
        sb.append(", fcrmtotRegAmt=").append(fcrmtotRegAmt);
        sb.append(", fcrmtotFiscOutCount=").append(fcrmtotFiscOutCount);
        sb.append(", fcrmtotFiscOutAmt=").append(fcrmtotFiscOutAmt);
        sb.append(", fcrmtotCbsOutCount=").append(fcrmtotCbsOutCount);
        sb.append(", fcrmtotCbsOutAmt=").append(fcrmtotCbsOutAmt);
        sb.append(", fcrmtotFiscInCount=").append(fcrmtotFiscInCount);
        sb.append(", fcrmtotFiscInAmt=").append(fcrmtotFiscInAmt);
        sb.append(", fcrmtotCbsInCount=").append(fcrmtotCbsInCount);
        sb.append(", fcrmtotCbsInAmt=").append(fcrmtotCbsInAmt);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCRMTOT
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<FCRMTOT_TXDATE>").append(this.fcrmtotTxdate).append("</FCRMTOT_TXDATE>");
        sb.append("<FCRMTOT_BRNO>").append(this.fcrmtotBrno).append("</FCRMTOT_BRNO>");
        sb.append("<FCRMTOT_CURRENCY>").append(this.fcrmtotCurrency).append("</FCRMTOT_CURRENCY>");
        sb.append("<FCRMTOT_REG_COUNT>").append(this.fcrmtotRegCount).append("</FCRMTOT_REG_COUNT>");
        sb.append("<FCRMTOT_REG_AMT>").append(this.fcrmtotRegAmt).append("</FCRMTOT_REG_AMT>");
        sb.append("<FCRMTOT_FISC_OUT_COUNT>").append(this.fcrmtotFiscOutCount).append("</FCRMTOT_FISC_OUT_COUNT>");
        sb.append("<FCRMTOT_FISC_OUT_AMT>").append(this.fcrmtotFiscOutAmt).append("</FCRMTOT_FISC_OUT_AMT>");
        sb.append("<FCRMTOT_CBS_OUT_COUNT>").append(this.fcrmtotCbsOutCount).append("</FCRMTOT_CBS_OUT_COUNT>");
        sb.append("<FCRMTOT_CBS_OUT_AMT>").append(this.fcrmtotCbsOutAmt).append("</FCRMTOT_CBS_OUT_AMT>");
        sb.append("<FCRMTOT_FISC_IN_COUNT>").append(this.fcrmtotFiscInCount).append("</FCRMTOT_FISC_IN_COUNT>");
        sb.append("<FCRMTOT_FISC_IN_AMT>").append(this.fcrmtotFiscInAmt).append("</FCRMTOT_FISC_IN_AMT>");
        sb.append("<FCRMTOT_CBS_IN_COUNT>").append(this.fcrmtotCbsInCount).append("</FCRMTOT_CBS_IN_COUNT>");
        sb.append("<FCRMTOT_CBS_IN_AMT>").append(this.fcrmtotCbsInAmt).append("</FCRMTOT_CBS_IN_AMT>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        return sb.toString();
    }
}