package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class Guard extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.GUARD_NO
     *
     * @mbg.generated
     */
    private String guardNo = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.GUARD_NAME
     *
     * @mbg.generated
     */
    private String guardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.GUARD_NAME_S
     *
     * @mbg.generated
     */
    private String guardNameS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.GUARD_TEL
     *
     * @mbg.generated
     */
    private String guardTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.GUARD_FAX
     *
     * @mbg.generated
     */
    private String guardFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.GUARD_ADDRESS
     *
     * @mbg.generated
     */
    private String guardAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.GUARD_CONTACT
     *
     * @mbg.generated
     */
    private String guardContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.GUARD_CONTACT_TEL
     *
     * @mbg.generated
     */
    private String guardContactTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.GUARD_CONTACT_MOBIL
     *
     * @mbg.generated
     */
    private String guardContactMobil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GUARD.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GUARD
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUARD
     *
     * @mbg.generated
     */
    public Guard(String guardNo, String guardName, String guardNameS, String guardTel, String guardFax, String guardAddress, String guardContact, String guardContactTel, String guardContactMobil, Integer updateUserid, Date updateTime) {
        this.guardNo = guardNo;
        this.guardName = guardName;
        this.guardNameS = guardNameS;
        this.guardTel = guardTel;
        this.guardFax = guardFax;
        this.guardAddress = guardAddress;
        this.guardContact = guardContact;
        this.guardContactTel = guardContactTel;
        this.guardContactMobil = guardContactMobil;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUARD
     *
     * @mbg.generated
     */
    public Guard() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.GUARD_NO
     *
     * @return the value of GUARD.GUARD_NO
     *
     * @mbg.generated
     */
    public String getGuardNo() {
        return guardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.GUARD_NO
     *
     * @param guardNo the value for GUARD.GUARD_NO
     *
     * @mbg.generated
     */
    public void setGuardNo(String guardNo) {
        this.guardNo = guardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.GUARD_NAME
     *
     * @return the value of GUARD.GUARD_NAME
     *
     * @mbg.generated
     */
    public String getGuardName() {
        return guardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.GUARD_NAME
     *
     * @param guardName the value for GUARD.GUARD_NAME
     *
     * @mbg.generated
     */
    public void setGuardName(String guardName) {
        this.guardName = guardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.GUARD_NAME_S
     *
     * @return the value of GUARD.GUARD_NAME_S
     *
     * @mbg.generated
     */
    public String getGuardNameS() {
        return guardNameS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.GUARD_NAME_S
     *
     * @param guardNameS the value for GUARD.GUARD_NAME_S
     *
     * @mbg.generated
     */
    public void setGuardNameS(String guardNameS) {
        this.guardNameS = guardNameS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.GUARD_TEL
     *
     * @return the value of GUARD.GUARD_TEL
     *
     * @mbg.generated
     */
    public String getGuardTel() {
        return guardTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.GUARD_TEL
     *
     * @param guardTel the value for GUARD.GUARD_TEL
     *
     * @mbg.generated
     */
    public void setGuardTel(String guardTel) {
        this.guardTel = guardTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.GUARD_FAX
     *
     * @return the value of GUARD.GUARD_FAX
     *
     * @mbg.generated
     */
    public String getGuardFax() {
        return guardFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.GUARD_FAX
     *
     * @param guardFax the value for GUARD.GUARD_FAX
     *
     * @mbg.generated
     */
    public void setGuardFax(String guardFax) {
        this.guardFax = guardFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.GUARD_ADDRESS
     *
     * @return the value of GUARD.GUARD_ADDRESS
     *
     * @mbg.generated
     */
    public String getGuardAddress() {
        return guardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.GUARD_ADDRESS
     *
     * @param guardAddress the value for GUARD.GUARD_ADDRESS
     *
     * @mbg.generated
     */
    public void setGuardAddress(String guardAddress) {
        this.guardAddress = guardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.GUARD_CONTACT
     *
     * @return the value of GUARD.GUARD_CONTACT
     *
     * @mbg.generated
     */
    public String getGuardContact() {
        return guardContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.GUARD_CONTACT
     *
     * @param guardContact the value for GUARD.GUARD_CONTACT
     *
     * @mbg.generated
     */
    public void setGuardContact(String guardContact) {
        this.guardContact = guardContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.GUARD_CONTACT_TEL
     *
     * @return the value of GUARD.GUARD_CONTACT_TEL
     *
     * @mbg.generated
     */
    public String getGuardContactTel() {
        return guardContactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.GUARD_CONTACT_TEL
     *
     * @param guardContactTel the value for GUARD.GUARD_CONTACT_TEL
     *
     * @mbg.generated
     */
    public void setGuardContactTel(String guardContactTel) {
        this.guardContactTel = guardContactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.GUARD_CONTACT_MOBIL
     *
     * @return the value of GUARD.GUARD_CONTACT_MOBIL
     *
     * @mbg.generated
     */
    public String getGuardContactMobil() {
        return guardContactMobil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.GUARD_CONTACT_MOBIL
     *
     * @param guardContactMobil the value for GUARD.GUARD_CONTACT_MOBIL
     *
     * @mbg.generated
     */
    public void setGuardContactMobil(String guardContactMobil) {
        this.guardContactMobil = guardContactMobil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.UPDATE_USERID
     *
     * @return the value of GUARD.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.UPDATE_USERID
     *
     * @param updateUserid the value for GUARD.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GUARD.UPDATE_TIME
     *
     * @return the value of GUARD.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GUARD.UPDATE_TIME
     *
     * @param updateTime the value for GUARD.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUARD
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", guardNo=").append(guardNo);
        sb.append(", guardName=").append(guardName);
        sb.append(", guardNameS=").append(guardNameS);
        sb.append(", guardTel=").append(guardTel);
        sb.append(", guardFax=").append(guardFax);
        sb.append(", guardAddress=").append(guardAddress);
        sb.append(", guardContact=").append(guardContact);
        sb.append(", guardContactTel=").append(guardContactTel);
        sb.append(", guardContactMobil=").append(guardContactMobil);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUARD
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Guard other = (Guard) that;
        return (this.getGuardNo() == null ? other.getGuardNo() == null : this.getGuardNo().equals(other.getGuardNo()))
            && (this.getGuardName() == null ? other.getGuardName() == null : this.getGuardName().equals(other.getGuardName()))
            && (this.getGuardNameS() == null ? other.getGuardNameS() == null : this.getGuardNameS().equals(other.getGuardNameS()))
            && (this.getGuardTel() == null ? other.getGuardTel() == null : this.getGuardTel().equals(other.getGuardTel()))
            && (this.getGuardFax() == null ? other.getGuardFax() == null : this.getGuardFax().equals(other.getGuardFax()))
            && (this.getGuardAddress() == null ? other.getGuardAddress() == null : this.getGuardAddress().equals(other.getGuardAddress()))
            && (this.getGuardContact() == null ? other.getGuardContact() == null : this.getGuardContact().equals(other.getGuardContact()))
            && (this.getGuardContactTel() == null ? other.getGuardContactTel() == null : this.getGuardContactTel().equals(other.getGuardContactTel()))
            && (this.getGuardContactMobil() == null ? other.getGuardContactMobil() == null : this.getGuardContactMobil().equals(other.getGuardContactMobil()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUARD
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getGuardNo() == null) ? 0 : getGuardNo().hashCode());
        result = 31 * result + ((getGuardName() == null) ? 0 : getGuardName().hashCode());
        result = 31 * result + ((getGuardNameS() == null) ? 0 : getGuardNameS().hashCode());
        result = 31 * result + ((getGuardTel() == null) ? 0 : getGuardTel().hashCode());
        result = 31 * result + ((getGuardFax() == null) ? 0 : getGuardFax().hashCode());
        result = 31 * result + ((getGuardAddress() == null) ? 0 : getGuardAddress().hashCode());
        result = 31 * result + ((getGuardContact() == null) ? 0 : getGuardContact().hashCode());
        result = 31 * result + ((getGuardContactTel() == null) ? 0 : getGuardContactTel().hashCode());
        result = 31 * result + ((getGuardContactMobil() == null) ? 0 : getGuardContactMobil().hashCode());
        result = 31 * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = 31 * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GUARD
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<GUARD_NO>").append(this.guardNo).append("</GUARD_NO>");
        sb.append("<GUARD_NAME>").append(this.guardName).append("</GUARD_NAME>");
        sb.append("<GUARD_NAME_S>").append(this.guardNameS).append("</GUARD_NAME_S>");
        sb.append("<GUARD_TEL>").append(this.guardTel).append("</GUARD_TEL>");
        sb.append("<GUARD_FAX>").append(this.guardFax).append("</GUARD_FAX>");
        sb.append("<GUARD_ADDRESS>").append(this.guardAddress).append("</GUARD_ADDRESS>");
        sb.append("<GUARD_CONTACT>").append(this.guardContact).append("</GUARD_CONTACT>");
        sb.append("<GUARD_CONTACT_TEL>").append(this.guardContactTel).append("</GUARD_CONTACT_TEL>");
        sb.append("<GUARD_CONTACT_MOBIL>").append(this.guardContactMobil).append("</GUARD_CONTACT_MOBIL>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        return sb.toString();
    }
}