package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class History extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_SEQ
     *
     * @mbg.generated
     */
    private Long historySeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_INSTANCEID
     *
     * @mbg.generated
     */
    private String historyInstanceid = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_BATCHID
     *
     * @mbg.generated
     */
    private Integer historyBatchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_JOBID
     *
     * @mbg.generated
     */
    private Integer historyJobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_TASKID
     *
     * @mbg.generated
     */
    private Integer historyTaskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_STEPID
     *
     * @mbg.generated
     */
    private Integer historyStepid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_MESSAGE
     *
     * @mbg.generated
     */
    private String historyMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_STATUS
     *
     * @mbg.generated
     */
    private String historyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_STARTTIME
     *
     * @mbg.generated
     */
    private Date historyStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_TASKBEGINTIME
     *
     * @mbg.generated
     */
    private Date historyTaskbegintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_TASKENDTIME
     *
     * @mbg.generated
     */
    private Date historyTaskendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_DURATION
     *
     * @mbg.generated
     */
    private Integer historyDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_LOGFILE
     *
     * @mbg.generated
     */
    private String historyLogfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_RUNHOST
     *
     * @mbg.generated
     */
    private String historyRunhost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_LOGFILECONTENT
     *
     * @mbg.generated
     */
    private String historyLogfilecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HISTORY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbg.generated
     */
    public History(Long historySeq, String historyInstanceid, Integer historyBatchid, Integer historyJobid, Integer historyTaskid, Integer historyStepid, String historyMessage, String historyStatus, Date historyStarttime, Date historyTaskbegintime, Date historyTaskendtime, Integer historyDuration, String historyLogfile, String historyRunhost) {
        this.historySeq = historySeq;
        this.historyInstanceid = historyInstanceid;
        this.historyBatchid = historyBatchid;
        this.historyJobid = historyJobid;
        this.historyTaskid = historyTaskid;
        this.historyStepid = historyStepid;
        this.historyMessage = historyMessage;
        this.historyStatus = historyStatus;
        this.historyStarttime = historyStarttime;
        this.historyTaskbegintime = historyTaskbegintime;
        this.historyTaskendtime = historyTaskendtime;
        this.historyDuration = historyDuration;
        this.historyLogfile = historyLogfile;
        this.historyRunhost = historyRunhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbg.generated
     */
    public History(Long historySeq, String historyInstanceid, Integer historyBatchid, Integer historyJobid, Integer historyTaskid, Integer historyStepid, String historyMessage, String historyStatus, Date historyStarttime, Date historyTaskbegintime, Date historyTaskendtime, Integer historyDuration, String historyLogfile, String historyRunhost, String historyLogfilecontent) {
        this.historySeq = historySeq;
        this.historyInstanceid = historyInstanceid;
        this.historyBatchid = historyBatchid;
        this.historyJobid = historyJobid;
        this.historyTaskid = historyTaskid;
        this.historyStepid = historyStepid;
        this.historyMessage = historyMessage;
        this.historyStatus = historyStatus;
        this.historyStarttime = historyStarttime;
        this.historyTaskbegintime = historyTaskbegintime;
        this.historyTaskendtime = historyTaskendtime;
        this.historyDuration = historyDuration;
        this.historyLogfile = historyLogfile;
        this.historyRunhost = historyRunhost;
        this.historyLogfilecontent = historyLogfilecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbg.generated
     */
    public History() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_SEQ
     *
     * @return the value of HISTORY.HISTORY_SEQ
     *
     * @mbg.generated
     */
    public Long getHistorySeq() {
        return historySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_SEQ
     *
     * @param historySeq the value for HISTORY.HISTORY_SEQ
     *
     * @mbg.generated
     */
    public void setHistorySeq(Long historySeq) {
        this.historySeq = historySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_INSTANCEID
     *
     * @return the value of HISTORY.HISTORY_INSTANCEID
     *
     * @mbg.generated
     */
    public String getHistoryInstanceid() {
        return historyInstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_INSTANCEID
     *
     * @param historyInstanceid the value for HISTORY.HISTORY_INSTANCEID
     *
     * @mbg.generated
     */
    public void setHistoryInstanceid(String historyInstanceid) {
        this.historyInstanceid = historyInstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_BATCHID
     *
     * @return the value of HISTORY.HISTORY_BATCHID
     *
     * @mbg.generated
     */
    public Integer getHistoryBatchid() {
        return historyBatchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_BATCHID
     *
     * @param historyBatchid the value for HISTORY.HISTORY_BATCHID
     *
     * @mbg.generated
     */
    public void setHistoryBatchid(Integer historyBatchid) {
        this.historyBatchid = historyBatchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_JOBID
     *
     * @return the value of HISTORY.HISTORY_JOBID
     *
     * @mbg.generated
     */
    public Integer getHistoryJobid() {
        return historyJobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_JOBID
     *
     * @param historyJobid the value for HISTORY.HISTORY_JOBID
     *
     * @mbg.generated
     */
    public void setHistoryJobid(Integer historyJobid) {
        this.historyJobid = historyJobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_TASKID
     *
     * @return the value of HISTORY.HISTORY_TASKID
     *
     * @mbg.generated
     */
    public Integer getHistoryTaskid() {
        return historyTaskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_TASKID
     *
     * @param historyTaskid the value for HISTORY.HISTORY_TASKID
     *
     * @mbg.generated
     */
    public void setHistoryTaskid(Integer historyTaskid) {
        this.historyTaskid = historyTaskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_STEPID
     *
     * @return the value of HISTORY.HISTORY_STEPID
     *
     * @mbg.generated
     */
    public Integer getHistoryStepid() {
        return historyStepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_STEPID
     *
     * @param historyStepid the value for HISTORY.HISTORY_STEPID
     *
     * @mbg.generated
     */
    public void setHistoryStepid(Integer historyStepid) {
        this.historyStepid = historyStepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_MESSAGE
     *
     * @return the value of HISTORY.HISTORY_MESSAGE
     *
     * @mbg.generated
     */
    public String getHistoryMessage() {
        return historyMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_MESSAGE
     *
     * @param historyMessage the value for HISTORY.HISTORY_MESSAGE
     *
     * @mbg.generated
     */
    public void setHistoryMessage(String historyMessage) {
        this.historyMessage = historyMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_STATUS
     *
     * @return the value of HISTORY.HISTORY_STATUS
     *
     * @mbg.generated
     */
    public String getHistoryStatus() {
        return historyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_STATUS
     *
     * @param historyStatus the value for HISTORY.HISTORY_STATUS
     *
     * @mbg.generated
     */
    public void setHistoryStatus(String historyStatus) {
        this.historyStatus = historyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_STARTTIME
     *
     * @return the value of HISTORY.HISTORY_STARTTIME
     *
     * @mbg.generated
     */
    public Date getHistoryStarttime() {
        return historyStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_STARTTIME
     *
     * @param historyStarttime the value for HISTORY.HISTORY_STARTTIME
     *
     * @mbg.generated
     */
    public void setHistoryStarttime(Date historyStarttime) {
        this.historyStarttime = historyStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_TASKBEGINTIME
     *
     * @return the value of HISTORY.HISTORY_TASKBEGINTIME
     *
     * @mbg.generated
     */
    public Date getHistoryTaskbegintime() {
        return historyTaskbegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_TASKBEGINTIME
     *
     * @param historyTaskbegintime the value for HISTORY.HISTORY_TASKBEGINTIME
     *
     * @mbg.generated
     */
    public void setHistoryTaskbegintime(Date historyTaskbegintime) {
        this.historyTaskbegintime = historyTaskbegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_TASKENDTIME
     *
     * @return the value of HISTORY.HISTORY_TASKENDTIME
     *
     * @mbg.generated
     */
    public Date getHistoryTaskendtime() {
        return historyTaskendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_TASKENDTIME
     *
     * @param historyTaskendtime the value for HISTORY.HISTORY_TASKENDTIME
     *
     * @mbg.generated
     */
    public void setHistoryTaskendtime(Date historyTaskendtime) {
        this.historyTaskendtime = historyTaskendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_DURATION
     *
     * @return the value of HISTORY.HISTORY_DURATION
     *
     * @mbg.generated
     */
    public Integer getHistoryDuration() {
        return historyDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_DURATION
     *
     * @param historyDuration the value for HISTORY.HISTORY_DURATION
     *
     * @mbg.generated
     */
    public void setHistoryDuration(Integer historyDuration) {
        this.historyDuration = historyDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_LOGFILE
     *
     * @return the value of HISTORY.HISTORY_LOGFILE
     *
     * @mbg.generated
     */
    public String getHistoryLogfile() {
        return historyLogfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_LOGFILE
     *
     * @param historyLogfile the value for HISTORY.HISTORY_LOGFILE
     *
     * @mbg.generated
     */
    public void setHistoryLogfile(String historyLogfile) {
        this.historyLogfile = historyLogfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_RUNHOST
     *
     * @return the value of HISTORY.HISTORY_RUNHOST
     *
     * @mbg.generated
     */
    public String getHistoryRunhost() {
        return historyRunhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_RUNHOST
     *
     * @param historyRunhost the value for HISTORY.HISTORY_RUNHOST
     *
     * @mbg.generated
     */
    public void setHistoryRunhost(String historyRunhost) {
        this.historyRunhost = historyRunhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_LOGFILECONTENT
     *
     * @return the value of HISTORY.HISTORY_LOGFILECONTENT
     *
     * @mbg.generated
     */
    public String getHistoryLogfilecontent() {
        return historyLogfilecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_LOGFILECONTENT
     *
     * @param historyLogfilecontent the value for HISTORY.HISTORY_LOGFILECONTENT
     *
     * @mbg.generated
     */
    public void setHistoryLogfilecontent(String historyLogfilecontent) {
        this.historyLogfilecontent = historyLogfilecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", historySeq=").append(historySeq);
        sb.append(", historyInstanceid=").append(historyInstanceid);
        sb.append(", historyBatchid=").append(historyBatchid);
        sb.append(", historyJobid=").append(historyJobid);
        sb.append(", historyTaskid=").append(historyTaskid);
        sb.append(", historyStepid=").append(historyStepid);
        sb.append(", historyMessage=").append(historyMessage);
        sb.append(", historyStatus=").append(historyStatus);
        sb.append(", historyStarttime=").append(historyStarttime);
        sb.append(", historyTaskbegintime=").append(historyTaskbegintime);
        sb.append(", historyTaskendtime=").append(historyTaskendtime);
        sb.append(", historyDuration=").append(historyDuration);
        sb.append(", historyLogfile=").append(historyLogfile);
        sb.append(", historyRunhost=").append(historyRunhost);
        sb.append(", historyLogfilecontent=").append(historyLogfilecontent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        History other = (History) that;
        return (this.getHistorySeq() == null ? other.getHistorySeq() == null : this.getHistorySeq().equals(other.getHistorySeq()))
            && (this.getHistoryInstanceid() == null ? other.getHistoryInstanceid() == null : this.getHistoryInstanceid().equals(other.getHistoryInstanceid()))
            && (this.getHistoryBatchid() == null ? other.getHistoryBatchid() == null : this.getHistoryBatchid().equals(other.getHistoryBatchid()))
            && (this.getHistoryJobid() == null ? other.getHistoryJobid() == null : this.getHistoryJobid().equals(other.getHistoryJobid()))
            && (this.getHistoryTaskid() == null ? other.getHistoryTaskid() == null : this.getHistoryTaskid().equals(other.getHistoryTaskid()))
            && (this.getHistoryStepid() == null ? other.getHistoryStepid() == null : this.getHistoryStepid().equals(other.getHistoryStepid()))
            && (this.getHistoryMessage() == null ? other.getHistoryMessage() == null : this.getHistoryMessage().equals(other.getHistoryMessage()))
            && (this.getHistoryStatus() == null ? other.getHistoryStatus() == null : this.getHistoryStatus().equals(other.getHistoryStatus()))
            && (this.getHistoryStarttime() == null ? other.getHistoryStarttime() == null : this.getHistoryStarttime().equals(other.getHistoryStarttime()))
            && (this.getHistoryTaskbegintime() == null ? other.getHistoryTaskbegintime() == null : this.getHistoryTaskbegintime().equals(other.getHistoryTaskbegintime()))
            && (this.getHistoryTaskendtime() == null ? other.getHistoryTaskendtime() == null : this.getHistoryTaskendtime().equals(other.getHistoryTaskendtime()))
            && (this.getHistoryDuration() == null ? other.getHistoryDuration() == null : this.getHistoryDuration().equals(other.getHistoryDuration()))
            && (this.getHistoryLogfile() == null ? other.getHistoryLogfile() == null : this.getHistoryLogfile().equals(other.getHistoryLogfile()))
            && (this.getHistoryRunhost() == null ? other.getHistoryRunhost() == null : this.getHistoryRunhost().equals(other.getHistoryRunhost()))
            && (this.getHistoryLogfilecontent() == null ? other.getHistoryLogfilecontent() == null : this.getHistoryLogfilecontent().equals(other.getHistoryLogfilecontent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getHistorySeq() == null) ? 0 : getHistorySeq().hashCode());
        result = 31 * result + ((getHistoryInstanceid() == null) ? 0 : getHistoryInstanceid().hashCode());
        result = 31 * result + ((getHistoryBatchid() == null) ? 0 : getHistoryBatchid().hashCode());
        result = 31 * result + ((getHistoryJobid() == null) ? 0 : getHistoryJobid().hashCode());
        result = 31 * result + ((getHistoryTaskid() == null) ? 0 : getHistoryTaskid().hashCode());
        result = 31 * result + ((getHistoryStepid() == null) ? 0 : getHistoryStepid().hashCode());
        result = 31 * result + ((getHistoryMessage() == null) ? 0 : getHistoryMessage().hashCode());
        result = 31 * result + ((getHistoryStatus() == null) ? 0 : getHistoryStatus().hashCode());
        result = 31 * result + ((getHistoryStarttime() == null) ? 0 : getHistoryStarttime().hashCode());
        result = 31 * result + ((getHistoryTaskbegintime() == null) ? 0 : getHistoryTaskbegintime().hashCode());
        result = 31 * result + ((getHistoryTaskendtime() == null) ? 0 : getHistoryTaskendtime().hashCode());
        result = 31 * result + ((getHistoryDuration() == null) ? 0 : getHistoryDuration().hashCode());
        result = 31 * result + ((getHistoryLogfile() == null) ? 0 : getHistoryLogfile().hashCode());
        result = 31 * result + ((getHistoryRunhost() == null) ? 0 : getHistoryRunhost().hashCode());
        result = 31 * result + ((getHistoryLogfilecontent() == null) ? 0 : getHistoryLogfilecontent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<HISTORY_SEQ>").append(this.historySeq).append("</HISTORY_SEQ>");
        sb.append("<HISTORY_INSTANCEID>").append(this.historyInstanceid).append("</HISTORY_INSTANCEID>");
        sb.append("<HISTORY_BATCHID>").append(this.historyBatchid).append("</HISTORY_BATCHID>");
        sb.append("<HISTORY_JOBID>").append(this.historyJobid).append("</HISTORY_JOBID>");
        sb.append("<HISTORY_TASKID>").append(this.historyTaskid).append("</HISTORY_TASKID>");
        sb.append("<HISTORY_STEPID>").append(this.historyStepid).append("</HISTORY_STEPID>");
        sb.append("<HISTORY_MESSAGE>").append(this.historyMessage).append("</HISTORY_MESSAGE>");
        sb.append("<HISTORY_STATUS>").append(this.historyStatus).append("</HISTORY_STATUS>");
        sb.append("<HISTORY_STARTTIME>").append(this.historyStarttime).append("</HISTORY_STARTTIME>");
        sb.append("<HISTORY_TASKBEGINTIME>").append(this.historyTaskbegintime).append("</HISTORY_TASKBEGINTIME>");
        sb.append("<HISTORY_TASKENDTIME>").append(this.historyTaskendtime).append("</HISTORY_TASKENDTIME>");
        sb.append("<HISTORY_DURATION>").append(this.historyDuration).append("</HISTORY_DURATION>");
        sb.append("<HISTORY_LOGFILE>").append(this.historyLogfile).append("</HISTORY_LOGFILE>");
        sb.append("<HISTORY_RUNHOST>").append(this.historyRunhost).append("</HISTORY_RUNHOST>");
        sb.append("<HISTORY_LOGFILECONTENT>").append(this.historyLogfilecontent).append("</HISTORY_LOGFILECONTENT>");
        return sb.toString();
    }
}