package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class Rmmon extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMMON.RMMON_HBKNO
     *
     * @mbg.generated
     */
    private String rmmonHbkno = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMMON.RMMON_T24_PENDING_CNT
     *
     * @mbg.generated
     */
    private Short rmmonT24PendingCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMMON.RMMON_FCS_CNT
     *
     * @mbg.generated
     */
    private Short rmmonFcsCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMMON.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMMON.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMMON
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMMON
     *
     * @mbg.generated
     */
    public Rmmon(String rmmonHbkno, Short rmmonT24PendingCnt, Short rmmonFcsCnt, Integer updateUserid, Date updateTime) {
        this.rmmonHbkno = rmmonHbkno;
        this.rmmonT24PendingCnt = rmmonT24PendingCnt;
        this.rmmonFcsCnt = rmmonFcsCnt;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMMON
     *
     * @mbg.generated
     */
    public Rmmon() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMMON.RMMON_HBKNO
     *
     * @return the value of RMMON.RMMON_HBKNO
     *
     * @mbg.generated
     */
    public String getRmmonHbkno() {
        return rmmonHbkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMMON.RMMON_HBKNO
     *
     * @param rmmonHbkno the value for RMMON.RMMON_HBKNO
     *
     * @mbg.generated
     */
    public void setRmmonHbkno(String rmmonHbkno) {
        this.rmmonHbkno = rmmonHbkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMMON.RMMON_T24_PENDING_CNT
     *
     * @return the value of RMMON.RMMON_T24_PENDING_CNT
     *
     * @mbg.generated
     */
    public Short getRmmonT24PendingCnt() {
        return rmmonT24PendingCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMMON.RMMON_T24_PENDING_CNT
     *
     * @param rmmonT24PendingCnt the value for RMMON.RMMON_T24_PENDING_CNT
     *
     * @mbg.generated
     */
    public void setRmmonT24PendingCnt(Short rmmonT24PendingCnt) {
        this.rmmonT24PendingCnt = rmmonT24PendingCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMMON.RMMON_FCS_CNT
     *
     * @return the value of RMMON.RMMON_FCS_CNT
     *
     * @mbg.generated
     */
    public Short getRmmonFcsCnt() {
        return rmmonFcsCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMMON.RMMON_FCS_CNT
     *
     * @param rmmonFcsCnt the value for RMMON.RMMON_FCS_CNT
     *
     * @mbg.generated
     */
    public void setRmmonFcsCnt(Short rmmonFcsCnt) {
        this.rmmonFcsCnt = rmmonFcsCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMMON.UPDATE_USERID
     *
     * @return the value of RMMON.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMMON.UPDATE_USERID
     *
     * @param updateUserid the value for RMMON.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMMON.UPDATE_TIME
     *
     * @return the value of RMMON.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMMON.UPDATE_TIME
     *
     * @param updateTime the value for RMMON.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMMON
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Rmmon other = (Rmmon) that;
        return (this.getRmmonHbkno() == null ? other.getRmmonHbkno() == null : this.getRmmonHbkno().equals(other.getRmmonHbkno()))
            && (this.getRmmonT24PendingCnt() == null ? other.getRmmonT24PendingCnt() == null : this.getRmmonT24PendingCnt().equals(other.getRmmonT24PendingCnt()))
            && (this.getRmmonFcsCnt() == null ? other.getRmmonFcsCnt() == null : this.getRmmonFcsCnt().equals(other.getRmmonFcsCnt()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMMON
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRmmonHbkno() == null) ? 0 : getRmmonHbkno().hashCode());
        result = prime * result + ((getRmmonT24PendingCnt() == null) ? 0 : getRmmonT24PendingCnt().hashCode());
        result = prime * result + ((getRmmonFcsCnt() == null) ? 0 : getRmmonFcsCnt().hashCode());
        result = prime * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMMON
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rmmonHbkno=").append(rmmonHbkno);
        sb.append(", rmmonT24PendingCnt=").append(rmmonT24PendingCnt);
        sb.append(", rmmonFcsCnt=").append(rmmonFcsCnt);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMMON
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<RMMON_HBKNO>").append(this.rmmonHbkno).append("</RMMON_HBKNO>");
        sb.append("<RMMON_T24_PENDING_CNT>").append(this.rmmonT24PendingCnt).append("</RMMON_T24_PENDING_CNT>");
        sb.append("<RMMON_FCS_CNT>").append(this.rmmonFcsCnt).append("</RMMON_FCS_CNT>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        return sb.toString();
    }
}