package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.util.Date;

public class Subsys extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSYS.SUBSYS_SUBSYSNO
     *
     * @mbg.generated
     */
    private Short subsysSubsysno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSYS.SUBSYS_NAME
     *
     * @mbg.generated
     */
    private String subsysName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSYS.SUBSYS_NAME_S
     *
     * @mbg.generated
     */
    private String subsysNameS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSYS.SUBSYS_ENABLE
     *
     * @mbg.generated
     */
    private Short subsysEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSYS.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSYS.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUBSYS
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSYS
     *
     * @mbg.generated
     */
    public Subsys(Short subsysSubsysno, String subsysName, String subsysNameS, Short subsysEnable, Integer updateUserid, Date updateTime) {
        this.subsysSubsysno = subsysSubsysno;
        this.subsysName = subsysName;
        this.subsysNameS = subsysNameS;
        this.subsysEnable = subsysEnable;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSYS
     *
     * @mbg.generated
     */
    public Subsys() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSYS.SUBSYS_SUBSYSNO
     *
     * @return the value of SUBSYS.SUBSYS_SUBSYSNO
     *
     * @mbg.generated
     */
    public Short getSubsysSubsysno() {
        return subsysSubsysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSYS.SUBSYS_SUBSYSNO
     *
     * @param subsysSubsysno the value for SUBSYS.SUBSYS_SUBSYSNO
     *
     * @mbg.generated
     */
    public void setSubsysSubsysno(Short subsysSubsysno) {
        this.subsysSubsysno = subsysSubsysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSYS.SUBSYS_NAME
     *
     * @return the value of SUBSYS.SUBSYS_NAME
     *
     * @mbg.generated
     */
    public String getSubsysName() {
        return subsysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSYS.SUBSYS_NAME
     *
     * @param subsysName the value for SUBSYS.SUBSYS_NAME
     *
     * @mbg.generated
     */
    public void setSubsysName(String subsysName) {
        this.subsysName = subsysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSYS.SUBSYS_NAME_S
     *
     * @return the value of SUBSYS.SUBSYS_NAME_S
     *
     * @mbg.generated
     */
    public String getSubsysNameS() {
        return subsysNameS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSYS.SUBSYS_NAME_S
     *
     * @param subsysNameS the value for SUBSYS.SUBSYS_NAME_S
     *
     * @mbg.generated
     */
    public void setSubsysNameS(String subsysNameS) {
        this.subsysNameS = subsysNameS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSYS.SUBSYS_ENABLE
     *
     * @return the value of SUBSYS.SUBSYS_ENABLE
     *
     * @mbg.generated
     */
    public Short getSubsysEnable() {
        return subsysEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSYS.SUBSYS_ENABLE
     *
     * @param subsysEnable the value for SUBSYS.SUBSYS_ENABLE
     *
     * @mbg.generated
     */
    public void setSubsysEnable(Short subsysEnable) {
        this.subsysEnable = subsysEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSYS.UPDATE_USERID
     *
     * @return the value of SUBSYS.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSYS.UPDATE_USERID
     *
     * @param updateUserid the value for SUBSYS.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSYS.UPDATE_TIME
     *
     * @return the value of SUBSYS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSYS.UPDATE_TIME
     *
     * @param updateTime the value for SUBSYS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSYS
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", subsysSubsysno=").append(subsysSubsysno);
        sb.append(", subsysName=").append(subsysName);
        sb.append(", subsysNameS=").append(subsysNameS);
        sb.append(", subsysEnable=").append(subsysEnable);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSYS
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Subsys other = (Subsys) that;
        return (this.getSubsysSubsysno() == null ? other.getSubsysSubsysno() == null : this.getSubsysSubsysno().equals(other.getSubsysSubsysno()))
            && (this.getSubsysName() == null ? other.getSubsysName() == null : this.getSubsysName().equals(other.getSubsysName()))
            && (this.getSubsysNameS() == null ? other.getSubsysNameS() == null : this.getSubsysNameS().equals(other.getSubsysNameS()))
            && (this.getSubsysEnable() == null ? other.getSubsysEnable() == null : this.getSubsysEnable().equals(other.getSubsysEnable()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSYS
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getSubsysSubsysno() == null) ? 0 : getSubsysSubsysno().hashCode());
        result = 31 * result + ((getSubsysName() == null) ? 0 : getSubsysName().hashCode());
        result = 31 * result + ((getSubsysNameS() == null) ? 0 : getSubsysNameS().hashCode());
        result = 31 * result + ((getSubsysEnable() == null) ? 0 : getSubsysEnable().hashCode());
        result = 31 * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = 31 * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSYS
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<SUBSYS_SUBSYSNO>").append(this.subsysSubsysno).append("</SUBSYS_SUBSYSNO>");
        sb.append("<SUBSYS_NAME>").append(this.subsysName).append("</SUBSYS_NAME>");
        sb.append("<SUBSYS_NAME_S>").append(this.subsysNameS).append("</SUBSYS_NAME_S>");
        sb.append("<SUBSYS_ENABLE>").append(this.subsysEnable).append("</SUBSYS_ENABLE>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        return sb.toString();
    }
}