package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.util.Date;

public class Svcsdcps extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.SEQNO
     *
     * @mbg.generated
     */
    private Long seqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.CALDATE
     *
     * @mbg.generated
     */
    private String caldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.FILENAME
     *
     * @mbg.generated
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.FILEHEADER
     *
     * @mbg.generated
     */
    private String fileheader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.DATAATTRIBUTE
     *
     * @mbg.generated
     */
    private String dataattribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.TXTYPE
     *
     * @mbg.generated
     */
    private String txtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.TXREASON
     *
     * @mbg.generated
     */
    private String txreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.EASYNO
     *
     * @mbg.generated
     */
    private String easyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.EASYENDYYMM
     *
     * @mbg.generated
     */
    private String easyendyymm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.SALINGMARK
     *
     * @mbg.generated
     */
    private String salingmark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.IDNO
     *
     * @mbg.generated
     */
    private String idno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.NAMEBIG5
     *
     * @mbg.generated
     */
    private String namebig5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.NAME2
     *
     * @mbg.generated
     */
    private String name2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.BIRTHDAY
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.ZIPCODE
     *
     * @mbg.generated
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.CONTACTADDRESS
     *
     * @mbg.generated
     */
    private String contactaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.EMAILADDRESS
     *
     * @mbg.generated
     */
    private String emailaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.NATIONALITY
     *
     * @mbg.generated
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.HASH
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.ERRCODE
     *
     * @mbg.generated
     */
    private String errcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.FILEDATA
     *
     * @mbg.generated
     */
    private String filedata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCPS.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVCSDCPS
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCPS
     *
     * @mbg.generated
     */
    public Svcsdcps(Long seqno, String caldate, String filename, String fileheader, String dataattribute, String txtype, String txreason, String easyno, String easyendyymm, String salingmark, String idno, String namebig5, String name2, String birthday, String phone, String mobile, String zipcode, String contactaddress, String emailaddress, String nationality, String hash, String errcode, String filedata, Integer updateuserid, Date updatetime) {
        this.seqno = seqno;
        this.caldate = caldate;
        this.filename = filename;
        this.fileheader = fileheader;
        this.dataattribute = dataattribute;
        this.txtype = txtype;
        this.txreason = txreason;
        this.easyno = easyno;
        this.easyendyymm = easyendyymm;
        this.salingmark = salingmark;
        this.idno = idno;
        this.namebig5 = namebig5;
        this.name2 = name2;
        this.birthday = birthday;
        this.phone = phone;
        this.mobile = mobile;
        this.zipcode = zipcode;
        this.contactaddress = contactaddress;
        this.emailaddress = emailaddress;
        this.nationality = nationality;
        this.hash = hash;
        this.errcode = errcode;
        this.filedata = filedata;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCPS
     *
     * @mbg.generated
     */
    public Svcsdcps() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.SEQNO
     *
     * @return the value of SVCSDCPS.SEQNO
     *
     * @mbg.generated
     */
    public Long getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.SEQNO
     *
     * @param seqno the value for SVCSDCPS.SEQNO
     *
     * @mbg.generated
     */
    public void setSeqno(Long seqno) {
        this.seqno = seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.CALDATE
     *
     * @return the value of SVCSDCPS.CALDATE
     *
     * @mbg.generated
     */
    public String getCaldate() {
        return caldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.CALDATE
     *
     * @param caldate the value for SVCSDCPS.CALDATE
     *
     * @mbg.generated
     */
    public void setCaldate(String caldate) {
        this.caldate = caldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.FILENAME
     *
     * @return the value of SVCSDCPS.FILENAME
     *
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.FILENAME
     *
     * @param filename the value for SVCSDCPS.FILENAME
     *
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.FILEHEADER
     *
     * @return the value of SVCSDCPS.FILEHEADER
     *
     * @mbg.generated
     */
    public String getFileheader() {
        return fileheader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.FILEHEADER
     *
     * @param fileheader the value for SVCSDCPS.FILEHEADER
     *
     * @mbg.generated
     */
    public void setFileheader(String fileheader) {
        this.fileheader = fileheader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.DATAATTRIBUTE
     *
     * @return the value of SVCSDCPS.DATAATTRIBUTE
     *
     * @mbg.generated
     */
    public String getDataattribute() {
        return dataattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.DATAATTRIBUTE
     *
     * @param dataattribute the value for SVCSDCPS.DATAATTRIBUTE
     *
     * @mbg.generated
     */
    public void setDataattribute(String dataattribute) {
        this.dataattribute = dataattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.TXTYPE
     *
     * @return the value of SVCSDCPS.TXTYPE
     *
     * @mbg.generated
     */
    public String getTxtype() {
        return txtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.TXTYPE
     *
     * @param txtype the value for SVCSDCPS.TXTYPE
     *
     * @mbg.generated
     */
    public void setTxtype(String txtype) {
        this.txtype = txtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.TXREASON
     *
     * @return the value of SVCSDCPS.TXREASON
     *
     * @mbg.generated
     */
    public String getTxreason() {
        return txreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.TXREASON
     *
     * @param txreason the value for SVCSDCPS.TXREASON
     *
     * @mbg.generated
     */
    public void setTxreason(String txreason) {
        this.txreason = txreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.EASYNO
     *
     * @return the value of SVCSDCPS.EASYNO
     *
     * @mbg.generated
     */
    public String getEasyno() {
        return easyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.EASYNO
     *
     * @param easyno the value for SVCSDCPS.EASYNO
     *
     * @mbg.generated
     */
    public void setEasyno(String easyno) {
        this.easyno = easyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.EASYENDYYMM
     *
     * @return the value of SVCSDCPS.EASYENDYYMM
     *
     * @mbg.generated
     */
    public String getEasyendyymm() {
        return easyendyymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.EASYENDYYMM
     *
     * @param easyendyymm the value for SVCSDCPS.EASYENDYYMM
     *
     * @mbg.generated
     */
    public void setEasyendyymm(String easyendyymm) {
        this.easyendyymm = easyendyymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.SALINGMARK
     *
     * @return the value of SVCSDCPS.SALINGMARK
     *
     * @mbg.generated
     */
    public String getSalingmark() {
        return salingmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.SALINGMARK
     *
     * @param salingmark the value for SVCSDCPS.SALINGMARK
     *
     * @mbg.generated
     */
    public void setSalingmark(String salingmark) {
        this.salingmark = salingmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.IDNO
     *
     * @return the value of SVCSDCPS.IDNO
     *
     * @mbg.generated
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.IDNO
     *
     * @param idno the value for SVCSDCPS.IDNO
     *
     * @mbg.generated
     */
    public void setIdno(String idno) {
        this.idno = idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.NAMEBIG5
     *
     * @return the value of SVCSDCPS.NAMEBIG5
     *
     * @mbg.generated
     */
    public String getNamebig5() {
        return namebig5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.NAMEBIG5
     *
     * @param namebig5 the value for SVCSDCPS.NAMEBIG5
     *
     * @mbg.generated
     */
    public void setNamebig5(String namebig5) {
        this.namebig5 = namebig5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.NAME2
     *
     * @return the value of SVCSDCPS.NAME2
     *
     * @mbg.generated
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.NAME2
     *
     * @param name2 the value for SVCSDCPS.NAME2
     *
     * @mbg.generated
     */
    public void setName2(String name2) {
        this.name2 = name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.BIRTHDAY
     *
     * @return the value of SVCSDCPS.BIRTHDAY
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.BIRTHDAY
     *
     * @param birthday the value for SVCSDCPS.BIRTHDAY
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.PHONE
     *
     * @return the value of SVCSDCPS.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.PHONE
     *
     * @param phone the value for SVCSDCPS.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.MOBILE
     *
     * @return the value of SVCSDCPS.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.MOBILE
     *
     * @param mobile the value for SVCSDCPS.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.ZIPCODE
     *
     * @return the value of SVCSDCPS.ZIPCODE
     *
     * @mbg.generated
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.ZIPCODE
     *
     * @param zipcode the value for SVCSDCPS.ZIPCODE
     *
     * @mbg.generated
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.CONTACTADDRESS
     *
     * @return the value of SVCSDCPS.CONTACTADDRESS
     *
     * @mbg.generated
     */
    public String getContactaddress() {
        return contactaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.CONTACTADDRESS
     *
     * @param contactaddress the value for SVCSDCPS.CONTACTADDRESS
     *
     * @mbg.generated
     */
    public void setContactaddress(String contactaddress) {
        this.contactaddress = contactaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.EMAILADDRESS
     *
     * @return the value of SVCSDCPS.EMAILADDRESS
     *
     * @mbg.generated
     */
    public String getEmailaddress() {
        return emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.EMAILADDRESS
     *
     * @param emailaddress the value for SVCSDCPS.EMAILADDRESS
     *
     * @mbg.generated
     */
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.NATIONALITY
     *
     * @return the value of SVCSDCPS.NATIONALITY
     *
     * @mbg.generated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.NATIONALITY
     *
     * @param nationality the value for SVCSDCPS.NATIONALITY
     *
     * @mbg.generated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.HASH
     *
     * @return the value of SVCSDCPS.HASH
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.HASH
     *
     * @param hash the value for SVCSDCPS.HASH
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.ERRCODE
     *
     * @return the value of SVCSDCPS.ERRCODE
     *
     * @mbg.generated
     */
    public String getErrcode() {
        return errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.ERRCODE
     *
     * @param errcode the value for SVCSDCPS.ERRCODE
     *
     * @mbg.generated
     */
    public void setErrcode(String errcode) {
        this.errcode = errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.FILEDATA
     *
     * @return the value of SVCSDCPS.FILEDATA
     *
     * @mbg.generated
     */
    public String getFiledata() {
        return filedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.FILEDATA
     *
     * @param filedata the value for SVCSDCPS.FILEDATA
     *
     * @mbg.generated
     */
    public void setFiledata(String filedata) {
        this.filedata = filedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.UPDATEUSERID
     *
     * @return the value of SVCSDCPS.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.UPDATEUSERID
     *
     * @param updateuserid the value for SVCSDCPS.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCPS.UPDATETIME
     *
     * @return the value of SVCSDCPS.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCPS.UPDATETIME
     *
     * @param updatetime the value for SVCSDCPS.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCPS
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqno=").append(seqno);
        sb.append(", caldate=").append(caldate);
        sb.append(", filename=").append(filename);
        sb.append(", fileheader=").append(fileheader);
        sb.append(", dataattribute=").append(dataattribute);
        sb.append(", txtype=").append(txtype);
        sb.append(", txreason=").append(txreason);
        sb.append(", easyno=").append(easyno);
        sb.append(", easyendyymm=").append(easyendyymm);
        sb.append(", salingmark=").append(salingmark);
        sb.append(", idno=").append(idno);
        sb.append(", namebig5=").append(namebig5);
        sb.append(", name2=").append(name2);
        sb.append(", birthday=").append(birthday);
        sb.append(", phone=").append(phone);
        sb.append(", mobile=").append(mobile);
        sb.append(", zipcode=").append(zipcode);
        sb.append(", contactaddress=").append(contactaddress);
        sb.append(", emailaddress=").append(emailaddress);
        sb.append(", nationality=").append(nationality);
        sb.append(", hash=").append(hash);
        sb.append(", errcode=").append(errcode);
        sb.append(", filedata=").append(filedata);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCPS
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Svcsdcps other = (Svcsdcps) that;
        return (this.getSeqno() == null ? other.getSeqno() == null : this.getSeqno().equals(other.getSeqno()))
            && (this.getCaldate() == null ? other.getCaldate() == null : this.getCaldate().equals(other.getCaldate()))
            && (this.getFilename() == null ? other.getFilename() == null : this.getFilename().equals(other.getFilename()))
            && (this.getFileheader() == null ? other.getFileheader() == null : this.getFileheader().equals(other.getFileheader()))
            && (this.getDataattribute() == null ? other.getDataattribute() == null : this.getDataattribute().equals(other.getDataattribute()))
            && (this.getTxtype() == null ? other.getTxtype() == null : this.getTxtype().equals(other.getTxtype()))
            && (this.getTxreason() == null ? other.getTxreason() == null : this.getTxreason().equals(other.getTxreason()))
            && (this.getEasyno() == null ? other.getEasyno() == null : this.getEasyno().equals(other.getEasyno()))
            && (this.getEasyendyymm() == null ? other.getEasyendyymm() == null : this.getEasyendyymm().equals(other.getEasyendyymm()))
            && (this.getSalingmark() == null ? other.getSalingmark() == null : this.getSalingmark().equals(other.getSalingmark()))
            && (this.getIdno() == null ? other.getIdno() == null : this.getIdno().equals(other.getIdno()))
            && (this.getNamebig5() == null ? other.getNamebig5() == null : this.getNamebig5().equals(other.getNamebig5()))
            && (this.getName2() == null ? other.getName2() == null : this.getName2().equals(other.getName2()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getZipcode() == null ? other.getZipcode() == null : this.getZipcode().equals(other.getZipcode()))
            && (this.getContactaddress() == null ? other.getContactaddress() == null : this.getContactaddress().equals(other.getContactaddress()))
            && (this.getEmailaddress() == null ? other.getEmailaddress() == null : this.getEmailaddress().equals(other.getEmailaddress()))
            && (this.getNationality() == null ? other.getNationality() == null : this.getNationality().equals(other.getNationality()))
            && (this.getHash() == null ? other.getHash() == null : this.getHash().equals(other.getHash()))
            && (this.getErrcode() == null ? other.getErrcode() == null : this.getErrcode().equals(other.getErrcode()))
            && (this.getFiledata() == null ? other.getFiledata() == null : this.getFiledata().equals(other.getFiledata()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCPS
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getSeqno() == null) ? 0 : getSeqno().hashCode());
        result = 31 * result + ((getCaldate() == null) ? 0 : getCaldate().hashCode());
        result = 31 * result + ((getFilename() == null) ? 0 : getFilename().hashCode());
        result = 31 * result + ((getFileheader() == null) ? 0 : getFileheader().hashCode());
        result = 31 * result + ((getDataattribute() == null) ? 0 : getDataattribute().hashCode());
        result = 31 * result + ((getTxtype() == null) ? 0 : getTxtype().hashCode());
        result = 31 * result + ((getTxreason() == null) ? 0 : getTxreason().hashCode());
        result = 31 * result + ((getEasyno() == null) ? 0 : getEasyno().hashCode());
        result = 31 * result + ((getEasyendyymm() == null) ? 0 : getEasyendyymm().hashCode());
        result = 31 * result + ((getSalingmark() == null) ? 0 : getSalingmark().hashCode());
        result = 31 * result + ((getIdno() == null) ? 0 : getIdno().hashCode());
        result = 31 * result + ((getNamebig5() == null) ? 0 : getNamebig5().hashCode());
        result = 31 * result + ((getName2() == null) ? 0 : getName2().hashCode());
        result = 31 * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = 31 * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = 31 * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = 31 * result + ((getZipcode() == null) ? 0 : getZipcode().hashCode());
        result = 31 * result + ((getContactaddress() == null) ? 0 : getContactaddress().hashCode());
        result = 31 * result + ((getEmailaddress() == null) ? 0 : getEmailaddress().hashCode());
        result = 31 * result + ((getNationality() == null) ? 0 : getNationality().hashCode());
        result = 31 * result + ((getHash() == null) ? 0 : getHash().hashCode());
        result = 31 * result + ((getErrcode() == null) ? 0 : getErrcode().hashCode());
        result = 31 * result + ((getFiledata() == null) ? 0 : getFiledata().hashCode());
        result = 31 * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = 31 * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCPS
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<SEQNO>").append(this.seqno).append("</SEQNO>");
        sb.append("<CALDATE>").append(this.caldate).append("</CALDATE>");
        sb.append("<FILENAME>").append(this.filename).append("</FILENAME>");
        sb.append("<FILEHEADER>").append(this.fileheader).append("</FILEHEADER>");
        sb.append("<DATAATTRIBUTE>").append(this.dataattribute).append("</DATAATTRIBUTE>");
        sb.append("<TXTYPE>").append(this.txtype).append("</TXTYPE>");
        sb.append("<TXREASON>").append(this.txreason).append("</TXREASON>");
        sb.append("<EASYNO>").append(this.easyno).append("</EASYNO>");
        sb.append("<EASYENDYYMM>").append(this.easyendyymm).append("</EASYENDYYMM>");
        sb.append("<SALINGMARK>").append(this.salingmark).append("</SALINGMARK>");
        sb.append("<IDNO>").append(this.idno).append("</IDNO>");
        sb.append("<NAMEBIG5>").append(this.namebig5).append("</NAMEBIG5>");
        sb.append("<NAME2>").append(this.name2).append("</NAME2>");
        sb.append("<BIRTHDAY>").append(this.birthday).append("</BIRTHDAY>");
        sb.append("<PHONE>").append(this.phone).append("</PHONE>");
        sb.append("<MOBILE>").append(this.mobile).append("</MOBILE>");
        sb.append("<ZIPCODE>").append(this.zipcode).append("</ZIPCODE>");
        sb.append("<CONTACTADDRESS>").append(this.contactaddress).append("</CONTACTADDRESS>");
        sb.append("<EMAILADDRESS>").append(this.emailaddress).append("</EMAILADDRESS>");
        sb.append("<NATIONALITY>").append(this.nationality).append("</NATIONALITY>");
        sb.append("<HASH>").append(this.hash).append("</HASH>");
        sb.append("<ERRCODE>").append(this.errcode).append("</ERRCODE>");
        sb.append("<FILEDATA>").append(this.filedata).append("</FILEDATA>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}