package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.util.Date;

public class Svcsdcti extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.SEQNO
     *
     * @mbg.generated
     */
    private Long seqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.CALDATE
     *
     * @mbg.generated
     */
    private String caldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.FILENAME
     *
     * @mbg.generated
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.FILEHEADER
     *
     * @mbg.generated
     */
    private String fileheader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.DATAATTRIBUTE
     *
     * @mbg.generated
     */
    private String dataattribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.TXCODE
     *
     * @mbg.generated
     */
    private String txcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.EASYNO
     *
     * @mbg.generated
     */
    private String easyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.TXDATE
     *
     * @mbg.generated
     */
    private String txdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.TXTIME
     *
     * @mbg.generated
     */
    private String txtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.TXAMOUNT
     *
     * @mbg.generated
     */
    private Long txamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.TXCORPNO
     *
     * @mbg.generated
     */
    private Integer txcorpno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.TXLOCATIONNO
     *
     * @mbg.generated
     */
    private String txlocationno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.TXCORPNAME
     *
     * @mbg.generated
     */
    private String txcorpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.TXLOCATIONNAME
     *
     * @mbg.generated
     */
    private String txlocationname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.CHARGEBACKREASON
     *
     * @mbg.generated
     */
    private String chargebackreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.ONLINE
     *
     * @mbg.generated
     */
    private String online;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.HASH
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.ERRCODE
     *
     * @mbg.generated
     */
    private String errcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.FILEDATA
     *
     * @mbg.generated
     */
    private String filedata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVCSDCTI.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVCSDCTI
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCTI
     *
     * @mbg.generated
     */
    public Svcsdcti(Long seqno, String caldate, String filename, String fileheader, String dataattribute, String txcode, String easyno, String txdate, String txtime, Long txamount, Integer txcorpno, String txlocationno, String txcorpname, String txlocationname, String chargebackreason, String online, String hash, String errcode, String filedata, Integer updateuserid, Date updatetime) {
        this.seqno = seqno;
        this.caldate = caldate;
        this.filename = filename;
        this.fileheader = fileheader;
        this.dataattribute = dataattribute;
        this.txcode = txcode;
        this.easyno = easyno;
        this.txdate = txdate;
        this.txtime = txtime;
        this.txamount = txamount;
        this.txcorpno = txcorpno;
        this.txlocationno = txlocationno;
        this.txcorpname = txcorpname;
        this.txlocationname = txlocationname;
        this.chargebackreason = chargebackreason;
        this.online = online;
        this.hash = hash;
        this.errcode = errcode;
        this.filedata = filedata;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCTI
     *
     * @mbg.generated
     */
    public Svcsdcti() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.SEQNO
     *
     * @return the value of SVCSDCTI.SEQNO
     *
     * @mbg.generated
     */
    public Long getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.SEQNO
     *
     * @param seqno the value for SVCSDCTI.SEQNO
     *
     * @mbg.generated
     */
    public void setSeqno(Long seqno) {
        this.seqno = seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.CALDATE
     *
     * @return the value of SVCSDCTI.CALDATE
     *
     * @mbg.generated
     */
    public String getCaldate() {
        return caldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.CALDATE
     *
     * @param caldate the value for SVCSDCTI.CALDATE
     *
     * @mbg.generated
     */
    public void setCaldate(String caldate) {
        this.caldate = caldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.FILENAME
     *
     * @return the value of SVCSDCTI.FILENAME
     *
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.FILENAME
     *
     * @param filename the value for SVCSDCTI.FILENAME
     *
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.FILEHEADER
     *
     * @return the value of SVCSDCTI.FILEHEADER
     *
     * @mbg.generated
     */
    public String getFileheader() {
        return fileheader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.FILEHEADER
     *
     * @param fileheader the value for SVCSDCTI.FILEHEADER
     *
     * @mbg.generated
     */
    public void setFileheader(String fileheader) {
        this.fileheader = fileheader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.DATAATTRIBUTE
     *
     * @return the value of SVCSDCTI.DATAATTRIBUTE
     *
     * @mbg.generated
     */
    public String getDataattribute() {
        return dataattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.DATAATTRIBUTE
     *
     * @param dataattribute the value for SVCSDCTI.DATAATTRIBUTE
     *
     * @mbg.generated
     */
    public void setDataattribute(String dataattribute) {
        this.dataattribute = dataattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.TXCODE
     *
     * @return the value of SVCSDCTI.TXCODE
     *
     * @mbg.generated
     */
    public String getTxcode() {
        return txcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.TXCODE
     *
     * @param txcode the value for SVCSDCTI.TXCODE
     *
     * @mbg.generated
     */
    public void setTxcode(String txcode) {
        this.txcode = txcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.EASYNO
     *
     * @return the value of SVCSDCTI.EASYNO
     *
     * @mbg.generated
     */
    public String getEasyno() {
        return easyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.EASYNO
     *
     * @param easyno the value for SVCSDCTI.EASYNO
     *
     * @mbg.generated
     */
    public void setEasyno(String easyno) {
        this.easyno = easyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.TXDATE
     *
     * @return the value of SVCSDCTI.TXDATE
     *
     * @mbg.generated
     */
    public String getTxdate() {
        return txdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.TXDATE
     *
     * @param txdate the value for SVCSDCTI.TXDATE
     *
     * @mbg.generated
     */
    public void setTxdate(String txdate) {
        this.txdate = txdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.TXTIME
     *
     * @return the value of SVCSDCTI.TXTIME
     *
     * @mbg.generated
     */
    public String getTxtime() {
        return txtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.TXTIME
     *
     * @param txtime the value for SVCSDCTI.TXTIME
     *
     * @mbg.generated
     */
    public void setTxtime(String txtime) {
        this.txtime = txtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.TXAMOUNT
     *
     * @return the value of SVCSDCTI.TXAMOUNT
     *
     * @mbg.generated
     */
    public Long getTxamount() {
        return txamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.TXAMOUNT
     *
     * @param txamount the value for SVCSDCTI.TXAMOUNT
     *
     * @mbg.generated
     */
    public void setTxamount(Long txamount) {
        this.txamount = txamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.TXCORPNO
     *
     * @return the value of SVCSDCTI.TXCORPNO
     *
     * @mbg.generated
     */
    public Integer getTxcorpno() {
        return txcorpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.TXCORPNO
     *
     * @param txcorpno the value for SVCSDCTI.TXCORPNO
     *
     * @mbg.generated
     */
    public void setTxcorpno(Integer txcorpno) {
        this.txcorpno = txcorpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.TXLOCATIONNO
     *
     * @return the value of SVCSDCTI.TXLOCATIONNO
     *
     * @mbg.generated
     */
    public String getTxlocationno() {
        return txlocationno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.TXLOCATIONNO
     *
     * @param txlocationno the value for SVCSDCTI.TXLOCATIONNO
     *
     * @mbg.generated
     */
    public void setTxlocationno(String txlocationno) {
        this.txlocationno = txlocationno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.TXCORPNAME
     *
     * @return the value of SVCSDCTI.TXCORPNAME
     *
     * @mbg.generated
     */
    public String getTxcorpname() {
        return txcorpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.TXCORPNAME
     *
     * @param txcorpname the value for SVCSDCTI.TXCORPNAME
     *
     * @mbg.generated
     */
    public void setTxcorpname(String txcorpname) {
        this.txcorpname = txcorpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.TXLOCATIONNAME
     *
     * @return the value of SVCSDCTI.TXLOCATIONNAME
     *
     * @mbg.generated
     */
    public String getTxlocationname() {
        return txlocationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.TXLOCATIONNAME
     *
     * @param txlocationname the value for SVCSDCTI.TXLOCATIONNAME
     *
     * @mbg.generated
     */
    public void setTxlocationname(String txlocationname) {
        this.txlocationname = txlocationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.CHARGEBACKREASON
     *
     * @return the value of SVCSDCTI.CHARGEBACKREASON
     *
     * @mbg.generated
     */
    public String getChargebackreason() {
        return chargebackreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.CHARGEBACKREASON
     *
     * @param chargebackreason the value for SVCSDCTI.CHARGEBACKREASON
     *
     * @mbg.generated
     */
    public void setChargebackreason(String chargebackreason) {
        this.chargebackreason = chargebackreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.ONLINE
     *
     * @return the value of SVCSDCTI.ONLINE
     *
     * @mbg.generated
     */
    public String getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.ONLINE
     *
     * @param online the value for SVCSDCTI.ONLINE
     *
     * @mbg.generated
     */
    public void setOnline(String online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.HASH
     *
     * @return the value of SVCSDCTI.HASH
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.HASH
     *
     * @param hash the value for SVCSDCTI.HASH
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.ERRCODE
     *
     * @return the value of SVCSDCTI.ERRCODE
     *
     * @mbg.generated
     */
    public String getErrcode() {
        return errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.ERRCODE
     *
     * @param errcode the value for SVCSDCTI.ERRCODE
     *
     * @mbg.generated
     */
    public void setErrcode(String errcode) {
        this.errcode = errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.FILEDATA
     *
     * @return the value of SVCSDCTI.FILEDATA
     *
     * @mbg.generated
     */
    public String getFiledata() {
        return filedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.FILEDATA
     *
     * @param filedata the value for SVCSDCTI.FILEDATA
     *
     * @mbg.generated
     */
    public void setFiledata(String filedata) {
        this.filedata = filedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.UPDATEUSERID
     *
     * @return the value of SVCSDCTI.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.UPDATEUSERID
     *
     * @param updateuserid the value for SVCSDCTI.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVCSDCTI.UPDATETIME
     *
     * @return the value of SVCSDCTI.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVCSDCTI.UPDATETIME
     *
     * @param updatetime the value for SVCSDCTI.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCTI
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqno=").append(seqno);
        sb.append(", caldate=").append(caldate);
        sb.append(", filename=").append(filename);
        sb.append(", fileheader=").append(fileheader);
        sb.append(", dataattribute=").append(dataattribute);
        sb.append(", txcode=").append(txcode);
        sb.append(", easyno=").append(easyno);
        sb.append(", txdate=").append(txdate);
        sb.append(", txtime=").append(txtime);
        sb.append(", txamount=").append(txamount);
        sb.append(", txcorpno=").append(txcorpno);
        sb.append(", txlocationno=").append(txlocationno);
        sb.append(", txcorpname=").append(txcorpname);
        sb.append(", txlocationname=").append(txlocationname);
        sb.append(", chargebackreason=").append(chargebackreason);
        sb.append(", online=").append(online);
        sb.append(", hash=").append(hash);
        sb.append(", errcode=").append(errcode);
        sb.append(", filedata=").append(filedata);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCTI
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Svcsdcti other = (Svcsdcti) that;
        return (this.getSeqno() == null ? other.getSeqno() == null : this.getSeqno().equals(other.getSeqno()))
            && (this.getCaldate() == null ? other.getCaldate() == null : this.getCaldate().equals(other.getCaldate()))
            && (this.getFilename() == null ? other.getFilename() == null : this.getFilename().equals(other.getFilename()))
            && (this.getFileheader() == null ? other.getFileheader() == null : this.getFileheader().equals(other.getFileheader()))
            && (this.getDataattribute() == null ? other.getDataattribute() == null : this.getDataattribute().equals(other.getDataattribute()))
            && (this.getTxcode() == null ? other.getTxcode() == null : this.getTxcode().equals(other.getTxcode()))
            && (this.getEasyno() == null ? other.getEasyno() == null : this.getEasyno().equals(other.getEasyno()))
            && (this.getTxdate() == null ? other.getTxdate() == null : this.getTxdate().equals(other.getTxdate()))
            && (this.getTxtime() == null ? other.getTxtime() == null : this.getTxtime().equals(other.getTxtime()))
            && (this.getTxamount() == null ? other.getTxamount() == null : this.getTxamount().equals(other.getTxamount()))
            && (this.getTxcorpno() == null ? other.getTxcorpno() == null : this.getTxcorpno().equals(other.getTxcorpno()))
            && (this.getTxlocationno() == null ? other.getTxlocationno() == null : this.getTxlocationno().equals(other.getTxlocationno()))
            && (this.getTxcorpname() == null ? other.getTxcorpname() == null : this.getTxcorpname().equals(other.getTxcorpname()))
            && (this.getTxlocationname() == null ? other.getTxlocationname() == null : this.getTxlocationname().equals(other.getTxlocationname()))
            && (this.getChargebackreason() == null ? other.getChargebackreason() == null : this.getChargebackreason().equals(other.getChargebackreason()))
            && (this.getOnline() == null ? other.getOnline() == null : this.getOnline().equals(other.getOnline()))
            && (this.getHash() == null ? other.getHash() == null : this.getHash().equals(other.getHash()))
            && (this.getErrcode() == null ? other.getErrcode() == null : this.getErrcode().equals(other.getErrcode()))
            && (this.getFiledata() == null ? other.getFiledata() == null : this.getFiledata().equals(other.getFiledata()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCTI
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getSeqno() == null) ? 0 : getSeqno().hashCode());
        result = 31 * result + ((getCaldate() == null) ? 0 : getCaldate().hashCode());
        result = 31 * result + ((getFilename() == null) ? 0 : getFilename().hashCode());
        result = 31 * result + ((getFileheader() == null) ? 0 : getFileheader().hashCode());
        result = 31 * result + ((getDataattribute() == null) ? 0 : getDataattribute().hashCode());
        result = 31 * result + ((getTxcode() == null) ? 0 : getTxcode().hashCode());
        result = 31 * result + ((getEasyno() == null) ? 0 : getEasyno().hashCode());
        result = 31 * result + ((getTxdate() == null) ? 0 : getTxdate().hashCode());
        result = 31 * result + ((getTxtime() == null) ? 0 : getTxtime().hashCode());
        result = 31 * result + ((getTxamount() == null) ? 0 : getTxamount().hashCode());
        result = 31 * result + ((getTxcorpno() == null) ? 0 : getTxcorpno().hashCode());
        result = 31 * result + ((getTxlocationno() == null) ? 0 : getTxlocationno().hashCode());
        result = 31 * result + ((getTxcorpname() == null) ? 0 : getTxcorpname().hashCode());
        result = 31 * result + ((getTxlocationname() == null) ? 0 : getTxlocationname().hashCode());
        result = 31 * result + ((getChargebackreason() == null) ? 0 : getChargebackreason().hashCode());
        result = 31 * result + ((getOnline() == null) ? 0 : getOnline().hashCode());
        result = 31 * result + ((getHash() == null) ? 0 : getHash().hashCode());
        result = 31 * result + ((getErrcode() == null) ? 0 : getErrcode().hashCode());
        result = 31 * result + ((getFiledata() == null) ? 0 : getFiledata().hashCode());
        result = 31 * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = 31 * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCTI
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<SEQNO>").append(this.seqno).append("</SEQNO>");
        sb.append("<CALDATE>").append(this.caldate).append("</CALDATE>");
        sb.append("<FILENAME>").append(this.filename).append("</FILENAME>");
        sb.append("<FILEHEADER>").append(this.fileheader).append("</FILEHEADER>");
        sb.append("<DATAATTRIBUTE>").append(this.dataattribute).append("</DATAATTRIBUTE>");
        sb.append("<TXCODE>").append(this.txcode).append("</TXCODE>");
        sb.append("<EASYNO>").append(this.easyno).append("</EASYNO>");
        sb.append("<TXDATE>").append(this.txdate).append("</TXDATE>");
        sb.append("<TXTIME>").append(this.txtime).append("</TXTIME>");
        sb.append("<TXAMOUNT>").append(this.txamount).append("</TXAMOUNT>");
        sb.append("<TXCORPNO>").append(this.txcorpno).append("</TXCORPNO>");
        sb.append("<TXLOCATIONNO>").append(this.txlocationno).append("</TXLOCATIONNO>");
        sb.append("<TXCORPNAME>").append(this.txcorpname).append("</TXCORPNAME>");
        sb.append("<TXLOCATIONNAME>").append(this.txlocationname).append("</TXLOCATIONNAME>");
        sb.append("<CHARGEBACKREASON>").append(this.chargebackreason).append("</CHARGEBACKREASON>");
        sb.append("<ONLINE>").append(this.online).append("</ONLINE>");
        sb.append("<HASH>").append(this.hash).append("</HASH>");
        sb.append("<ERRCODE>").append(this.errcode).append("</ERRCODE>");
        sb.append("<FILEDATA>").append(this.filedata).append("</FILEDATA>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}