package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.math.BigDecimal;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class T24cash extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T24CASH.T24CASH_DATE
     *
     * @mbg.generated
     */
    private String t24cashDate = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T24CASH.T24CASH_BRNO
     *
     * @mbg.generated
     */
    private String t24cashBrno = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T24CASH.T24CASH_CUR
     *
     * @mbg.generated
     */
    private String t24cashCur = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T24CASH.T24CASH_ZONE
     *
     * @mbg.generated
     */
    private String t24cashZone = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T24CASH.T24CASH_ACCT
     *
     * @mbg.generated
     */
    private String t24cashAcct = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T24CASH.T24CASH_AMT_OPEN
     *
     * @mbg.generated
     */
    private BigDecimal t24cashAmtOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T24CASH.T24CASH_AMT_CLOSE
     *
     * @mbg.generated
     */
    private BigDecimal t24cashAmtClose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T24CASH.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T24CASH.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T24CASH
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T24CASH
     *
     * @mbg.generated
     */
    public T24cash(String t24cashDate, String t24cashBrno, String t24cashCur, String t24cashZone, String t24cashAcct, BigDecimal t24cashAmtOpen, BigDecimal t24cashAmtClose, Integer updateUserid, Date updateTime) {
        this.t24cashDate = t24cashDate;
        this.t24cashBrno = t24cashBrno;
        this.t24cashCur = t24cashCur;
        this.t24cashZone = t24cashZone;
        this.t24cashAcct = t24cashAcct;
        this.t24cashAmtOpen = t24cashAmtOpen;
        this.t24cashAmtClose = t24cashAmtClose;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T24CASH
     *
     * @mbg.generated
     */
    public T24cash() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T24CASH.T24CASH_DATE
     *
     * @return the value of T24CASH.T24CASH_DATE
     *
     * @mbg.generated
     */
    public String getT24cashDate() {
        return t24cashDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T24CASH.T24CASH_DATE
     *
     * @param t24cashDate the value for T24CASH.T24CASH_DATE
     *
     * @mbg.generated
     */
    public void setT24cashDate(String t24cashDate) {
        this.t24cashDate = t24cashDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T24CASH.T24CASH_BRNO
     *
     * @return the value of T24CASH.T24CASH_BRNO
     *
     * @mbg.generated
     */
    public String getT24cashBrno() {
        return t24cashBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T24CASH.T24CASH_BRNO
     *
     * @param t24cashBrno the value for T24CASH.T24CASH_BRNO
     *
     * @mbg.generated
     */
    public void setT24cashBrno(String t24cashBrno) {
        this.t24cashBrno = t24cashBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T24CASH.T24CASH_CUR
     *
     * @return the value of T24CASH.T24CASH_CUR
     *
     * @mbg.generated
     */
    public String getT24cashCur() {
        return t24cashCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T24CASH.T24CASH_CUR
     *
     * @param t24cashCur the value for T24CASH.T24CASH_CUR
     *
     * @mbg.generated
     */
    public void setT24cashCur(String t24cashCur) {
        this.t24cashCur = t24cashCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T24CASH.T24CASH_ZONE
     *
     * @return the value of T24CASH.T24CASH_ZONE
     *
     * @mbg.generated
     */
    public String getT24cashZone() {
        return t24cashZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T24CASH.T24CASH_ZONE
     *
     * @param t24cashZone the value for T24CASH.T24CASH_ZONE
     *
     * @mbg.generated
     */
    public void setT24cashZone(String t24cashZone) {
        this.t24cashZone = t24cashZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T24CASH.T24CASH_ACCT
     *
     * @return the value of T24CASH.T24CASH_ACCT
     *
     * @mbg.generated
     */
    public String getT24cashAcct() {
        return t24cashAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T24CASH.T24CASH_ACCT
     *
     * @param t24cashAcct the value for T24CASH.T24CASH_ACCT
     *
     * @mbg.generated
     */
    public void setT24cashAcct(String t24cashAcct) {
        this.t24cashAcct = t24cashAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T24CASH.T24CASH_AMT_OPEN
     *
     * @return the value of T24CASH.T24CASH_AMT_OPEN
     *
     * @mbg.generated
     */
    public BigDecimal getT24cashAmtOpen() {
        return t24cashAmtOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T24CASH.T24CASH_AMT_OPEN
     *
     * @param t24cashAmtOpen the value for T24CASH.T24CASH_AMT_OPEN
     *
     * @mbg.generated
     */
    public void setT24cashAmtOpen(BigDecimal t24cashAmtOpen) {
        this.t24cashAmtOpen = t24cashAmtOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T24CASH.T24CASH_AMT_CLOSE
     *
     * @return the value of T24CASH.T24CASH_AMT_CLOSE
     *
     * @mbg.generated
     */
    public BigDecimal getT24cashAmtClose() {
        return t24cashAmtClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T24CASH.T24CASH_AMT_CLOSE
     *
     * @param t24cashAmtClose the value for T24CASH.T24CASH_AMT_CLOSE
     *
     * @mbg.generated
     */
    public void setT24cashAmtClose(BigDecimal t24cashAmtClose) {
        this.t24cashAmtClose = t24cashAmtClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T24CASH.UPDATE_USERID
     *
     * @return the value of T24CASH.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T24CASH.UPDATE_USERID
     *
     * @param updateUserid the value for T24CASH.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T24CASH.UPDATE_TIME
     *
     * @return the value of T24CASH.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T24CASH.UPDATE_TIME
     *
     * @param updateTime the value for T24CASH.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T24CASH
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", t24cashDate=").append(t24cashDate);
        sb.append(", t24cashBrno=").append(t24cashBrno);
        sb.append(", t24cashCur=").append(t24cashCur);
        sb.append(", t24cashZone=").append(t24cashZone);
        sb.append(", t24cashAcct=").append(t24cashAcct);
        sb.append(", t24cashAmtOpen=").append(t24cashAmtOpen);
        sb.append(", t24cashAmtClose=").append(t24cashAmtClose);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T24CASH
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        T24cash other = (T24cash) that;
        return (this.getT24cashDate() == null ? other.getT24cashDate() == null : this.getT24cashDate().equals(other.getT24cashDate()))
            && (this.getT24cashBrno() == null ? other.getT24cashBrno() == null : this.getT24cashBrno().equals(other.getT24cashBrno()))
            && (this.getT24cashCur() == null ? other.getT24cashCur() == null : this.getT24cashCur().equals(other.getT24cashCur()))
            && (this.getT24cashZone() == null ? other.getT24cashZone() == null : this.getT24cashZone().equals(other.getT24cashZone()))
            && (this.getT24cashAcct() == null ? other.getT24cashAcct() == null : this.getT24cashAcct().equals(other.getT24cashAcct()))
            && (this.getT24cashAmtOpen() == null ? other.getT24cashAmtOpen() == null : this.getT24cashAmtOpen().equals(other.getT24cashAmtOpen()))
            && (this.getT24cashAmtClose() == null ? other.getT24cashAmtClose() == null : this.getT24cashAmtClose().equals(other.getT24cashAmtClose()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T24CASH
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getT24cashDate() == null) ? 0 : getT24cashDate().hashCode());
        result = 31 * result + ((getT24cashBrno() == null) ? 0 : getT24cashBrno().hashCode());
        result = 31 * result + ((getT24cashCur() == null) ? 0 : getT24cashCur().hashCode());
        result = 31 * result + ((getT24cashZone() == null) ? 0 : getT24cashZone().hashCode());
        result = 31 * result + ((getT24cashAcct() == null) ? 0 : getT24cashAcct().hashCode());
        result = 31 * result + ((getT24cashAmtOpen() == null) ? 0 : getT24cashAmtOpen().hashCode());
        result = 31 * result + ((getT24cashAmtClose() == null) ? 0 : getT24cashAmtClose().hashCode());
        result = 31 * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = 31 * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T24CASH
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<T24CASH_DATE>").append(this.t24cashDate).append("</T24CASH_DATE>");
        sb.append("<T24CASH_BRNO>").append(this.t24cashBrno).append("</T24CASH_BRNO>");
        sb.append("<T24CASH_CUR>").append(this.t24cashCur).append("</T24CASH_CUR>");
        sb.append("<T24CASH_ZONE>").append(this.t24cashZone).append("</T24CASH_ZONE>");
        sb.append("<T24CASH_ACCT>").append(this.t24cashAcct).append("</T24CASH_ACCT>");
        sb.append("<T24CASH_AMT_OPEN>").append(this.t24cashAmtOpen).append("</T24CASH_AMT_OPEN>");
        sb.append("<T24CASH_AMT_CLOSE>").append(this.t24cashAmtClose).append("</T24CASH_AMT_CLOSE>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        return sb.toString();
    }
}