<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.syscom</groupId>
        <artifactId>feptcb</artifactId>
        <version>1.0.0</version>
    </parent>
    <groupId>com.syscom.feptcb</groupId>
    <artifactId>fep-gateway</artifactId>
    <name>fep-gateway</name>
    <description>gateway</description>
    <packaging>${project.packaging}</packaging>
    <properties>
        <project-shell>fep_gateway</project-shell>
        <!-- ${project.description}必須在最後的位置 -->
        <profiles-active>jms,integration,${project.description}</profiles-active>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-bom</artifactId>
                <version>${log4j2.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${netty-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-jms</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-invoker</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-scheduler</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <!-- 排除fep-cache, 因為Gateway程式不允許直接從DB抓資料 -->
                <exclusion>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-cache</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring-boot-starter-web-version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>${netty-version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <version>${spring-boot-starter-actuator-vesion}</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <version>${micrometer-registry-prometheus-version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring-boot-starter-test-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter-api-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.ibm.ims</groupId>
            <artifactId>IMSConnectAPI</artifactId>
            <version>${ibm-ims-connect-version}</version>
            <scope>system</scope>
            <systemPath>${pom.basedir}/../fep-lib/lib/ims-connect-api-3.2.0.7.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>${spring-boot-starter-security-version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok-version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <profiles>
        <!-- Springboot方式build版, 將所有的檔包括引用的第三方jar檔都包在一個fep-gateway.jar檔中 -->
        <profile>
            <id>springboot-jar</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <project.packaging>jar</project.packaging>
            </properties>
            <build>
                <finalName>${project.artifactId}</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <version>${spring-boot-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>com.syscom.fep.gateway.SyscomFepGatewayApplication</mainClass>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>repackage</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin-version}</version>
                        <configuration>
                            <source>${java-source-version}</source>
                            <target>${java-target-version}</target>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <!-- Maven方式build版, 並配合iterator-maven-plugin實現拆分方式build版, 利於換版單獨更換jar檔
            1. 僅將本專案中的class檔包在jar檔中
            2. 將第三方引用的jar檔直接放在上一級目錄的dependencies目錄下
            3. 將引用fep其他專案的jar檔放在lib目錄下
            目錄結構如下:
                /fep-app
                    /bin/fep-function.sh
                    /config/各項配置檔
                    /dependencies/引用第三方的jar檔
                    /fep-gateway
                        /lib/引用fep的jar檔
                        application.properties
                        fep-gateway-run.bat
                        fep-gateway.jar
                        fep-gateway-start.sh
                        fep-gateway-status.sh
                        fep-gateway-stop.sh
        -->
        <profile>
            <id>maven-jar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <project.packaging>jar</project.packaging>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-clean-plugin</artifactId>
                        <version>${maven-clean-plugin-version}</version>
                        <configuration>
                            <followSymLinks>false</followSymLinks>
                            <filesets>
                                <fileset>
                                    <directory>../../${assembly-directory}</directory>
                                    <includes>
                                        <include>${project.artifactId}-*.tar.gz</include>
                                    </includes>
                                </fileset>
                            </filesets>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>properties-maven-plugin</artifactId>
                        <version>${properties-maven-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>read-project-properties</goal>
                                </goals>
                                <configuration>
                                    <files>
                                        <!-- 讀取屬性檔 -->
                                        <file>${assembly-config-path}/assembly-${assembly-prop}.properties</file>
                                    </files>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>com.soebes.maven.plugins</groupId>
                        <artifactId>iterator-maven-plugin</artifactId>
                        <version>${iterator-maven-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>iterator</goal>
                                </goals>
                                <configuration>
                                    <itemsWithProperties>
                                        <itemWithProperty>
                                            <name>atm</name>
                                            <properties>
                                                <assembly-name>atm</assembly-name>
                                                <assembly-func>-atm</assembly-func>
                                                <assembly-shell>_atm</assembly-shell>
                                                <assembly-jvm-xms>256m</assembly-jvm-xms>
                                                <assembly-jvm-xmx>512m</assembly-jvm-xmx>
                                                <assembly-jvm-metaspaceSize>256m</assembly-jvm-metaspaceSize>
                                                <assembly-profiles-active>${profiles-active}${assembly-func},${project.description}${assembly-func}-ssl</assembly-profiles-active>
                                            </properties>
                                        </itemWithProperty>
                                        <itemWithProperty>
                                            <name>fisc</name>
                                            <properties>
                                                <assembly-name>fisc</assembly-name>
                                                <assembly-func>-fisc</assembly-func>
                                                <assembly-shell>_fisc</assembly-shell>
                                                <assembly-jvm-xms>256m</assembly-jvm-xms>
                                                <assembly-jvm-xmx>512m</assembly-jvm-xmx>
                                                <assembly-jvm-metaspaceSize>256m</assembly-jvm-metaspaceSize>
                                                <assembly-profiles-active>${profiles-active}${assembly-func}</assembly-profiles-active>
                                            </properties>
                                        </itemWithProperty>
                                        <itemWithProperty>
                                            <name>atm-agent</name>
                                            <properties>
                                                <assembly-name>atm-agent</assembly-name>
                                                <assembly-func>-atm-agent</assembly-func>
                                                <assembly-shell>_atm_agent</assembly-shell>
                                                <assembly-jvm-xms>256m</assembly-jvm-xms>
                                                <assembly-jvm-xmx>512m</assembly-jvm-xmx>
                                                <assembly-jvm-metaspaceSize>256m</assembly-jvm-metaspaceSize>
                                                <assembly-profiles-active>${profiles-active}${assembly-func}</assembly-profiles-active>
                                            </properties>
                                        </itemWithProperty>
                                        <itemWithProperty>
                                            <name>fisc-agent</name>
                                            <properties>
                                                <assembly-name>fisc-agent</assembly-name>
                                                <assembly-func>-fisc-agent</assembly-func>
                                                <assembly-shell>_fisc_agent</assembly-shell>
                                                <assembly-jvm-xms>256m</assembly-jvm-xms>
                                                <assembly-jvm-xmx>512m</assembly-jvm-xmx>
                                                <assembly-jvm-metaspaceSize>256m</assembly-jvm-metaspaceSize>
                                                <assembly-profiles-active>${profiles-active}${assembly-func}</assembly-profiles-active>
                                            </properties>
                                        </itemWithProperty>
                                        <itemWithProperty>
                                            <name>cbs</name>
                                            <properties>
                                                <assembly-name>cbs</assembly-name>
                                                <assembly-func>-cbs</assembly-func>
                                                <assembly-shell>_cbs</assembly-shell>
                                                <assembly-jvm-xms>256m</assembly-jvm-xms>
                                                <assembly-jvm-xmx>512m</assembly-jvm-xmx>
                                                <assembly-jvm-metaspaceSize>256m</assembly-jvm-metaspaceSize>
                                                <assembly-profiles-active>${profiles-active}${assembly-func}</assembly-profiles-active>
                                            </properties>
                                        </itemWithProperty>
                                    </itemsWithProperties>
                                    <pluginExecutors>
                                        <pluginExecutor>
                                            <plugin>
                                                <groupId>org.apache.maven.plugins</groupId>
                                                <artifactId>maven-antrun-plugin</artifactId>
                                                <version>${maven-antrun-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <id>copy-release-note</id>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>run</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>run</goal>
                                            <configuration>
                                                <target>
                                                    <delete file="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                                    <copy file="${assembly-release-note-path}/${project.artifactId}${assembly-func}.txt"
                                                          tofile="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                                </target>
                                            </configuration>
                                        </pluginExecutor>
                                        <pluginExecutor>
                                            <plugin>
                                                <groupId>org.apache.maven.plugins</groupId>
                                                <artifactId>maven-jar-plugin</artifactId>
                                                <version>${maven-jar-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <id>make-jar</id>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>jar</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>jar</goal>
                                            <configuration>
                                                <finalName>${project.artifactId}</finalName>
                                                <classifier>${assembly-name}</classifier>
                                                <archive>
                                                    <addMavenDescriptor>false</addMavenDescriptor>
                                                    <manifest>
                                                        <addClasspath>true</addClasspath>
                                                        <classpathPrefix>../dependencies/</classpathPrefix>
                                                        <mainClass>com.syscom.fep.gateway.SyscomFepGatewayApplication</mainClass>
                                                    </manifest>
                                                    <manifestEntries>
                                                        <Class-Path>${assembly-prop-classpath}</Class-Path>
                                                    </manifestEntries>
                                                </archive>
                                            </configuration>
                                        </pluginExecutor>
                                        <pluginExecutor>
                                            <plugin>
                                                <artifactId>maven-assembly-plugin</artifactId>
                                                <version>${maven-assembly-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <id>make-assembly</id>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>single</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>single</goal>
                                            <configuration>
                                                <finalName>${project.artifactId}</finalName>
                                                <ignoreMissingDescriptor>true</ignoreMissingDescriptor>
                                                <descriptors>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-bash}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-cmd}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-dependencies}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/assembly-${assembly-bin}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-config}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/${assembly-name}/assembly-${assembly-bin}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/${assembly-name}/assembly-${assembly-config}.xml</descriptor>
                                                </descriptors>
                                                <outputDirectory>${assembly-output-path}</outputDirectory>
                                            </configuration>
                                        </pluginExecutor>
                                    </pluginExecutors>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin-version}</version>
                        <configuration>
                            <source>${java-source-version}</source>
                            <target>${java-target-version}</target>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>