<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.syscom</groupId>
    <artifactId>feptcb</artifactId>
    <version>1.0.0</version>
    <name>feptcb</name>
    <packaging>pom</packaging>
    <properties>
        <revision>1.0.0</revision>
        <safeaa-core-version>1.0.0</safeaa-core-version>
        <fep-enclib-version>1.0.0</fep-enclib-version>
        <!-- 所有第三方套件的版本號全部定義在下方 -->
        <ant-contrib-version>1.0b3</ant-contrib-version>
        <axistools-maven-plugin-version>1.4</axistools-maven-plugin-version>
        <caffeine-version>3.2.0</caffeine-version>
        <classgraph-version>4.8.179</classgraph-version>
        <commons-beanutils-version>1.10.0</commons-beanutils-version>
        <commons-codec-version>1.18.0</commons-codec-version>
        <commons-collections4-version>4.5.0-M3</commons-collections4-version>
        <commons-compress-version>1.27.1</commons-compress-version>
        <commons-discovery-version>0.5</commons-discovery-version>
        <commons-email-version>1.6.0</commons-email-version>
        <commons-io-version>2.18.0</commons-io-version>
        <commons-lang3-version>3.17.0</commons-lang3-version>
        <commons-math3-version>3.6.1</commons-math3-version>
        <commons-net-version>3.11.1</commons-net-version>
        <commons-pool2-version>2.12.1</commons-pool2-version>
        <commons-text-version>1.13.0</commons-text-version>
        <dom4j-version>2.1.4</dom4j-version>
        <esapi-version>2.6.0.0</esapi-version>
        <gson-version>2.12.1</gson-version>
        <hibernate-validator-version>8.0.2.Final</hibernate-validator-version>
        <httpclient5-version>5.4.4</httpclient5-version>
        <ibm-ims-connect-version>3.2.0.7</ibm-ims-connect-version>
        <ibm-mq-jakarta-client-version>9.4.1.0</ibm-mq-jakarta-client-version>
        <iterator-maven-plugin-version>0.5.1</iterator-maven-plugin-version>
        <jackson-version>2.18.2</jackson-version>
        <jakarta.annotation-api-version>2.1.1</jakarta.annotation-api-version>
        <jakarta.servlet-api-version>6.1.0</jakarta.servlet-api-version>
        <jasypt-spring-boot-starter-version>3.0.5</jasypt-spring-boot-starter-version>
        <java-ordered-properties-version>1.0.4</java-ordered-properties-version>
        <java-source-version>11</java-source-version>
        <java-target-version>11</java-target-version>
        <javax.servlet-api-version>4.0.1</javax.servlet-api-version>
        <javax.validation-version>2.0.1.Final</javax.validation-version>
        <jaxb-impl-version>4.0.5</jaxb-impl-version>
        <jaxb40-maven-plugin-version>0.16.1</jaxb40-maven-plugin-version>
        <jcc-version>12.1.0.0</jcc-version>
        <jdom2-version>2.0.6.1</jdom2-version>
        <jersey-version>4.0.0-M2</jersey-version>
        <jt400-version>21.0.0</jt400-version>
        <junit-jupiter-api-version>5.11.4</junit-jupiter-api-version>
        <log4j2.version>2.24.3</log4j2.version>
        <log4jdbc-version>1.2</log4jdbc-version>
        <logback-ext-loggly-version>0.1.5</logback-ext-loggly-version>
        <logback-jackson-version>0.1.5</logback-jackson-version>
        <logback-json-classic-version>0.1.5</logback-json-classic-version>
        <logback-version>1.5.16</logback-version>
        <lombok-version>1.18.36</lombok-version>
        <maven-antrun-plugin-version>3.0.0</maven-antrun-plugin-version>
        <maven-assembly-plugin-version>3.3.0</maven-assembly-plugin-version>
        <maven-clean-plugin-version>3.1.0</maven-clean-plugin-version>
        <maven-compiler-plugin-version>3.10.1</maven-compiler-plugin-version>
        <maven-dependency-plugin-version>3.3.0</maven-dependency-plugin-version>
        <maven-jar-plugin-version>3.2.2</maven-jar-plugin-version>
        <maven-javadoc-plugin-version>3.3.2</maven-javadoc-plugin-version>
        <maven-jaxb2-plugin-version>0.15.3</maven-jaxb2-plugin-version>
        <maven-resources-plugin-version>3.3.1</maven-resources-plugin-version>
        <maven-surefire-plugin-version>3.0.0-M5</maven-surefire-plugin-version>
        <maven-war-plugin-version>3.3.2</maven-war-plugin-version>
        <micrometer-registry-prometheus-version>1.14.3</micrometer-registry-prometheus-version>
        <mq-jms-spring-boot-starter-version>3.3.5</mq-jms-spring-boot-starter-version>
        <mybatis-generator-core-version>1.4.0</mybatis-generator-core-version><!-- 注意這個MBG只能使用1.4.0的版本, 用1.4.2會有Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.的異常 -->
        <mybatis-generator-maven-plugin-version>1.4.0</mybatis-generator-maven-plugin-version><!-- 注意這個MBG只能使用1.4.0的版本, 用1.4.2會有Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.的異常 -->
        <mybatis-spring-boot-starter-test-version>3.0.4</mybatis-spring-boot-starter-test-version>
        <mybatis-spring-boot-starter-version>3.0.4</mybatis-spring-boot-starter-version>
        <netty-version>4.1.118.Final</netty-version>
        <org-slf4j-version>2.0.16</org-slf4j-version>
        <oshi-core-version>6.6.6</oshi-core-version>
        <pagehelper-spring-boot-starter-version>2.1.0</pagehelper-spring-boot-starter-version>
        <pagehelper-version>6.1.0</pagehelper-version>
        <poi-version>5.4.0</poi-version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <properties-maven-plugin-version>1.1.0</properties-maven-plugin-version>
        <spring-boot-configuration-processor-version>3.4.5</spring-boot-configuration-processor-version>
        <spring-boot-dependencies-version>3.4.5</spring-boot-dependencies-version>
        <spring-boot-devtools-version>3.4.5</spring-boot-devtools-version>
        <spring-boot-maven-plugin-version>3.4.5</spring-boot-maven-plugin-version>
        <spring-boot-starter-actuator-vesion>3.4.5</spring-boot-starter-actuator-vesion>
        <spring-boot-starter-aop-version>3.4.5</spring-boot-starter-aop-version>
        <spring-boot-starter-cache-version>3.4.5</spring-boot-starter-cache-version>
        <spring-boot-starter-quartz-version>3.4.5</spring-boot-starter-quartz-version>
        <spring-boot-starter-security-version>3.4.5</spring-boot-starter-security-version>
        <spring-boot-starter-test-version>3.4.5</spring-boot-starter-test-version>
        <spring-boot-starter-thymeleaf-version>3.4.5</spring-boot-starter-thymeleaf-version>
        <spring-boot-starter-version>3.4.5</spring-boot-starter-version>
        <spring-boot-starter-web-services-version>3.4.5</spring-boot-starter-web-services-version>
        <spring-boot-starter-web-version>3.4.5</spring-boot-starter-web-version>
        <spring-cloud-context-version>4.2.0</spring-cloud-context-version>
        <spring-integration-version>6.4.1</spring-integration-version>
        <spring-version>6.2.5</spring-version>
        <spring-webmvc-portlet-version>4.3.30.RELEASE</spring-webmvc-portlet-version>
        <spring-ws-core-version>4.0.11</spring-ws-core-version>
        <springdoc-openapi-ui-version>1.8.0</springdoc-openapi-ui-version>
        <springfox-boot-starter-version>3.0.0</springfox-boot-starter-version>
        <sql-injection-safe-version>1.0.2</sql-injection-safe-version>
        <thymeleaf-layout-dialect-version>3.4.0</thymeleaf-layout-dialect-version>
        <uadetector-resources-version>2014.10</uadetector-resources-version>
        <xstream-version>1.4.21</xstream-version>
        <zip4j-version>2.11.5</zip4j-version>
        <!-- 所有第三方套件的版本號全部定義在上方 -->
        <project-name-config>fep-config</project-name-config>
        <project-name-lib>fep-lib</project-name-lib>
        <project-name-enchelper>fep-enchelper</project-name-enchelper>
        <assembly-fep-app>fep-app</assembly-fep-app>
        <assembly-bin>bin</assembly-bin>
        <assembly-bash>bash</assembly-bash>
        <assembly-cmd>cmd</assembly-cmd>
        <assembly-lib>lib</assembly-lib>
        <assembly-vo>vo</assembly-vo>
        <assembly-config>config</assembly-config>
        <assembly-dependencies>dependencies</assembly-dependencies>
        <assembly-resources>resources</assembly-resources>
        <assembly-mybatis>mybatis</assembly-mybatis>
        <assembly-batch-task>batch-task</assembly-batch-task>
        <assembly-server-aa>server-aa</assembly-server-aa>
        <assembly-base>base</assembly-base>
        <assembly-prop>prop</assembly-prop>
        <assembly-own>own</assembly-own>
        <assembly-format-tar-gz>tar.gz</assembly-format-tar-gz>
        <assembly-format-jar>jar</assembly-format-jar>
        <assembly-file-mode>0755</assembly-file-mode>
        <assembly-lineEnding>unix</assembly-lineEnding>
        <assembly-directory>fep-assembly</assembly-directory>
        <assembly-output-path>../../${assembly-directory}</assembly-output-path>
        <war-directory>fep-war</war-directory>
        <war-output-path>../../${war-directory}</war-output-path>
        <assembly-mybatis-directory>fep-assembly-mybatis</assembly-mybatis-directory>
        <assembly-mybatis-output-path>../../${assembly-mybatis-directory}</assembly-mybatis-output-path>
        <assembly-batch-task-directory>fep-assembly-batch-task</assembly-batch-task-directory>
        <assembly-batch-task-output-path>../../${assembly-batch-task-directory}</assembly-batch-task-output-path>
        <assembly-server-aa-directory>fep-assembly-server-aa</assembly-server-aa-directory>
        <assembly-server-aa-output-path>../../${assembly-server-aa-directory}</assembly-server-aa-output-path>
        <assembly-config-path>../${project-name-config}/src/main/assembly</assembly-config-path>
        <assembly-lib-lib-path>../${project-name-lib}/lib</assembly-lib-lib-path>
        <assembly-enchelper-lib-path>../${project-name-enchelper}/lib</assembly-enchelper-lib-path>
        <assembly-release-note-path>../../fep-release-note</assembly-release-note-path>
        <assembly-file-readme>readme.txt</assembly-file-readme>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin-version}</version>
                <configuration>
                    <source>${java-source-version}</source>
                    <target>${java-target-version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <compilerArgument>-Xlint:unchecked</compilerArgument>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <modules>
        <module>fep-config</module>
        <module>fep-lib</module>
        <module>fep-frmcommon</module>
        <module>fep-vo</module>
        <module>fep-enchelper</module>
        <module>fep-common</module>
        <module>fep-base</module>
        <module>fep-base-aa</module>
        <module>fep-cache</module>
        <module>fep-configuration</module>
        <module>fep-mybatis</module>
        <module>fep-mybatis-enc</module>
        <module>fep-mybatis-ems</module>
        <module>fep-mybatis-deslog</module>
        <module>fep-mybatis-his</module>
        <module>fep-ws-client</module>
        <module>fep-jms</module>
        <module>fep-batch-base</module>
        <module>fep-invoker</module>
        <module>fep-server-aa</module>
        <module>fep-server-common</module>
        <module>fep-batch-task</module>
        <module>fep-scheduler</module>
        <module>fep-notify</module>
        <module>fep-server</module>
        <module>fep-service</module>
        <module>fep-web</module>
        <module>fep-gateway</module>
        <module>fep-batch</module>
        <module>fep-batch-cmdline</module>
        <!--<module>fep-suipConnect</module> -->
    </modules>
    <profiles>
        <profile>
            <id>maven-jar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-clean-plugin</artifactId>
                        <version>${maven-clean-plugin-version}</version>
                        <configuration>
                            <followSymLinks>false</followSymLinks>
                            <filesets>
                                <fileset>
                                    <directory>../${assembly-directory}</directory>
                                </fileset>
                                <fileset>
                                    <directory>../${assembly-mybatis-directory}</directory>
                                </fileset>
                                <fileset>
                                    <directory>../${assembly-batch-task-directory}</directory>
                                </fileset>
                                <fileset>
                                    <directory>../${assembly-server-aa-directory}</directory>
                                </fileset>
                            </filesets>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>war</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-clean-plugin</artifactId>
                        <version>${maven-clean-plugin-version}</version>
                        <configuration>
                            <followSymLinks>false</followSymLinks>
                            <filesets>
                                <fileset>
                                    <directory>../${war-directory}</directory>
                                </fileset>
                                <fileset>
                                    <directory>../${assembly-mybatis-directory}</directory>
                                </fileset>
                                <fileset>
                                    <directory>../${assembly-batch-task-directory}</directory>
                                </fileset>
                                <fileset>
                                    <directory>../${assembly-server-aa-directory}</directory>
                                </fileset>
                            </filesets>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>