<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.syscom</groupId>
        <artifactId>feptcb</artifactId>
        <version>1.0.0</version>
    </parent>
    <groupId>com.syscom.feptcb</groupId>
    <artifactId>fep-server-aa</artifactId>
    <name>fep-server-aa</name>
    <dependencies>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-base-aa</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-enchelper</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-server-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-invoker</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-batch-base</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring-boot-starter-test-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter-api-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-notify-vo</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>${pom.basedir}/../fep-lib/lib/fep-notify-vo.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.astar</groupId>
            <artifactId>tb-convert</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>${pom.basedir}/../fep-lib/lib/tb-convert-1.0.0.jar</systemPath>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin-version}</version>
                <configuration>
                    <source>${java-source-version}</source>
                    <target>${java-target-version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin-version}</version>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>${maven-clean-plugin-version}</version>
                <configuration>
                    <followSymLinks>false</followSymLinks>
                    <filesets>
                        <fileset>
                            <directory>../../${assembly-server-aa-directory}</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <!-- 以下按照package將AA對應包進jar檔中, 例如atmp下的AA程式會包進target/fep-server-aa-1.0.0-atmp.jar, 最後再copy重命名到source/fep-assembly-server-aa/fep-server-aa-atmp.jar -->
            <plugin>
                <groupId>com.soebes.maven.plugins</groupId>
                <artifactId>iterator-maven-plugin</artifactId>
                <version>${iterator-maven-plugin-version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>iterator</goal>
                        </goals>
                        <configuration>
                            <itemsWithProperties>
                                <itemWithProperty>
                                    <name>AABaseFactory</name>
                                    <properties>
                                        <assembly-name>AABaseFactory</assembly-name>
                                        <assembly-package-folder>/</assembly-package-folder>
                                        <assembly-spring-components-file>META-INF/spring.components</assembly-spring-components-file>
                                    </properties>
                                </itemWithProperty>
                                <itemWithProperty>
                                    <name>atmp</name>
                                    <properties>
                                        <assembly-name>atmp</assembly-name>
                                        <assembly-package-folder>${assembly-name}/</assembly-package-folder>
                                    </properties>
                                </itemWithProperty>
                                <itemWithProperty>
                                    <name>eatm</name>
                                    <properties>
                                        <assembly-name>eatm</assembly-name>
                                        <assembly-package-folder>${assembly-name}/</assembly-package-folder>
                                    </properties>
                                </itemWithProperty>
                                <itemWithProperty>
                                    <name>hce</name>
                                    <properties>
                                        <assembly-name>hce</assembly-name>
                                        <assembly-package-folder>${assembly-name}/</assembly-package-folder>
                                    </properties>
                                </itemWithProperty>
                                <itemWithProperty>
                                    <name>inbk</name>
                                    <properties>
                                        <assembly-name>inbk</assembly-name>
                                        <assembly-package-folder>${assembly-name}/</assembly-package-folder>
                                    </properties>
                                </itemWithProperty>
                                <itemWithProperty>
                                    <name>nb</name>
                                    <properties>
                                        <assembly-name>nb</assembly-name>
                                        <assembly-package-folder>${assembly-name}/</assembly-package-folder>
                                    </properties>
                                </itemWithProperty>
                                <itemWithProperty>
                                    <name>rm</name>
                                    <properties>
                                        <assembly-name>rm</assembly-name>
                                        <assembly-package-folder>${assembly-name}/</assembly-package-folder>
                                    </properties>
                                </itemWithProperty>
                                <itemWithProperty>
                                    <name>va</name>
                                    <properties>
                                        <assembly-name>va</assembly-name>
                                        <assembly-package-folder>${assembly-name}/</assembly-package-folder>
                                    </properties>
                                </itemWithProperty>
                                <itemWithProperty>
                                    <name>ims</name>
                                    <properties>
                                        <assembly-name>ims</assembly-name>
                                        <assembly-package-folder>${assembly-name}/</assembly-package-folder>
                                    </properties>
                                </itemWithProperty>
                            </itemsWithProperties>
                            <pluginExecutors>
                                <pluginExecutor>
                                    <plugin>
                                        <artifactId>maven-assembly-plugin</artifactId>
                                        <version>${maven-assembly-plugin-version}</version>
                                        <executions>
                                            <execution>
                                                <id>make-assembly</id>
                                                <phase>package</phase>
                                                <goals>
                                                    <goal>single</goal>
                                                </goals>
                                            </execution>
                                        </executions>
                                    </plugin>
                                    <goal>single</goal>
                                    <configuration>
                                        <descriptors>
                                            <descriptor>${assembly-config-path}/${project.artifactId}/assembly-${assembly-server-aa}.xml</descriptor>
                                        </descriptors>
                                        <outputDirectory>${project.build.directory}</outputDirectory>
                                    </configuration>
                                </pluginExecutor>
                                <pluginExecutor>
                                    <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-antrun-plugin</artifactId>
                                        <version>${maven-antrun-plugin-version}</version>
                                        <executions>
                                            <execution>
                                                <phase>package</phase>
                                                <goals>
                                                    <goal>run</goal>
                                                </goals>
                                            </execution>
                                        </executions>
                                    </plugin>
                                    <goal>run</goal>
                                    <configuration>
                                        <target>
                                            <copy file="${project.build.directory}/${project.artifactId}-${project.version}-${assembly-name}.jar"
                                                  tofile="${assembly-server-aa-output-path}/${project.artifactId}-${assembly-name}.jar"/>
                                        </target>
                                    </configuration>
                                </pluginExecutor>
                            </pluginExecutors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- 將source/fep-assembly-server-aa下的fep-server-aa-AABaseFactory.jar重命名為fep-server-aa.jar -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${maven-antrun-plugin-version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <configuration>
                            <target>
                                <move file="${assembly-server-aa-output-path}/${project.artifactId}-AABaseFactory.jar"
                                      tofile="${assembly-server-aa-output-path}/${project.artifactId}.jar"/>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>