package com.syscom.fep.mybatis.his.mapper;

import com.syscom.fep.mybatis.his.model.Ucdid;
import org.apache.ibatis.annotations.Param;

public interface UcdidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCDID
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Ucdid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCDID
     *
     * @mbg.generated
     */
    int insert(Ucdid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCDID
     *
     * @mbg.generated
     */
    int insertSelective(Ucdid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCDID
     *
     * @mbg.generated
     */
    Ucdid selectByPrimaryKey(@Param("ucdidIdno") String ucdidIdno, @Param("ucdidHealthid") String ucdidHealthid, @Param("ucdid2566Txdate") String ucdid2566Txdate, @Param("ucdid2566Stan") String ucdid2566Stan);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCDID
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ucdid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCDID
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ucdid record);
}