server.port=8302

spring.fep.application.name=fep-gateway

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-atm-agent
management.endpoint.health.show-details=always


#ATM Gateway Server Agent
spring.register.bean[0]=com.syscom.fep.gateway.agent.atm.ATMGatewayServerAgentConfiguration
spring.register.bean[1]=com.syscom.fep.gateway.agent.atm.ATMGatewayServerAgentJobLauncher
spring.register.controller[0]=com.syscom.fep.gateway.agent.atm.ATMGatewayServerAgent

#ATM Gateway Server Agent Configuration
spring.fep.gateway.agent.atm.cmdStart=/fep/fep-app/fep-gateway-atm/fep_gateway_atm_run.sh
spring.fep.gateway.agent.atm.httpChangeFEPAP=http://${spring.fep.hostip}:8300/recv/atm/changefepap
spring.fep.gateway.agent.atm.httpCheckFEPAP=http://${spring.fep.hostip}:8300/recv/atm/checkfepap

#ATM Gateway Server Agent Configuration ProcessCommandJobs
spring.fep.gateway.agent.atm.cmdJobConfig[0].cronExpression=0 0 2 * * ?
spring.fep.gateway.agent.atm.cmdJobConfig[0].command=/fep/fep-app/fep-batch-cmdline/fep_archivinglogfile_run.sh
spring.fep.gateway.agent.atm.cmdJobConfig[1].cronExpression=0 0 3 * * ?
spring.fep.gateway.agent.atm.cmdJobConfig[1].command=

#register Scheduler Job
spring.fep.scheduler.job.register[0].className=com.syscom.fep.scheduler.job.impl.AppMonitorJob
spring.fep.scheduler.job.register[0].configClassName=com.syscom.fep.scheduler.job.impl.AppMonitorJobConfig
spring.fep.scheduler.job.register[1].className=com.syscom.fep.scheduler.job.impl.SystemMonitorJob
spring.fep.scheduler.job.register[1].configClassName=com.syscom.fep.scheduler.job.impl.SystemMonitorJobConfig

#AppMonitorJob
spring.fep.scheduler.job.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.scheduler.job.app-monitor.serviceName=${management.metrics.tags.application}
spring.fep.scheduler.job.app-monitor.serviceHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.app-monitor.serviceHostName=${spring.fep.hostname}
spring.fep.scheduler.job.app-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}
spring.fep.scheduler.job.app-monitor.monitorPrimaryUrl=http://10.0.54.33:8730/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.monitorSecondaryUrl=http://10.0.54.34:8730/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.recordHttpLog=true


#SystemMonitorJob
spring.fep.scheduler.job.system-monitor.cronExpression=0 0/1 * * * ?
spring.fep.scheduler.job.system-monitor.systemHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.system-monitor.systemHostName=${spring.fep.hostname}
spring.fep.scheduler.job.system-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}
spring.fep.scheduler.job.system-monitor.monitorUrl=http://10.0.54.35:8730/recv/mon/system
spring.fep.scheduler.job.system-monitor.monitorPrimaryUrl=http://10.0.54.33:8730/recv/mon/system
spring.fep.scheduler.job.system-monitor.monitorUrlSecondaryUrl=http://10.0.54.34:8730/recv/mon/systeme
spring.fep.scheduler.job.system-monitor.systemMount=/fep,/fep/logs
