server.port=8084

spring.fep.application.name=fep-batch

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}
management.endpoint.health.show-details=always

spring.fep.batch.subsys=1;2;3;4;5;6;7;8;9
spring.fep.batch.mailsender=fep@tcb-bank.com.tw
spring.fep.batch.maillist=AP1_FEP@tcb-bank.com.tw
spring.fep.batch.updateNextRunTimeInitialDelayMilliseconds=30000
spring.fep.batch.updateNextRunTimeIntervalMilliseconds=60000

spring.fep.batch.resultFilePath=/fep/logs/batch/batchResult.log