#base
spring.fep.systemid=FEP
spring.fep.hostip=10.0.54.1
spring.fep.hostname=fepgw1P

#embedded server
spring.fep.embedded.server.baseDir=/fep/tmp/${management.metrics.tags.application}/basedir/
spring.fep.embedded.server.docRoot=/fep/tmp/${management.metrics.tags.application}/docroot/

#log
logging.config=classpath:logback-spring.xml
spring.fep.log.path=/fep/logs
spring.fep.log.jdbc.sqltiming.level=DEBUG
spring.fep.log.mybatis.level=DEBUG

#restful
spring.fep.restful.timeout=30000

#restful server url
spring.fep.server.url.atm=http://10.0.54.35:8731/recv/atm

#server protocl
#restful, when FEP Server recv message from Gateway via restful
#socket, when FEP Server recv message from Gateway via socket
spring.fep.server.protocol.atm=socket
spring.fep.server.protocol.fisc=socket

#BATCH
spring.fep.batch.base.host[0].name=fepap1P
spring.fep.batch.base.host[0].ip=10.0.54.33
spring.fep.batch.base.host[0].url=http://${spring.fep.batch.base.host[0].ip}:8084
spring.fep.batch.base.host[1].name=fepap2P
spring.fep.batch.base.host[1].ip=10.0.54.34
spring.fep.batch.base.host[1].url=http://${spring.fep.batch.base.host[1].ip}:8084
spring.fep.batch.base.task.path=/fep/fep-app/fep-batch-task
spring.fep.batch.base.task.jarNameTemplate=fep-batch-task-{0}.jar

#socket gateway to FEP server 
#spring.fep.server.netty.atm.host=${spring.fep.hostip}
spring.fep.server.netty.atm.host=10.0.54.35
spring.fep.server.netty.atm.port=8731
spring.fep.server.netty.atm.reestablishConnectionInterval=5000
spring.fep.server.netty.atm.acceptIp=
spring.fep.server.netty.atm.serverBisThreadNum=300
spring.fep.server.netty.atm.clientBisThreadNum=300

#ATM
spring.fep.server.netty.atm.rcvBufAllocator=16384
spring.fep.server.netty.atm.soRcvBuf=16384
spring.fep.server.netty.atm.soSndBuf=16384