server.port=8203

spring.fep.application.name=fep-service

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-log
management.endpoint.health.show-details=always

#register Bean
spring.register.bean[0]=com.syscom.fep.service.ems.queue.EMSLogReceiver

#EMS Service Configuration
spring.fep.service.ems.resetNotifyInterval=3
spring.fep.service.ems.repeatInterval=3
spring.fep.service.ems.mailSender=fep2022@qq.com
spring.fep.service.ems.mailList=richard_yu@email.lingan.com.cn,myfifa2005@qq.com
spring.fep.service.ems.mailListNps2262=richard_yu@email.lingan.com.cn,myfifa2005@qq.com
spring.fep.service.ems.warningPattern=\u7121\u6CD5\u53D6\u5F97ENCLib;RC:10,;RC:11,;RC:17,;RC:81,;RC:82,;RC:83,;RC:84,;RC:94,;RC:95,;RC:98,;RC:99,

# enable mail
spring.fep.mail.enable=true

# enable mitake sms
spring.fep.sms.mitake.enable=true

#EMS Receiver
spring.fep.jms.ems.receiver.prop.queueManager=QM1
spring.fep.jms.ems.receiver.prop.channel=DEV.ADMIN.SVRCONN
spring.fep.jms.ems.receiver.prop.connName=10.3.101.3(1414)
spring.fep.jms.ems.receiver.prop.user=admin
spring.fep.jms.ems.receiver.prop.password=ENC(qTrx9C64J6cFB8P4TTt6KGEUyAqe2TdRtf5FhZAtl10LZI15gP9KVJXklM9+dbuV)
spring.fep.jms.ems.receiver.prop.queue-names.ems.destination=FEP.EMS.LOG.QL
spring.fep.jms.ems.receiver.prop.queue-names.ems.concurrency=5-10

spring.fep.log.jdbc.sqltiming.level=OFF
spring.fep.log.mybatis.level=WARN
spring.fep.log.jdbc.level=OFF

spring.fep.mybatis.interceptor.audittrail.enable=false
spring.fep.mybatis.interceptor.logger.enable=false