server.port=8101

spring.fep.application.name=fep-server

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-fisc
management.endpoint.health.show-details=always

#log
spring.fep.log.total.size.cap=100GB

#register Controller recv message from Gateway via restful
spring.register.controller[0]=com.syscom.fep.server.controller.restful.FISCController

#register Netty Server recv message from Gateway via socket
spring.register.bean[0]=com.syscom.fep.server.netty.impl.FISCNettyServer