#base
spring.fep.systemid=FEP10
spring.fep.hostip=10.3.101.3
spring.fep.hostname=fepap1

#embedded server
spring.fep.embedded.server.baseDir=/home/syscom/tmp/${management.metrics.tags.application}/basedir/
spring.fep.embedded.server.docRoot=/home/syscom/tmp/${management.metrics.tags.application}/docroot/

#log
logging.config=classpath:logback-spring.xml
spring.fep.log.path=/home/syscom/fep-app/logs
spring.fep.log.jdbc.sqltiming.level=OFF
spring.fep.log.mybatis.level=OFF
spring.fep.log.jdbc.level=DEBUG

#thread pool
spring.fep.thread-pool.threadNamePrefix=fep-thread-pool-
spring.fep.thread-pool.corePoolSize=10
spring.fep.thread-pool.maxPoolSize=20
spring.fep.thread-pool.queueCapacity=50
spring.fep.thread-pool.keepAlive=60
spring.fep.thread-pool.waitForJobsToCompleteOnShutdown=true

#ENCLib
spring.fep.enclib.enable=true
spring.fep.enclib.atmagent.enable=false

#t24
spring.fep.t24.method.comparetota.enable=false

#ims
spring.fep.ims.tx.clientid=IFEPTA{0},1,5
spring.fep.ims.pbo.clientid=IFEPTB{0},1,5

#restful
spring.fep.restful.timeout=30000

#mail
spring.fep.mail.smtp=
spring.fep.mail.port=-1
spring.fep.mail.account=
spring.fep.mail.sscode=

#hiair sms
spring.fep.sms.hiair.socketHost=202.39.54.130
spring.fep.sms.hiair.socketPort=8000
spring.fep.sms.hiair.username=user
spring.fep.sms.hiair.sscode=12345678
spring.fep.sms.hiair.mobile=9876543210
spring.fep.sms.hiair.socketSoTimeout=30000

#mitake sms
spring.fep.sms.mitake.domain=https://stgtcb.mitake.com.tw:8105/tcb/mtk/SmSend
spring.fep.sms.mitake.username=TCBTEST
spring.fep.sms.mitake.sscode=ENC(dCo3yokr6hD4bNOT/l7RLUdtROyG6rBfnl1YlQdj74OMRGJVfKfy5/juQwOEwLqS)
spring.fep.sms.mitake.charsetUrl=UTF-8
spring.fep.sms.mitake.httpConnectTimeout=30000
spring.fep.sms.mitake.httpReadTimeout=60000

#Notify Helper
spring.fep.notify.url.sendNotify=http://${spring.fep.hostip}:9090/sendNotify
spring.fep.notify.url.logNotify=http://${spring.fep.hostip}:9090/logNotify
spring.fep.notify.url.sendMiddlePlatForm=http://${spring.fep.hostip}:9090/sendMiddlePlatForm

#BATCH
spring.fep.batch.base.host[0].name=fepap1
spring.fep.batch.base.host[0].ip=${spring.fep.hostip}
spring.fep.batch.base.host[0].url=http://${spring.fep.batch.base.host[0].ip}:8084
spring.fep.batch.base.host[1].name=fepap2
spring.fep.batch.base.host[1].ip=${spring.fep.hostip}
spring.fep.batch.base.host[1].url=http://${spring.fep.batch.base.host[1].ip}:8085
spring.fep.batch.base.task.path=/home/syscom/fep-app/fep-batch-task
spring.fep.batch.base.task.jarNameTemplate=fep-batch-task-{0}.jar

#server url
spring.fep.server.url.atm=http://${spring.fep.hostip}:8100/recv/atm
spring.fep.server.url.fisc=http://${spring.fep.hostip}:8101/recv/fisc

#server protocl
#restful, when FEP Server recv message from Gateway via restful
#socket, when FEP Server recv message from Gateway via socket
spring.fep.server.protocol.atm=socket
spring.fep.server.protocol.fisc=socket

#ATM
spring.fep.server.netty.atm.host=${spring.fep.hostip}
spring.fep.server.netty.atm.port=8731
spring.fep.server.netty.atm.serverBisThreadNum=300
spring.fep.server.netty.atm.clientBisThreadNum=300
spring.fep.server.netty.atm.rcvBufAllocator=81920
spring.fep.server.netty.atm.useDynamicEventExecutorGroup=true
spring.fep.server.atm.executorCorePoolSize=300
spring.fep.server.atm.executorQueueCapacity=300

#FISC
spring.fep.server.netty.fisc.host=${spring.fep.hostip}
spring.fep.server.netty.fisc.port=28081
spring.fep.server.netty.fisc.serverBisThreadNum=10
spring.fep.server.netty.fisc.useDynamicEventExecutorGroup=true
spring.fep.server.encoding.fisc=ascii
spring.fep.server.fiscHelper.isWrLog=false

#ATMMon
spring.fep.server.netty.atmmon.host=${spring.fep.hostip}
spring.fep.server.netty.atmmon.port=28087
spring.fep.server.netty.atmmon.serverBisThreadNum=10
spring.fep.server.netty.atmmon.useDynamicEventExecutorGroup=true

#PKI
spring.fep.pki.path=/PKI/fatinst1/acdu,/PKI/fatinst1/acdp,/PKI/fbdinst1/acdu,/PKI/fbdinst1/acdp,/PKI/fhpinst1/acdu,/PKI/fhpinst1/acdp

#Monitor Service Name to Alias Map
spring.fep.monitor.serviceNameToAliasMap.suipsrv=suipsrvA
spring.fep.monitor.serviceNameToAliasMap.suipsrv1=suipsrvB

#FISC Adapter

spring.fep.fisc-adapter.nodes[0].clientId=B006A01O
spring.fep.fisc-adapter.nodes[0].primaryHost=${spring.fep.hostip}
spring.fep.fisc-adapter.nodes[0].port=8732
spring.fep.fisc-adapter.nodes[0].secondaryHost=${spring.fep.hostip}
spring.fep.fisc-adapter.nodes[1].clientId=B006A02O
spring.fep.fisc-adapter.nodes[1].primaryHost =${spring.fep.hostip}
spring.fep.fisc-adapter.nodes[1].port=8734
spring.fep.fisc-adapter.nodes[1].secondaryHost=${spring.fep.hostip}
spring.fep.fisc-adapter.nodes[2].clientId=B006A03O
spring.fep.fisc-adapter.nodes[2].primaryHost=${spring.fep.hostip}
spring.fep.fisc-adapter.nodes[2].port=8736
spring.fep.fisc-adapter.nodes[2].secondaryHost=${spring.fep.hostip}
#\u9023\u63A5\u5931\u6557\u6642, delay\u79D2\u6578\u5F8C\u91CD\u9023
spring.fep.fisc-adapter.delay=5
#\u7576\u670D\u52D9\u555F\u52D5\u5F8C\u5EFA\u7ACB\u4E00\u500B\u56FA\u5B9ATimer\u6BCF\u9694N\u79D2\u9032\u884C\u8173\u4F4D\u5065\u5EB7\u5075\u6E2C\u975EHEALTHY\u7684\u53C3\u6578\u662F\u5426\u6062\u5FA9\u6B63\u5E38
spring.fep.fisc-adapter.checkPrimaryInterval=60
#\u6536\u53D6\u53E6\u4E00\u53F0\u4E3B\u6A5F\u7684response queue\u7684\u903E\u6642\u6642\u9593
spring.fep.fisc-adapter.alternativeQueueReceiveTimeout=5000
#FISCGW\u7684Protocol
spring.fep.fisc-adapter.protocol=restful
#\u82E5protocol\u8A2D\u70BArestful\u6642, \u624D\u9700\u8981\u4EE5\u4E0B\u7684\u53C3\u6578,{0}\u53CA{1}\u7531FISCAdapter\u5224\u65B7\u5F8C\u4EE3\u5165host\u53CAport
spring.fep.fisc-adapter.svcUrl=http://{0}:{1}/api/VFISC/SendReceive

#CBS Adapter
spring.fep.cbs-adapter.primary[0].host=${spring.fep.hostip}
spring.fep.cbs-adapter.primary[0].port=8752
spring.fep.cbs-adapter.primary[0].cbsType=CBS
spring.fep.cbs-adapter.primary[1].host=${spring.fep.hostip}
spring.fep.cbs-adapter.primary[1].port=8754
spring.fep.cbs-adapter.primary[1].cbsType=473X
spring.fep.cbs-adapter.primary[2].host=${spring.fep.hostip}
spring.fep.cbs-adapter.primary[2].port=8756
spring.fep.cbs-adapter.primary[2].cbsType=FISC
spring.fep.cbs-adapter.primary[3].host=${spring.fep.hostip}
spring.fep.cbs-adapter.primary[3].port=8758
spring.fep.cbs-adapter.primary[3].cbsType=NONATM
spring.fep.cbs-adapter.primary[4].host=${spring.fep.hostip}
spring.fep.cbs-adapter.primary[4].port=8760
spring.fep.cbs-adapter.primary[4].cbsType=FISCTCB
spring.fep.cbs-adapter.secondary[0].host=${spring.fep.hostip}
spring.fep.cbs-adapter.secondary[0].port=8752
spring.fep.cbs-adapter.secondary[0].cbsType=CBS
spring.fep.cbs-adapter.secondary[1].host=${spring.fep.hostip}
spring.fep.cbs-adapter.secondary[1].port=8754
spring.fep.cbs-adapter.secondary[1].cbsType=473X
spring.fep.cbs-adapter.secondary[2].host=${spring.fep.hostip}
spring.fep.cbs-adapter.secondary[2].port=8756
spring.fep.cbs-adapter.secondary[2].cbsType=FISC
spring.fep.cbs-adapter.secondary[3].host=${spring.fep.hostip}
spring.fep.cbs-adapter.secondary[3].port=8758
spring.fep.cbs-adapter.secondary[3].cbsType=NONATM
spring.fep.cbs-adapter.secondary[4].host=${spring.fep.hostip}
spring.fep.cbs-adapter.secondary[4].port=8760
spring.fep.cbs-adapter.secondary[4].cbsType=FISCTCB
spring.fep.cbs-adapter.delay=3
spring.fep.cbs-adapter.checkPrimaryInterval=60