management.metrics.tags.application=fep-batch-cmdline-simple

spring.fep.batch.base.host[0].name=
spring.fep.batch.base.host[0].ip=
spring.fep.batch.base.host[0].url=
spring.fep.batch.base.task.path=/home/syscom/fep-app/fep-batch-task
spring.fep.batch.base.task.jarNameTemplate=fep-batch-task-{0}.jar