server.port=8084

spring.fep.application.name=fep-batch

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}
management.endpoint.health.show-details=always

spring.fep.batch.subsys=1;2
spring.fep.batch.mailsender=
spring.fep.batch.maillist=
spring.fep.batch.updateNextRunTimeInitialDelayMilliseconds=30000
spring.fep.batch.updateNextRunTimeIntervalMilliseconds=60000
spring.fep.batch.execute.shell.path=/home/syscom/fep-app/fep-batch-cmdline/fep-batch-cmdline-run.sh
spring.fep.batch.resultFilePath=/home/syscom/batch/batchResult.log
spring.fep.batch.checkAndNotifyAllMisfiredInitialDelaySeconds=1800
spring.fep.batch.checkAndNotifyAllMisfiredIntervalSeconds=1800
spring.fep.batch.checkAndNotifyAllMisfiredToleranceSeconds=60

# enable mail
spring.fep.mail.enable=true

# enable mitake sms
spring.fep.sms.mitake.enable=true