#base
spring.fep.systemid=FEP
spring.fep.hostip=10.0.54.33
spring.fep.hostname=fepap1P

#embedded server
spring.fep.embedded.server.baseDir=/fep/tmp/${management.metrics.tags.application}/basedir/
spring.fep.embedded.server.docRoot=/fep/tmp/${management.metrics.tags.application}/docroot/

#log
#logging.level.root=DEBUG
logging.config=classpath:logback-spring.xml
spring.fep.log.path=/fep/logs
spring.fep.log.jdbc.sqltiming.level=DEBUG
spring.fep.log.mybatis.level=DEBUG
#spring.fep.log.jdbc.sqltiming.level=OFF
#spring.fep.log.mybatis.level=OFF
spring.fep.log.jdbc.level=DEBUG

#ENCLib
spring.fep.enclib.enable=true
spring.fep.enclib.atmagent.enable=true

#t24
spring.fep.t24.method.comparetota.enable=false

#ims TB03 & TB04
spring.fep.ims.tx.clientid=IFEPPA{0},1,20
spring.fep.ims.pbo.clientid=IFEPPC{0},1,20
spring.fep.ims.changekey.clientid=IFEPPE{0},1,2

#restful
spring.fep.restful.timeout=30000

#mail
spring.fep.mail.smtp=172.29.0.82
spring.fep.mail.port=25
spring.fep.mail.account=fep
spring.fep.mail.sscode=

#mitake sms
spring.fep.sms.mitake.domain=https://tcb.mitake.com.tw:8105/tcb/mtk/SmSend
spring.fep.sms.mitake.username=ATMMSG
spring.fep.sms.mitake.sscode=ENC(c4etelebFyoH+oVzocV0fCj734mzpYTnT96U1v0zRgTumWMBOj0fcz3MlTtz/LI7)
spring.fep.sms.mitake.charsetUrl=UTF-8
spring.fep.sms.mitake.httpConnectTimeout=30000
spring.fep.sms.mitake.httpReadTimeout=60000


#Notify Helper
spring.fep.notify.url.sendNotify=http://${spring.fep.hostip}:9090/sendNotify
spring.fep.notify.url.logNotify=http://${spring.fep.hostip}:9090/logNotify

#BATCH
spring.fep.batch.base.host[0].name=fepap1P
spring.fep.batch.base.host[0].ip=10.0.54.33
spring.fep.batch.base.host[0].url=http://${spring.fep.batch.base.host[0].ip}:8084
spring.fep.batch.base.host[1].name=fepap2P
spring.fep.batch.base.host[1].ip=10.0.54.34
spring.fep.batch.base.host[1].url=http://${spring.fep.batch.base.host[1].ip}:8084
spring.fep.batch.base.task.path=/fep/fep-app/fep-batch-task
spring.fep.batch.base.task.jarNameTemplate=fep-batch-task-{0}.jar

#server url
spring.fep.server.url.atm=http://${spring.fep.hostip}:8731/recv/atm
spring.fep.server.url.fisc=http://${spring.fep.hostip}:8733/recv/fisc

#server protocl
#restful, when FEP Server recv message from Gateway via restful
#socket, when FEP Server recv message from Gateway via socket
spring.fep.server.protocol.atm=socket
spring.fep.server.protocol.fisc=socket



spring.fep.ims.enableSSL=false
spring.fep.ims.keyStore=
spring.fep.ims.trustKeyStore=
spring.fep.ims.keyStoreCode=
spring.fep.ims.enableTrace=false

#ATM
spring.fep.server.netty.atm.host=${spring.fep.hostip}
spring.fep.server.netty.atm.port=8731
spring.fep.server.netty.atm.reestablishConnectionInterval=5000
spring.fep.server.netty.atm.acceptIp=
spring.fep.server.netty.atm.serverBisThreadNum=600
spring.fep.server.netty.atm.clientBisThreadNum=300
spring.fep.server.netty.atm.rcvBufAllocator=16384
spring.fep.server.netty.atm.useDynamicEventExecutorGroup=true
spring.fep.server.netty.atm.dynamicEventExecutorIdleCheckInterval=5000

#FISC
spring.fep.server.netty.fisc.host=${spring.fep.hostip}
spring.fep.server.netty.fisc.port=8733
spring.fep.server.netty.fisc.reestablishConnectionInterval=5000
spring.fep.server.netty.fisc.acceptIp=
spring.fep.server.encoding.fisc=ebcdic
spring.fep.server.netty.fisc.serverBisThreadNum=100
spring.fep.server.netty.fisc.useDynamicEventExecutorGroup=true

#ATMMon
spring.fep.server.netty.atmmon.host=${spring.fep.hostip}
spring.fep.server.netty.atmmon.port=28087
spring.fep.server.netty.atmmon.reestablishConnectionInterval=5000
spring.fep.server.netty.atmmon.acceptIp=

#Old PKI
#spring.fep.pki.path=/PKI
#spring.fep.pki.file-acdu=acdu
#spring.fep.pki.file-acdp=acdp
#spring.fep.pki.db-instance-name1=fapinst1
#spring.fep.pki.db-instance-name1-db=FEPDB,DESDB
#spring.fep.pki.db-instance-name2=fbpinst1
#spring.fep.pki.db-instance-name2-db=EMSDB,DESLOGDB,FEPHIS

#new PKI
spring.fep.pki.path=/PKI/fapinst1/acdu,/PKI/fapinst1/acdp,/PKI/fbpinst1/acdu,/PKI/fbpinst1/acdp,/PKI/fhpinst1/acdu,/PKI/fhpinst1/acdp

#Monitor Service Name to Alias Map
spring.fep.monitor.serviceNameToAliasMap.suipsrv=suipsrvA
spring.fep.monitor.serviceNameToAliasMap.suipsrv1=suipsrvB

#FISC Adapter
spring.fep.fisc-adapter.nodes[0].clientId=B006A02O
spring.fep.fisc-adapter.nodes[0].primaryHost=172.29.14.1
spring.fep.fisc-adapter.nodes[0].port=8732
spring.fep.fisc-adapter.nodes[0].secondaryHost=172.29.14.2
spring.fep.fisc-adapter.nodes[1].clientId=B006A03O
spring.fep.fisc-adapter.nodes[1].primaryHost=172.29.14.2
spring.fep.fisc-adapter.nodes[1].port=8734
spring.fep.fisc-adapter.nodes[1].secondaryHost=172.29.14.1
spring.fep.fisc-adapter.nodes[2].clientId=B006A04O
spring.fep.fisc-adapter.nodes[2].primaryHost=172.29.14.2
spring.fep.fisc-adapter.nodes[2].port=8736
spring.fep.fisc-adapter.nodes[2].secondaryHost=172.29.14.1

spring.fep.fisc-adapter.delay=5
spring.fep.fisc-adapter.alternativeQueueReceiveTimeout=5000
spring.fep.fisc-adapter.protocol=socket

#CBS Adapter
spring.fep.cbs-adapter.primary[0].host=${spring.fep.hostip}
spring.fep.cbs-adapter.primary[0].port=8752
spring.fep.cbs-adapter.primary[0].cbsType=CBS
spring.fep.cbs-adapter.primary[1].host=${spring.fep.hostip}
spring.fep.cbs-adapter.primary[1].port=8754
spring.fep.cbs-adapter.primary[1].cbsType=473X
spring.fep.cbs-adapter.primary[2].host=${spring.fep.hostip}
spring.fep.cbs-adapter.primary[2].port=8756
spring.fep.cbs-adapter.primary[2].cbsType=FISC
spring.fep.cbs-adapter.primary[3].host=${spring.fep.hostip}
spring.fep.cbs-adapter.primary[3].port=8758
spring.fep.cbs-adapter.primary[3].cbsType=FISCTCB
spring.fep.cbs-adapter.primary[4].host=${spring.fep.hostip}
spring.fep.cbs-adapter.primary[4].port=8760
spring.fep.cbs-adapter.primary[4].cbsType=NONATM

#CBS Adapter secondary
spring.fep.cbs-adapter.secondary[0].host=10.0.54.34
spring.fep.cbs-adapter.secondary[0].port=8752
spring.fep.cbs-adapter.secondary[0].cbsType=CBS
spring.fep.cbs-adapter.secondary[1].host=10.0.54.34
spring.fep.cbs-adapter.secondary[1].port=8754
spring.fep.cbs-adapter.secondary[1].cbsType=473X
spring.fep.cbs-adapter.secondary[2].host=10.0.54.34
spring.fep.cbs-adapter.secondary[2].port=8756
spring.fep.cbs-adapter.secondary[2].cbsType=FISC
spring.fep.cbs-adapter.secondary[3].host=10.0.54.34
spring.fep.cbs-adapter.secondary[3].port=8758
spring.fep.cbs-adapter.secondary[3].cbsType=FISCTCB
spring.fep.cbs-adapter.secondary[4].host=10.0.54.34
spring.fep.cbs-adapter.secondary[4].port=8760
spring.fep.cbs-adapter.secondary[4].cbsType=NONATM


spring.fep.cbs-adapter.delay=3
spring.fep.cbs-adapter.checkPrimaryInterval=60
