server.port=8153

spring.fep.application.name=fep-server

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-pyBatch
management.endpoint.health.show-details=always

spring.register.bean[0]=com.syscom.fep.server.queue.PYBatchReceiver


#PYBATCH MAP Queue
#spring.fep.jms.pybatch.debug=-1
spring.fep.jms.pybatch.optionType=0
spring.fep.jms.pybatch.prop[0].queueManager=QMFEPP01
spring.fep.jms.pybatch.prop[0].channel=SVRCONN.FEPAP
spring.fep.jms.pybatch.prop[0].connName=10.0.54.33(1414)
spring.fep.jms.pybatch.prop[0].user=
spring.fep.jms.pybatch.prop[0].password=

spring.datasource.fepdb.hikari.maximum-pool-size=150
spring.datasource.desdb.hikari.maximum-pool-size=150