server.port=8151

spring.fep.application.name=fep-server

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-eoi
management.endpoint.health.show-details=always

spring.register.bean[0]=com.syscom.fep.server.queue.EOIServerReceiver


#EOI MAP Queue
#spring.fep.jms.eoi.debug=-1
spring.fep.jms.eoi.prop[0].queueManager=QMFEPP01
spring.fep.jms.eoi.prop[0].channel=SVRCONN.FEPAP
spring.fep.jms.eoi.prop[0].connName=10.0.54.33(1414)
spring.fep.jms.eoi.prop[0].user=
spring.fep.jms.eoi.prop[0].password=

spring.datasource.fepdb.hikari.maximum-pool-size=30
spring.datasource.desdb.hikari.maximum-pool-size=30