server.port=8214


spring.fep.application.name=fep-server
logging.config=classpath:logback-spring-posgw.xml

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-posgw
management.endpoint.health.show-details=always

# register Pos Gateway Spring Bean
spring.register.bean[0]=com.syscom.fep.server.gateway.pos.PosGateway

# Configuration for Pos Gateway
spring.fep.server.gateway.pos.host=${spring.fep.hostip}
spring.fep.server.gateway.pos.port=2919
spring.fep.server.gateway.pos.byPassCheckClientIp=10.0.54.53,10.0.54.54


