server.port=8220

spring.fep.application.name=fep-server

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-fido
management.endpoint.health.show-details=always

spring.register.bean[0]=com.syscom.fep.server.queue.FIDOServerReceiver

spring.datasource.hikari.maximum-pool-size=15

#FIDO MAP Queue

spring.fep.jms.fido.prop[0].queueManager=QMFEPP01
spring.fep.jms.fido.prop[0].channel=SVRCONN.FEPAP
spring.fep.jms.fido.prop[0].connName=10.0.54.33(1414)
spring.fep.jms.fido.prop[0].user=
spring.fep.jms.fido.prop[0].password=

spring.datasource.fepdb.hikari.maximum-pool-size=10
spring.datasource.desdb.hikari.maximum-pool-size=10