server.port=8213

spring.fep.application.name=fep-server

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-imsgw
management.endpoint.health.show-details=always

spring.fep.ims.enableTrace=false

# register IMS Gateway Spring Bean
spring.register.bean[0]=com.syscom.fep.server.gateway.ims.IMSGatewayConfiguration
spring.register.bean[1]=com.syscom.fep.server.gateway.ims.IMSGatewayManager
spring.register.bean[2]=com.syscom.fep.server.gateway.ims.keepalive.IMSGatewayKeepAliveServerConfiguration
spring.register.bean[3]=com.syscom.fep.server.gateway.ims.keepalive.IMSGatewayKeepAliveClientConfiguration
spring.register.bean[4]=com.syscom.fep.server.gateway.ims.keepalive.IMSGatewayKeepAliveRestfulClient

# register Restful Controller for Operation Command
spring.register.controller[0]=com.syscom.fep.server.gateway.ims.IMSGatewayController
# register Restful Controller for Receive and Ack KeepAlive
spring.register.controller[1]=com.syscom.fep.server.gateway.ims.keepalive.IMSGatewayKeepAliveRestfulServer

# Configuration for IMS Gateway
spring.fep.server.gateway.ims.imsApiLogPath=/fep/logs/
spring.fep.server.gateway.ims.sleepForRebuildConnectionInMilliseconds=100
spring.fep.server.gateway.ims.waitTransactionExecutedFinishedBeforeTerminate=true
spring.fep.server.gateway.ims.waitTransactionExecutedFinishedAtMostBeforeTerminateInMilliseconds=10000
spring.fep.server.gateway.ims.httpChannel=http://10.0.54.34:8213/recv/ims/channel
spring.fep.server.gateway.ims.httpTimeout=10000
spring.fep.server.gateway.ims.sleepForStartPrimary=3000
spring.fep.server.gateway.ims.mailAddress=AP1_FEP@tcb-bank.com.tw
spring.fep.server.gateway.ims.recordHttpLog=true

#==================================Primary==========================================
# Primary Sender
spring.fep.server.gateway.ims.primary.sender.host=10.0.178.1
spring.fep.server.gateway.ims.primary.sender.port=6669
spring.fep.server.gateway.ims.primary.sender.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.primary.sender.clientId=IFEPPA51,IFEPPA53,IFEPPA55,IFEPPA57
spring.fep.server.gateway.ims.primary.sender.resumeInterval=120000
spring.fep.server.gateway.ims.primary.sender.pingIMSInterval=300000
spring.fep.server.gateway.ims.primary.sender.dataStore=ICONDS

# Primary Alternative Sender
spring.fep.server.gateway.ims.primary.alternative-sender.host=10.0.178.1
spring.fep.server.gateway.ims.primary.alternative-sender.port=6669
spring.fep.server.gateway.ims.primary.alternative-sender.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.primary.alternative-sender.clientId=IFEPPC51,IFEPPC53,IFEPPC55,IFEPPC57
spring.fep.server.gateway.ims.primary.alternative-sender.resumeInterval=120000
spring.fep.server.gateway.ims.primary.alternative-sender.pingIMSInterval=300000
spring.fep.server.gateway.ims.primary.alternative-sender.dataStore=ICONDS

# Primary Receiver
spring.fep.server.gateway.ims.primary.receiver.host=10.0.178.1
spring.fep.server.gateway.ims.primary.receiver.port=6669
spring.fep.server.gateway.ims.primary.receiver.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.primary.receiver.clientId=IFEPPB51,IFEPPB53,IFEPPB55,IFEPPB57
spring.fep.server.gateway.ims.primary.receiver.resumeInterval=60000
spring.fep.server.gateway.ims.primary.receiver.dataStore=ICONDS

# Primary Alternative Receiver
spring.fep.server.gateway.ims.primary.alternative-receiver.host=10.0.178.1
spring.fep.server.gateway.ims.primary.alternative-receiver.port=6669
spring.fep.server.gateway.ims.primary.alternative-receiver.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.primary.alternative-receiver.clientId=IFEPPD51,IFEPPD53,IFEPPD55,IFEPPD57
spring.fep.server.gateway.ims.primary.alternative-receiver.resumeInterval=60000
spring.fep.server.gateway.ims.primary.alternative-receiver.dataStore=ICONDS
#==================================Primary==========================================

#==================================Secondary========================================
# Secondary Sender
spring.fep.server.gateway.ims.secondary.sender.host=10.0.178.1
spring.fep.server.gateway.ims.secondary.sender.port=6669
spring.fep.server.gateway.ims.secondary.sender.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.secondary.sender.clientId=IFEPPA52,IFEPPA54,IFEPPA56,IFEPPA58
spring.fep.server.gateway.ims.secondary.sender.resumeInterval=120000
spring.fep.server.gateway.ims.secondary.sender.pingIMSInterval=300000
spring.fep.server.gateway.ims.secondary.sender.dataStore=ICONDS

# Secondary Alternative Sender
spring.fep.server.gateway.ims.secondary.alternative-sender.host=10.0.178.1
spring.fep.server.gateway.ims.secondary.alternative-sender.port=6669
spring.fep.server.gateway.ims.secondary.alternative-sender.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.secondary.alternative-sender.clientId=IFEPPC52,IFEPPC54,IFEPPC56,IFEPPC58
spring.fep.server.gateway.ims.secondary.alternative-sender.resumeInterval=120000
spring.fep.server.gateway.ims.secondary.alternative-sender.pingIMSInterval=300000
spring.fep.server.gateway.ims.secondary.alternative-sender.dataStore=ICONDS

# Secondary Receiver
spring.fep.server.gateway.ims.secondary.receiver.host=10.0.178.1
spring.fep.server.gateway.ims.secondary.receiver.port=6669
spring.fep.server.gateway.ims.secondary.receiver.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.secondary.receiver.clientId=IFEPPB52,IFEPPB54,IFEPPB56,IFEPPB58
spring.fep.server.gateway.ims.secondary.receiver.resumeInterval=60000
spring.fep.server.gateway.ims.secondary.receiver.dataStore=ICONDS

# Secondary Alternative Receiver
spring.fep.server.gateway.ims.secondary.alternative-receiver.host=10.0.178.1
spring.fep.server.gateway.ims.secondary.alternative-receiver.port=6669
spring.fep.server.gateway.ims.secondary.alternative-receiver.reestablishConnectionInterval=10000
spring.fep.server.gateway.ims.secondary.alternative-receiver.clientId=IFEPPD52,IFEPPD54,IFEPPD56,IFEPPD58
spring.fep.server.gateway.ims.secondary.alternative-receiver.resumeInterval=60000
spring.fep.server.gateway.ims.secondary.alternative-receiver.dataStore=ICONDS
#==================================Secondary========================================

#IMS Gateway KeepAlive Server
spring.fep.server.gateway.ims.keepalive.server.host=${spring.fep.hostip}
spring.fep.server.gateway.ims.keepalive.server.port=8702
spring.fep.server.gateway.ims.keepalive.server.logging=true

#IMS Gateway KeepAlive Client
spring.fep.server.gateway.ims.keepalive.client.host=10.0.54.34
spring.fep.server.gateway.ims.keepalive.client.port=8702
spring.fep.server.gateway.ims.keepalive.client.interval=30
spring.fep.server.gateway.ims.keepalive.client.retryCount=3
spring.fep.server.gateway.ims.keepalive.client.retryInterval=5
spring.fep.server.gateway.ims.keepalive.client.timeout=5
spring.fep.server.gateway.ims.keepalive.client.httpKeepAlive=http://10.0.54.34:8213/recv/keepalive
spring.fep.server.gateway.ims.keepalive.client.logging=true

#IMS Gateway Job
spring.fep.gateway.job.ims.app-monitor.cronExpression=0 0/30 * * * ?
spring.fep.gateway.job.ims.app-monitor.monitorUrl=http://10.0.54.35:8730/recv/net/client
spring.fep.gateway.job.ims.app-monitor.recordHttpLog=true
