server.port=9090
spring.fep.hostip=10.0.54.33
spring.fep.application.name=fep-notify

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}
management.endpoint.health.show-details=always

spring.mvc.pathmatch.matching-strategy=ant_path_matcher


##### cache configure #####
cache.expireAfterWrite=600
cache.maximumSize=5000

##### email configure #####
fep.notify.email001.smtp=172.29.0.82
fep.notify.email001.port=25
fep.notify.email001.account=fep
fep.notify.email001.sscode=
fep.notify.email001.from=fep@tcb-bank.com.tw
fep.notify.email001.classname=com.syscom.fep.notify.common.email.Email001

##### sms configure #####
fep.notify.sms001.domain=https://tcb.mitake.com.tw:8105/tcb/mtk/SmSend
fep.notify.sms001.username=
fep.notify.sms001.sscode=
fep.notify.sms001.classname=com.syscom.fep.notify.common.sms.Sms001

##### notClassified configure #####
fep.notify.notclassified001.url=
fep.notify.notclassified001.appIds=
fep.notify.notclassified001.classname=com.syscom.fep.notify.common.notClassified.NotClassified001


##### push configure #####
fep.notify.push001.hostname=10.0.54.33
fep.notify.push001.port=1414
fep.notify.push001.channel=SVRCONN.FEPAP
fep.notify.push001.managerId=QMFEPP01
fep.notify.push001.accessQueueId=AP.PUSH.ONLINE.RQ
fep.notify.push001.toMqUserID=fepmq
fep.notify.push001.classname=com.syscom.fep.notify.common.push.Push001

#AppMonitorJob
spring.fep.scheduler.job.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.scheduler.job.app-monitor.serviceName=${management.metrics.tags.application}
spring.fep.scheduler.job.app-monitor.serviceHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.app-monitor.serviceHostName=${spring.fep.hostname}
spring.fep.scheduler.job.app-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}
spring.fep.scheduler.job.app-monitor.monitorPrimaryUrl=http://${spring.fep.hostip}:8730/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.monitorSecondaryUrl=http://10.0.54.34:8730/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.recordHttpLog=true
