server.port=8933

spring.fep.application.name=fep-server

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-fisc
management.endpoint.health.show-details=always


#register Controller recv message from Gateway via restful
spring.register.controller[0]=com.syscom.fep.server.controller.restful.FISCController

#register Netty Server recv message from Gateway via socket
spring.register.bean[0]=com.syscom.fep.server.netty.impl.FISCNettyServer
