# FEPDB
spring.datasource.fepdb.driver-class-name=net.sf.log4jdbc.DriverSpy
spring.datasource.fepdb.jdbc-url=jdbc:log4jdbc:db2://10.0.58.99:50000/FEPDB:currentSchema=FEP;progressiveStreaming=2;
# FEPDB Hikari Pool
spring.datasource.fepdb.hikari.minimum-idle=10
spring.datasource.fepdb.hikari.maximum-pool-size=200
spring.datasource.fepdb.hikari.idle-timeout=540000
spring.datasource.fepdb.hikari.max-lifetime=600000
spring.datasource.fepdb.hikari.connection-timeout=60000
spring.datasource.fepdb.hikari.connection-test-query=SELECT 1 FROM SYSIBM.SYSDUMMY1

# DESDB
spring.datasource.desdb.driver-class-name=net.sf.log4jdbc.DriverSpy
spring.datasource.desdb.jdbc-url=jdbc:log4jdbc:db2://10.0.58.99:50000/DESDB:currentSchema=FEP;fullyMaterializeInputStreams=true;progressiveStreaming=2;
# DESDB Hikari Pool
spring.datasource.desdb.hikari.minimum-idle=10
spring.datasource.desdb.hikari.maximum-pool-size=200
spring.datasource.desdb.hikari.idle-timeout=540000
spring.datasource.desdb.hikari.max-lifetime=600000
spring.datasource.desdb.hikari.connection-timeout=60000
spring.datasource.desdb.hikari.connection-test-query=SELECT 1 FROM SYSIBM.SYSDUMMY1

# EMSDB
spring.datasource.emsdb.driver-class-name=net.sf.log4jdbc.DriverSpy
spring.datasource.emsdb.jdbc-url=jdbc:log4jdbc:db2://10.0.78.49:60000/EMSDB:currentSchema=FEP;fullyMaterializeInputStreams=true;progressiveStreaming=2;
# EMSDB Hikari Pool
spring.datasource.emsdb.hikari.minimum-idle=10
spring.datasource.emsdb.hikari.maximum-pool-size=200
spring.datasource.emsdb.hikari.idle-timeout=540000
spring.datasource.emsdb.hikari.max-lifetime=600000
spring.datasource.emsdb.hikari.connection-timeout=60000
spring.datasource.emsdb.hikari.connection-test-query=SELECT 1 FROM SYSIBM.SYSDUMMY1

# DESLOGDB
spring.datasource.deslogdb.driver-class-name=net.sf.log4jdbc.DriverSpy
spring.datasource.deslogdb.jdbc-url=jdbc:log4jdbc:db2://10.0.78.49:60000/DESLOGDB:currentSchema=FEP;fullyMaterializeInputStreams=true;progressiveStreaming=2;
# DESLOGDB Hikari Pool
spring.datasource.deslogdb.hikari.minimum-idle=10
spring.datasource.deslogdb.hikari.maximum-pool-size=200
spring.datasource.deslogdb.hikari.idle-timeout=540000
spring.datasource.deslogdb.hikari.max-lifetime=600000
spring.datasource.deslogdb.hikari.connection-timeout=60000
spring.datasource.deslogdb.hikari.connection-test-query=SELECT 1 FROM SYSIBM.SYSDUMMY1

# FEPHIS
spring.datasource.fephis.driver-class-name=net.sf.log4jdbc.DriverSpy
spring.datasource.fephis.jdbc-url=jdbc:log4jdbc:db2://10.0.78.49:55000/FEPHISDB:currentSchema=FEP;fullyMaterializeInputStreams=true;progressiveStreaming=2;
# FEPHIS Hikari Pool
spring.datasource.fephis.hikari.minimum-idle=10
spring.datasource.fephis.hikari.maximum-pool-size=200
spring.datasource.fephis.hikari.idle-timeout=540000
spring.datasource.fephis.hikari.max-lifetime=600000
spring.datasource.fephis.hikari.connection-timeout=60000
spring.datasource.fephis.hikari.connection-test-query=SELECT 1 FROM SYSIBM.SYSDUMMY1

#for old version Hikari Pool
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=200
spring.datasource.hikari.idle-timeout=540000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM SYSIBM.SYSDUMMY1

#AuditTrail Interceptor
spring.fep.mybatis.interceptor.audittrail.enable=true
spring.fep.mybatis.interceptor.audittrail.ignore-tablename-prefix-list=SYSCOMAUDITTRAIL

#Logger Interceptor
spring.fep.mybatis.interceptor.logger.enable=true
spring.fep.mybatis.interceptor.logger.maskFieldNames=\
APIDTL_TROUT_ACTNO,APIDTL_TRIN_ACTNO,APIDTL_IDNO,\
ATMIAC_ACTNO,\
ATMSTAT_ACTNO,\
BDFPARM_DBACT,BDFPARM_CRACT,\
BILLPMT_TRIN_ACTNO,BILLPMT_TROUT_ACTNO,BILLPMT_IDNO,BILLTAX_TRIN_ACTNO,BILLTAX_TROUT_ACTNO,BILLTAX_IDNO,\
CBACT_ACTNO,\
CBSPEND_ACTNO,CBSPEND_IB_ACTNO,\
CLRACTNO_ACTNO,\
TRIN_ACTNO_ACTUAL,\
CWAVPARM_DBACT,\
FEPTXN_MAJOR_ACTNO,FEPTXN_TRIN_ACTNO,FEPTXN_TRIN_ACTNO_ACTUAL,FEPTXN_TROUT_ACTNO,FEPTXN_TRK2,FEPTXN_TRK3,FEPTXN_PINBLOCK,FEPTXN_TX_ACTNO,FEPTXN_IDNO,FEPTXN_CBS_INT_ACTNO,FEPTXN_CBS_SUP_ACTNO,\
FEPTXN_CBS_FEE_ACTNO,FEPTXN_TELEPHONE,FEPTXN_CLIENTIP,FEPTXN_DEPOSITOR,FEPTXN_DR_CUST,FEPTXN_CR_CUST,FEPTXNTCB_NOTICE_CUSID,FEPTXNTCB_NOTICE_MOBILENO,FEPTXNTCB_NOTICE_EMAIL,FEPTXNTCB_FROMACT,\
FEPTXNTCB_TOACT,FEPTXNTCB_HBKNO_TOACT,FEPTXNTCB_ACTNAME,\
FWDTXN_IDNO,\
FMASK_ACTNO,\
FUNDLOG_TROUT_ACTNO,FUNDLOG_TRIN_ACTNO,\
FWDTXN_TROUT_ACTNO,FWDTXN_TRIN_ACTNO,\
ICTLTXN_TROUT_ACTNO,\
INBKPEND_TROUT_ACTNO,INBKPEND_MAJOR_ACTNO,INBKPEND_TRIN_ACTNO,INBKPEND_TRIN_ACTNO_ACTUAL,\
INTLTXN_TROUT_ACTNO,\
MSGCTL_CBS_INT_ACTNO,MSGCTL_CBS_SUP_ACTNO,MSGCTL_CBS_FEE_ACTNO,MSGFILE_RESPONSIBLE,\
NOTIFYLOG_NUMBER,NOTIFYLOG_FROMNAME,NOTIFYLOG_FROMEMAIL,NOTIFYLOG_TOMAIL,NOTIFYLOG_IDNO,\
NPSCUST_ACTNO,\
NPSDTL_TROUT_ACTNO,NPSDTL_TRIN_ACTNO,NPSDTL_IDNO,\
NWDREG_TROUT_ACTNO,NWDREG_IDNO,\
NWDTXN_TROUT_ACTNO,NWDTXN_IDNO,\
OBTLTXN_TROUT_ACTNO,OBTLTXN_MAJOR_ACTNO,\
ODRC_ACTNO,\
OWLIMIT_ACTNO,\
ODRC_ACTNO,\
OWLIMIT_ACTNO,\
QRPTXN_TROUT_ACTNO,\
Name,Email,Tel,\
SMLPARM_FROMNAME,SMLPARM_FROMEMAIL,\
SMSMSG_TROUT_ACTNO,SMSMSG_NUMBER,SMSMSG_EMAIL,SMSMSG_IDNO,SMSMSG_SMS_PHONE,SMSMSG_DR_CUST,SMSMSG_CR_CUST,SMSMSG_TRIN_ACTNO,\
TF252M_TRIN_ACTNO,TF252M_TROUT_ACTNO,\
TF252X_TRIN_ACTNO,TF252X_TROUT_ACTNO,\
VATXN_TROUT_ACTNO,VATXN_PACTNO,VATXN_ACTNO,VATXN_IDNO,VATXN_MOBILE,VATXN_BIRTHDAY,VATXN_HPHONE,\
VENDOR_CONTACT,VENDOR_CONTACT_TEL,VENDOR_CONTACT_MOBIL,\
CustomerMAccount,CustomerSAccount,\
INBK2160_TROUT_ACTNO,INBK2160_MAJOR_ACTNO,INBK2160_ORI_TRIN_ACTNO,\
EAITXN_IDNO,EAITXN_TRNSFROUTIDNO,EAITXN_TRNSFROUTACCNT,EAITXN_TRNSFRINIDNO,EAITXN_TRNSFRINACCNT,EAITXN_TRNSFRINNAME,EAITXN_TRNSFROUTNAME,EAITXN_PAYEREMAIL


#pagehelper
pagehelper.pageSizeZero=true
