#IBM Queue
spring.fep.jms.prop.queueManager=QMFEPP01
spring.fep.jms.prop.channel=SVRCONN.FEPAP
spring.fep.jms.prop.connName=10.0.54.33(1414)
spring.fep.jms.prop.user=
spring.fep.jms.prop.password=

#EMS Sender 
spring.fep.jms.ems.sender.log[0].queueManager=QMFEPLOGP01
spring.fep.jms.ems.sender.log[0].channel=SVRCONN.TOEMS
spring.fep.jms.ems.sender.log[0].connName=${spring.fep.hostip}(1415)
spring.fep.jms.ems.sender.log[0].user=
spring.fep.jms.ems.sender.log[0].password=
spring.fep.jms.ems.sender.log[0].queue-names.ems.destination=FEP.LOG.QL
spring.fep.jms.ems.sender.log[1].queueManager=QMFEPLOGP02
spring.fep.jms.ems.sender.log[1].channel=SVRCONN.TOEMS
spring.fep.jms.ems.sender.log[1].connName=10.0.54.34(1415)
spring.fep.jms.ems.sender.log[1].user=
spring.fep.jms.ems.sender.log[1].password=
spring.fep.jms.ems.sender.log[1].queue-names.ems.destination=FEP.LOG.QL
spring.fep.jms.ems.sender.alert[0].queueManager=QMFEPLOGP01
spring.fep.jms.ems.sender.alert[0].channel=SVRCONN.TOEMS
spring.fep.jms.ems.sender.alert[0].connName=${spring.fep.hostip}(1415)
spring.fep.jms.ems.sender.alert[0].user=
spring.fep.jms.ems.sender.alert[0].password=
spring.fep.jms.ems.sender.alert[0].queue-names.ems.destination=FEP.EMS.QL
spring.fep.jms.ems.sender.alert[1].queueManager=QMFEPLOGP02
spring.fep.jms.ems.sender.alert[1].channel=SVRCONN.TOEMS
spring.fep.jms.ems.sender.alert[1].connName=10.0.54.34(1415)
spring.fep.jms.ems.sender.alert[1].user=
spring.fep.jms.ems.sender.alert[1].password=
spring.fep.jms.ems.sender.alert[1].queue-names.ems.destination=FEP.EMS.QL

#Batch
spring.fep.jms.batch.prop.queueManager=QMFEPP01
spring.fep.jms.batch.prop.channel=SVRCONN.FROMBATCH
spring.fep.jms.batch.prop.connName=${spring.fep.hostip}(1414)
spring.fep.jms.batch.prop.user=
spring.fep.jms.batch.prop.password=

#BATCH Host
spring.fep.jms.batch.hosts.prop[0].host-name=${spring.fep.batch.base.host[0].name}
spring.fep.jms.batch.hosts.prop[0].queueManager=QMFEPP01
spring.fep.jms.batch.hosts.prop[0].channel=SVRCONN.TOBATCH
spring.fep.jms.batch.hosts.prop[0].connName=${spring.fep.batch.base.host[0].ip}(1414)
spring.fep.jms.batch.hosts.prop[0].user=
spring.fep.jms.batch.hosts.prop[0].password=
spring.fep.jms.batch.hosts.prop[0].queue-names.batch.destination=FEP.BATCH.QL
spring.fep.jms.batch.hosts.prop[1].host-name=${spring.fep.batch.base.host[1].name}
spring.fep.jms.batch.hosts.prop[1].queueManager=QMFEPP02
spring.fep.jms.batch.hosts.prop[1].channel=SVRCONN.TOBATCH
spring.fep.jms.batch.hosts.prop[1].connName=${spring.fep.batch.base.host[1].ip}(1414)
spring.fep.jms.batch.hosts.prop[1].user=
spring.fep.jms.batch.hosts.prop[1].password=
spring.fep.jms.batch.hosts.prop[1].queue-names.batch.destination=FEP.BATCH.QL

#===============================================================================

#FISC Receiver(for service)
spring.fep.jms.fisc.receiver.prop.queueManager=QMFEPP01
spring.fep.jms.fisc.receiver.prop.channel=SVRCONN.FROMFISCGW
spring.fep.jms.fisc.receiver.prop.connName=10.0.54.33(1414)
spring.fep.jms.fisc.receiver.prop.user=
spring.fep.jms.fisc.receiver.prop.password=

#FISC Receiver Alternative(for service)
spring.fep.jms.fisc.receiver.alternative.prop.queueManager=QMFEPP02
spring.fep.jms.fisc.receiver.alternative.prop.channel=SVRCONN.FROMFISCGW
spring.fep.jms.fisc.receiver.alternative.prop.connName=10.0.54.34(1414)
spring.fep.jms.fisc.receiver.alternative.prop.user=
spring.fep.jms.fisc.receiver.alternative.prop.password=


#Queue Name New
spring.fep.jms.queue-names.test.destination=TestQueue
spring.fep.jms.queue-names.batch.destination=FEP.BATCH.QL
spring.fep.jms.queue-names.ems.destination=FEP.EMS.QL
spring.fep.jms.queue-names.ems.concurrency=20-50
spring.fep.jms.queue-names.nb.destination=NB.FEP.ONLINE.RQ
spring.fep.jms.queue-names.nbAck.destination=
spring.fep.jms.queue-names.nbQAck.destination=
spring.fep.jms.queue-names.nbPAck.destination=
spring.fep.jms.queue-names.mb.destination=MB.FEP.ONLINE.RQ
spring.fep.jms.queue-names.mbAck.destination=
spring.fep.jms.queue-names.mch.destination=MCH.FEP.ONLINE.RQ
spring.fep.jms.queue-names.mchAck.destination=
spring.fep.jms.queue-names.vo.destination=VO.FEP.ONLINE.RQ
spring.fep.jms.queue-names.voAck.destination=
spring.fep.jms.queue-names.eatm.destination=EATM.FEP.ONLINE.RQ
spring.fep.jms.queue-names.eatmAck.destination=
spring.fep.jms.queue-names.hce.destination=HCE.FEP.ONLINE.RQ
spring.fep.jms.queue-names.hceAck.destination=
spring.fep.jms.queue-names.mft.destination=ZMQ.FEP.ONLINE.RQ
spring.fep.jms.queue-names.mftAck.destination=ZMQ.FEP.ONLINE.RS
spring.fep.jms.queue-names.twmp.destination=FEP.TWMP.ONLINE.RQ
spring.fep.jms.queue-names.twmpACK.destination=
spring.fep.jms.queue-names.cbspend.destination=FEP.CBSPEND.ONLINE.RQ

spring.fep.jms.queue-names.fisc.destination=FEP.FISC.ONLINE.RS
spring.fep.jms.queue-names.fiscAlternative.destination=FEP.FISC.ONLINE.RS

spring.fep.jms.queue-names.eoi.destination=EOI.FEP.ONLINE.RQ
spring.fep.jms.queue-names.eoiAck.destination=
spring.fep.jms.queue-names.eip.destination=EIP.FEP.ONLINE.RQ
spring.fep.jms.queue-names.eipAck.destination=
spring.fep.jms.queue-names.pyBatch.destination=NPAY.FEP.BATCH.RQ
spring.fep.jms.queue-names.pyBatchAck.destination=
spring.fep.jms.queue-names.vip.destination=NPAY.FEP.VIP.RQ
spring.fep.jms.queue-names.vipAck.destination=
spring.fep.jms.queue-names.nonvip.destination=NPAY.FEP.NONVIP.RQ
spring.fep.jms.queue-names.nonvipAck.destination=
spring.fep.jms.queue-names.bizloan.destination=BIZLOAN.FEP.ONLINE.RQ
spring.fep.jms.queue-names.bizloanAck.destination=
spring.fep.jms.queue-names.digital.destination=DIGITAL.FEP.ONLINE.RQ
spring.fep.jms.queue-names.digitalAck.destination=
spring.fep.jms.queue-names.fido.destination=FIDO.FEP.ONLINE.RQ
spring.fep.jms.queue-names.fidoAck.destination=
spring.fep.jms.queue-names.onl.destination=ONL.FEP.ONLINE.RQ
spring.fep.jms.queue-names.onlAck.destination=
spring.fep.jms.queue-names.sso.destination=SSO.FEP.ONLINE.RQ
spring.fep.jms.queue-names.ssoAck.destination=
spring.fep.jms.queue-names.pyBatch.concurrency=20
spring.fep.jms.queue-names.nb.concurrency=10
spring.fep.jms.queue-names.mb.concurrency=3
spring.fep.jms.queue-names.mch.concurrency=10
spring.fep.jms.queue-names.eoi.concurrency=3
spring.fep.jms.queue-names.eip.concurrency=10
spring.fep.jms.queue-names.vo.concurrency=3
spring.fep.jms.queue-names.eatm.concurrency=3
spring.fep.jms.queue-names.hce.concurrency=5
spring.fep.jms.queue-names.mft.concurrency=20
spring.fep.jms.queue-names.twmp.concurrency=10
spring.fep.jms.queue-names.vip.concurrency=40
spring.fep.jms.queue-names.nonvip.concurrency=40
spring.fep.jms.queue-names.bizloan.concurrency=3
spring.fep.jms.queue-names.digital.concurrency=3
spring.fep.jms.queue-names.fido.concurrency=3
spring.fep.jms.queue-names.onl.concurrency=10
spring.fep.jms.queue-names.sso.concurrency=3


#Topic Name
spring.fep.jms.topic-names.test.destination=TestTopic

