<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.syscom</groupId>
        <artifactId>feptcb</artifactId>
        <version>1.0.0</version>
    </parent>
    <groupId>com.syscom.feptcb</groupId>
    <artifactId>fep-ws-client</artifactId>
    <name>fep-ws-client</name>
    <dependencies>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-frmcommon</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-base</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-jms</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web-services</artifactId>
            <version>${spring-boot-starter-web-services-version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring-boot-starter-test-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter-api-version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>**/*.wsdl</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin-version}</version>
                <configuration>
                    <source>${java-source-version}</source>
                    <target>${java-target-version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin-version}</version>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.helger.maven</groupId>
                <artifactId>jaxb40-maven-plugin</artifactId>
                <version>${jaxb40-maven-plugin-version}</version>
                <executions>
                    <execution>
                        <id>FISC</id>
                        <!-- 如果需要重新產出WS Client程式，需要改為test或者generate-sources -->
                        <phase>none</phase>
                        <configuration>
                            <schemaLanguage>WSDL</schemaLanguage>
                            <generateDirectory>src/main/java</generateDirectory>
                            <generatePackage>com.syscom.fep.ws.client.fisc.wsdl</generatePackage>
                            <readOnly>true</readOnly>
                            <schemas>
                                <schema>
                                    <url>http://localhost:18738/FISCGWWS?wsdl</url>
                                </schema>
                            </schemas>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <locale>zh-TW</locale>
                            <episode>false</episode>
                            <forceRegenerate>true</forceRegenerate>
                        </configuration>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>T24</id>
                        <!-- 如果需要重新產出WS Client程式，需要改為test或者generate-sources -->
                        <phase>none</phase>
                        <configuration>
                            <schemaLanguage>WSDL</schemaLanguage>
                            <generateDirectory>src/main/java</generateDirectory>
                            <generatePackage>com.syscom.fep.ws.client.t24.wsdl</generatePackage>
                            <readOnly>true</readOnly>
                            <schemas>
                                <schema>
                                    <url>http://localhost:18738/FEP/NativeMessage.svc?wsdl=wsdl0</url>
                                </schema>
                            </schemas>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <locale>zh-TW</locale>
                            <episode>false</episode>
                            <forceRegenerate>true</forceRegenerate>
                        </configuration>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>