#base
spring.fep.systemid=FEP10
spring.fep.hostip=172.29.14.1
spring.fep.hostname=fepfiscgw1P

#embedded server
spring.fep.embedded.server.baseDir=/fep/tmp/${management.metrics.tags.application}/basedir/
spring.fep.embedded.server.docRoot=/fep/tmp/${management.metrics.tags.application}/docroot/

#log
#logging.level.root=DEBUG
logging.config=classpath:logback-spring.xml
spring.fep.log.path=/fep/logs
spring.fep.log.jdbc.sqltiming.level=DEBUG
spring.fep.log.mybatis.level=DEBUG

#ENCLib
spring.fep.enclib.enable=false
spring.fep.enclib.atmagent.enable=false


#ims
spring.fep.ims.tx.clientid=IFEPPA{0},1,10
spring.fep.ims.pbo.clientid=IFEPPC{0},1,10

#restful
spring.fep.restful.timeout=30000

#mail
spring.fep.mail.smtp=172.29.0.82
spring.fep.mail.port=25
spring.fep.mail.account=fep
spring.fep.mail.sscode=ENC(3SM3px7gSO1uXkn8maceH+ruzkzWt6iFEeeSLiKub7Bk5iDBvspd8+6nqRWITw8DSXogtkPmgdA36hY6y/XCIg==)


#BATCH
spring.fep.batch.base.host[0].name=fepap1P
spring.fep.batch.base.host[0].ip=${spring.fep.hostip}
spring.fep.batch.base.host[0].url=http://${spring.fep.batch.base.host[0].ip}:8084
spring.fep.batch.base.task.path=/fep/fep-app/fep-batch-task
spring.fep.batch.base.task.jarNameTemplate=fep-batch-task-{0}.jar

#server url
spring.fep.server.url.atm=http://${spring.fep.hostip}:8731/recv/atm
spring.fep.server.url.fisc=http://${spring.fep.hostip}:8733/recv/fisc

#server protocl
#restful, when FEP Server recv message from Gateway via restful #socket, when FEP Server recv message from Gateway via socket spring.fep.server.protocol.atm=socket
spring.fep.server.protocol.fisc=socket

spring.fep.batch.task.cmdStart=/fep/fep-app/test_run.sh

#FISC
spring.fep.server.netty.fisc.host=${spring.fep.hostip}
spring.fep.server.netty.fisc.port=8733
spring.fep.server.netty.fisc.reestablishConnectionInterval=5000
spring.fep.server.netty.fisc.acceptIp=
spring.fep.server.encoding.fisc=ebcdic
spring.fep.server.netty.fisc.serverBisThreadNum=100
spring.fep.server.netty.fisc.useDynamicEventExecutorGroup=true

#ATMMon
spring.fep.server.netty.atmmon.host=${spring.fep.hostip}
spring.fep.server.netty.atmmon.port=28087
spring.fep.server.netty.atmmon.reestablishConnectionInterval=5000
spring.fep.server.netty.atmmon.acceptIp=


