<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.syscom</groupId>
        <artifactId>feptcb</artifactId>
        <version>1.0.0</version>
    </parent>
    <groupId>com.syscom.feptcb</groupId>
    <artifactId>fep-batch-cmdline</artifactId>
    <name>fep-batch-cmdline</name>
    <description>batch-cmdline</description>
    <properties>
        <project-shell>fep_batch_cmdline</project-shell>
        <!-- ${project.description}必須在最後的位置 -->
        <profiles-active>jms,integration,${project.description}</profiles-active>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-bom</artifactId>
                <version>${log4j2.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${netty-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-cache</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-configuration</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-base-aa</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-server-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-batch-base</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-enchelper</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-mybatis</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-mybatis-ems</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-mybatis-enc</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-mybatis-deslog</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-mybatis-his</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-invoker</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-vo</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-server-aa</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-ws-client</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring-boot-starter-test-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter-api-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok-version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <profiles>
        <!-- Springboot方式build版, 將所有的檔包括引用的第三方jar檔都包在一個fep-batch-cmdline.jar檔中 -->
        <profile>
            <id>springboot-jar</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <project.packaging>jar</project.packaging>
            </properties>
            <build>
                <finalName>${project.artifactId}</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <version>${spring-boot-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>com.syscom.fep.batch.SyscomFepBatchCmdLineApplication</mainClass>
                            <includeSystemScope>true</includeSystemScope>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>repackage</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin-version}</version>
                        <configuration>
                            <source>${java-source-version}</source>
                            <target>${java-target-version}</target>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <!-- Maven方式build版, 並配合iterator-maven-plugin實現拆分方式build版, 利於換版單獨更換jar檔
            1. 僅將本專案中的class檔包在jar檔中
            2. 將第三方引用的jar檔直接放在上一級目錄的dependencies目錄下
            3. 將引用fep其他專案的jar檔放在lib目錄下
            目錄結構如下:
                /fep-app
                    /bin/fep-function.sh
                    /config/各項配置檔
                    /dependencies/引用第三方的jar檔
                    /fep-batch-cmdline
                        /lib/引用fep的jar檔
                        application.properties
                        fep-batch-cmdline-run.bat
                        fep-batch-cmdline.jar
                        fep-batch-cmdline-start.sh
                        fep-batch-cmdline-status.sh
                        fep-batch-cmdline-stop.sh
        -->
        <profile>
            <id>maven-jar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <project.packaging>jar</project.packaging>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-clean-plugin</artifactId>
                        <version>${maven-clean-plugin-version}</version>
                        <configuration>
                            <followSymLinks>false</followSymLinks>
                            <filesets>
                                <fileset>
                                    <directory>../../${assembly-directory}</directory>
                                    <includes>
                                        <include>${project.artifactId}-*.tar.gz</include>
                                    </includes>
                                </fileset>
                            </filesets>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>properties-maven-plugin</artifactId>
                        <version>${properties-maven-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>read-project-properties</goal>
                                </goals>
                                <configuration>
                                    <files>
                                        <!-- 讀取屬性檔 -->
                                        <file>${assembly-config-path}/assembly-${assembly-prop}.properties</file>
                                        <!-- 讀取server-aa所有jar檔的classpath配置 -->
                                        <file>${assembly-config-path}/fep-server-aa/assembly-${assembly-server-aa}-${assembly-prop}.properties</file>
                                        <!-- 讀取mybatis所有jar檔的classpath配置 -->
                                        <file>${assembly-config-path}/fep-mybatis/assembly-${assembly-mybatis}-${assembly-prop}.properties</file>
                                    </files>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>${maven-antrun-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <delete file="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                        <copy file="${assembly-release-note-path}/${project.artifactId}.txt"
                                              tofile="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>${maven-jar-plugin-version}</version>
                        <configuration>
                            <finalName>${project.artifactId}</finalName>
                            <archive>
                                <addMavenDescriptor>false</addMavenDescriptor>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                    <classpathPrefix>../dependencies/</classpathPrefix>
                                    <mainClass>com.syscom.fep.batch.cmdline.SyscomFepBatchCmdLineApplication</mainClass>
                                </manifest>
                                <manifestEntries>
                                    <Class-Path>${assembly-prop-classpath} ${assembly-prop-server-aa-classpath} ${assembly-prop-mybatis-classpath}</Class-Path>
                                </manifestEntries>
                            </archive>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>com.soebes.maven.plugins</groupId>
                        <artifactId>iterator-maven-plugin</artifactId>
                        <version>${iterator-maven-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>iterator</goal>
                                </goals>
                                <configuration>
                                    <itemsWithProperties>
                                        <itemWithProperty>
                                            <name>batch-cmdline-simple</name>
                                            <properties>
                                                <assembly-name>simple</assembly-name>
                                                <assembly-func>-${assembly-name}</assembly-func>
                                                <assembly-shell>_${assembly-name}</assembly-shell>
                                                <assembly-jvm-xms>256m</assembly-jvm-xms>
                                                <assembly-jvm-xmx>512m</assembly-jvm-xmx>
                                                <assembly-jvm-metaspaceSize>256m</assembly-jvm-metaspaceSize>
                                                <assembly-profiles-active>${profiles-active}${assembly-func}</assembly-profiles-active>
                                            </properties>
                                        </itemWithProperty>
                                        <itemWithProperty>
                                            <name>batch-cmdline</name>
                                            <properties>
                                                <assembly-name/>
                                                <assembly-func/>
                                                <assembly-shell/>
                                                <assembly-jvm-xms>256m</assembly-jvm-xms>
                                                <assembly-jvm-xmx>512m</assembly-jvm-xmx>
                                                <assembly-jvm-metaspaceSize>256m</assembly-jvm-metaspaceSize>
                                                <assembly-profiles-active>mybatis,${profiles-active}${assembly-func}</assembly-profiles-active>
                                            </properties>
                                        </itemWithProperty>
                                    </itemsWithProperties>
                                    <pluginExecutors>
                                        <pluginExecutor>
                                            <plugin>
                                                <artifactId>maven-assembly-plugin</artifactId>
                                                <version>${maven-assembly-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <id>make-assembly</id>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>single</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>single</goal>
                                            <configuration>
                                                <finalName>${project.artifactId}</finalName>
                                                <ignoreMissingDescriptor>true</ignoreMissingDescriptor>
                                                <descriptors>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-dependencies}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/assembly-${assembly-bin}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/assembly-${assembly-cmd}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/assembly-${assembly-config}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/assembly-${assembly-lib}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/${assembly-name}/assembly-${assembly-bin}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/${assembly-name}/assembly-${assembly-config}.xml</descriptor>
                                                </descriptors>
                                                <outputDirectory>${assembly-output-path}</outputDirectory>
                                            </configuration>
                                        </pluginExecutor>
                                    </pluginExecutors>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin-version}</version>
                        <configuration>
                            <source>${java-source-version}</source>
                            <target>${java-target-version}</target>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>