server.port=8081

spring.fep.application.name=fep-web

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}
management.endpoint.health.show-details=always

server.servlet.session.tracking-modes=cookie
spring.thymeleaf.prefix=classpath:/templates/


spring.fep.web.title=\u5408\u4F5C\u91D1\u5EAB\u5546\u696D\u9280\u884C
spring.fep.web.web-type=FEP
spring.fep.web.query-only=0
spring.fep.web.ldap=true
spring.fep.web.time-out=30000
spring.fep.web.subsys=1,2,3,4,5,6,7,8,9,10,11,12,13,14
spring.fep.web.csvSavedPath=/fep/fep-app/csv/
spring.fep.web.UI_080100.showPid=true

#FEPMQService\u63A5\u6536\u6307\u4EE4\u7684Port
spring.fep.web.mq.service.port=8202
#FEPMQService\u63A5\u6536\u7684\u5730\u5740
spring.fep.web.mq.service.request=/api/CustomCommand

#For LDAP
spring.fep.web.system.webaddress=ldaps://10.0.31.1:636
spring.fep.web.system.strtemp=dc=tcb,dc=com
spring.fep.web.system.fileName=fepad.cer
spring.fep.web.system.filesscode=ENC(G2SYTHpTmoG+Opjr6IYznZwKPyz0YhGs6eWSgnOhsHHWeNGvWAQVvdjwbWe6+S4L)
spring.fep.web.system.certificateName=X.509
spring.fep.web.system.fiddler=fiddler

#APP Monitor
spring.fep.web.app-mon.ip=${spring.fep.hostip}
spring.fep.web.app-mon.port=8730

#create log path
spring.fep.log.path=/fep/waslogs

#log download path
spring.fep.web.system.download.feplogpath=/fep/logs/
spring.fep.web.system.download.fepwaslogpath=/fep/waslogs/
spring.fep.web.system.download.feplogarchivespath=/fep/logs/archives
spring.fep.web.system.download.fepwaslogarchivespath=/fep/waslogs/archives

#AP Log
spring.fep.web.aplog[0].server=fepap1P
spring.fep.web.aplog[0].logtype=aplog,waslog
spring.fep.web.aplog[0].service=https://10.0.54.33:9443/fepweb/UI060610/GetAPLog
spring.fep.web.aplog[1].server=fepap2P
spring.fep.web.aplog[1].logtype=aplog,waslog
spring.fep.web.aplog[1].service=https://10.0.54.34:9443/fepweb/UI060610/GetAPLog
spring.fep.web.aplog[2].server=fepgw1P
spring.fep.web.aplog[2].logtype=aplog
spring.fep.web.aplog[2].service=http://10.0.54.1:8302/fepgwagent/GetAPLog
spring.fep.web.aplog[3].server=fepgw2P
spring.fep.web.aplog[3].logtype=aplog
spring.fep.web.aplog[3].service=http://10.0.54.2:8302/fepgwagent/GetAPLog
spring.fep.web.aplog[4].server=fepfiscgw1P
spring.fep.web.aplog[4].logtype=aplog
spring.fep.web.aplog[4].service=http://172.29.14.1:8302/fepgwagent/GetAPLog
spring.fep.web.aplog[5].server=fepfiscgw2P
spring.fep.web.aplog[5].logtype=aplog
spring.fep.web.aplog[5].service=http://172.29.14.2:8302/fepgwagent/GetAPLog


#WEB audit Interceptor
spring.fep.web.interceptor.audit.enableAudit=true
spring.fep.web.interceptor.audit.showAudit=false
spring.fep.web.interceptor.audit.flushIntervalIntervalInMilliseconds=5000

#Queue Receiver
spring.fep.web.queue.ctrLUri.getConcurrency=http://{0}:{1}/consumers/{2}/getConcurrency
spring.fep.web.queue.ctrlUri.setConcurrency=http://{0}:{1}/consumers/{2}/setConcurrency
spring.fep.web.queue.receiver[0].programName=EATMServerReceiver
spring.fep.web.queue.receiver[0].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[0].port=8203
spring.fep.web.queue.receiver[1].programName=HCEServerReceiver
spring.fep.web.queue.receiver[1].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[1].port=8103
spring.fep.web.queue.receiver[2].programName=VOServerReceiver
spring.fep.web.queue.receiver[2].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[2].port=8291
spring.fep.web.queue.receiver[3].programName=MBServerReceiver
spring.fep.web.queue.receiver[3].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[3].port=8148
spring.fep.web.queue.receiver[4].programName=MFTServerReceiver
spring.fep.web.queue.receiver[4].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[4].port=8204
spring.fep.web.queue.receiver[5].programName=NBServerReceiver
spring.fep.web.queue.receiver[5].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[5].port=8147
spring.fep.web.queue.receiver[6].programName=PYBatchReceiver
spring.fep.web.queue.receiver[6].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[6].port=8153
spring.fep.web.queue.receiver[7].programName=TWMPServerReceiver
spring.fep.web.queue.receiver[7].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[7].port=8212
spring.fep.web.queue.receiver[8].programName=MCHServerReceiver
spring.fep.web.queue.receiver[8].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[8].port=8150
spring.fep.web.queue.receiver[9].programName=VIPServerReceiver
spring.fep.web.queue.receiver[9].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[9].port=8216
spring.fep.web.queue.receiver[10].programName=NONVIPServerReceiver
spring.fep.web.queue.receiver[10].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[10].port=8224
spring.fep.web.queue.receiver[11].programName=BizloanServerReceiver
spring.fep.web.queue.receiver[11].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[11].port=8218
spring.fep.web.queue.receiver[12].programName=DigitalServerReceiver
spring.fep.web.queue.receiver[12].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[12].port=8219
spring.fep.web.queue.receiver[13].programName=FIDOServerReceiver
spring.fep.web.queue.receiver[13].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[13].port=8220
spring.fep.web.queue.receiver[14].programName=ONLServerReceiver
spring.fep.web.queue.receiver[14].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[14].port=8221
spring.fep.web.queue.receiver[15].programName=SSOServerReceiver
spring.fep.web.queue.receiver[15].ip=${spring.fep.hostip}
spring.fep.web.queue.receiver[15].port=8223


#FISC Gateway Agent
spring.fep.web.fisc.ctrlUri.start=http://{0}:{1}/recv/fisc/start
spring.fep.web.fisc.ctrlUri.stop=http://{0}:{1}/recv/fisc/stop
spring.fep.web.fisc.ctrlUri.channel=http://{0}:{1}/recv/fisc/channel
spring.fep.web.fisc.ctrlUri.check=http://{0}:{1}/recv/fisc/check
spring.fep.web.fisc.waitInMillisecondsAfterStartAndStop=10000
spring.fep.web.fisc.agent[0].name=FISCGW1P
spring.fep.web.fisc.agent[0].ip=172.29.14.1
spring.fep.web.fisc.agent[0].port=8302
spring.fep.web.fisc.agent[1].name=FISCGW2P
spring.fep.web.fisc.agent[1].ip=172.29.14.2
spring.fep.web.fisc.agent[1].port=8302


#Simple Netty server
spring.fep.web.simple.netty.ctrlUri.getEventExecutorData=http://{0}:{1}/recv/{2}/getEventExecutorData
spring.fep.web.simple.netty.ctrlUri.setEventExecutorThreads=http://{0}:{1}/recv/{2}/setEventExecutorThreads
spring.fep.web.simple.netty.server[0].name=ATM Service
spring.fep.web.simple.netty.server[0].programName=ATMNettyServer
spring.fep.web.simple.netty.server[0].ip=${spring.fep.hostip}
spring.fep.web.simple.netty.server[0].port=8080
spring.fep.web.simple.netty.server[1].name=FISC Service
spring.fep.web.simple.netty.server[1].programName=FISCNettyServer
spring.fep.web.simple.netty.server[1].ip=${spring.fep.hostip}
spring.fep.web.simple.netty.server[1].port=8933

#CBS Gateway
spring.fep.web.cbs.ctrlUri.getAllLineStatus=http://{0}:{1}/recv/cbs/getAllLineStatus
spring.fep.web.cbs.ctrlUri.changeLineStatus=http://{0}:{1}/recv/cbs/changeLineStatus
spring.fep.web.cbs.ctrlUri.changeServerStatus=http://{0}:{1}/recv/cbs/changeServerStatus
spring.fep.web.cbs.waitInMillisecondsAfterChangeLineStatus=1000
spring.fep.web.cbs.gw[0].ip=10.0.54.33
spring.fep.web.cbs.gw[0].hostName=fepap1P
spring.fep.web.cbs.gw[0].port=8305
spring.fep.web.cbs.gw[1].ip=10.0.54.34
spring.fep.web.cbs.gw[1].hostName=fepap2P
spring.fep.web.cbs.gw[1].port=8305

#IMS Gateway
spring.fep.web.ims.ctrlUri.getAllLineStatus=http://{0}:{1}/recv/ims/getAllLineStatus
spring.fep.web.ims.ctrlUri.changeLineStatus=http://{0}:{1}/recv/ims/changeLineStatus
spring.fep.web.ims.waitInMillisecondsAfterChangeLineStatus=1000
spring.fep.web.ims.gw[0].ip=10.0.54.33
spring.fep.web.ims.gw[0].port=8213
spring.fep.web.ims.gw[1].ip=10.0.54.34
spring.fep.web.ims.gw[1].port=8213

#API Key
spring.fep.web.apikey=c884cf9291361c3381bded302b1e91c87d9bf600304581a432962b3eb047e542,\
                        82b3445fef4f3ec2d28f9a5dc8b4d1b36a064178c02e0e24e90cfeba5d5b25d7,\
                        4f99353377f58c43c5f6a77f7248c0506ff656354288598d39e8850f9ae575b0

#FEPUCDQry API Key
spring.fep.web.ucd.apikey=1eab68ce245da6402493faabea64ab7a35828b128b6bbe6d2717487ea40d69e,\
                            d8d31a136c005431b8e2c3d9cd07e4bf9e1d448e6ab6a07f98917181bda7f72b
							
# Channel & AppName Mapping for fepap
spring.fep.web.apChannelToAppName.BATCH=fep-batch;fep-batch-cmdline;fep-batch-task
spring.fep.web.apChannelToAppName.NOTIFY=fep-notify
spring.fep.web.apChannelToAppName.CBSGW=fep-gateway-cbs
spring.fep.web.apChannelToAppName.IMSGW=fep-server-imsgw
spring.fep.web.apChannelToAppName.FISC=fep-server-fisc
spring.fep.web.apChannelToAppName.ATM=fep-server-atm
spring.fep.web.apChannelToAppName.BIZ=fep-server-bizloan
spring.fep.web.apChannelToAppName.DIG=fep-server-digital
spring.fep.web.apChannelToAppName.EAT=fep-server-eatm
spring.fep.web.apChannelToAppName.EIP=fep-server-eip
spring.fep.web.apChannelToAppName.EOI=fep-server-eoi
spring.fep.web.apChannelToAppName.FID=fep-server-fido
spring.fep.web.apChannelToAppName.HCE=fep-server-hce
spring.fep.web.apChannelToAppName.MB=fep-server-mb
spring.fep.web.apChannelToAppName.MFT=fep-server-mft
spring.fep.web.apChannelToAppName.MCH=fep-server-mch
spring.fep.web.apChannelToAppName.pyBatch=fep-server-pyBatch
spring.fep.web.apChannelToAppName.NB=fep-server-nb
spring.fep.web.apChannelToAppName.ONL=fep-server-onl
spring.fep.web.apChannelToAppName.POS=fep-server-posgw
spring.fep.web.apChannelToAppName.SSO=fep-server-sso
spring.fep.web.apChannelToAppName.VO=fep-server-vo
spring.fep.web.apChannelToAppName.VIP=fep-server-vip
spring.fep.web.apChannelToAppName.NONVIP=fep-server-nonvip
spring.fep.web.apChannelToAppName.GRAYLIST=fep-server-graylist
spring.fep.web.apChannelToAppName.APPMON=fep-service-appmon
spring.fep.web.apChannelToAppName.CBSTRRN=fep-service-cbstimeoutrerun

# Channel & AppName Mapping for fepgw
spring.fep.web.gwChannelToAppName.FISC=fep-gateway-fisc;fep-gateway-fisc-agent
spring.fep.web.gwChannelToAppName.ATM=fep-gateway-atm;fep-gateway-atm-agent