management.metrics.tags.application=fep-batch-cmdline
spring.fep.log.path=/fep/logs
spring.fep.batch.task.inserteventmessagelog.processToLogNameMap={fep-gateway-cbs:[CBSGW],fep-server-atm:[ATMService],fep-server-fisc:[FISCService],fep-gateway-atm:[ATMGW],fep-gateway-fisc:[FISCGW],fep-server-imsgw:[IMSGateway]}
spring.fep.batch.task.inserteventmessagelog.ignoreLineContainsContent=KeepAlive
