server.port=8802

logging.config=classpath:logback-spring-ems.xml

spring.fep.application.name=fep-service

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-ems
management.endpoint.health.show-details=always

#register Controller
spring.register.bean[0]=com.syscom.fep.service.ems.queue.EMSLogReceiver

#EMSAlertLogController
spring.fep.service.ems.resetNotifyInterval=3
spring.fep.service.ems.repeatInterval=3
spring.fep.service.ems.mailSender=fep@tcb-bank.com.tw
spring.fep.service.ems.mailList=AP1_FEP@tcb-bank.com.tw
spring.fep.service.ems.maillistnps2262=
spring.fep.service.ems.warning-pattern=\u7121\u6CD5\u53D6\u5F97suipClient;RC:10,;RC:11,;RC:17,;RC:81,;RC:82,;RC:83,;RC:84,;RC:94,;RC:95,;RC:98,;RC:99,
spring.fep.service.ems.flushStatementsTotal=100

# enable mail
spring.fep.mail.enable=true

# enable mitake sms
spring.fep.sms.mitake.enable=false

#EMS Receiver
spring.fep.jms.ems.receiver.prop.queueManager=QMFEPLOGP02
spring.fep.jms.ems.receiver.prop.channel=SVRCONN.FROMEMS
spring.fep.jms.ems.receiver.prop.connName=${spring.fep.hostip}(1415)
spring.fep.jms.ems.receiver.prop.user=
spring.fep.jms.ems.receiver.prop.password=
spring.fep.jms.ems.receiver.prop.queue-names.ems.destination=FEP.EMS.QL
spring.fep.jms.ems.receiver.prop.queue-names.ems.concurrency=20-50

spring.fep.log.jdbc.sqltiming.level=DEBUG
spring.fep.log.mybatis.level=DEBUG
spring.fep.log.jdbc.level=DEBUG


spring.fep.mybatis.interceptor.audittrail.enable=false
spring.fep.mybatis.interceptor.logger.enable=false