server.port=8305
server.servlet.context-path=

spring.fep.application.name=fep-gateway

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-cbs
management.endpoint.health.show-details=always


#CBSGatewayManager
spring.register.bean[0]=com.syscom.fep.gateway.ims.cbs.CBSGatewayManager
#CBSGatewatControl
spring.register.controller[0]=com.syscom.fep.gateway.ims.cbs.CBSGatewayCtrl

#================================Adapter============================================
spring.fep.gateway.transmission.cbs.fepap[0].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[0].port=8752
spring.fep.gateway.transmission.cbs.fepap[0].bisThreadNum=600
spring.fep.gateway.transmission.cbs.fepap[0].cbsType=CBS
spring.fep.gateway.transmission.cbs.fepap[0].retrySendToIMS=false

spring.fep.gateway.transmission.cbs.fepap[1].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[1].port=8754
spring.fep.gateway.transmission.cbs.fepap[1].bisThreadNum=600
spring.fep.gateway.transmission.cbs.fepap[1].cbsType=473X

spring.fep.gateway.transmission.cbs.fepap[2].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[2].port=8756
spring.fep.gateway.transmission.cbs.fepap[2].bisThreadNum=600
spring.fep.gateway.transmission.cbs.fepap[2].cbsType=FISC

spring.fep.gateway.transmission.cbs.fepap[3].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[3].port=8758
spring.fep.gateway.transmission.cbs.fepap[3].bisThreadNum=600
spring.fep.gateway.transmission.cbs.fepap[3].cbsType=FISCTCB
spring.fep.gateway.transmission.cbs.fepap[3].retrySendToIMS=false

spring.fep.gateway.transmission.cbs.fepap[4].host=${spring.fep.hostip}
spring.fep.gateway.transmission.cbs.fepap[4].port=8760
spring.fep.gateway.transmission.cbs.fepap[4].bisThreadNum=600
spring.fep.gateway.transmission.cbs.fepap[4].cbsType=NONATM
spring.fep.gateway.transmission.cbs.fepap[4].retrySendToIMS=false
#================================Adapter============================================

#================================cbsType:CBS========================================
#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[0].host=10.0.178.1
spring.fep.gateway.transmission.cbs.sender[0].port=6669
spring.fep.gateway.transmission.cbs.sender[0].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[0].clientId=IFEPPA12,IFEPPA14,IFEPPA16,IFEPPA18
spring.fep.gateway.transmission.cbs.sender[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[0].pingIMSInterval=300000
spring.fep.gateway.transmission.cbs.sender[0].cbsType=CBS

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[0].host=10.0.178.1
spring.fep.gateway.transmission.cbs.receiver[0].port=6669
spring.fep.gateway.transmission.cbs.receiver[0].reestablishConnectionInterval=10000
#spring.fep.gateway.transmission.cbs.receiver[0].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[0].clientId=IFEPPB12,IFEPPB14,IFEPPB16,IFEPPB18
spring.fep.gateway.transmission.cbs.receiver[0].resumeInterval=60000
spring.fep.gateway.transmission.cbs.receiver[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[0].cbsType=CBS
#================================cbsType:CBS========================================

#================================cbsType:473X=======================================
#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[1].host=10.0.178.1
spring.fep.gateway.transmission.cbs.sender[1].port=6669
spring.fep.gateway.transmission.cbs.sender[1].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[1].clientId=IFEPPA22,IFEPPA24,IFEPPA26,IFEPPA28
spring.fep.gateway.transmission.cbs.sender[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[1].pingIMSInterval=300000
spring.fep.gateway.transmission.cbs.sender[1].cbsType=473X

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[1].host=10.0.178.1
spring.fep.gateway.transmission.cbs.receiver[1].port=6669
spring.fep.gateway.transmission.cbs.receiver[1].reestablishConnectionInterval=10000
#spring.fep.gateway.transmission.cbs.receiver[1].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[1].clientId=IFEPPB22,IFEPPB24,IFEPPB26,IFEPPB28
spring.fep.gateway.transmission.cbs.receiver[1].resumeInterval=60000
spring.fep.gateway.transmission.cbs.receiver[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[1].cbsType=473X
#================================cbsType:473X=======================================

#================================cbsType:FISC=======================================
#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[2].host=10.0.178.1
spring.fep.gateway.transmission.cbs.sender[2].port=6669
spring.fep.gateway.transmission.cbs.sender[2].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[2].clientId=IFEPPA32,IFEPPA34,IFEPPA36,IFEPPA38
spring.fep.gateway.transmission.cbs.sender[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[2].pingIMSInterval=300000
spring.fep.gateway.transmission.cbs.sender[2].cbsType=FISC

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[2].host=10.0.178.1
spring.fep.gateway.transmission.cbs.receiver[2].port=6669
spring.fep.gateway.transmission.cbs.receiver[2].reestablishConnectionInterval=10000
#spring.fep.gateway.transmission.cbs.receiver[2].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[2].clientId=IFEPPB32,IFEPPB34,IFEPPB36,IFEPPB38
spring.fep.gateway.transmission.cbs.receiver[2].resumeInterval=60000
spring.fep.gateway.transmission.cbs.receiver[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[2].cbsType=FISC
#================================cbsType:FISC=======================================

#================================cbsType:FISCTCB=======================================
#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[3].host=10.0.178.1
spring.fep.gateway.transmission.cbs.sender[3].port=6669
spring.fep.gateway.transmission.cbs.sender[3].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[3].clientId=IFEPPA62,IFEPPA64,IFEPPA66,IFEPPA68
spring.fep.gateway.transmission.cbs.sender[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[3].pingIMSInterval=300000
spring.fep.gateway.transmission.cbs.sender[3].cbsType=FISCTCB

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[3].host=10.0.178.1
spring.fep.gateway.transmission.cbs.receiver[3].port=6669
spring.fep.gateway.transmission.cbs.receiver[3].reestablishConnectionInterval=10000
#spring.fep.gateway.transmission.cbs.receiver[3].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[3].resumeInterval=60000
spring.fep.gateway.transmission.cbs.receiver[3].clientId=IFEPPB62,IFEPPB64,IFEPPB66,IFEPPB68
spring.fep.gateway.transmission.cbs.receiver[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[3].cbsType=FISCTCB
#================================cbsType:FISCTCB=======================================

#================================cbsType:NONATM=======================================
#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.sender[4].host=10.0.178.1
spring.fep.gateway.transmission.cbs.sender[4].port=6669
spring.fep.gateway.transmission.cbs.sender[4].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.sender[4].clientId=IFEPPA72,IFEPPA74,IFEPPA76,IFEPPA78
spring.fep.gateway.transmission.cbs.sender[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.sender[4].pingIMSInterval=300000
spring.fep.gateway.transmission.cbs.sender[4].cbsType=NONATM

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.receiver[4].host=10.0.178.1
spring.fep.gateway.transmission.cbs.receiver[4].port=6669
spring.fep.gateway.transmission.cbs.receiver[4].reestablishConnectionInterval=10000
#spring.fep.gateway.transmission.cbs.receiver[4].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.receiver[4].resumeInterval=60000
spring.fep.gateway.transmission.cbs.receiver[4].clientId=IFEPPB72,IFEPPB74,IFEPPB76,IFEPPB78
spring.fep.gateway.transmission.cbs.receiver[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.receiver[4].cbsType=NONATM
#================================cbsType:NONATM=======================================


#====================Alternative=cbsType:CBS========================================
#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.alternative-sender[0].host=10.0.178.1
spring.fep.gateway.transmission.cbs.alternative-sender[0].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[0].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[0].clientId=IFEPPC12,IFEPPC14,IFEPPC16,IFEPPC18
spring.fep.gateway.transmission.cbs.alternative-sender[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[0].pingIMSInterval=300000
spring.fep.gateway.transmission.cbs.alternative-sender[0].cbsType=CBS

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[0].host=10.0.178.1
spring.fep.gateway.transmission.cbs.alternative-receiver[0].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[0].reestablishConnectionInterval=10000
#spring.fep.gateway.transmission.cbs.alternative-receiver[0].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[0].clientId=IFEPPD12,IFEPPD14,IFEPPD16,IFEPPD18
spring.fep.gateway.transmission.cbs.alternative-receiver[0].resumeInterval=60000
spring.fep.gateway.transmission.cbs.alternative-receiver[0].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[0].cbsType=CBS
#====================Alternative=cbsType:CBS========================================

#====================Alternative=cbsType:473X=======================================
#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.alternative-sender[1].host=10.0.178.1
spring.fep.gateway.transmission.cbs.alternative-sender[1].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[1].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[1].clientId=IFEPPC22,IFEPPC24,IFEPPC26,IFEPPC28
spring.fep.gateway.transmission.cbs.alternative-sender[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[1].pingIMSInterval=300000
spring.fep.gateway.transmission.cbs.alternative-sender[1].cbsType=473X

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[1].host=10.0.178.1
spring.fep.gateway.transmission.cbs.alternative-receiver[1].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[1].reestablishConnectionInterval=10000
#spring.fep.gateway.transmission.cbs.alternative-receiver[1].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[1].clientId=IFEPPD22,IFEPPD24,IFEPPD26,IFEPPD28
spring.fep.gateway.transmission.cbs.alternative-receiver[1].resumeInterval=60000
spring.fep.gateway.transmission.cbs.alternative-receiver[1].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[1].cbsType=473X
#====================Alternative=cbsType:473X=======================================

#====================Alternative=cbsType:FISC=======================================
#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.alternative-sender[2].host=10.0.178.1
spring.fep.gateway.transmission.cbs.alternative-sender[2].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[2].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[2].clientId=IFEPPC32,IFEPPC34,IFEPPC36,IFEPPC38
spring.fep.gateway.transmission.cbs.alternative-sender[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[2].pingIMSInterval=300000
spring.fep.gateway.transmission.cbs.alternative-sender[2].cbsType=FISC

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[2].host=10.0.178.1
spring.fep.gateway.transmission.cbs.alternative-receiver[2].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[2].reestablishConnectionInterval=10000
#spring.fep.gateway.transmission.cbs.alternative-receiver[2].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[2].clientId=IFEPPD32,IFEPPD34,IFEPPD36,IFEPPD38
spring.fep.gateway.transmission.cbs.alternative-receiver[2].resumeInterval=60000
spring.fep.gateway.transmission.cbs.alternative-receiver[2].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[2].cbsType=FISC
#====================Alternative=cbsType:FISC=======================================

#====================Alternative=cbsType:FISCTCB=======================================
#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.alternative-sender[3].host=10.0.178.1
spring.fep.gateway.transmission.cbs.alternative-sender[3].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[3].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[3].clientId=IFEPPC62,IFEPPC64,IFEPPC66,IFEPPC68
spring.fep.gateway.transmission.cbs.alternative-sender[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[3].pingIMSInterval=300000
spring.fep.gateway.transmission.cbs.alternative-sender[3].cbsType=FISCTCB

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[3].host=10.0.178.1
spring.fep.gateway.transmission.cbs.alternative-receiver[3].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[3].reestablishConnectionInterval=10000
#spring.fep.gateway.transmission.cbs.alternative-receiver[3].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[3].resumeInterval=60000
spring.fep.gateway.transmission.cbs.alternative-receiver[3].clientId=IFEPPD62,IFEPPD64,IFEPPD66,IFEPPD68
spring.fep.gateway.transmission.cbs.alternative-receiver[3].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[3].cbsType=FISCTCB
#====================Alternative=cbsType:FISCTCB=======================================

#====================Alternative=cbsType:NONATM=======================================
#CBS Gateway Sender
spring.fep.gateway.transmission.cbs.alternative-sender[4].host=10.0.178.1
spring.fep.gateway.transmission.cbs.alternative-sender[4].port=6669
spring.fep.gateway.transmission.cbs.alternative-sender[4].reestablishConnectionInterval=10000
spring.fep.gateway.transmission.cbs.alternative-sender[4].clientId=IFEPPC72,IFEPPC74,IFEPPC76,IFEPPC78
spring.fep.gateway.transmission.cbs.alternative-sender[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-sender[4].pingIMSInterval=300000
spring.fep.gateway.transmission.cbs.alternative-sender[4].cbsType=NONATM

#CBS Gateway Receiver
spring.fep.gateway.transmission.cbs.alternative-receiver[4].host=10.0.178.1
spring.fep.gateway.transmission.cbs.alternative-receiver[4].port=6669
spring.fep.gateway.transmission.cbs.alternative-receiver[4].reestablishConnectionInterval=10000
#spring.fep.gateway.transmission.cbs.alternative-receiver[4].disConnectInterval=120000
spring.fep.gateway.transmission.cbs.alternative-receiver[4].resumeInterval=60000
spring.fep.gateway.transmission.cbs.alternative-receiver[4].clientId=IFEPPD72,IFEPPD74,IFEPPD76,IFEPPD78
spring.fep.gateway.transmission.cbs.alternative-receiver[4].dataStore=ICONDS
spring.fep.gateway.transmission.cbs.alternative-receiver[4].cbsType=NONATM
#====================Alternative=cbsType:NONATM=======================================

#register Scheduler Job
spring.fep.scheduler.job.register[0].className=com.syscom.fep.scheduler.job.impl.AppMonitorJob
spring.fep.scheduler.job.register[0].configClassName=com.syscom.fep.scheduler.job.impl.AppMonitorJobConfig
spring.fep.scheduler.job.register[1].className=com.syscom.fep.gateway.job.cbs.CBSGatewayAppMonitorJob
spring.fep.scheduler.job.register[1].configClassName=com.syscom.fep.gateway.job.cbs.CBSGatewayAppMonitorJobConfig

#AppMonitorJob
spring.fep.scheduler.job.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.scheduler.job.app-monitor.serviceName=${management.metrics.tags.application}
spring.fep.scheduler.job.app-monitor.serviceHostIp=${spring.fep.hostip}
spring.fep.scheduler.job.app-monitor.serviceHostName=${spring.fep.hostname}
spring.fep.scheduler.job.app-monitor.serviceUrl=http://${spring.fep.hostip}:${server.port}
spring.fep.scheduler.job.app-monitor.monitorPrimaryUrl=http://10.0.54.34:8730/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.monitorSecondaryUrl=http://10.0.54.33:8730/api/mon/SendMessage
spring.fep.scheduler.job.app-monitor.recordHttpLog=true

#CBS Gateway Job
spring.fep.gateway.job.cbs.app-monitor.cronExpression=0 0/1 * * * ?
spring.fep.gateway.job.cbs.app-monitor.monitorUrl=http://${spring.fep.hostip}:8730/recv/net/client