server.port=8150

spring.fep.application.name=fep-server

management.endpoints.prometheus.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.fep.application.name}-mch
management.endpoint.health.show-details=always

spring.register.bean[0]=com.syscom.fep.server.queue.MCHServerReceiver


#MCH MAP Queue
#spring.fep.jms.mch.debug=-1
spring.fep.jms.mch.prop[0].queueManager=QMFEPP02
spring.fep.jms.mch.prop[0].channel=SVRCONN.FEPAP
spring.fep.jms.mch.prop[0].connName=10.0.54.34(1414)
spring.fep.jms.mch.prop[0].user=
spring.fep.jms.mch.prop[0].password=

spring.datasource.fepdb.hikari.maximum-pool-size=130
spring.datasource.desdb.hikari.maximum-pool-size=130