package com.syscom.fep.mybatis.mapper;

import com.syscom.fep.mybatis.model.Atmdevlog;
import jakarta.annotation.Resource;
import org.apache.ibatis.annotations.Param;

@Resource
public interface AtmdevlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMDEVLOG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Atmdevlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMDEVLOG
     *
     * @mbg.generated
     */
    int insert(Atmdevlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMDEVLOG
     *
     * @mbg.generated
     */
    int insertSelective(Atmdevlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMDEVLOG
     *
     * @mbg.generated
     */
    Atmdevlog selectByPrimaryKey(@Param("atmdevlogId") Integer atmdevlogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMDEVLOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Atmdevlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATMDEVLOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Atmdevlog record);
}