package com.syscom.fep.mybatis.mapper;

import com.syscom.fep.mybatis.model.Card;
import org.apache.ibatis.annotations.Param;

public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbg.generated
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbg.generated
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbg.generated
     */
    Card selectByPrimaryKey(@Param("cardActno") String cardActno, @Param("cardCardSeq") Short cardCardSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Card record);
}