package com.syscom.fep.mybatis.mapper;

import com.syscom.fep.mybatis.model.Ejfno;
import org.apache.ibatis.annotations.Param;

public interface EjfnoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJFNO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Ejfno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJFNO
     *
     * @mbg.generated
     */
    int insert(Ejfno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJFNO
     *
     * @mbg.generated
     */
    int insertSelective(Ejfno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJFNO
     *
     * @mbg.generated
     */
    Ejfno selectByPrimaryKey(@Param("ejfno") Integer ejfno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJFNO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ejfno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJFNO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ejfno record);
}