package com.syscom.fep.mybatis.mapper;

import com.syscom.fep.mybatis.model.Svcsdcnr;
import jakarta.annotation.Resource;
import org.apache.ibatis.annotations.Param;

@Resource
public interface SvcsdcnrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCNR
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Svcsdcnr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCNR
     *
     * @mbg.generated
     */
    int insert(Svcsdcnr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCNR
     *
     * @mbg.generated
     */
    int insertSelective(Svcsdcnr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCNR
     *
     * @mbg.generated
     */
    Svcsdcnr selectByPrimaryKey(@Param("seqno") Long seqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCNR
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Svcsdcnr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVCSDCNR
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Svcsdcnr record);
}