package com.syscom.fep.mybatis.mapper;

import com.syscom.fep.mybatis.model.Zone;
import org.apache.ibatis.annotations.Param;

public interface ZoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE
     *
     * @mbg.generated
     */
    int insert(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE
     *
     * @mbg.generated
     */
    int insertSelective(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE
     *
     * @mbg.generated
     */
    Zone selectByPrimaryKey(@Param("zoneCode") String zoneCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Zone record);
}