<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.syscom</groupId>
        <artifactId>feptcb</artifactId>
        <version>1.0.0</version>
    </parent>
    <groupId>com.syscom.feptcb</groupId>
    <artifactId>fep-notify</artifactId>
    <name>fep-notify</name>
    <description>notify</description>
    <packaging>${project.packaging}</packaging>
    <properties>
        <project-shell>fep_notify</project-shell>
        <!-- ${project.description}必須在最後的位置 -->
        <profiles-active>mybatis,scheduler,jms,integration,${project.description}</profiles-active>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-bom</artifactId>
                <version>${log4j2.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${netty-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring-boot-starter-web-version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>${spring-boot-starter-version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
            <version>${spring-boot-starter-aop-version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring-version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring-boot-starter-test-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot-starter</artifactId>
            <version>${jasypt-spring-boot-starter-version}</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>${springdoc-openapi-ui-version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson-version}</version>
        </dependency>
        <!-- cache -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
            <version>${spring-boot-starter-cache-version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <version>${caffeine-version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-jms</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-scheduler</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <version>${spring-boot-starter-actuator-vesion}</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <version>${micrometer-registry-prometheus-version}</version>
        </dependency>
    </dependencies>
    <profiles>
        <!-- Springboot方式build版, 將所有的檔包括引用的第三方jar檔都包在一個fep-notify.jar檔中 -->
        <profile>
            <id>springboot-jar</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <project.packaging>jar</project.packaging>
            </properties>
            <build>
                <finalName>${project.artifactId}</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <version>${spring-boot-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>com.syscom.fep.FepNotifyApplication</mainClass>
                            <includeSystemScope>true</includeSystemScope>
                            <profiles>
                                <profile>mybatis</profile>
                                <profile>scheduler</profile>
                                <profile>jms</profile>
                                <profile>integration</profile>
                                <profile>notify</profile>
                            </profiles>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>repackage</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin-version}</version>
                        <configuration>
                            <source>${java-source-version}</source>
                            <target>${java-target-version}</target>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <!-- Maven方式build版, 並配合iterator-maven-plugin實現拆分方式build版, 利於換版單獨更換jar檔
            1. 僅將本專案中的class檔包在jar檔中
            2. resource下的檔直接放在fep-config目錄下
            3. 將第三方引用的jar檔直接放在上一級目錄的dependencies目錄下
            4. 將引用fep其他專案的jar檔, 包括safeaa的jar檔放在lib目錄下
            目錄結構如下:
                /fep-app
                    /bin/fep-function.sh
                    /config/各項配置檔
                    /dependencies/引用第三方的jar檔
                    /fep-notify
                        /lib/引用fep的jar檔, safeaa的jar檔
                        application.properties
                        fep-notify.jar
                         -->
        <profile>
            <id>maven-jar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <project.packaging>jar</project.packaging>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-clean-plugin</artifactId>
                        <version>${maven-clean-plugin-version}</version>
                        <configuration>
                            <followSymLinks>false</followSymLinks>
                            <filesets>
                                <fileset>
                                    <directory>../../${assembly-directory}</directory>
                                    <includes>
                                        <include>${project.artifactId}-*.tar.gz</include>
                                    </includes>
                                </fileset>
                            </filesets>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>properties-maven-plugin</artifactId>
                        <version>${properties-maven-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>read-project-properties</goal>
                                </goals>
                                <configuration>
                                    <files>
                                        <!-- 讀取屬性檔 -->
                                        <file>${assembly-config-path}/assembly-${assembly-prop}.properties</file>
                                        <!-- 讀取mybatis所有jar檔的classpath配置 -->
                                        <file>${assembly-config-path}/fep-mybatis/assembly-${assembly-mybatis}-${assembly-prop}.properties</file>
                                    </files>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>${maven-antrun-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <delete file="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                        <copy file="${assembly-release-note-path}/${project.artifactId}.txt"
                                              tofile="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>${maven-jar-plugin-version}</version>
                        <configuration>
                            <finalName>${project.artifactId}</finalName>
                            <archive>
                                <addMavenDescriptor>false</addMavenDescriptor>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                    <classpathPrefix>../dependencies/</classpathPrefix>
                                    <mainClass>com.syscom.fep.FepNotifyApplication</mainClass>
                                </manifest>
                                <manifestEntries>
                                    <Class-Path>${assembly-prop-classpath} ${assembly-prop-mybatis-classpath}</Class-Path>
                                </manifestEntries>
                            </archive>
                            <excludes>
                                <exclude>static/**</exclude>
                                <exclude>templates/**</exclude>
                            </excludes>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>com.soebes.maven.plugins</groupId>
                        <artifactId>iterator-maven-plugin</artifactId>
                        <version>${iterator-maven-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>iterator</goal>
                                </goals>
                                <configuration>
                                    <itemsWithProperties>
                                        <itemWithProperty>
                                            <name>notify</name>
                                            <properties>
                                                <assembly-func/>
                                                <assembly-shell/>
                                                <assembly-jvm-xms>256m</assembly-jvm-xms>
                                                <assembly-jvm-xmx>512m</assembly-jvm-xmx>
                                                <assembly-jvm-metaspaceSize>256m</assembly-jvm-metaspaceSize>
                                                <assembly-profiles-active>${profiles-active}${assembly-func}</assembly-profiles-active>
                                            </properties>
                                        </itemWithProperty>
                                    </itemsWithProperties>
                                    <pluginExecutors>
                                        <pluginExecutor>
                                            <plugin>
                                                <artifactId>maven-assembly-plugin</artifactId>
                                                <version>${maven-assembly-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <id>make-assembly</id>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>single</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>single</goal>
                                            <configuration>
                                                <finalName>${project.artifactId}</finalName>
                                                <descriptors>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-bash}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-dependencies}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}/assembly-${assembly-bin}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-cmd}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-config}.xml</descriptor>
                                                </descriptors>
                                                <outputDirectory>${assembly-output-path}</outputDirectory>
                                            </configuration>
                                        </pluginExecutor>
                                    </pluginExecutors>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- 以下是build一個fep-notify-1.0.0-vo.jar -->
                    <plugin>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <version>${maven-assembly-plugin-version}</version>
                        <executions>
                            <execution>
                                <id>make-assembly</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <descriptors>
                                <descriptor>${assembly-config-path}/${project.artifactId}/assembly-${assembly-vo}.xml</descriptor>
                            </descriptors>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                        </configuration>
                    </plugin>
                    <!-- fep-notify-1.0.0-vo.jar更名為fep-notify-vo.jar檔並複製到/fep-lib/lib資料夾下 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>${maven-antrun-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>install</phase>
                                <configuration>
                                    <target>
                                        <copy file="${project.build.directory}/${project.artifactId}-${project.version}-${assembly-vo}.jar"
                                              tofile="${assembly-lib-lib-path}/${project.artifactId}-${assembly-vo}.jar" />
                                    </target>
                                </configuration>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin-version}</version>
                        <configuration>
                            <source>${java-source-version}</source>
                            <target>${java-target-version}</target>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>