## 2023/11/22 sslConfigs 1.0 & 2.0
##First SSL
#spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeyPath=fep-1.p12
#spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeySscode=ENC(HX1pBrc+YSq724TJ/jwtd89hwsrWIccsnz492BpvmE7sx9P/+PaHBHrrrk2jroDo)
#spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeyType=PKCS12
#
##Second SSL
#spring.fep.gateway.transmission.atm.sslConfigs[1].sslKeyPath=fep-2.p12
#spring.fep.gateway.transmission.atm.sslConfigs[1].sslKeySscode=ENC(HX1pBrc+YSq724TJ/jwtd89hwsrWIccsnz492BpvmE7sx9P/+PaHBHrrrk2jroDo)
#spring.fep.gateway.transmission.atm.sslConfigs[1].sslKeyType=PKCS12

#====================================================================================================================================

## 2025/06/22 sslConfigs 2.0 & 3.0
#First SSL  2025/11/06 command out
#spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeyPath=fep-2.p12
#spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeySscode=ENC(HX1pBrc+YSq724TJ/jwtd89hwsrWIccsnz492BpvmE7sx9P/+PaHBHrrrk2jroDo)
#spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeyType=PKCS12

#Second SSL
spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeyPath=fep-3.p12
spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeySscode=ENC(+P7wsJ0HGuEVwcYfCYBhToJQEMpPpX44eIvZmTAdrclW4rFREe6A1x940JllLpfy)
spring.fep.gateway.transmission.atm.sslConfigs[0].sslKeyType=PKCS12
