<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.syscom</groupId>
        <artifactId>feptcb</artifactId>
        <version>1.0.0</version>
    </parent>
    <groupId>com.syscom.feptcb</groupId>
    <artifactId>fep-web</artifactId>
    <name>fep-web</name>
    <description>web</description>
    <packaging>${project.packaging}</packaging>
    <properties>
        <project-shell>fep_web</project-shell>
        <!-- ${project.description}必須在最後的位置 -->
        <profiles-active>mybatis,scheduler,jms,safeaa,integration,${project.description}</profiles-active>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-bom</artifactId>
                <version>${log4j2.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${netty-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-configuration</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-batch-task</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-server-aa</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-scheduler</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-mybatis-ems</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-mybatis-deslog</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-mybatis-his</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.feptcb</groupId>
            <artifactId>fep-mybatis-enc</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.syscom.safeaatcb</groupId>
            <artifactId>safeaa-core</artifactId>
            <version>${safeaa-core-version}</version>
            <scope>system</scope>
            <systemPath>${pom.basedir}/lib/safeaa-core.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring-boot-starter-web-version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
            <version>${spring-boot-starter-thymeleaf-version}</version>
        </dependency>
        <dependency>
            <groupId>nz.net.ultraq.thymeleaf</groupId>
            <artifactId>thymeleaf-layout-dialect</artifactId>
            <version>${thymeleaf-layout-dialect-version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>${pagehelper-spring-boot-starter-version}</version>
        </dependency>
        <!-- <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <version>${spring-boot-devtools-version}</version>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency> -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring-boot-starter-test-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <version>${spring-boot-starter-actuator-vesion}</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <version>${micrometer-registry-prometheus-version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter-api-version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>${spring-boot-starter-security-version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok-version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <profiles>
        <!-- Springboot方式build版, 將所有的檔包括引用的第三方jar檔都包在一個fep-web.jar檔中 -->
        <profile>
            <id>springboot-jar</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <project.packaging>jar</project.packaging>
            </properties>
            <build>
                <finalName>${project.artifactId}</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <version>${spring-boot-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>com.syscom.fep.web.SyscomFepWebApplication</mainClass>
                            <includeSystemScope>true</includeSystemScope>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>repackage</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin-version}</version>
                        <configuration>
                            <source>${java-source-version}</source>
                            <target>${java-target-version}</target>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <!-- Maven方式build版, 並配合iterator-maven-plugin實現拆分方式build版, 利於換版單獨更換jar檔
            1. 僅將本專案中的class檔包在jar檔中
            2. resource下的檔直接放在fep-web目錄下
            3. 將第三方引用的jar檔直接放在上一級目錄的dependencies目錄下
            4. 將引用fep其他專案的jar檔, 包括safeaa的jar檔放在lib目錄下
            目錄結構如下:
                /fep-app
                    /bin/fep-function.sh
                    /config/各項配置檔
                    /dependencies/引用第三方的jar檔
                    /fep-web
                        /lib/引用fep的jar檔, safeaa的jar檔
                        /static/各種js, css, 圖檔等靜態檔案
                        /template/html檔
                        application.properties
                        fep-web-run.bat
                        fep-web.jar
                        fep-web-start.sh
                        fep-web-status.sh
                        fep-web-stop.sh
        -->
        <profile>
            <id>maven-jar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <project.packaging>jar</project.packaging>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-clean-plugin</artifactId>
                        <version>${maven-clean-plugin-version}</version>
                        <configuration>
                            <followSymLinks>false</followSymLinks>
                            <filesets>
                                <fileset>
                                    <directory>../../${assembly-directory}</directory>
                                    <includes>
                                        <include>${project.artifactId}-*.tar.gz</include>
                                    </includes>
                                </fileset>
                            </filesets>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>properties-maven-plugin</artifactId>
                        <version>${properties-maven-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>read-project-properties</goal>
                                </goals>
                                <configuration>
                                    <files>
                                        <!-- 讀取屬性檔 -->
                                        <file>${assembly-config-path}/assembly-${assembly-prop}.properties</file>
                                        <!-- 讀取server-aa所有jar檔的classpath配置 -->
                                        <file>${assembly-config-path}/fep-server-aa/assembly-${assembly-server-aa}-${assembly-prop}.properties</file>
                                        <!-- 讀取mybatis所有jar檔的classpath配置 -->
                                        <file>${assembly-config-path}/fep-mybatis/assembly-${assembly-mybatis}-${assembly-prop}.properties</file>
                                    </files>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>${maven-antrun-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <delete file="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                        <copy file="${assembly-release-note-path}/${project.artifactId}.txt"
                                              tofile="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>${maven-jar-plugin-version}</version>
                        <configuration>
                            <finalName>${project.artifactId}</finalName>
                            <archive>
                                <addMavenDescriptor>false</addMavenDescriptor>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                    <classpathPrefix>../dependencies/</classpathPrefix>
                                    <mainClass>com.syscom.fep.web.SyscomFepWebApplication</mainClass>
                                </manifest>
                                <manifestEntries>
                                    <Class-Path>${assembly-prop-classpath} ${assembly-prop-server-aa-classpath} ${assembly-prop-mybatis-classpath} lib/safeaa-core.jar</Class-Path>
                                </manifestEntries>
                            </archive>
                            <excludes>
                                <exclude>static/**</exclude>
                                <exclude>templates/**</exclude>
                            </excludes>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>com.soebes.maven.plugins</groupId>
                        <artifactId>iterator-maven-plugin</artifactId>
                        <version>${iterator-maven-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>iterator</goal>
                                </goals>
                                <configuration>
                                    <itemsWithProperties>
                                        <itemWithProperty>
                                            <name>web</name>
                                            <properties>
                                                <assembly-func/>
                                                <assembly-shell/>
                                                <assembly-jvm-xms>256m</assembly-jvm-xms>
                                                <assembly-jvm-xmx>512m</assembly-jvm-xmx>
                                                <assembly-jvm-metaspaceSize>256m</assembly-jvm-metaspaceSize>
                                                <assembly-profiles-active>${profiles-active}${assembly-func}</assembly-profiles-active>
                                            </properties>
                                        </itemWithProperty>
                                    </itemsWithProperties>
                                    <pluginExecutors>
                                        <pluginExecutor>
                                            <plugin>
                                                <artifactId>maven-assembly-plugin</artifactId>
                                                <version>${maven-assembly-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <id>make-assembly</id>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>single</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>single</goal>
                                            <configuration>
                                                <finalName>${project.artifactId}</finalName>
                                                <descriptors>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-bash}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-dependencies}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-bin}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-cmd}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-config}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/assembly-${assembly-resources}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}${assembly-func}/assembly-${assembly-lib}.xml</descriptor>
                                                    <descriptor>${assembly-config-path}/${project.artifactId}${assembly-func}/assembly-${assembly-config}.xml</descriptor>
                                                </descriptors>
                                                <outputDirectory>${assembly-output-path}</outputDirectory>
                                            </configuration>
                                        </pluginExecutor>
                                    </pluginExecutors>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin-version}</version>
                        <configuration>
                            <source>${java-source-version}</source>
                            <target>${java-target-version}</target>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <!-- build war檔, 將所有的檔包括引用的第三方jar檔都包在一個${war-output-path}\fep-web-*.war檔中, 並且將配置檔全部放在war檔外 -->
        <profile>
            <id>war</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <project.packaging>war</project.packaging>
                <assembly-profiles-active>${profiles-active}</assembly-profiles-active>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                    <version>${spring-boot-starter-web-version}</version>
                    <exclusions>
                        <exclusion>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-tomcat</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>jakarta.servlet</groupId>
                    <artifactId>jakarta.servlet-api</artifactId>
                    <version>${jakarta.servlet-api-version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>javax.servlet</groupId>
                    <artifactId>javax.servlet-api</artifactId>
                    <version>${javax.servlet-api-version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-config</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-lib</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-mybatis</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-server-aa</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope> <!-- 注意這裡設定是provided, 則需要將fep-server-aa其他dependency複製到下面 -->
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-batch-task</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-server-common</artifactId>
                    <version>${project.version}</version>
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-batch-base</artifactId>
                    <version>${project.version}</version>
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-base-aa</artifactId>
                    <version>${project.version}</version>
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-invoker</artifactId>
                    <version>${project.version}</version>
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-enchelper</artifactId>
                    <version>${project.version}</version>
                </dependency>
                <dependency>
                    <groupId>com.syscom.feptcb</groupId>
                    <artifactId>fep-ws-client</artifactId>
                    <version>${project.version}</version>
                </dependency>
            </dependencies>
            <build>
                <finalName>${project.artifactId}</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-clean-plugin</artifactId>
                        <version>${maven-clean-plugin-version}</version>
                        <configuration>
                            <followSymLinks>false</followSymLinks>
                            <filesets>
                                <fileset>
                                    <directory>../../${war-directory}</directory>
                                    <includes>
                                        <include>${project.artifactId}*.war</include>
                                    </includes>
                                </fileset>
                            </filesets>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>${maven-antrun-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <delete file="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                        <copy file="${assembly-release-note-path}/${project.artifactId}.txt"
                                              tofile="${project.build.outputDirectory}/${assembly-file-readme}"/>
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>${maven-jar-plugin-version}</version>
                        <configuration>
                            <excludes>
                                <exclude>static/**</exclude>
                                <exclude>templates/**</exclude>
                            </excludes>
                        </configuration>
                        <executions>
                            <execution>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <finalName>${project.artifactId}</finalName>
                                    <classesDirectory>${project.build.directory}/classes</classesDirectory>
                                    <outputDirectory>${project.build.directory}/${project.artifactId}/WEB-INF/lib</outputDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- 很奇怪, 自己會build一個war檔, 所以這裡相當於是覆蓋加入一個plugin -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-war-plugin</artifactId>
                        <version>${maven-war-plugin-version}</version>
                        <configuration>
                            <warName>${project.artifactId}</warName>
                            <webResources>
                                <resource>
                                    <directory>${project.build.outputDirectory}</directory>
                                    <targetPath>/</targetPath>
                                    <includes>
                                        <include>${assembly-file-readme}</include>
                                    </includes>
                                </resource>
                            </webResources>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>com.soebes.maven.plugins</groupId>
                        <artifactId>iterator-maven-plugin</artifactId>
                        <version>${iterator-maven-plugin-version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>iterator</goal>
                                </goals>
                                <configuration>
                                    <itemsWithProperties>
                                        <itemWithProperty>
                                            <name>web</name>
                                            <properties>
                                                <assembly-func/>
                                                <assembly-profiles-active>${profiles-active}${assembly-func},jndi</assembly-profiles-active>
                                            </properties>
                                        </itemWithProperty>
                                    </itemsWithProperties>
                                    <pluginExecutors>
                                        <!-- 跑UT程式 -->
                                        <pluginExecutor>
                                            <plugin>
                                                <groupId>org.apache.maven.plugins</groupId>
                                                <artifactId>maven-surefire-plugin</artifactId>
                                                <version>${maven-surefire-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>test</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>test</goal>
                                            <configuration>
                                                <!-- <skipTests>true</skipTests> -->
                                                <includes>
                                                    <!-- 這支UT程式會將fep-XXX-YYY-1.0.0.jar檔中的-1.0.0移除掉 -->
                                                    <include>**/RemoveVersion.java</include>
                                                </includes>
                                            </configuration>
                                        </pluginExecutor>
                                        <pluginExecutor>
                                            <plugin>
                                                <groupId>org.apache.maven.plugins</groupId>
                                                <artifactId>maven-war-plugin</artifactId>
                                                <version>${maven-war-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>war</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>war</goal>
                                            <configuration>
                                                <warName>${project.artifactId}${assembly-func}</warName>
                                                <failOnMissingWebXml>false</failOnMissingWebXml>
                                                <packagingExcludes>
                                                    WEB-INF/classes/com/, <!-- classes資料夾下的class檔會包進fep-web.jar中, 故這裡不用再包一次 -->
                                                    WEB-INF/classes/META-INF/, <!-- classes資料夾下的META-INF檔會包進fep-web.jar中, 故這裡不用再包一次 -->
                                                    WEB-INF/classes/${assembly-file-readme}, <!-- readme.txt檔上面已經包進war檔了, 故這裡不用再包一次 -->
                                                    WEB-INF/lib/fep-*-1.0.0.jar <!-- 拿掉有版本號的fep-XXX-YYY-1.0.0.jar檔 -->
                                                </packagingExcludes>
                                                <webResources>
                                                    <!-- 將移除版本號後的fep-XXX-YYY-jar檔包進去 -->
                                                    <resource>
                                                        <directory>${project.build.directory}/${project.artifactId}/WEB-INF/lib</directory>
                                                        <targetPath>WEB-INF/lib</targetPath>
                                                        <includes>
                                                            <include>fep-*.jar</include>
                                                        </includes>
                                                    </resource>
                                                    <!-- 本專案lib資料夾下的jar檔包進去 -->
                                                    <resource>
                                                        <directory>${pom.basedir}/lib</directory>
                                                        <targetPath>WEB-INF/lib</targetPath>
                                                        <includes>
                                                            <include>*.jar</include>
                                                        </includes>
                                                    </resource>
                                                    <!-- 將${assembly-server-aa-output-path}下拆分server-aa的所有jar檔包進去 -->
                                                    <resource>
                                                        <directory>${assembly-server-aa-output-path}</directory>
                                                        <targetPath>WEB-INF/lib</targetPath>
                                                        <includes>
                                                            <include>*.jar</include>
                                                        </includes>
                                                    </resource>
                                                    <!-- 將${assembly-mybatis-output-path}下拆分mybatis的所有jar檔包進去 -->
                                                    <resource>
                                                        <directory>${assembly-mybatis-output-path}</directory>
                                                        <targetPath>WEB-INF/lib</targetPath>
                                                        <includes>
                                                            <include>*.jar</include>
                                                        </includes>
                                                    </resource>
                                                    <!-- 將fep-lib/lib/目錄下的jar檔包進去 -->
                                                    <resource>
                                                        <directory>${assembly-lib-lib-path}</directory>
                                                        <targetPath>WEB-INF/lib</targetPath>
                                                        <includes>
                                                            <include>*.jar</include>
                                                        </includes>
                                                    </resource>
                                                    <!-- 將fep-enchelper/lib/目錄下的jar檔包進去 -->
                                                    <resource>
                                                        <directory>${assembly-enchelper-lib-path}</directory>
                                                        <targetPath>WEB-INF/lib</targetPath>
                                                        <includes>
                                                            <include>*.jar</include>
                                                        </includes>
                                                    </resource>
                                                    <resource>
                                                        <directory>${assembly-config-path}</directory>
                                                        <targetPath>WEB-INF/classes</targetPath>
                                                        <includes>
                                                            <include>application.properties</include>
                                                        </includes>
                                                        <filtering>true</filtering>
                                                    </resource>
                                                </webResources>
                                            </configuration>
                                        </pluginExecutor>
                                        <pluginExecutor>
                                            <plugin>
                                                <groupId>org.apache.maven.plugins</groupId>
                                                <artifactId>maven-antrun-plugin</artifactId>
                                                <version>${maven-antrun-plugin-version}</version>
                                                <executions>
                                                    <execution>
                                                        <phase>package</phase>
                                                        <goals>
                                                            <goal>run</goal>
                                                        </goals>
                                                    </execution>
                                                </executions>
                                            </plugin>
                                            <goal>run</goal>
                                            <configuration>
                                                <target>
                                                    <copy todir="${war-output-path}">
                                                        <fileset dir="${project.build.directory}">
                                                            <include name="${project.artifactId}${assembly-func}.war"/>
                                                        </fileset>
                                                    </copy>
                                                    <delete>
                                                        <fileset dir="${project.build.directory}/${project.artifactId}/WEB-INF/lib">
                                                            <include name="fep-*-1.0.0.jar"/>
                                                        </fileset>
                                                    </delete>
                                                </target>
                                            </configuration>
                                        </pluginExecutor>
                                    </pluginExecutors>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin-version}</version>
                        <configuration>
                            <source>${java-source-version}</source>
                            <target>${java-target-version}</target>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <parameters>true</parameters>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin-version}</version>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>